### ISSUE TITLE
Add WCAG-EM / ATAG reference

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#1000]
From the [survey](https://www.w3.org/2002/09/wbs/35422/Conformance-Challenges-FPWD/results), this is just to add my comment about including some reference to WCAG-EM & ATAG.

How about a paragraph in the abstract, below the 4 points (above "One of the reasons for publication of this document..."), such as:

"The WCAG 2.x conformance model does build in several mitigations to these factors such as partial conformance for 3rd party content. The _Website Accessibility Conformance Evaluation Methodology (WCAG-EM) 1.0_ (link) provides a good practice guide on sampling large websites. Also, the _Authoring Tools Accessibility guidelines 2.0_ (link) provides guidance on enabling and encouraging accessible content from authors. However, the level of scale, complexity and personalisation provided by some websites has highlighted challenges in meeting conformance that could be accounted for in a future version of the guidelines and/or a future version of WCAG-EM.”

**Comment by bruce-usab** [comment]
Thanks @alastc and @peterkorn as this was my main comment from the survey.

**Comment by sajkaj** [comment]
Addressed in the fourth paragraph beginning: "The WCAG 2.x conformance model contains a mitigation related partial conformance" at the [Problem Statement](https://w3c.github.io/wcag/conformance-challenges/#problem-statement).
