### ISSUE TITLE
In WCAG Editors Draft 2.2, Change WCAG 2.0 to WCAG 2.1 

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1010]
At the Requirements for Web Content Accessibility Guidelines 2.2 W3C Editor's Draft 10 September 2019

https://w3c.github.io/wcag/guidelines/22/

Don't we want to change WCAG 2.0 to WCAG 2.1 for:

- https://w3c.github.io/wcag/guidelines/22/#utilize-the-wcag-2-0-conformance-model
- https://w3c.github.io/wcag/guidelines/22/#utilize-the-wcag-2-0-a-aa-aaa-model

Although nothing might have changed we also will change this at:

- https://github.com/w3c/wcag/issues/968
- https://github.com/w3c/wcag/issues/967

**Comment by alastc** [comment]
HI Jake, I think this one is done now?

Hard to tell because the links don't go to the right place anymore, but I did do a pass of WCAG 2.2 updates.

**Comment by jake-abma** [comment]
seems fine!
