### ISSUE TITLE
[Editorial] "Text Alternatives" reference

### ISSUE THREAD

**Issue by Malvoz** [w3c/wcag#1029]
In https://www.w3.org/TR/WCAG21/#dfn-text-alternative:

> NOTE
> 
> Refer to [Understanding Text Alternatives](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance) for more information.

Would you agree that the "Understanding Text Alternatives" link destination should be changed to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance#uc-text-alternatives-head? Since it is the section of interest.

**Comment by JAWS-test2** [comment]
Link to current version would be better: https://www.w3.org/WAI/WCAG21/Understanding/conformance#text-alternatives

**Comment by kfranqueiro** [comment]
Resolved by #1830
