### ISSUE TITLE
List of sufficient techniques for situation B seems to be not complete

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#103]
https://lists.w3.org/Archives/Public/public-comments-wcag20/2015Jun/0004.html 

Name: Jan Milde
Email: jmilde@opentext.com
Affiliation: 
Document: QR
Item Number: Success Criterion 4.1.2
Part of Item: 
Comment Type: editorial
Summary of Issue: List of sufficient techniques for situation B seems to be not complete
Comment (Including rationale for any proposed change):
In the document it says:
"Situation B: If using script or code [...]:
Exposing the names and roles, [...] and providing notification of changes *using one of the following techniques*:"

Then, obviously a list of techniques should follow, but there is one entry in that list. I assume there are supposed to be more than one entry.

Note: In "How to Meet Success Criterion 4.1.2" the list is completely empty.

**Comment by joshueoconnor** [comment]
Related to #104

**Comment by WayneEDick** [comment]
The obvious solution is to insert the WAI ARIA in for B.  ARIA1-ARIA 21 Apply.  
My only question is this.  There is variant behavior resulting from some of these techniques depending on Browser/ Assistive Technology.  There is a PFWG group addressing these issues but I do not know their progress as  yet.  Should we just list techniques that display consistent behavior across all browser / AT combinations or list them all? There has been considerable dissatisfaction among the developer community (those who really try to make this work) relating to this issue.

**Comment by WayneEDick** [comment]
Suggested change:
http://www.nosetothepage.org/I103.html

**Comment by joshueoconnor** [comment]
Working group surveyed about this suggested change https://www.w3.org/2002/09/wbs/35422/Sept1st2015/

**Comment by awkawk** [comment]
@WayneEDick, my IT is blocking your domain - can you provide the text on the wiki or somewhere else?

**Comment by joshueoconnor** [comment]
@WayneEDick The working group reviewed this item, and decided to wait until you were on a call to discuss further. The group felt it was a good idea, but not to throw every ARIA technique at it. Also what constituted a UI component is open for debate!

**Comment by joshueoconnor** [comment]
@WayneEDick Will it be possible to add the list to our wiki? Some people have problems seeing the nosetothepage domain. Thanks.

**Comment by WayneEDick** [comment]
Situation B: If using script or code to re-purpose a standard user interface component in a markup language:

    Exposing the names and roles, allowing user-settable properties to be directly set, and providing notification of changes using one of the following techniques: *
        ARIA1: Using the aria-describedby property to provide a descriptive label for user interface controls
        ARIA2: Identifying a required field with the aria-required property
        ARIA4: Using a WAI-ARIA role to expose the role of a user interface component
        ARIA5: Using WAI-ARIA state and property attributes to expose the state of a user interface component
        ARIA6: Using aria-label to provide labels for objects
        ARIA7: Using aria-labelledby for link purpose
        ARIA8: Using aria-label for link purpose
        ARIA9: Using aria-labelledby to concatenate a label from several text nodes
        ARIA10: Using aria-labelledby to provide a text alternative for non-text content
        ARIA11: Using ARIA landmarks to identify regions of a page
        ARIA12: Using role=heading to identify headings
        ARIA13: Using aria-labelledby to name regions and landmarks
        ARIA14: Using aria-label to provide an invisible label where a visible label cannot be used
        ARIA15: Using aria-describedby to provide descriptions of images
        ARIA16: Using aria-labelledby to provide a name for user interface controls
        ARIA17: Using grouping roles to identify related form controls
        ARIA18: Using aria-alertdialog to Identify Errors
        ARIA19: Using ARIA role=alert or Live Regions to Identify Errors
        ARIA20: Using the region role to identify a region of the page
        ARIA21: Using Aria-Invalid to Indicate An Error Field

    * ARIA Techniques are the recommended way to expose re purposing of standard user interface elements..

**Comment by WayneEDick** [comment]
Here is another possibility. Just refer to the ARIA Techniques as Follows:
Situation B: If using script or code to re-purpose a standard user interface component in a markup language.

WAI ARIA techniques are the preferred way to extend markup. They may be found at: Aria Techniques for WCAG 2.0

http://www.w3.org/TR/WCAG20-TECHS/

**Comment by WobleDuck** [comment]
This issue is ready for consideration. I have included a simpler form where
we just reference the WAI ARIA techniques document (ARIA Techniques for
WCAG 2.0).  This will then adjust as techniques are added to the document.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
