### ISSUE TITLE
Retiring technique H59 Using the link element and navigation tools

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1036]
From a recent question of w3c-wai-ig (https://lists.w3.org/Archives/Public/w3c-wai-ig/2020JanMar/0042.html) I'd propose retiring/removing this technique https://www.w3.org/TR/WCAG20-TECHS/H59.html

There is, to my knowledge, currently no support in user agents nor assistive technologies for this. And while it may be true that there are possibly extensions for modern browsers that can surface this information, I'd hazard a guess that they're not widely used/installed (because not much content out there uses the rel/rev attributes ... chicken and egg).

**Comment by alanfluff** [comment]
+1 (I was the question asker).

**Comment by patrickhlauke** [comment]
resurfacing this ... so what would be the process, if we agree that this is obsolete? remove it altogether (maybe just in 2.2)? add a note to it to say that it's effectively "nice idea, but browsers never bothered to actually do anything with this"?

**Comment by patrickhlauke** [comment]
Closed by https://github.com/w3c/wcag/pull/2970
