### ISSUE TITLE
Invalid language code used in G101 example 7 

### ISSUE THREAD

**Issue by dd8** [w3c/wcag#1039]
The W3 validator reports invalid `lang=jp` for 
https://www.w3.org/WAI/WCAG21/Techniques/general/G101.html

>Bad value jp for attribute lang on element span: 
>The language subtag jp is not a valid ISO language part of a language tag.

The correct language code is `lang='ja'` or `lang='ja-JP'`  

If you search the IANA registry for 'Description: Japanese' you can confirm this:
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by awkawk** [comment]
Thanks.
