### ISSUE TITLE
1.2.2 and 1.2.4 Non-Vocal Music Captioning Requirements

### ISSUE THREAD

**Issue by lauracarlson** [w3c/wcag#105]
Is non-vocal music exempt from captioning? For instance music recitals without vocals?

The Federal Communications Commission (FCC) established closed captioning rules, which state, "Also not required to have closed captions are programs that are mainly non-vocal music, such as a symphony or ballet performance."
http://nad.org/issues/television-and-closed-captioning/exemptions-closed-captioning-rule

Could non-vocal music please be addressed in Understanding SC 1.2.2
http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-captions.html
and 
Understanding SC 1.2.4
http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-real-time-captions.html

Thanks!

**Comment by lauracarlson** [comment]
I found the following text in a 2004 WCAG draft:
"Exception: If the content is a music program that is primarily non-vocal, then captions are not required."
http://www.w3.org/TR/2004/WD-WCAG20-20040730/#non-vocal-music

Was there a reason this verbiage was dropped from the spec? Perhaps in anticipation that instrumental music should be identified by title and artist perhaps described [1]? 

Perhaps one of our WCAG Working Group veterans know the background.

[1] http://www.washingtonpost.com/local/with-closed-captioning-music-can-help-tell-a-story/2013/07/24/18a172e2-f3d2-11e2-aa2e-4088616498b4_story.html

**Comment by cstrobbe** [comment]
I think the key here is to look at the [definition of captions](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-real-time-captions.html#captionsdef): 
> synchronized visual and/or text alternative for both speech and 
> non-speech audio information needed to understand the media content

The non-vocal music is addressed in "non-speech audio information needed to understand the media content". (This reminds me of captions that say what piece is being played, or what kind of music (e.g. "sad music"), or simply that some music is playing, depending on what the viewer needs to know to understand what is going on.)

**Comment by DavidMacDonald** [comment]
I don't remember any big discussions during that time about removing that line from the draft in 2004. My guess is that is what Christophe mentions above... usually there should be simple captions in music only videos, describing the music. That is what I've always done.
It is good to identify the type of music etc... I would also say that for music only, an organization is not running much risk if they place the name and type of music before the video rather than in the captions. However, strictly speaking, if there is audio, a deaf person needs to know in the captions any information that will help them understand the nature of that sound...

**Comment by lauracarlson** [comment]
Hi Christophe and David,

Thank you both for your input. It is very helpful.

So to help clarify, perhaps we could add an example in the "Examples of Success Criterion" sections [1] [2] along the lines of:

*   **A non-vocal music**
       * An orchestra provides captions at each performance, which identifies music by title, movement, composer, and any information that will help the user understand the nature of the audio.

End proposed text.

So maybe captions for that could be something such as:

[Orchestral Suite No. 3.2 in D major, BWV 1068, Air in D major]
 [Johann Sebastian Bach Composer] 
♪ Calm melody with a slow tempo ♪

[1] http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-real-time-captions.html#media-equiv-real-time-captions-examples-head

[2] http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-captions.html#media-equiv-captions-examples-head

**Comment by lauracarlson** [comment]
As discussed in the July 21, 2015,  [WCAG WG Meeting](http://www.w3.org/2015/07/21-wai-wcag-minutes.html#item02) the [proposed text](https://github.com/w3c/wcag/issues/105#issuecomment-118034823) should be ready for survey.

**Comment by lauracarlson** [comment]
I've updated the text per the August 25 survey editorial suggestions. 

@awkawk the text should be ready to be incorporated into the docs. Thank you!

**Comment by awkawk** [comment]
Accepted by group August 25: http://www.w3.org/2015/08/25-wai-wcag-minutes.html#item06

**Comment by awkawk** [comment]
Integrated into media-equiv-captions.xml (https://github.com/w3c/wcag/commit/dc54f22107aa92a8417cbc2fec20e3014becc8ed#diff-fb7d2879576fd446302750c4aef11456) and media-equiv-real-time-captions.xml (https://github.com/w3c/wcag/commit/ff893b14087fb69441c730b3aa59194e1e34439c#diff-378995cf4734095267c148c487db6f3a)
