### ISSUE TITLE
Understanding Success Criterion 1.2.2: Captions (Prerecorded) (e.g., for images)

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#1051]
Understanding Success Criterion 1.2.2: Captions (Prerecorded)
[https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded.html](url)

Intent (third paragraph)
`Captions are not needed when the synchronized media is, itself, an alternate presentation of information that is also presented via text on the Web page. For example, if information on a page is accompanied by a synchronized media presentation that presents no more information than is already presented in text, but is easier for people with cognitive, language, or learning disabilities to understand, then it would not need to be captioned since the information is already presented on the page in text or in text alternatives (e.g., for images).`

The (e.g., for images) is confusing. Images do not have captioning, or is this saying that an image can be used in the place of video captions, if it is an alternate presentation of information?

Any feedback appreciated

**Comment by JAWS-test** [comment]
The video can be a second method to display information that is present on the page in text or graphic form. The text or the text alternative of the graphic is then sufficient to perceive the information. In this case, the video does not need to be accessible, i.e. it does not require captions

**Comment by LaurenceRLewis** [comment]
Thanks @JAWS-test That makes sense. The way the paragraph is written I was not sure.
