### ISSUE TITLE
2.4.11 Focus Visible (enhanced) is included in the 2.1 Understanding Documentation

### ISSUE THREAD

**Issue by JasonAment** [w3c/wcag#1054]
Why is 2.4.11 Focus Visible (Enhanced) included in the WCAG 2.1 Understanding document?  Shouldn't the Understanding document be scoped to just the SC's that are relevant to 2.1?

[WCAG 2.1 Understanding](https://www.w3.org/WAI/WCAG21/Understanding/)
[2.4.11 Focus Visible (Enhanced) Understanding](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible-enhanced)

![screenshot showing the presence of the focus visible enhanced link](https://user-images.githubusercontent.com/16707962/75562999-6805d780-59fe-11ea-8047-7446bc676753.png)

I recommend removing the reference to 2.4.11 Focus Visible (Enhanced) from the Understanding Documentation for 2.1 and include it only in the 2.2 Understanding documentation.  

For reference, the [WCAG 2.0 Understanding](https://www.w3.org/TR/UNDERSTANDING-WCAG20/) does not include any of the 2.1 updates in it.

**Comment by patrickhlauke** [comment]
Related https://github.com/w3c/wcag/issues/1043 - seems the generator fix still surfaced 2.4.11 when it shouldn't @michael-n-cooper @alastc

**Comment by alastc** [comment]
Hi @JasonAment,

I'm afraid that will happen because we only have one place (hopefully soon under /wcag/ instead of /wcag21/) for the informative documents (understanding & techniques).

We've added a status indicator for the new documents, like so:
https://w3c.github.io/wcag/understanding/focus-visible-enhanced 

That should appear on the version you linked soon.

Cheers,

-Alastair

**Comment by patrickhlauke** [comment]
@alastc how will this "single place" approach handle if an SC is changed (per recent discussions about moving SCs to different levels, or even making normative changes to the actual SC text)? i'd have thought it would make more sense to make clearly versioned and separate understanding resources
