### ISSUE TITLE
Grammar and clarity of SC2.4.11 Focus Visible (Enhanced)

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1055]
Could I suggest a number of minor changes to the wording of SC2.4.11, as currently seen in the 7 Feb Editor's Draft, to correct grammar, use correct words, and improve technical accuracy, and also some further changes to make the SC easier to understand? Nothing here is to change the sense of what it says (I hope, but correct me if I have inadvertently suggested something that would change it). It is solely to make it  grammatically correct and more easily understandable. 

At the moment it contains a number of phrases that I think are difficult to understand. These will lead to misunderstanding, confusion and argument, and result in designers and developers making errors as a result. (In fact I see someone has already said they didn't understand part of it in one of the other discussions here on GitHub before it was even released!) It is better to say things clearly even if it means adding a few more words.

And while the Understanding documents are necessary for full understanding of many WCAG success criteria, I do believe that each SC should at least be clear in its basic intention without needing the Understanding document to say what it even means at the most basic level. I don't think that is true in the case of SC2.4.11. An SC is normative, while its Understanding document is merely non-normative. The Understanding can therefore give examples to assist understanding, but the SC should be understandable on its own merits or you have no normative rule!.

I've numbered the items below so we can refer to them individually when making comments. At the end of this you'll find a complete version of how the SC would read if these suggested changes are included. (And sorry for the strange indenting, I don't know if there's a way to break numbered items into paragraphs more cleanly.) 

And for simplicity I refer to the three checkpoints "Minimum area", "Focus contrast", and "Contrast and thickness" as the !st, 2nd and 3rd checkpoints respectively. 

1.	**First paragraph:** "...displays a visible keyboard focus...". 
The keyboard "focus" is a position in the content on screen (i.e. where the focus currently is). It can't be displayed - a "focus indicator" is displayed to indicate where the focus position is. It is the indicator that is "visible" not the focus. 
So the SC should read: "...displays a visible keyboard focus indicator...".

2.	**2nd checkpoint:** I'll discuss the second checkpoint first because it's the easiest one. In the words "...at least a 3:1 contrast ratio...", the word order here seems a bit clumsy (though this may be me being overly-sensitive!)
Word it as "...a contrast ratio of at least 3 to1..."

3.	"... with the colors changed from the unfocused control." 
Also in the first checkpoint, these words are ungrammatical and don't make sense (not to my admittedly simple mind anyway!). 
Say "...with the colors of the unfocused control."

4.	The above sentence also needs the insertion of the word "corresponding", or similar, to convey the idea that, where a focusable component consists of more than one color, it is not saying that all colors of the focused control must have 3 to 1 contrast with all colors of the unfocused control. It is only saying the color of each individual part of the focused control should have 3 to 1 contrast with the color of the correspondingly same part of the unfocused control, if that part has changed colour. (Clarification will still be needed in the Understanding, but adding this one word will make it clear for most people.) 

      So the 2nd checkpoint becomes:
"Color changes used to indicate focus have a contrast ratio of at least 3 to1 with the corresponding colors of the unfocused control."

5.	I would also suggest adding the explanation about corresponding colours, just given in the previous item above, into the Understanding document to further clarify what is meant for color change indicators.

6.	**1st checkpoint:** As currently worded, the phrase "focus indication area" is used in two different ways in this SC. In the first checkpoint it is referring to the number of CSS pixels in the area, not the area itself. But the same phrase in the third checkpoint is concerned with the area itself, and the color contrast it has, not the number of pixels in it. 

      You can't use the same term for two different things (so the glossary definition cannot be referred to in both places)! So I think it would be more explicit, and therefore easier to understand, if the first checkpoint says:
"the number of CSS pixels that change color to provide the focus indicator..." 

7.	"...is greater than or equal to the longest side of the bounding rectangle of the focused control, times 2 CSS pixels". 
This is difficult to understand. What does it mean to multiply a side of a rectangle by 2 pixels? Mathematically that is not a correct thing to say. Also it should be the number of CSS pixels in the "length" of the longest side, not just "the longest  side". 
Say, "...is greater than or equal to twice the length, in CSS pixels, of the longest side of the bounding rectangle of the focused control."

8.	So taking the previous two items together, the whole checkpoint would become:
"the number of CSS pixels that change color to provide the focus indicator is greater than or equal to twice the length, in CSS pixels, of the longest side of the bounding rectangle of the focused control."

9.	And since it is referring to a number of CSS pixels rather than an area, I think the name of this first checkpoint would be better "Minimum pixels" rather than minimum area. (The two detailed references in the text of the checkpoint make it clear we are talking about CSS pixels, so no need to include that word in the name, to keep it short.)

10.	It is also extremely difficult to decipher, from the SC's current wording, whether the first and third of the three checkpoints apply only to outline indicators, or to both outline and colour change indicators. This confusion arises because they both refer to the "focus indicator area" which is defined in the glossary as "The number of CSS pixels that change between the focused and unfocused states...". That wording can include colour change indicators, since pixels in the component certainly change (color) between the focused and non-focused states. 

      That is how I understood the 1st checkpoint when I first read this SC - that it covered both colour change indicators and outlines. On reading the Understanding document this appears not to be the intention. But whichever one of these interpretations is correct, the SC should make it clear. The 2nd checkpoint says "Color changes used to indicate focus" to make clear what it is talking about - I think the 1st and 3rd checkpoints should do similarly. 

      The corresponding way to do this is to say "In outlines used to indicate focus.....". But the wording would have to allow for various structures including outlines, borders, underlines, side lines, circles and other shapes as seen in the examples in the Understanding document. So to keep it generic I think we can say "outlines or other shapes": That rules out the colour change indicators.

      So start the definition of the 1st checkpoint with the words:
"In outlines or other shapes used to indicate focus....."

      If I am wrong in this understanding and the checkpoint actually applies to both type of indicator, then those extra words should be (or it could be stated in a Note under the SC):
"In color changes and in outlines or other shapes used to indicate focus....."

11.	**3rd checkpoint:** When I first read this SC I understood the 3rd checkpoint, "Contrast or thickness", to cover both colour change indicators and outlines. I wasted some time due to that misunderstanding. It was only when I read the Understanding document that I realised it was not intended for colour change indicators. And I notice someone else has also misunderstood that point in one of the other GitHub discussions, and had to be corrected. If people experienced in the WCAG can make that mistake, then how many developers and others will do so? 

      As with the first checkpoint, start with 
"In outlines or other shapes used to indicate focus....."

      As above, if the checkpoint actually applies to both type of indicator, then those extra words should be:
"In color changes and in outlines or other shapes used to indicate focus....."

12.	A second reason the previous item must explicitly exclude indicators where the whole component changes its colors is because otherwise it would allow any contrast, no matter how minimal, because the whole component is always going to be more than 2 CSS pixels thick, for any component that is more than 2px in height - so no need to consider the first part of the either/or, the contrast! 

13.	"The focus indication area has a 3:1 contrast ratio against all adjacent colors for the minimum area or greater..."
In the 3rd checkpoint these words are meaningless and confusing. You can't have "colors for" an area.  Presumably "colors of the minimum area" is meant here. But even with that change it is still not clear what is meant here. 

      The problem is in trying to use the word "area", when what we are really talkng about is a number of CSS pixels. "Area" implies the whole area contained inside a container. Here we don't mean the area inside the outline, we only mean the actual pixels making up the outline itself. Area is a two dimensional shape, not a number. So we should say "number" not "area". 

      And the word "either" could be added as well to go with the "or". So I think the whole thing would be clearer if it says:
"either the minimum number of CSS pixels of the focus indicator have a 3 to1 contrast against all adjacent colors, or the focus indicator has a thickness of at least 2 CSS pixels."

14.	"...has a thickness of at least 2 CSS pixels"
Having said that last item, I think there is a mistake in logic here. It seems to me that the 3rd checkpoint, as stated in the draft, allows an outline, for a button for instance, to be of almost no contrast at all with the button, or even the same color as the button, providing it is 2px thick. This works if it is an outline outside the button (which I guess was the intention?) because the the button is now structurally bigger than it was so is visible that way. But many designers put the outline inside the button or component. That would clearly make the non-contrasting indicator in this example invisible. So we need to add a further condition to stop that.

      Make it "...has a thickness of at least 2 CSS pixels and is outside the boundary of the unfocused control"

15.	**Accessible terms:** Given that when discussing accessibility good practice we always tell our readers and listeners to write dashes as "to" not a dash, so that ranges and ratios, for instance, are written as "3 to 1" not "3 - 1", should we not follow our own advice? (Because, of course, many screen readers (in their default state - as used by newbies and non-technical people who may not know they can change how their reader announces things) will announce this ratio as "three one", which is not the same thing at all.) 

      If we don't follow our own good practice advice, especially in the wording of the WCAG itself and also in the associated Understanding and other associated documents, how can we expect designers and developers to do so!

      So I suggest both references to this in the SC, and all the references in the Understanding document, should be changed to "3 to 1".

16.	**Glossary:** In the glossary definition of "Focus indication area..."
The words "The number of CSS pixels that change.." confuses the length of the longest side with the area. The words "The number of" should not be here in the definition of the area, they should be in the SC itself in the first checkpoint where it is calculating the number of pixels, but not in the "Contrast or thickness" checkpoint where it is talking about the actual area and its color contrast. (Also see earlier item above.)

      Reword it in the glossary and the Understanding document to "The pixels that change..." But in any case I have not included this term "Focus indication area..." in these reworded SC checkpoints, because, to my mind, having to look up the glossary just makes understanding an already difficult SC even more difficult, and not referring to the glossary hasn't added many extra words in the end. 

17.	In the above I have also suggested the use of "focus indicator" rather than "focus indication", as already used throughout the Understanding document, as the former is the term I believe web developers, document writers and most other people use (hence why the Understanding doc does). I realise indication has probably been chosen because it is more abstract, but in my personal opinion this just makes the SC that little bit more difficult to understand precisely because "focus indication" is not the term many people would use in real life.

### Final comments

NB: When I said above that these checkpoints are difficult to understand, I don't mean by just us in the accessibility industry, I mean especially by designers and developers and managers and other non-accessibility people who have to try to implement the WCAG. We have to think how they might understand what we say. The WCAG has a reputation in the web industry for being notoriously difficult to follow! But I think at least some of these suggested changes will help make this new SC easier to understand and follow.

**Applying all the above recommendations would produce the following:**

### Complete amended wording

"When a User Interface Component displays a visible keyboard focus indicator, all of the following are true:

**Minimum pixels:** In outlines or other shapes used to indicate focus the number of CSS pixels that change color to provide the focus indicator is greater than or equal to twice the length, in CSS pixels, of the longest side of the bounding rectangle of the focused control.

**Focus contrast:** Color changes used to indicate focus have a contrast ratio of at least 3 to1 with the corresponding colors of the unfocused control.

**Contrast or thickness:** In outlines or other shapes used to indicate focus either the minimum number of CSS pixels of the focus indicator have a 3 to1 contrast against all adjacent colors, or the focus indicator has a thickness of at least 2 CSS pixels and is outside the boundary of the unfocused control"

### And a green Note

I also think the statement in the Understanding document, "A 1px wide vertical line (such as a blinking cursor) would not pass the size requirement, a text input would need a larger or separate focus indicator." is so important that it is worthy of being a green Note under the SC, where it will be seen be everyone not just those who plow through the Understanding.

I hope the above items all make sense, but please feel free to challenge any of them!

**Comment by alastc** [comment]
Hi Guy,

I haven't worked through all of this yet, but a key part is the definition of what the indicator is, or can be.

Wording it as "In outlines or other shapes" means a lot of (perfectly visible) indicators would be scoped out. For example, switching background colours on a button.

Focusing on the "change of pixels" enables maximum flexibility. Perhaps a more directive approach is better, that's an open question, but I am concerned that it scopes out reasonable options.

**Comment by guyhickling** [comment]
Thank you Alastair, that does clarify some of it. So you are saying that the Minimum Area and Contrast or Thickness checkpoints (both? or just one of them?) apply to colour-change indicators as well as to the outline/line type of indicator? That's ok, but then that needs to be made clear in the SC itself. 

I'm not trying to exclude colour indicators (colour reversals are good indicators), or to say the first and third checkpoints don't apply to them. What I am trying to say here is that, whatever indicators each checkpoint applies to must be specifically stated so people are not in doubt - and I believe that must be done in the normative SC, not in the Understanding so developers et al. cannot contest it or misunderstand it. 

To have a situation where people have to sit down for ages to think it all over to work out what the SC applies to, or worse still come to the wrong conclusion because it has not been made clear, is wrong. It leads to confusion and wrong decisions.

One other thing, we will need more in the Understanding document to explain how the first and third checkpoints apply to colour-change indicators, because I'm not certain I understand that yet!

**Comment by guyhickling** [comment]
So we could change "In outlines or other shapes used to indicate focus...." to "In colour changes and outlines and other shapes used to indicate focus..."

**Comment by alastc** [comment]
> So you are saying that the Minimum Area and Contrast or Thickness checkpoints (both? or just one of them?) apply to colour-change indicators as well as to the outline/line type of indicator?

All apply, I think the confusion might be the assumption that it is a shape or outline. The  success criteria revolves around the "focus indication area", each bullet applies to the _change_, whatever the change is.

Also consider that any perceptible change in a pixel will be a change of colour, that doesn't differentiate indicators types.

Looking at the current 1st bullet:
> Minimum area: The _focus indication area_ is greater than or equal to the longest side of the bounding rectangle of the focused control, times 2 CSS pixels. 

and proposed:
> Minimum pixels: In outlines or other shapes used to indicate focus the number of CSS pixels that change color to provide the focus indicator is greater than or equal to twice the length, in CSS pixels, of the longest side of the bounding rectangle of the focused control.

So the changes are:
- Narrower scope of what it applies to (outlines & shapes only);
- Pulls the definition of the focus indication area into the SC text;
- Doesn't use the word "area", which I think is a concept it needs, otherwise people assume it is bounding boxes only.

**Comment by guyhickling** [comment]
> Narrower scope of what it applies to (outlines & shapes only);

No, I'm not trying to limit the scope in any way. I'm just trying to ensure that everybody who reads it can understand what that scope is, because it certainly doesn't seem clear at the moment (it is to those of us who have been thinking about it for a long time - but not to developers who come upon it for the first time). So my suggested wording (as revised) for items (10) and (11) of "**In colour changes and outlines and** other shapes used to indicate focus..." I think makes that clear. It spells it out.

> Pulls the definition of the focus indication area into the SC text

Yes it does, for the reason given above. I.e. that "the phrase "focus indication area" is used in two different ways in this SC. In one place, the first checkpoint, it is referring to the **number of CSS pixels** in the area, not the area itself. But the same phrase in the third checkpoint is concerned with **the area itself, and the color contrast it has**, not the number of pixels in it."

That's trying to use the same glossary definition for two different things. That doesn't work, it's not logical! It's a contradiction.

The answer is, yes, to pull part or all of the definition into the SC text. I happen to think having the whole thing in the SC makes it easier to understand (which I worded it the way I did). But we could no doubt achieve something where part is still in the glossary if you prefer, but only the part that applies in both cases.

> Doesn't use the word "area", which I think is a concept it needs, otherwise people assume it is bounding boxes only. 

But "bounding boxes" is precisely what the SC does mean - in the case of outline indicators it does mean the actual pixels of the bounding box! It doesn't mean the area enclosed inside the outline (that only works for colour change indicators). That's what all that stuff in the Understanding document about "...at least a 2px line along the longest side..." is about. I think there is some confusion here because the SC is again trying to use the same term "area" for two different things, for the number of pixels in a thin outline and for whole-component colour changes. 

On the other hand, "number of CSS pixels" in the outline seems to me much clearer, because it can be applied both to the four lines in an outline, and to the area of a colour change. But I'm open to other suggestions for it.

So I hope we can apply most of the amendments I've suggested at the start of this thread (or things similar), but with the new revised wording we've arrived at for items (10) and (11), to make it clearer and easier to understand.

**Comment by kerstinp** [comment]
@all 

I want to jump in for a short comment on "bounding box". "bounding box" (BBox) is a technical term in PDF, please find a very short explanation here at the bottom of the page: https://www.prepressure.com/pdf/basics/page-boxes. In case "bounding box" will be used I think a detailed explanation in the glossary is needed for what is meant and especially what is not meant to avoid any misunderstandings. Personally I would prefer not to use a technical term (like "bounding box" and possibly not "box" at all) when it has a special meaning in a technology which is also covered by WCAG to avoid misunderstandings, confusions and discussions. 

Cheers

Kerstin

**Comment by alastc** [comment]
Hi Guy,

After running through the larger changes, I'm just looping back to see if any of the points above remain to tackle.

I think most things have been covered in the [updated version](https://raw.githack.com/w3c/wcag/wcag22-focus-visible-enh-updates/understanding/22/focus-visible-enhanced.html), but a couple of things I didn't adjust:

4. "Color changes used to indicate focus have a contrast ratio of at least 3 to1 with the **corresponding** colors of the unfocused control."

That bullet is now:
"**Change of contrast**: Color changes used to indicate focus have at least a 3:1 contrast ratio with the colors changed from the unfocused control."

I think "changed" is a better term, corresponding makes me wonder what it is corresponding to?

5. Not changing due to 4, but it did remind me to rename the sections of the understanding, and re-order to match the SC text, thanks!

6. Ah, the 'number of' does make the third bullet less clear. Our test for that is to include the definition in the SC text and see if it holds up (being flexible on tense/grammar). That would result in: 
> **Minimum area**: The pixels that change between the focused and unfocused states of a User Interface Component is greater than or equal to a 1 CSS pixel border of the focused control.
> **Adjacent contrast**: The pixels that change between the focused and unfocused states of a User Interface Component (have) a 3:1 contrast ratio against all adjacent colors for the minimum area or greater, or (have) a thickness of at least 2 CSS pixels.

9. Area vs pixels: I'm not sure that helps, and I'd like to keep some indication that it is not just a border but is somewhat flexible.

10 - 14, I see where you're coming from, but I would rather explain it better in the understanding that make the SC text (appear) more prescriptive. I've re-written the top of the "Size of indicator" section, now called "Minimum area" to match the SC text.

15. Good point, we had an issue from a screenreader user making a slightly different suggestion, which is easier to keep in line with all the current documentation from 2.0/2.1.

I think that was it, I'll commit some changes and the previous should update soon.

Cheers,

-Alastair

**Comment by scha14** [comment]
Hi @guyhickling, with the edited current version @alastc mentioned above and the [updated version which is option 3 in this document](https://docs.google.com/document/d/1F83m-HXRkXz1QCF6_QNtQGzIULugMiFSLgtqDRgKA-s/edit#), are there remaining concerns we can address?

**Comment by guyhickling** [comment]
Well, that dreadful "bounding rectangle" clause (item 7 above) has been deleted, and items 1 and 17 above are fixed, and item 6 reworded, so those are some improvements. The SC is still lacking in clarity somewhat but I know that isn't going to change now.

The new 2.2 Editors Draft released yesterday is still showing the originally drafted 2.4.11 - when will the new version you link to above be added into the draft?

**Comment by alastc** [comment]
Hi Guy, we're aiming to get a wide review do with all the new SCs out by the end of the month.

**Comment by guyhickling** [comment]
Alastair, thank you for letting me know. So does that mean all comments are wanted before the end of the month? Or will a few more SCs appear before then? I am looking at the moment at the new SCs in the draft released a couple of days ago.

**Comment by scha14** [comment]
@guyhickling we should have a new draft with some more changes in the next two weeks. Will post the most updated drafts here. Thank you!

**Comment by guyhickling** [comment]
@scha14 Thank you.

**Comment by scha14** [comment]
Hi @guyhickling the changes to the SC are in the [draft here](https://www.w3.org/TR/WCAG22/#focus-visible-enhanced). Please let me know if this issue is okay to close. Thank you!

**Comment by guyhickling** [comment]
That link is to the first draft way back in February. Can you send the link to the finally revised wording?

**Comment by scha14** [comment]
Sorry about that @guyhickling. [Here is the PR](https://github.com/w3c/wcag/pull/1121/files) and [preview of changes](https://raw.githack.com/w3c/wcag/wcag22-focus-visible-enh-updates/understanding/22/focus-appearance-enhanced.html)

**Comment by alastc** [comment]
The editors draft has the latest as well: https://w3c.github.io/wcag/guidelines/22/#focus-appearance-minimum

**Comment by scha14** [comment]
Hi @guyhickling, is this good to close?

**Comment by guyhickling** [comment]
@scha14 There's just one point, the title of this issue is now wrong as the SC2.4.11 has been renamed to "Minimum" instead of "Enhanced". Should that be changed before closing it, or doesn't it matter now since we're closing it? 

I have just one suggestion to make for the new Unobscured bullet point in 2.4.11, but that is best raised in a new issue (I've just added #1271) as it is a 4th bullet newly added. 

Apart from that, most of the changes I wanted have been incorporated or the text reworded, so I'm happy with the wording now. (With the exception of the either/or contrast which I still believe leaves a loophole for developers to provide poor indicators, but that was rejected by the WG so is covered.)

So yes, you can close this issue. Many thanks.

**Comment by scha14** [comment]
Thank you @guyhickling for raising this and helping add clarity to the SC. Closing this issue.
