### ISSUE TITLE
2.2.2 Is Play/Pause button mandatory for Carousels?

### ISSUE THREAD

**Issue by mkkwon** [w3c/wcag#1066]
I noticed that in all the examples of accessible carousels, they've always had a Play/Pause button to toggle whether the carousel is paused or resumes play, seen in links below:
* https://www.w3.org/WAI/tutorials/carousels/working-example/
* https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190814/examples/carousel/carousel-1.html

However, looking at all the guidelines, from https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=222#pause-stop-hide to https://www.w3.org/WAI/WCAG21/quickref/#keyboard, there's no clear indication that there *must* be a play/pause button.

Therefore, if user clicks on the previous/next carousel button OR any of the individual slide selection button and that prompts a PAUSE action, **would that suffice for meeting criteria 2.2.2?** 
An example of clicking on slide selection controls pausing the carousel can be seen at https://www.blizzard.com/en-us/

//edit: speaking on the play/pause topic, would hovering to pause also fulfill this requirement? Seen here: https://www.w3.org/TR/wai-aria-practices/examples/carousel/carousel-1.html

"Hovering the mouse over any carousel content pauses automatic rotation. Automatic rotation resumes when the mouse moves away from the carousel unless another condition, such as keyboard focus, that prevents rotation has been triggered."

**Comment by patrickhlauke** [comment]
for avoidance of doubt: pausing on mouse hover *alone* does not solve the problem for keyboard-only users. only in combination with a similar way for keyboard users to achieve the same.

further, i'd also say that only pausing on hover or if a part of the carousel itself has focus will not help users that are currently trying to interact with/read/etc other parts of the page. for those users, the carousel will be a constant distraction, which is exactly what this SC is trying to prevent. so while a play/pause button per se is not hard required, it's one of the best ways to pass the requirement of the SC that there be "a mechanism for the user to pause, stop, or hide it"

**Comment by patrickhlauke** [comment]
still doesn't mean mechanism HAS to be play/pause button - could be a setting somewhere in your account preferences, taking a hint from any `prefers-reduced-motion` browser setting, etc. the mechanism itself can be argue over...
