### ISSUE TITLE
SC 2.1.1: these two advisory techniques are not applicable

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag#107]
These two techniques (yet to be detailed) do not fit in with the requirements of this SC. 
Developers sometimes  consider implementing them  to help better conformance with this SC.
• Providing keyboard shortcuts to important links and form controls (future link)
Comment: This only facilitates quick navigation / findability but does not fix something that is not keyboard operable. 
• Using unique letter combinations to begin each item of a list (future link)
Comment: Again, this helps quick nav / findability  for screen reader users for example like in a list of links.
It does not fix something that is not keyboard operable.

Please consider deleting these from the advisory techniques for this SC.
Thanks,
Sailesh Panchang

**Comment by mraccess77** [comment]
Advisory techniques document is very clear http://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation.html

"These techniques are not required or sufficient for meeting any success criteria, but can make certain types of Web content more accessible to more people."

These items do make content more accessible to people with disabilities and thus should stay.  We have no other place to put things like this -- removing them would be a lose.

**Comment by spanchang** [comment]
If "These techniques are not required or sufficient for meeting any success criteria, but can make certain types of Web content more accessible to more people", then all advisory techniques should  perhaps be listed under one heading and not be made  SC-specific. 
In this instant case, for instance, as pointed out by the first comment, the advisory techniques  may facilitate navigation which is different from the goal of this SC i.e. providing keyboard operability.
Thanks and regards,
Sailesh

**Comment by mraccess77** [comment]
Shortcuts are more than navigation -- they are about making keyboard operation easier.  Advisory statement is clear advisories do not allow you to meet success criteria but make things easier -- and they do that.  For example, control+p to print makes keyboard operation easier for a user sot hey don't have to press multiple keys to operate the print button.

**Comment by mraccess77** [comment]
Advisory can be mapped to guidelines such as SC 2.1 but my guess is that those pages are far less looked at and since 2.1.1 is the primary success criteria dealing with keyboard access for A and AA it's the best place to call these things to people's attention.

**Comment by spanchang** [comment]
>> Shortcuts are more than navigation -- they are about making keyboard operation easier.
Agreed, but an accesskey does not make an element that is not keyboard operable work from a keyboard interface. 
>> control+p to print makes keyboard operation easier 
Yes sometimes. 
Depending on the browser it may trigger the action or simply move focus to the element, no?  
>> Advisory can be mapped to guidelines such as SC 2.1 but my guess is that those pages are far less looked at ... 
It is misleading to  place these techniques at SC level when The "How to meet" techniques template does have a place for advisory techniques at guideline level. 
A note under every SC can remind readers to review guideline specific techniques too. That will dispell your apprehensions then.

**Comment by spanchang** [comment]
>> Shortcuts are more than navigation -- they are about making keyboard operation easier.
Agreed, but an accesskey does not make an element that is not keyboard operable work from a keyboard interface. 
>> control+p to print makes keyboard operation easier 
Yes sometimes. 
Depending on the browser it may trigger the action or simply move focus to the element, no?  
>> Advisory can be mapped to guidelines such as SC 2.1 but my guess is that those pages are far less looked at ... 
It is misleading to  place these techniques at SC level when The "How to meet" techniques template does have a place for advisory techniques at guideline level. 
A note under every SC can remind readers to review guideline specific techniques too. That will dispell your apprehensions then.

**Comment by mraccess77** [comment]
Proposed draft response for survey: Thank you for your feedback and the resulting helpful discussion.  While these techniques do apply to keyboard operability as a whole the placement of the advisory techniques under SC 2.1.1 rather than Guideline 2.1 allows these techniques to be displayed in the Understanding WCAG 2.0 and How to Meet WCAG 2.0 documents in prominent locations within success criteria that will likely be seen by people looking for ways to create and supplement keyboard access.  In regards to your concern that these techniques talk about supplementing keyboard access that already exist and not providing the primary access -- the understanding documents are clear that advisory techniques are not required to meet a success criteria and do not imply that a success criteria has been met.  Thus, inclusion of the advisory techniques does not indicate an endorsement that these be implemented.  At this time these advisory techniques will remain in their current location.

**Comment by awkawk** [comment]
Proposal accepted by group http://www.w3.org/2015/08/25-wai-wcag-minutes.html#item06

No change to be implemented at this time.
