### ISSUE TITLE
4.1.1 Parsing - Exception for custom attributes other than data-*?

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#1078]
Currently, our test procedure for 4.1.1 Parsing is basically
- run W3C validator on the page
- Run Paciello's Validate bookmarklet on the result page of validation

We noticed that custom attributes that do not use the data-* format, like Angular's ng-* attributes, will cause validation errors that remain after filtering results with the Validate bookmarklet.

- Is there any reason to expect that the use of such custom attributes will cause a11y problems?
- If not, should we introduce an exception for validation errors that are down to the use of custom attributes?
- Finally (and this is basically an aside question to Paciello, @patrickhlauke ) should the Validate bookmarklet filter out common cases like ng-*?

**Comment by patrickhlauke** [comment]
> In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features.

custom attributes are not arguably covered by the normative wording of the SC. and they're unlikely to cause any real-world accessibility problem (unless browsers have a bad reaction to an accidentally unclosed attribute that leads them to drop the following valid/necessary attribute on the floor somewhere, but then that would result in some other visible/noticeable problem - e.g. under 4.1.2 or 1.3.1)

the TPG bookmarklet should simply filter out/ignore ANY warnings about attributes, i'd say... /cc @stevefaulkner

**Comment by stevefaulkner** [comment]
@patrickhlauke  @detlevhfischer  note that this has been partially implemented via a PR from Dennis Lembree an age ago https://github.com/stevefaulkner/wcagparsing  the source is there and PRs are welcome.

**Comment by patrickhlauke** [comment]
Aha, so an older version of the bookmarklet floating around somewhere (possibly from here ? https://developer.paciellogroup.com/blog/2015/11/wcag-2-0-parsing-criterion-is-a-pita/)

**Comment by patrickhlauke** [comment]
(assume this issue here can be closed, as it's fairly clear from the normative language of the spec that attributes - other than duplicate attributes and non-unique IDs - do not fall under the SC's purview)

**Comment by alastc** [comment]
Detlev, I think the answers to your questions were:
- No
- Not applicable
- Yes (and it does now)

Closing, please re-open is there is something un-answered...
