### ISSUE TITLE
Addition to paragraph under 3.1

### ISSUE THREAD

**Issue by lauracarlson** [w3c/wcag#1094]
Regarding the following paragraph under [3.1  Treatment of 3rd party content and Statements of Partial Conformance](https://w3c.github.io/wcag/conformance-challenges/#Challenge-3.1):

> Such approaches may add substantial friction, especially to individual website visitors and users, to the point that they may be disinclined to make contributions. Further, they aren't a guarantee of perfection in those contributions (Is the ALT text thoughtfully authored, or just filler text to make the upload happen? Did the text truly avoid reference to sensory characteristics?)…

To present the other side of the matter suggest adding the following sentence: 

> On the other hand, such approaches may offer a great opportunity to help educate users and provide a teachable moment that would help make accessibility practices more ubiquitous.

**Comment by peterkorn** [comment]
Thank you for this suggestion Laura.  At the end of each of the mitigation descriptions for the 4 challenges, there is a sentence discussing the value of that approach.  I would just tack your proposed language onto that final sentence.  Thus the final sentence of the final paragraph of Challenge #3 would read:

Nonetheless, these are some approaches to consider to help minimize the amount of 3rd party content that poses accessibility challenges, which may also offer a great opportunity to help educate users and provide a teachable moment that would help make accessibility practices more ubiquitous.

**Comment by lauracarlson** [comment]
Hi Peter,

Works for me.

Thank you,

Laura

**Comment by sajkaj** [comment]
Text is now in [Editor's Draft](https://w3c.github.io/wcag/conformance-challenges/).

**Comment by lauracarlson** [comment]
Thank you, Janina.

On 4/7/20, sajkaj <notifications@github.com> wrote:
> Closed #1094.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag/issues/1094#event-3208940924


-- 
Laura L. Carlson
