### ISSUE TITLE
4. Robust: Duplicated "by" in sentence

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#1098]
In the normative 2.1 spec, the principle "Robust" is explained with a short sentence that includes two words "by" beside one another:

> Content must be robust enough that it can be interpreted by by a wide variety of user agents, including assistive technologies.

https://www.w3.org/TR/WCAG21/#text-alternatives

**Comment by anevins12** [comment]
Related? https://github.com/w3c/wcag/issues/488

**Comment by awkawk** [comment]
Thanks. This has been identified as an erratum: https://github.com/w3c/wcag/issues/374

**Comment by awkawk** [comment]
#488 is related in that it duplicates the same word. :) 

That one has the "errata" label which indicates that the group already approved it as an Erratum.
