### ISSUE TITLE
Update G65 breadcrumb technique to follow the HTML5 pattern?

### ISSUE THREAD

**Issue by lauracarlson** [w3c/wcag#110]
In the HTML5 specification a nav element, an unordered list element, and a right arrow symbol → are recommended to mark up breadcrumbs. Please consult [4.12.2 Bread crumb navigation](http://www.w3.org/TR/html5/common-idioms.html#rel-up).

Example markup from the HTML5 spec:

```
<nav>
<h2>You are here:</h2>
<ul id="navlist">
<li><a href="/">Main</a> →</li> 
<li><a href="/products/">Products</a> →</li> 
<li><a href="/products/dishwashers/">Dishwashers</a> →</li> 
<li><a>Second hand</a></li> 
</ul>
</nav>
```

HTML5 discourages the use of the right angle bracket symbol ">" to indicate path direction as it is "not clearly conveyed to all users." 

Assistive technology  announces how many items are in a list, which can be helpful. The nav element would make information more useful. Both provide good semantic information. &lt;nav&gt; and &lt;ul&gt; elements are  supported by browsers and screen readers.

So should we update  [G65 Providing a breadcrumb trail](http://www.w3.org/TR/WCAG20-TECHS/G65.html) to follow the HTML5 pattern?

@stevefaulkner 's [Bread Crumb Tests](https://dl.dropboxusercontent.com/u/377471/breadcrumb.html) are available.

**Comment by lauracarlson** [comment]
## 1\. New proposed separator:

add "→" to the example separators to read:

> Examples of separators include ">", "|", "/", "::", and "→".

## 2\. New proposed example:

Add a third example to read something such as:

> ### Example 3
> 
> 
> The information architecture of an ecommerce Web site is categorized from general to increasingly more specific product subsections. A location breadcrumb trail conveys the position of the current "Laptops" page within the site hierarchy and helps users orient themselves within the site. Regardless of how users arrive on the "Laptops" page i.e., by searching or following a link, the trail indicates where they are within the site hierarchy, which provides the ability to step back levels to find more generalized related items.
> 
> 
> 
> ### Example Code: 
> 
>     
>  You are here: Acme Company → Electronics → Computers → Laptops
>                 
> 
> The trail begins with the text "You are here" and ends with the current page. Items in the trail are clickable or tappable links with the exception of "You are here" and "Laptops." This example uses a right arrow symbol (→) as a separator, which is not voiced in some screenreaders and pronounced as "rightwards arrow" in Voiceover.
> 
>
> 

## 3\. New proposed added resources:

> ## Resources
> 
> 
* [HTML5 Bread crumb navigation](http://www.w3.org/TR/html5/common-idioms.html#rel-up)
>

**Comment by lauracarlson** [comment]
A [live page with the example breadcrumb markup and CSS](http://www.d.umn.edu/~lcarlson/wcagwg/tests/breadcrumb_example.html) is available.

**Comment by joshueoconnor** [comment]
Is this ready? Or are you waiting for more input?
If it is ready please update the 'Ready for Survey' label. Thanks.

**Comment by lauracarlson** [comment]
Hi Josh,

[I asked for input on the GL list](https://lists.w3.org/Archives/Public/w3c-wai-gl/2015JulSep/thread.html#msg192) and received a [response from Jon Gunderson](https://github.com/w3c/wcag/issues/110), which I incorporated.

I was hoping other folks especially Steve Faulkner will review and give feedback. @stevefaulkner do you see anything amiss with [the proposal for G65](https://github.com/w3c/wcag/issues/110#issuecomment-131810378)?

**Comment by stevefaulkner** [comment]
hI Laura, apologies for not responding earlier, the technique and examples
look good to me!

On Monday, 31 August 2015, Laura Carlson <notifications@github.com> wrote:

> Hi Josh,
>
> I asked for input on the GL list
> <https://lists.w3.org/Archives/Public/w3c-wai-gl/2015JulSep/thread.html#msg192>
> and received a response from Jon Gunderson
> <https://github.com/w3c/wcag/issues/110>, which I incorporated.
>
> I was hoping other folks especially Steve Faulkner will review and give
> feedback. @stevefaulkner <https://github.com/stevefaulkner> do you see
> anything amiss with the proposal for G65
> <https://github.com/w3c/wcag/issues/110#issuecomment-131810378>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/wcag/issues/110#issuecomment-136349050>.
>


-- 
--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by awkawk** [comment]
Laura, my only comment is that some of the text in the example description you provide is redundant to the overall description in the technique.   

Specifically, I think that the first sentence of the description is all that is needed.

**Comment by lauracarlson** [comment]
@stevefaulkner: Thank you very much for checking it, Steve.

@awkawk: I agree, more succinct is better. Thank you for the suggestion. I removed the text: "A location breadcrumb trail conveys the position of the current "Laptops" page within the site hierarchy and helps users orient themselves within the site. Regardless of how users arrive on the "Laptops" page i.e., by searching or following a link, the trail indicates where they are within the site hierarchy, which provides the ability to step back levels to find more generalized related items." What do you think? Any other ideas for improvements? 

@awkawk or @joshueoconnor: If you think the text is okay please mark it ready for WG survey as I don't have permissions to mark it ready. Thank you!

**Comment by lauracarlson** [comment]
Approved 9/8/2015: http://www.w3.org/2015/09/08-wai-wcag-minutes.html#item04

**Comment by awkawk** [comment]
Added changes to wcag/wcag20/sources/techniques/general/G65.xml
