### ISSUE TITLE
Links TBD

### ISSUE THREAD

**Issue by Malvoz** [w3c/wcag#1102]
- In https://www.w3.org/TR/WCAG21/#cc4, the link "[Understanding accessibility support](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance)" should point to https://www.w3.org/WAI/WCAG21/Understanding/conformance#accessibility-support.
- In https://www.w3.org/TR/WCAG21/#cc5, the link "[Understanding Conformance Requirements](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance)" should point to https://www.w3.org/WAI/WCAG21/Understanding/conformance
- In https://www.w3.org/TR/WCAG21/#issue-container-generatedID-37, the link "[Understanding Conformance Claims](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance)" should point to https://www.w3.org/WAI/WCAG21/Understanding/conformance#conformance-claims
- In https://www.w3.org/TR/WCAG21/#issue-container-generatedID-42, the link "[Level of Assistive Technology Support Needed for "Accessibility Support"](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance)" should point to https://www.w3.org/WAI/WCAG21/Understanding/conformance#support-level
- In https://www.w3.org/TR/WCAG21/#issue-container-generatedID-46, the link "[Understanding Accessibility-Supported Web Technology Uses](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance)" should point to https://www.w3.org/WAI/WCAG21/Understanding/conformance#documented-lists
- In https://www.w3.org/TR/WCAG21/#issue-container-generatedID-72, the link "[Understanding Conforming Alternate Versions](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance)" should point to https://www.w3.org/WAI/WCAG21/Understanding/conformance#conforming-alt-versions
- In https://www.w3.org/TR/WCAG21/#h-note-121, the link "[Understanding Success Criterion 1.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast)" should point to https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

**Comment by alastc** [comment]
These are all updated in main (including to WCAG 2.2 for the most recent version). Unfortunately that will only appear in the main WCAG 2.1 doc if we can publish an update.
