### ISSUE TITLE
Challenges with conformance won't really be a specification

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#1103]
The status of this document section says that it is a draft of a "potential specification" but it is actually the draft of a working group Note, not a specification - nothing normative in it at all. Seems the language needs clarifying.

**Comment by awkawk** [comment]
The WCAG 2.0 Notes start with: "This is [draft of] a Working Group Note.. "

**Comment by JaninaSajka** [comment]
Mary Jo, Andrew, we all agree that this doc will not be a specification. I have taken this Status Section language up with Michael in some detail. The long and short of it is that even he's unable to change it. It's burned to respec, where there are several status types among which to choose. Judy wanted the "unofficial" status type chosen for now, and the "specification" word is an unfortunate byproduct of that choice. Michael further assures me that, once we're cleared for FPWD, that Status language will most definitely change and it will be clearly stated that this document "is intended to become a W3C Note." Also, we will insert a series of questions for which we'd like comments from the wider community. Now is a good time to be thinking of what some of those questions might be.

hth.

Janina
