### ISSUE TITLE
Challenges with conformance: Document says to apply the Challenges with Conformance label, but that can't be done by commenters

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#1104]
Suggest edit to say to open a GitHub issue with "Challenges with Conformance" in the title. Personally, when I'm opening issues I cannot apply any GitHub labels to the issue so I imagine neither can commenters.

**Comment by awkawk** [comment]
You can't apply the label? I can, but am not sure if that is a permissions thing? I can't apply a label until there is at least one character in the title, so if you try to apply a label first it blocks you...

**Comment by maryjom** [comment]
@awkawk I am viewing the submitted issue and I do not have any active link to add a label.

**Comment by awkawk** [comment]
The gear icon next to labels (see screenshot) is where I have it.
![Screen Shot 2020-04-14 at 9 55 22 AM](https://user-images.githubusercontent.com/4228257/79232947-2d34f300-7e36-11ea-848a-2a83867614c6.png)

**Comment by maryjom** [comment]
@awkawk There is no gear icon.
<img width="236" alt="Screen Shot 2020-04-14 at 9 57 11 AM" src="https://user-images.githubusercontent.com/5894100/79233080-5b1a3780-7e36-11ea-8002-08da214de3ac.png">

**Comment by awkawk** [comment]
OK, so that seems like a permissions issue that would impact most public commenters. @michael-n-cooper and @alastc?

**Comment by maryjom** [comment]
@awkawk I am putting "Challenges with Conformance" at the beginning of the title to help with filtering so the wg can add the appropriate filters.

**Comment by JaninaSajka** [comment]
Sorry you had to teach us about this the hard way Mary Jo. There's now a draft pre-publication solution in [Working Draft 5](https://raw.githack.com/w3c/wcag/conformance-challenges-working-draft5/conformance-challenges/).
