### ISSUE TITLE
Question: 2.4.1 Bypass Blocks Sufficient Techniques

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#1128]
Understanding Success Criterion 2.4.1: Bypass Blocks
https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html

Section: Sufficient Techniques

There are two parts where the instructions for part 1 and par 2 include: "using one of the following techniques".

Could someone clarify if this means" 'if the website includes at least one technique for either part 1 or part 2; the success criterion is met?'

Or 

does the website need to meet at least one sufficient technique for both parts 1 and part 2?

Thanks for any feedback.

**Comment by JAWS-test** [comment]
I would say: as with all other Understanding documents, it is sufficient to implement one of the techniques. See also the sentence directly above: "Each numbered item in this section represents a technique or combination of techniques that the WCAG Working Group deems sufficient for meeting this Success Criterion"

**Comment by alastc** [comment]
Your ultimate yardstick is whether you meet the SC text. I.e. whether you provide a way of bypassing blocks of repeated content.

You could do that with techniques from only group 1, or only group 2, or a mixture.

In general (for standard websites) I'd recommend G1, ARIA11, and H69. However, if you're working on a PDF, or have an unusual layout you might use one of the others as well or instead.
