### ISSUE TITLE
0.5.2 Typo error

### ISSUE THREAD

**Issue by rob212** [w3c/wcag#1131]
There is a mistype in “0.5.2 Numbering in WCAG 2.1”. 

The word ‘criteria’ has been written, 
  ‘ccriteria’

In the sentence:

“This avoids the need to change the section number of success criteria from WCAG 2.0, which would be caused by inserting new success critera between existing success ccriteria in the guideline, but it means success criteria in each guideline are no longer grouped by conformance level.”

**Comment by awkawk** [comment]
Already accepted as an erratum. https://github.com/w3c/wcag/issues/414
