### ISSUE TITLE
Example #2 of F22 seems to stretch SC 3.2.5 requirement

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag#114]
Hello WG,
About example #2 in F22 links in new window:
This supposedly suggests  that failing to indicate that a link opens a new window is a SC 3.2.5 AAA failure. 
The normative SC 3.2.5 says: 'changes are initiated only by user request '. This really does not require clarification, yet the understanding doc explains this  to remove doubts one may have when it says: Clicking on a link is an example of an action that is "initiated only by user request."
Surely, when one fixes an SC 3.2.5 issue caused by a  popup that opens unexpectedly by replacing it with a link that opens a new window (H83), it is good practice to clarify the behavior with advisory text 'opens new window'. 
User agents for a long time have been giving an audio cue when a new window is opened. 
So basing a decision that  links opening in a new window require notification based on an example in a failure technique when surrounding explanation / other examples do not support this tantamounts to   stretching the normative requirements.
Please can you delete example #2 or clarify that  failing to indicate that a link opens a new window is not an SC 3.2.5 failure per se? If it is really a failure the understanding doc needs to document that clearly too.
Thanks,
Sailesh Panchang

**Comment by awkawk** [comment]
Sailesh, 
Following a link is by user request but the opening of the new window is not unless the user knows that the window will open.  That is why H83 requires the advance notice of the new window opening.

You mention user agents indicating that new windows are opening - do you mean screen readers or other UA?

**Comment by spanchang** [comment]
Hi Andrew,
I meant screen readers.
It is listed as a benefit in the understanding doc but is it not over
and above  the cue provided by SRs?  So is it a failure as far as SR
users are concerned?
Maybe the understanding doc should clarify that opening a link in a
new window is an unexpected change of context, no?
Thanks,
Sailesh

**Comment by awkawk** [comment]
Sailesh,
I think that if anything we need to make clear that there may be multiple changes of context at play for a user - the content may change, the window/viewport may change, etc., and unless the user knowingly initiates each type of the change then they have a 3.2.5 issue.  

We could change the note from:
Clicking on a link is an example of an action that is "initiated only by user request."
to:
It is possible for more that one change of context to occur simultaneously.  For example, clicking on a link which automatically opens a new window is an example of two separate changes of context related to the change in content and to the change in the viewport (window).  The change in the content in this case is initiated by user request when they click on the link, but unless the user can be aware that the link will open in a new window then that change of context cannot be regarded as user-initiated.

**Comment by spanchang** [comment]
Andrew,
Alright, that  explains it and clearly signals that links that open in a
new window without notification is a failure of 3.2.5.
Thanks,
Sailesh

**Comment by awkawk** [comment]
Approved 9/8/2015 http://www.w3.org/2015/09/08-wai-wcag-minutes.html

**Comment by awkawk** [comment]
Edit made in wcag/wcag20/sources/understanding/consistent-behavior-no-extreme-changes-context.xml
