### ISSUE TITLE
It is time to remove the Flash techniques

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#1140]
The technology is at End of Life (https://www.adobe.com/products/flashplayer/end-of-life.html) - let's just remove the techniques.

**Comment by patrickhlauke** [comment]
I'd say it's also worth considering doing an early removal of Silverlight techniques ... or at least marking the calendars for its EOL is October 2021 https://support.microsoft.com/en-us/help/4511036/silverlight-end-of-support
