### ISSUE TITLE
Incorrect navigation links in Understanding document

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#1144]
The first SC in almost every GL has a link to “Previous SC:” that doesn’t go to the previous SC, it goes to the first SC in the preceding GL.
https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships

Some first SC have other problems, like they link to the first SC of the previous GL but include link text that suggests otherwise:
https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold
https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable
https://www.w3.org/WAI/WCAG21/Understanding/on-focus

And there are ones that do it right:
https://www.w3.org/WAI/WCAG21/Understanding/keyboard

**Comment by patrickhlauke** [comment]
another manifestation of issues we had previously? https://github.com/w3c/wcag/issues/1043
