### ISSUE TITLE
Loophole in SC2.4.11 allows almost invisible focus indicators

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1156]
The new SC2.4.11 Focus Visible (Enhanced) has a major loophole in the wording. The definition of Adjacent Contrast uses "or" between the two requirements for 3 to 1 contrast and 2px thickness. This allows a 2px outline but without any requirement at all for colour contrast. So a developer can add an outline that is much less than 3 to 1 contrast against the adjacent background. In fact it need be only 0.1 to 1 contrast, which would be completely invisible to every one. 

One way this will work in actual practice, is that developers would not have to bother changing the focus indicator's colour as it moves around the page from one background to another. You can see an example of how this works by just looking at the default focus outline in the Google Chrome browser. It is blue, and it remains blue even when the item in focus is on any close shade of blue background. So invisible to all ordinary people! 

(In fact the 2px thickness is already required by the Minimum Area clause, so I don't think it needs to be repeated here, does it, unless I'm misunderstanding the meanings of these different clauses?) 

Change the "or" to "and" in the body of the clause to prevent this loophole, and change the name of the clause to "Contrast and thickness" to match.

**Comment by patrickhlauke** [comment]
i thought the idea was that the contrast requirement would come nonetheless from 1.4.11 and the idea was to avoid overlap in this part?

**Comment by mraccess77** [comment]
I believe a contrast ratio is excluded from that bullet on purpose because it's 2px so it's wide enough that even with less contrast it will be noticeable by size - at least that is how I understood it from Alastair.

**Comment by alastc** [comment]
Hi @guyhickling,

I think the foundation of this question is not seeing the difference between a 'change' of contrast and 'adjacent' contrast. Without that confusion I can't see a loophole.

The fact you raised this indicates there might be something to add to the Understanding doc about that difference, but could you confirm that was the crux of the issue first?

Cheers,

-Alatair

**Comment by guyhickling** [comment]
Alastair, No, the foundation and reason for raising this issue is that SC2.4.11, as currently worded, does not say what you intend it to mean. And when the WCAG doesn't say what it really means (of which there are already too many examples as it is!), that's when developers push back against audits.  They refuse to fix things the tester has found, and claim that false issues are being raised,  because they can use the wording of a Success Criterion to claim what they have done passes. 

Web developers and other people will misunderstand SC2.4.11 after release because the third bullet point contains a very clear "or" statement. The logical meaning of "or" is clear to most people, but computer developers and other IT people especially understand the difference between and/or. Every elementary computer course and reference covers and/or logic and what "and" and "or" mean. "Or" means either the first option, or the second option, or both of them together. 

We in this discussion all know what the intention of the SC is, but we must try to see things as many designers and developers will see it. 

### The third bullet
With that in mind, there is no mistaking the meaning of the third bullet point - it clearly allows a focus outline around the outside of a link or button to be 2px thick without also requiring it to have a 3 to 1 contrast. That is the result of using the "or" operator. In other words, there are situations (where the 2px thickness exists) where any level of contrast is permissible no matter how faint or difficult to see the contrast may be. The third bullet clearly allows that. To say otherwise requires changing the "or" to "and". 

So this makes exactly the same mistake as WCAG 2.1 where 2.4.7 requires the focus indicator to be "visible" but does NOT require a minimum contrast, with the result that developers continue to create focus indicators that only people with impaired vision cannot see. That's why we are adding the new SC but, in fact, it still contains the same loophole!

### And the second bullet
And it's no good saying the "indicator would still need to meet the 'change of contrast' bullet", because that second bullet does not clearly - in its wording - cover focus outlines. It is very unclear in what it says. 

First, it reads like it applies only to the kind of focus indicator where the fore and background colours are reversed or changed, because it talks about "Color changes used to indicate focus". Certainly that is what it seemed to mean when I first saw it. (Yes I know you SAY the second bullet applies to focus outlines as well, but nothing in the second bullet says that. Developers haven't seen what we write here in GitHub :-) )

Then the words, "...colors changed from the unfocused control". Is an outline appearing only on focus,  around the outside of a control, part of the control's colours? That's debatable; it isn't necessarily the obvious way for all people to think. And people will reason it surely can't be the case here - because the third bullet clearly says 3 to 1 contrast is NOT required (understand I'm reasoning here as outside people not privy to our discussions will understand it!) 

You need to add add something to the second bullet that makes clear what it applies to (i.e. focus outlines as well as colour-change indicators), if you want to use it to clarify the third bullet. People should not have to go through all the Understanding document before the can even begin to understand the SC. I believe normative SCs should be clear in their own right, leaving the Understanding document to just add examples and clarify points of minor ambiguity or practice.

### Three colour problem
>> Without that "or" you have the 3-color contrast problem

The "or" doesn't change that at all. The "or" (or "and" as it should be) compares the 3:1 contrast and 2px thickness clauses. Why should "anding" of how thick the indicator is make any difference to the choosing of the colour of the indicator? Requiring a minimum physical thickness has no effect on choosing a contrasting colour, so whether the thickness clause is "and" or "or" with the colour contrast clause makes no difference to the available choice of colours developers can use use. But using "and" will stop developers ignoring the colour contrast matter completely

### The solution
Correct the third bullet logic operator from "or" to "and". That will require the indicator to have high contrast against adjacent colours, but does not affect the choice of 3:1 contrast colours to choose from. 

And if possible also make clearer in the second bullet's wording what it applies to (or show a green Note below it to explain).

I suggest it would be a good test to show these bullet points to twenty web developers, ones never involved in these WCAG discussions, and ask how they understand them. Ask them if they think this SC requires a focus outline to have both 3:1 contrast and 2px thickness, or not. (Actually W3C ought to do user testing like this using  non-WG users on all new SCs! - just a side-thought.) 

I'll add a second post presently explaining a typical scenario where this SC, as worded now, will allow developers to continue using near-invisible focus indicators.

**Comment by guyhickling** [comment]
And here is one very common scenario where developers frequently allow near-invisible focus indicators, and which won't easily be stopped by this SC if the wording is not changed.

Take a website with one theme colour - let's say dark blue. Pages are white, but they also have a large area using the dark blue as the background, and this area contains various links and buttons.

The developer uses an outline round the outside of links and buttons as the focus indicator, of a blue that is close to the theme colour but not exactly so (developers often don't stick to the exact same colour value when adding bits to a page, and I assuming this here so it will pass SC2.4.7 Focus Visible, to keep that out of this discussion). The focus indicator is clearly visible on the white pages, of course, but as soon as it enters the blue-background area it becomes almost invisible because the colours are so close. (Note, this behaviour is frequently seen on websites that have differently coloured backgrounds, when focus moves from one background to another.)

Now the developer can (so they think) comply with WCAG 2.2 by making the cursor 2px thick. He can see the focus outline even on the blue areas of the page, so he thinks all is well. In fact, anyone with poor eyesight or colour blindness cannot see where focus is in the blue areas. Some users will be unable to use the site.

**Comment by alastc** [comment]
Hi Guy,

>  it clearly allows a focus outline around the outside of a link or button to be 2px thick without also requiring it to have a 3 to 1 contrast.

Without requiring it to have 3:1 contrast with all *adjacent* colours. That is not the same as what you are saying. It must still have a *change* of contrast of 3:1.

The same language structure (with "the following are true" and a bullet with an "or" in it), is used in 1.2.1, 1.4.3, 1.4.6, 1.4.11, 1.4.13, & 2.2.2. It hasn't been an issue for those SCs.

You wrote:
> that second bullet does not clearly - in its wording - cover focus outlines.
> ... I know you SAY the second bullet applies to focus outlines as well, but nothing in the second bullet says that.

For others reading this, the wording is: "Color changes used to indicate focus have at least a 3:1 contrast ratio with the colors changed from the unfocused control."

I agree developers don't read what's here, but they should read the understanding document which has a whole section on "change of color", including:

> When a component changes to include a focus indicator, that change can always be measured as a change of color contrast. For example, if a yellow outline is added to a button on a blue background, the change of color is from blue to yellow. 

Later you wrote:
>  Is an outline appearing only on focus, around the outside of a control, part of the control's colours? That's debatable

I really don't think it is. The bullet doesn't ask for the controls colours, it says "color changes used to indicate focus". 

In the scenario you followed up with, it fails on change of contrast.

I'll ask for some second & third options because I'm not getting this issue.

Cheers,

-Alastair

**Comment by mraccess77** [comment]
@guyhickling Currently this proposed SC allows for 2px focus indicators to have < 3:1 contrast to adjacent colors as long as the colors that would have been covered by the indicator have <= 3:1 to the previous state.  So while it allows for less than optimal contrast it should contrast with the previous non-focused state sufficiently.  While I agree this is not the best experience flipping backgrounds which currently passes is not optimal either as all of these techniques rely on users to compare states and with magnification you may only have one control in view at a time.  However, if we increase the requirements this criterion may not be accepted.  I'd rather have this than no new criterion.

**Comment by alastc** [comment]
> This SC2.4.11 is different because we want outline indicators to have both Item A and Item B together. We want all focus indicators to have a thickness of at least 2px, AND ALSO to have the 3 to 1 contrast against the adjacent colours as well so they are visible to all. 

Ok, I think we're getting somewhere, I'm understanding your perspective better now.

The problem is that we cannot achieve both of these things consistently:
1. Contrast for the change of colour.
2. Contrast against adjacent colours.

Take a solid green button for example, in [this codepen](https://codepen.io/alastc/pen/XWXpbPp). You have very few colours that will contrast with both the background and the button. 

If you test with the 40 odd variations in [my test cases](https://alastairc.uk/tests/wcag22-examples/focus-more-visible.html), the change of colour is actually more important than the adjacent colour.
(Add [-2.html](https://alastairc.uk/tests/wcag22-examples/focus-more-visible.html) at the end for the second page, [-3.html](https://alastairc.uk/tests/wcag22-examples/focus-more-visible.html) & [-4.html](https://alastairc.uk/tests/wcag22-examples/focus-more-visible.html))

So I agree that if you can contrast with both the background (change) and adjacent colors (including the control) that is better. However, that gives very narrow design options.

So the intent is that if it doesn't meet the adjacent colour contrast then it has to be thicker. It is intended to be that way and I strongly believe that we need that flexibility to progress.

Also, after several threads on this I'm yet to see a problematic example that actually passes the criteria. (Except for the pattern one someone created, which was very inventive!)

> But since (in my opinion as described in my previous post) the "change of contrast" bullet hasn't made clear (enough for some people) what it's talking about, it's not sufficient to overcome any misunderstanding caused by the third bullet!

Well, I don't' think you are misunderstanding the third bullet, but I'm interested in any updates to the change of contrast bullet that mean the same thing.

**Comment by guyhickling** [comment]
Thank you Alastair for you reply. Yes, I agree the developer will often have only a few colour choices for the focus indicator. And I appreciate your point now about "the change of colour is actually more important than the adjacent colour", which I didn't get the first time you showed your test cases. However I don't think the limited choice should matter because:

1) There only have to be a few choices. The keyboard focus is  not a major design issue - as can be realised from the fact that many designers and developers don't realise keyboard indicators even exist. They design with a mouse for mouse users, and until we a11y people tell them in an audit report that keyboard navigation is actually a thing, they have never thought about it! - hence, of course, why so many websites have no focus indicator at all. They just haven't realised.

2) Your codepen illustrates the 3 colour problem well. But there are always a few contrasting colours to use. The developer just has to find one. (And it doesn't have to be the same colour throughout the page. it can change for components and/or backgrounds of different colours.) If they don't like the choice of colours, they can always use a CSS outline-offset.

3) The exception is in complex multicoloured components or backgrounds, but they would need their own solution anyway. That could be covered by an exception clause, or a green Note.

4) No one sees the keyboard focus indicator except (a) keyboard users - and they are the ones who need to see it, they don't care what colour it is so long as they can see it easily. And (b) when a mouse user clicks a link but the page is slow to load, the indicator shows briefly for a second or two until the new page displays. Even that brief appearance can be prevented with a little JavaScript.  

Just to clarify the difficulty for keyboard users, from my own personal difficulty, if the outline doesn't have a good colour contrast. When the focus outline is a similar colour to the button, or to its border if it has one as in your TEST CASES test cases example 2, the effect is to make the button bigger, or its border thicker, while in focus. But to find that I have to be looking at the button when the change actually happens. If I just look round the page for a button that has a thicker border than the others, I cannot find it. I frequently find myself tabbing backwards and forwards, watching different areas of the page, until I spot where there is a button that is increasing and decreasing its size or border thickness as I move focus. 

So I am fine if the newly focussed button is close to where it was before, because I can see the movement in the area I am looking at. But if focus has jumped to the other side of the page, or far down the page, that's when I find difficulty spotting where it has gone. (People using magnifiers probably have a similar problem?)

On the other hand a good contrast outline is much easier to find, because I don't need to see that change happen, the colour difference helps me. Of course that's just me with still moderately good eyesight, failing though it is. And I only keyboard navigate when auditing. Many people have far worse vision than I have, but I can see from my partial difficulty how difficult it must be for them. Hence why I am anxious to make a well contrasting, thick focus indicator, a requirement.

**Comment by alastc** [comment]
>  The keyboard focus is not a major design issue - as can be realised from the fact that many designers and developers don't realise keyboard indicators even exist.
> ...
> No one sees the keyboard focus indicator except (a) keyboard users

That is not the same as my experience, which is often:

> "The client has said / filed a bug that you get a weird outline when clicking on some links, can you get rid of it?"
https://alastairc.uk/2016/09/fixing-outlines-on-click/

Until [focus-visible is better supported](https://caniuse.com/#search=focus-visible), that issue isn't going away. In fact, it will become more common because if people are not relying on default indicators then it will happen more! (The focus-visible pseudo selector replicates the browser's feature of not showing the focus on-click.)

> there are always a few contrasting colours to use

But, and in combination with the above scenario, if they are large and obvious then they really need to match the design, and forcing people to use odd (and subjectively ugly) indicators could lead to less desirable work-arounds. E.g. falling back to a background change rather than adding an outline.

I am familiar with the issues you describe in following a focus indicator, I do that a lot myself, and I ran through 15 of the key the test-cases with members of the low-vision task force.

The problem I have with increasing the requirement is that it creates false positives. I.e. indicators which are generally visible (including to people with low vision) would be caught. For example, the yellow indicator on the search box of www.gov.uk. That doesn't contrast with the white interior of the input, but is visible (and tested with people).

This type of SC is particularly difficult in some respects because the more accurate we make it to catching problematic cases, the more complex it would be to understand.

Also, I'll ask again: After several threads on this I'm yet to see a problematic example that actually passes the criteria. (Except for the pattern one someone created, which was very inventive!)

**Comment by alastc** [comment]
Also, on this example:
> When the focus outline is a similar colour to the button, or to its border if it has one as in your test cases example 2, the effect is to make the button bigger, or its border thicker, while in focus. But to find that I have to be looking at the button when the change actually happens.

I see the issue, but we also have to consider that our contrast algorithm ignores hue. That's partly why my test-cases were worst-case scenarios with black/grey/white. 

However, you could use a thick blue outline around a medium-green component and it will stand out to almost everyone (expect perhaps acromats? Perhaps?). It would look super obvious to designers/developers, and we'd be saying that fails, and not really for good reason.

**Comment by mbgower** [comment]
@guyhickling, in a [prior comment](https://github.com/w3c/wcag/issues/1156#issuecomment-642080067), you said
> whether in the Understanding docs or even in other normative SCs, it will be very difficult to argue against anyone who wants to push back or challenge

That's not true. One must meet all SCs. Meeting one does not allow me to not meet another. There is a clear requirement in 1.4.11 that 'the Visual information required to identify user interface components and states have a contrast ratio of at least 3:1 against adjacent color(s). So even if you read the OR to negate the prior part of the bullet, it doesn't except the requirement for 1.4.11.

My suggestion to make this clear by adding a note that reads:
**Note: These enhancements complement the requirement in 1.4.11 Non-text Contrast that the focus indicator achieves a 3:1 contrast against adjacent color**

One of the things apparent when we peruse 1.4.11 is that "adjacent color" gets a little messy when we're talking about an indicator of a UI's focus state. Some may read the UI component itself as an adjacent color to the focus indicator. I don't think that's true in the case of 1.4.11, but I think the wording of the third bullet in 2.4.11 clearly brings this in as a consideration in meeting 2.4.11 **Unless it is at least 2 CSS pixels thick**. That is my understanding of why that "or" must persist. A 2-pixel increase in thickness around the UI component makes it much more noticeable as a change.

From [another of your comments](https://github.com/w3c/wcag/issues/1156#issuecomment-645609516), I agree that the wording of the second bullet is at least cumbersome:
> Color changes used to indicate focus have at least a 3:1 contrast ratio with the colors changed from the unfocused control."

I suggest removing "changed" and a few shifts to read:
Where color changes are used to indicate focus, they contrast at least 3:1 with the colors from the unfocused control."

**Comment by guyhickling** [comment]
> yet to see a problematic example that actually passes the criteria

I didn't answer that one because I wasn't sure what you were wanting. Can you explain further please?

**Comment by guyhickling** [comment]
Alastair, your said "That is not the same as my experience" with regard to concerns over the indicator shown on mouse clicking. Umm, maybe I'm too optimistic in that viewpoint. However the outline on click can be hidden using JavaScript without needing to wait for focus-visible. There is also a [polyfill](athttps://www.npmjs.com/package/focus-visible) for focus-visible which would probably do the trick, though I haven't been through it in detail, and it is under development so might need some adjustment. Certainly, for focus indicators on keyboard focus, I don't think there should be a problem, since at least half the design/dev people in this world don't write for keyboard users, don't test keyboard use, and are only bothered about keyboard testing if we tell them to do so in an audit. At which point if we say also require contrast I can't see that they should worry too much what it looks like, so long as we are saying it is so keyboard users can see it easily.

**Comment by guyhickling** [comment]
@mbgower  I agree the "changed from the unfocused control" is part of what makes the second bullet hard to understand, and I wish they would improve it. However the "changed" does have to be there in some form or other (or replaced by a better way of putting it) because this bullet is about the colours of the focus indicator compared with the colours those same pixels had before focus was received - i.e. the change in colour of those pixels.

**Comment by alastc** [comment]
Hi @guyhickling,

By problematic example I mean: an example indicator (ideally in the wild) that is visually problematic _and_ fails the new criteria text.

> However the outline on click can be hidden using JavaScript ... 

I'm not sure we want to encourage 1000s of different ways of hiding focus with JavaScript. I think I need to emphasis why I think it will become more of an issue:

- If people have been relying on the default indicator so far, **the default does not appear onclick**, so it has not been a visible thing so far.
- Meeting the new SC means not relying on the default indicator, so for a lot of people/sites they will be adding focus indicators for the first time, and **these appear onclick**.
- Unless we make a really big deal about hiding keyboard focus from mouse-click usage, a lot of people are now going to be seeing the focus indicators onclick.
- Adding a simple (contrasting) focus indicator can also trigger things like a focus indicator around the `<main>` element if you do skip links properly. That can be hidden, but it often triggers that conversation I outlined in the blog post.

Maybe I've had this conversation more often because we've long been recommending highly visible indicators and then going through the full implementations & discussions with lots of stakeholders. 

That's why I think, on balance, we'll get a better result with some flexibility on the design approach.

**Comment by mraccess77** [comment]
Hi @alastc was interested in your comment that "Meeting the new SC means not relying on the default indicator, so for a lot of people/sites they will be adding focus indicators for the first time, and these appear onclick."  Is this still the case with the new indicators in Chrome?  It seems like it may depend on adjacent colors or do we really feel that every developer will need to create their own indicator?

**Comment by mraccess77** [comment]
@mbgower seems to raise an interesting point of the intersection between SC 1.4.11 and they newly proposed enhanced visual focus SC.  That the 2px exception for the proposed SC may then fail the language of SC 1.4.11 - or at least that is what I understood by the comment.

**Comment by alastc** [comment]
>  Is this still the case with the new indicators in Chrome? It seems like it may depend on adjacent colors or do we really feel that every developer will need to create their own indicator?

There are two strands to this:
1. It doesn't apply across all browsers, Chrome & Edge are affected.
2. It doesn't help in all scenarios.

The first is the minefield of accessibility-supported decisions, but I think we'd agree(?) that unless the defaults across most browsers were strong the requirement would still be needed. 

The second reason also helps to justify the requirement, as the outline, whilst a big improvement, doesn't always meet the requirement. For example (and as mentioned in their blog post), a blue button on a white background will make it difficult to see.

On 1.4.11, after much discussion (including #926, there might be others) I'm not sure there is much utility in trying to apply 1.4.11 to focus styles, particularly in 2.2 with the new SC in place.

**Comment by alastc** [comment]
Draft proposed response, to be put to the group:

Draft response : 

> The concern seems to be around contrast between adjacent colors, change of contrast and the thickness of the focus indicator. In the understanding document, the definition of change of color is:
> 
> “When a component changes to include a focus indicator, that change can always be measured as a change of color contrast. For example, if a yellow outline is added to a button on a blue background, the change of color is from blue to yellow.”
> 
> In the potentially problematic examples listed in the thread are where the focus indicator meets the 2px requirement but is lower than 3:1 contrast with the page background, for example - would fail since the change of contrast in consideration is the contrast between page background and focus indicator. 
> 
> The SC does allow in this case for less than 3:1 contrast between the indicator and the color of the button/UI element itself and states that the 2 px requirement would make it sufficiently distinguishable from the unfocused state as in this example. While the ideal scenario would be to have all three, that would overly restrict design choices. Problematic examples of pages that will pass the SC appear to be rare in practice. 
> 
> The group appreciates the desire to provide the best focus indicator in all circumstances, but we also have to consider that increasing the requirement could then catch highly visible indicators (false positives) and restrict the design approaches that can be used.

**Comment by scha14** [comment]
Edited draft response to be put to the group 

> To clarify the distinction between adjacent, background and change of contrast colors, [the group passed](https://github.com/w3c/wcag/issues/1212) a change to [understanding document](https://raw.githack.com/w3c/wcag/wcag22-focus-visible-enh-updates/understanding/22/focus-appearance-minimum.html), in which the second bullet will read:
>  
> 
> > _Color changes used to indicate focus have at least a 3:1 contrast ratio with the colors in the unfocused control._
> 
>  
> It will also include the note below
>  
> 
> > _Note: These enhancements complement the requirement in 1.4.11 Non-text Contrast that the focus indicator achieves a 3:1 contrast against the adjacent background color_
> 
>  
> The SC allows for less than 3:1 contrast between the indicator and the color of the button/UI element itself and states that the 2 px boundary that sufficiently contrasts with the background color would make it sufficiently distinguishable from the unfocused state. While the ideal scenario would be to have all three, that would overly restrict design choices. 
> 
> The group appreciates the desire to provide the best focus indicator in all circumstances, while also considering that increasing the requirement could catch highly visible indicators (false positives) and restrict the design approaches that can be used.

**Comment by alastc** [comment]
HI @scha14,

I think the update to the bullet would be in the SC text? It is replicated in the understanding doc, but to be clear it applies in the main spec as well. (I assume, I wasn't there last week!)

**Comment by alastc** [comment]
Hi everyone, this was reviewed in the meeting yesterday and the above response was agreed:
https://www.w3.org/2020/08/04-ag-minutes.html#item03

There is still an open question about adding a note refering to 1.4.11, but there are a few other issues in that area it would be best to clear up first.

**Comment by mbgower** [comment]
@alastc The above PR should address the 1.4.11 note.
