### ISSUE TITLE
Understanding SC 1.4.11: "that indicator it must meet" (editorial)

### ISSUE THREAD

**Issue by cstrobbe** [w3c/wcag#1219]
The fifth example of the [Active User Interface Component Examples in Understanding SC 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#active-user-interface-component-examples) contains the text,

> Where a text-input has an indicator such as a complete border (`#76766`), **that indicator it must meet** 3:1 contrast ratio. 

The pronoun "it" is redundant here.

**Comment by scha14** [comment]
https://github.com/w3c/wcag/pull/1220
