### ISSUE TITLE
Findable Help SC3.2.6 hard to understand

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1228]
I'm sorry folks, but this SC is almost incomprehensible. It has no meaning to anyone meeting it for the first time. You have to go to the Understanding document to even find out what it is about and what it requires! 

Firstly, the SC is apparently about Help (according to its title) but, after that, it doesn't mention "help" at all until it finally gets a mention in just one out of the 4 list items at the end. The body of the criterion, before the list, just says "For single page Web applications or any set of Web pages, if one of the following is available, then access to at least one option is included in the same relative order on each page." - how does any of that relate to help? 

This can be made much more understandable by just adding four words. Change "...if one of the following is available..." to:

> ...if one of the following four help sources is available...

This SC needs all the help it can get - pun intended! :-)

Also it is not immediately obvious what "the following"  refers to. In normal English writing, if we say "the following" when referring to a list we usually show the list immediately afterwards, with only a colon (:) in between. If we have a lot of other text between them we usually say "in the following list of.....", just to clarify what is referred to. (Compare other non-W3C documents.) So the above change improves that bit as well.

**Comment by guyhickling** [comment]
Issues #1228 to #1232 are all suggested changes of wording to this same SC for clarity. And #1242 puts them all together in one amended text so we can see what the end result would be if accepted. NB: No change in meaning is intended in any of them, these are all simply to make the language of the SC easier to understand. So if you spot any unintended difference in meaning, please let me know.

**Comment by scha14** [comment]
Hi @guyhickling is it okay to close this issue and continue the discussion on #1242 where all comments are together? Thank you for your patience.

**Comment by guyhickling** [comment]
The draft change you mention in #1231 solves this issue as well more or less, so yes, this can be closed.

**Comment by alastc** [comment]
Closing this, as 1231 will be surveyed.
