### ISSUE TITLE
Findable Help SC3.2.6 - what is self-help?

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1229]
The third bullet of this SC says "self-help option". 

A "self-help option" is a process where a person helps themselves in some way _instead of_ relying on the system. In this context of obtaining "help" that might mean Googling for it. The Understanding document also recognises that an internet search would be the obvious way to understand that when it says "Self help methods beyond the site, such as using internet search, can be too difficult."

In contrast, the methods of help this SC is referring to are all provided by the website or app. The Understanding  says "....such as an up-to-date Frequently Asked Questions, How Do I page, Support page". Calling them self-help is confusing.

So I suggest amending the third bullet of this SC to something like "help provided by the website or application", or possibly "system-provided help", or something similar, to be more accurate.

**Comment by scha14** [comment]
Draft response : 

Draft response:

Looking for a better way to say self help mechanism. System provided help could mean OS or browser help, and help provided by website/app basically covers all the other categories listed - those could be confusing.

The understanding document explains what self help means, but it could help to make that clearer in the SC. Maybe self-help documentation?  Looking for more suggestions.

**Comment by guyhickling** [comment]
> Looking for more suggestions.

How about "help content on the website or application" or "help within the pages". That would cover FAQs pages,  sections of help in a page (with an anchor so it can be linked to from the other pages), lists of references, a glossary page, anything like that.

**Comment by scha14** [comment]
Draft changes : 
> Changes bullet to self-help option provided by the author
https://github.com/w3c/wcag/pull/1376 and https://github.com/w3c/wcag/pull/1375

**Comment by scha14** [comment]
@guyhickling could we close this and continue the discussion in https://github.com/w3c/wcag/issues/1231?

**Comment by scha14** [comment]
Closing this to address in the issue https://github.com/w3c/wcag/issues/1242, where all issues are combined. Please reopen if this remains unaddressed. Thank you!

**Comment by scha14** [comment]
Closing this to address in the issue #1242, where all issues are combined. Please reopen if this remains unaddressed. Thank you!
