### ISSUE TITLE
Retire technique H59

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1234]
[Using the link element and navigation tools](https://www.w3.org/WAI/WCAG21/Techniques/html/H59) may really not be all that useful/relevant anymore. To my knowledge, no browser actually exposes those link elements to users in any way. Old Opera browsers used to have an optional toolbar that would take advantage of these links and show some navigation buttons, but I seem to remember that even back then this was the exception. I'm not aware of any commonly-used extensions for modern browsers that take advantage of these links/expose them to the user either. x-ref #1077

**Comment by patrickhlauke** [comment]
edited title, as it's advisory for 2.4.5 but sufficient for 2.4.8

**Comment by patrickhlauke** [comment]
so, coming back to this...worth making a pull request? or does this need further discussion first?

**Comment by JAWS-test** [comment]
> worth making a pull request? 

YES
