### ISSUE TITLE
SC3.3.8: Redundant entry - When information previously entered has been saved

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1239]
This is to recommend adding another use case to the scope of this SC. The Understanding limits coverage of this SC to a single session, so if the user aborts the process then returns later, they have to reenter all the data. Which is fine for that situation.

However there is another situation where, in a long and complicated data entry process, the website deliberately allows you to save your data part way, and resume entry at a later date. Banks often do this for more complicated applications. The income tax return in the UK also allows this.

In these cases the organisation has saved your data in their database, and will almost certainly have reloaded some or all of it when you return to finish the job, in order both to display parts of it (for instance user name and so on), and to find out where to resume input. So it would be quite reasonable to extend the coverage of this SC to such cases since the website already has that data available. 

This could be done very simply by adding a few words to cover this case in the relevant places in the Understanding. There are two places. The first is where it says:
> This Success Criterion pertains to the current user session, and is not applicable a user returns after closing a session or navigating away

and lower down it says:
> This Success Criterion does not add a requirement to remember information between sessions, a process is defined on the basis of an activity and does not continue across sessions

In both cases we could add the following words or similar:
> ....except where the user has been allowed to save their entered data part way through the process.

**Comment by alastc** [comment]
Hi @guyhickling,

The group agreed a response to this issue: 
<hr>
Whilst agreeing that sites *should* save information between sessions, we didn't want to make that a requirement and make implementations harder. Where sites are already providing that functionality, it does not appear to gain anything for us to add that requirement for those that already provide it. Also, given that any site where you can complete a process in one session is in scope, it would have to meet the SC anyway.

**Comment by guyhickling** [comment]
> Whilst agreeing that sites _should_ save information between sessions, we didn't want to make that a requirement

No one said anything about making data saving a requirement! I suggested only "....except **where the user has been allowed to save** their entered data part way through the process." No requirement to save data from the first session there - you seem to be deliberately misunderstanding it in order to reject the suggestion. I also said "In these cases the organisation has saved your data in their database..."

Where the user has been allowed to save their data part way in an earlier session, the website will invariably reload it to confirm the previously entered data reached the database ok, so the data is now available again for populating later fields. 

> Where sites are already providing that functionality.....

The point, however, is that reloading the data doesn't mean the designer or developer will have the foresight to populate fields in the subsequent data input, with data from the first session. This SC was created to require repopulating with available data. But since the Understanding document specifically excludes data form a previous session, some developers may use that as get-out permission for them not to bother with repopulating.

All this needs is to accept the above use case happens on many websites (we all complete forms all the time that allow saving part way, from banks, government departments, financial businesses). It just wants a few words to be added to the Understanding document to include this case, as outlined at the top of this issue. Simple enough, surely.
