### ISSUE TITLE
Proposed SVG SC for 1.4.5 (text in images)

### ISSUE THREAD

**Issue by LjWatson** [w3c/wcag#124]
I think that the SVG ```<text>``` element might be a viable technique for passing SC1.4.5 (text in images). Post on this here:
https://www.paciellogroup.com/blog/2015/12/does-svg-text-pass-wcag-1-4-5-images-of-text/

Thoughts welcome. If it turns out there is agreement on this, I'd be happy to draft the technique.

**Comment by awkawk** [comment]
Leonie, my take on this is that this is something that would be great to have a technique for.  I'll check with the group.  It should also work for 1.4.9.

**Comment by joshueoconnor** [comment]
I'd like to see a technique for this - thanks Leonie.

**Comment by awkawk** [comment]
Discussed on the WG call and we would love to have you suggest a technique.  Closing this item and request that you submit the tech as a separate pull request.

**Comment by LjWatson** [comment]
Will do.

 

Is this the correct repo? The readme.md says no more pull requests should be submitted.

 

Is there documentation available? Looking through this repo, it isn’t clear how a new technique should be incorporated.

 

Thanks.

**Comment by awkawk** [comment]
Use https://github.com/w3c/wcag/tree/Working-Branch-for-Q1-2016
