### ISSUE TITLE
Include mobile apps in SC3.2.6 Findable Help 

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1244]
Is there a reason why this SC currently only applies to "single page Web applications or any set of Web pages"? I would have thought it should apply to mobile apps as well, unless there is something I haven't thought of?

The same principle applies to mobile apps as for websites - if a reference to a source of help is provided, then it should be in the same relative place on each page of the mobile app. 

It is true that many mobile apps have a pretty minimal page header, so that might not be the best place to show the help reference. But most apps have a main menu, usually a hamburger menu, and that could certainly be used to hold a help option if one isn't already shown there.

Given that WCAG 2.1 concentrated especially on mobile devices, it seems a backward step to exclude them from this one. So could mobile apps be added to the list of applications in this SC? I suggest saying:
> single page Web applications or any set of Web pages or set of pages in a mobile app

**Comment by patrickhlauke** [comment]
>  I would have thought it should apply to mobile apps as well, unless there is something I haven't thought of?

WCAG is only scoped to *Web Content* (it's in the name). Native desktop or mobile apps are not directly covered by WCAG. Hence the reason why there are documents like WCAG2ICT https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/

**Comment by guyhickling** [comment]
Yes of course, it couldn't reference apps, I wasn't thinking! I'm closing this; thank you.
