### ISSUE TITLE
Cleanup of the non-linked techniques.

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#1245]
We have a lot of bullets in the techniques that are not linked.

When they are not linked it means there is not a written-up technique and it has not been through any approval process.

The technique suggestions can be useful, but they are not conistent. Some use @ symbols to mark them as 'to-do', e.g: https://w3c.github.io/wcag/understanding/accessible-authentication.html#techniques 

I suggest we:
- Check each understanding doc for un-published techniques.
- Mark in a consistent way, e.g. "Potential technique: ..."

**Comment by mbgower** [comment]
@alastc please review my approach at https://github.com/w3c/wcag/pull/2131

There are still a few "@@" uses in the Understanding documents after this PR, but they are not technique placeholders.

**Comment by alastc** [comment]
I attached this to a later issue (and added to survey), so I'll close this one.
