### ISSUE TITLE
G18 and G45 are listed as sufficient for SC 1.4.11 in the How to Meet document

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1248]
These 2 techniques G18 and G45 are listed as sufficient for SC 1.4.11 in the How to Meet document but are not listed as sufficient in the understanding or techniques documents.  They should be removed from the How to Meet document if they are not accurately mapped.

**Comment by alastc** [comment]
Hi Jon,

We have several issues that boil down to: The "How to Meet" needs to be synced up.

It's in progress, but I'd rather not have to deal with many versions of the problem which all have the same solution (which is in progress by @michael-n-cooper).

Cheers,

-Alastair
