### ISSUE TITLE
SCR18 is listed as both sufficient and advisory for SC 3.3.3

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1258]
SCR18 is listed as sufficient and advisory.  Can we remove the advisory marking or is there some reason to keep it?

https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion

**Comment by kfranqueiro** [comment]
It appears SCR18 was removed from Sufficient in https://github.com/w3c/wcag/commit/6781cba2cc9d9bc0f91af02a2913368ab2f88a0e?w=1, wherein the situations under Sufficient were edited, so it is no longer listed under 2 different subsections.
