### ISSUE TITLE
minor issues for wide review draft

### ISSUE THREAD

**Issue by slhenry** [w3c/wcag#1267]
Some things I noted -- which might be just an anomaly of the version I reviewed &mdash; https://w3c.github.io/wcag/guidelines/22/ on 7 August

* [Changelog](https://w3c.github.io/wcag/guidelines/22/#changelog) needs additions
* Under [5.1 New Features in WCAG 2.2](https://w3c.github.io/wcag/guidelines/22/#new-features-in-wcag-2-2),
   * the link "Focus Visible (enhanced)" no worky
   * the list starts with "The following Success Criteria are new in WCAG 2.2:" so it's not communicated which SCs isn't new,  just changed Level

**Comment by alastc** [comment]
I think these are taken care of in the code, it just needs publishing.

Changelog: https://github.com/w3c/wcag/blob/master/guidelines/index.html#L747

5.1: https://github.com/w3c/wcag/blob/master/guidelines/index.html#L92

I assume @michael-n-cooper is going to publish from the master-branch, so these will be done in the wide review version.
