### ISSUE TITLE
broken links in Understanding

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag#1283]
From https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html

In the Intent section,
 "SC 2.4.7 focus visible"
links to: https://www.w3.org/WAI/WCAG22/20/focus-visible.html

**Comment by slhenry** [comment]
From https://www.w3.org/WAI/WCAG22/Understanding/dragging

In the Intent section,
"single pointer"
links to https://www.w3.org/WAI/WCAG22/Understanding/dragging#dfn-single-pointer
that does not exist.

**Comment by alastc** [comment]
Fixed in main
