### ISSUE TITLE
"user interface component" lowercase fixes

### ISSUE THREAD

**Issue by slhenry** [w3c/wcag#1284]
"user interface component" is mostly lowercase throughout WCAG.

Places it needs to be corrected to lowercase:
* [ ] https://www.w3.org/TR/WCAG22/#identify-purpose
* [ ] https://www.w3.org/TR/WCAG22/#focus-appearance-minimum
* [ ] https://www.w3.org/TR/WCAG22/#focus-appearance-enhanced
* [ ] https://www.w3.org/TR/WCAG22/#dfn-focus-indication-area

**Comment by scha14** [comment]
https://github.com/w3c/wcag/pull/1469/files

**Comment by alastc** [comment]
@michael-n-cooper I think this is editorial, any objection with just merging?

**Comment by alastc** [comment]
Re-opening, I don't think the PR updated the focus-appearance SCs.

**Comment by scha14** [comment]
https://github.com/w3c/wcag/blob/master/guidelines/sc/22/focus-appearance-minimum.html
https://github.com/w3c/wcag/blob/master/guidelines/sc/22/focus-appearance-enhanced.html
https://github.com/w3c/wcag/blob/master/guidelines/terms/22/focus-indicator-area.html

They seem to already be lowercase. Am I looking at the wrong branch?

**Comment by alastc** [comment]
Ah, sorry, I was just going from the original post, and the original draft did have them upper case. It looks like someone (possibly me?) already did the new ones!

Thanks
