### ISSUE TITLE
SC 1.1.1 – Situation D – ARIA6/10 redundant

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#129]
Hi!

I have reviewed the Understanding/Techniques briefly this morning and I have noticed that ARIA6 and ARIA10 are mentioned twice in the sufficient techniques for 1.1.1 — Emphasis mine:

> Situation D: If non-text content is time-based media (including live video-only and live audio-only); a test or exercise that would be invalid if presented in text; or primarily intended to create a specific sensory experience:
>
> 1. Providing a descriptive label using one of the following Short text alternative techniques for Situation D :
2. **ARIA6: Using aria-label to provide labels for objects (ARIA)**
3. **ARIA10: Using aria-labelledby to provide a text alternative for non-text content (ARIA)**
4. G68: Providing a short text alternative that describes the purpose of live audio-only and live video-only content using one of the following Short text alternative techniques for Situation D :
5. G100: Providing a short text alternative which is the accepted name or a descriptive name of the non-text content using one of the following Short text alternative techniques for Situation D :
>
> Short text alternative techniques for Situation D:
>
> * **ARIA6: Using aria-label to provide labels for objects (ARIA)**
* **ARIA10: Using aria-labelledby to provide a text alternative for non-text content (ARIA)**
* G196: Using a text alternative on one item within a group of images that describes all items in the group
* FLASH1: Setting the name property for a non-text object (Flash)
* FLASH5: Combining adjacent image and text buttons for the same resource (Flash)

As the situation’s first technique says “Providing a descriptive label using one of the following Short text alternative techniques for Situation D :” referring to the short text alternatives for situation D section below where ARIA 6/10 are mentioned, it is redundant to mention them in the unordered list, too.

**Comment by awkawk** [comment]
Thanks Eric, fixed (https://github.com/w3c/wcag/commit/9f65c293477d747138d713d166aeb65c7d2a0f28)
