### ISSUE TITLE
SC 3.3.8: Redundant entry - Typo on Understanding page

### ISSUE THREAD

**Issue by NoahGresser** [w3c/wcag#1294]
On the Understanding page, under the ["Intent" heading](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html#intent) there is a typo in the following sentence:
> This Success Criterion pertains to the current user session, and is not applicable a user returns after closing a session or navigating away.

The word "if" is missing after "applicable".

The sentence should read:
> This Success Criterion pertains to the current user session, and is not applicable if a user returns after closing a session or navigating away.

**Comment by scha14** [comment]
https://github.com/w3c/wcag/pull/1295 Thank you Noah!

**Comment by NoahGresser** [comment]
Thank you for the quick response!
