### ISSUE TITLE
SC 2.4.11: Focus Appearance (Minimum) -  Possible grammatical error on Understanding page

### ISSUE THREAD

**Issue by NoahGresser** [w3c/wcag#1296]
On the Understanding page, in the notes under the definition of "[user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-user-interface-component)", the start of the second sentence in the following note:

>  NOTE
Multiple user interface components may be implemented as a single programmatic element. Components here is not tied to programming techniques, but rather to what the user perceives as separate controls.

seems to be grammatically incorrect, as the word "Components" is plural, but the use of "is" implies that it is singular.

The note should probably read as either:

>  NOTE
Multiple user interface components may be implemented as a single programmatic element. Components here are not tied to programming techniques, but rather to what the user perceives as separate controls.

or

>  NOTE
Multiple user interface components may be implemented as a single programmatic element. The term "Components" here is not tied to programming techniques, but rather to what the user perceives as separate controls.

**Comment by patrickhlauke** [comment]
the second suggestion is what this intends to convey
