### ISSUE TITLE
Clarification on the definition of electronic publication

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#1299]
The new [definition of electronic publication](https://www.w3.org/TR/WCAG22/#dfn-electronic-publications) has me wondering if an instruction manual would fall into this. Let's say the manual is a PDF with separate virtual pages, and has a series of sections:

1. "Getting Started With Your Turboencabulator"
2. "Assembling Your Turboencabulator"
3. "Modifying…"
4. "Common Problems With…"
5. "Legal Notices And Customer Support"

Does that structure and content count as "content presented as a series of articles"? Or, because each section is named, does that make them chapters and therefore the manual is a book?

**Comment by alastc** [comment]
Draft: response:

<hr>

The PDF would fit into the definition of electronic publication as it is a "document in the form of a book, textbook..."

What would bring it under the scope of the SC is that it also has 'page break locators' in the PDF (i.e. pages). In the case of PDFs the user-agent (e.g. Browser, Acrobat reader) provides the page navigation mechanism.

In the case of ebooks (with page-markers) it is (currently) the authors responsibility to provide the navigation mechanism.

<hr>

CCing @DavidMacDonald and @awkawk for comment before this goes to the group.

**Comment by alastc** [comment]
Hi @fstrr, 

We've got a new version which I think addresses (or removes!) everything you'd commented about:
https://raw.githack.com/w3c/wcag/wcag22-fixed-ref-points-updates-2021-jan/understanding/22/fixed-reference-points.html

Either that will be agreed, or the SC will be deferred, so I'm closing this issue.
