### ISSUE TITLE
Technique F47 improvement

### ISSUE THREAD

**Issue by webcc** [w3c/wcag#13]
In the file:

https://github.com/w3c/wcag/blob/master/wcag20/sources/failure-tech-src.xml

The technique F47 should make a reference to the own documentation of Mozilla, where the use of blink is deprecated and discouraged:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink

**Comment by joshueoconnor** [comment]
Item merged on 22/9/2014

https://github.com/w3c/wcag/pull/24
