### ISSUE TITLE
SC 2.4.13: Fixed Reference Points "on the same page"

### ISSUE THREAD

**Issue by jbuller** [w3c/wcag#1302]
The paragraph feels out of place
>The term “on the same page” is common in English to describe when two people are talking about the same thing and agree on the content of the conversation. This success criteria makes sure that all users can literally be on the same page.

It sounds likes it's explaining a term that's just been used - when it hasn't. The concept of two people with different content arrangements, knowing they are referring to the same thing hasn't been mentioned yet. 
If it is useful at all as a aide-memoire then I think it belongs lower down in the explanation.

**Comment by alastc** [comment]
PR #1580 created to update that.

**Comment by alastc** [comment]
HI @jbuller, thanks for that, another change we made removed that paragraph, so I'm closing this issue.
