### ISSUE TITLE
SC 3.2.6 Being responsible for content

### ISSUE THREAD

**Issue by jbuller** [w3c/wcag#1303]
>The human contact details should enable the user to connect with the organization or the part of the organization responsible for the content. For example, an online jobs / recruitment portal should provide a contact method for the team that supports the recruitment portal and not a catch-all for the entire company. Each layer of contact added prolongs the time before the user will receive help.

Being responsible for content and being able to assist with issues relating to the content are not the same thing. A customer support person may be able to help but not be able to affect the content. It seems you are prescribing organisational structures and not accounting for efficiencies of corporate support systems. At the other end of the scale, the guidance both demands and prohibits the use of a single mailbox for a small entity.

It's not clear what 'layer' is referring to either. I presume it is relating to the above point. But it could also be interpreted (without the context of the paragraph) as somewhat referring to the layers of the SC - human contact, chatbot, self help, contact mechanism.

**Comment by scha14** [comment]
Draft response :

https://github.com/w3c/wcag/pull/1366 changes _responsible for_ to _can assist with_

For the second point about _each layer of contact_, the phrase only appears in the context of the paragraph that talks explicitly about human contact details. The interpretation is clear to mean the number of steps a user has to go through to reach someone who can help. It is left unchanged for now.

**Comment by alastc** [comment]
The group responded with:
<hr>
We have changed "responsible for" to "that can assist with" to address your comment. Regarding the point about each layer of contact, the phrase only appears in the context of the paragraph that talks explicitly about human contact details. Within context it means the number of steps a user has to go through to reach someone who can help. We have left it unchanged for now.
