### ISSUE TITLE
C7 - change needed in CSS code for example

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#131]
C7: Using CSS to hide a portion of the link text contains the following CSS to visually hide an element:

a span {
    height: 1px;
    width: 1px;
    position: absolute;
    overflow: hidden;
    top: -10px;
}

Is there any reason to include the negative top value? If top, right, bottom, and left are not set, the element will stay in the rendered place. This would prevent any mess-ups with—for example—focus styles. A way around this would be to set position to relative on the parent element, but that means extra code that isn’t strictly necessary if top wasn’t set.

**Comment by kwahlbin** [comment]
This is the CSS that we recommend that has worked across different platforms, browsers and AT

.visually-hidden
{
  position: absolute;
  clip: rect(1px 1px 1px 1px);  /* for Internet Explorer */
  clip: rect(1px, 1px, 1px, 1px);
  padding: 0;
  border: 0;
  height: 1px;
  width: 1px;
  overflow: hidden;
}

**Comment by MichielBijl** [comment]
This opening post was [originally posted on the WAI IG mailing list](http://lists.w3.org/Archives/Public/w3c-wai-ig/2016JanMar/0048.html).

@kwahlbin that looks good to me. For which version(s) of IE is the space separated rect value?

**Comment by awkawk** [comment]
I understand that the IE fix is for IE 6/7.  I think we can let it go if that is correct.

**Comment by awkawk** [comment]
Can we make this change? If not, let's close this issue.

**Comment by alastc** [comment]
I think it is worth an update, I did a PR in #630 

This [post from TPG](https://developer.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/) was useful for seeing the test results of various methods (updated in 2016).

The question that struck me was: Is this still recommended, or would we point to a variation of [ARIA1](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA1)?

**Comment by patrickhlauke** [comment]
> The question that struck me was: Is this still recommended, or would we point to a variation of [ARIA1](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA1)?

depends which browser/AT combos you're aiming to support. more specifically, if you're wanting to support (generally old) AT that doesn't have full ARIA support. I seem to remember (but shamefully, haven't got the ability to test just now) that even fairly recent screen magnifiers with screen reading functionality still struggle with some basic ARIA stuff...

**Comment by alastc** [comment]
I'm happy to keep it (as updated), just want sure if we need a similar one for ARIA usage that is 'more' recommended.

**Comment by awkawk** [comment]
Thanks for the comment - we have implemented the change in Pull Request #630
