### ISSUE TITLE
SC 2.5.8 Pointer Target Spacing - target size

### ISSUE THREAD

**Issue by EmanuelaGorla** [w3c/wcag#1311]
I appreciate that the new [SC 2.5.8](https://www.w3.org/TR/WCAG22/#pointer-target-spacing) does not cover target size as this is already covered by SC 2.5.5, and I like the fact that the new SC provides a "second best option" for those instances where complying with SC 2.5.5 is not feasible. However, a large non-interactive area around a very small interactive component will not necessarily make it easy for users to see or activate the component. Could a minimum target size be included in SC 2.5.8 also? A target size smaller than 44 by 44 CSS pixels, which is often difficult to achieve, but still large enough for most users to be able to perceive and operate?

**Comment by scha14** [comment]
Proposed response 

> This SC is intended to avoid accidentally activating targets if they are spaced too close together. It is hard to establish what would be a large enough size below 44 pixels for most users. 
> 
> That is why, as a next level [SC 2.5.5 ](https://www.w3.org/WAI/WCAG22/Understanding/target-size.html) is intended to make sure the targets are large enough to be confidently activated.

**Comment by alastc** [comment]
The proposed response was accepted by the group, 8th Aug 2020.

There are other issues open that may impact this, but we'll continue the conversations there.
