### ISSUE TITLE
Translations URLs pointing to folders rather than documents

### ISSUE THREAD

**Issue by plannero** [w3c/wcag#1319]
Some official translations of WCAG also have official URL:s. Eg:
https://www.w3.org/Translations/WCAG20-ru/ (Russian) and
https://www.w3.org/Translations/WCAG20-sv/ (Swedish)

Previously, those URL:s pointed directly to the current version of the specification document (making possible deep linking to sections using URL-suffixes such as #keyboard-operation or #text-equiv ) but the URL:s now lead to a unix-like folder listing instead of a document. It is possible to use this folder listing to reach the latest version of the translation, but if you do, you lose the deep linking target and have to search the document. 

I would be happy if somebody at W3C could revert to the previous setup, as I have many documents with deep links to specific SC in the official Swedish translation of WCAG 2.0.

Thanks!

**Comment by michael-n-cooper** [comment]
I fixed some redirects for these and other WCAG 2 translations.
