### ISSUE TITLE
2.5.8 Pointer Target Spacing could include link to the definition of mechanism

### ISSUE THREAD

**Issue by ajanec01** [w3c/wcag#1321]
The first bullet point of [2.5.8](https://www.w3.org/TR/WCAG22/#pointer-target-spacing) (Enlarge) could include the [definition of mechanism](https://www.w3.org/TR/WCAG22/#dfn-mechanism) just as [sc 1.4.8 ](https://www.w3.org/TR/WCAG22/#visual-presentation)does.

Also, if I understand those definitions correctly, a simple browser extension with a bit of css would make this criterion a pass for all desktop sites. Is this correct?

**Comment by scha14** [comment]
https://github.com/w3c/wcag/pull/1338 adds the definition of mechanism to the first bullet point. 

For the second part, it depends on whether the browser extension meets the defined success criteria for the conformance level claimed. It may be explicitly provided in the content, or may be relied upon to be provided by either the platform or by user agents, including assistive technologies.

**Comment by scha14** [comment]
@ajanec01 please comment if this is okay to close. Thank you

**Comment by ajanec01** [comment]
Hey @scha14 
Good to close.
Thanks!

**Comment by alastc** [comment]
We need to run the new aspects past the group, then we'll circle back to close this.

**Comment by alastc** [comment]
Oh, actually, it's very editorial, sorry, I'll merge that!
