### ISSUE TITLE
H88: need to refer to HTML 5

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#133]
<a href="http://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/H88.html">Current draft</a> says "At the time this technique was published, the appropriate versions of these technologies is HTML 4.01 and XHTML 1.0. HTML 4.01 is the latest mature version of HTML, which provides specific accessibility features and is widely supported by user agents."

However we know the latest HTML recommendation spec is HTML 5. I think that the draft should be updated.

**Comment by awkawk** [comment]
Pull request to address: https://github.com/w3c/wcag/pull/137

**Comment by joshueoconnor** [comment]
@cooper can live with it.

**Comment by momdo** [comment]
In March of this year, the status of [HTML4](https://www.w3.org/TR/2018/SPSD-html401-20180327/) and [XHTML1](https://www.w3.org/TR/2018/SPSD-xhtml1-20180327/) have been changed to Superseded Recommendation.
