### ISSUE TITLE
2.5.7: Dragging - essential example

### ISSUE THREAD

**Issue by wardav** [w3c/wcag#1336]
I am trying to work out what an example would be for essential on 2.5.7: Dragging. 

I am aware that the generic essential definition is used across SC. But it's often useful to have examples. For example, pointer cancellation has:

- An activity that emulates a physical on-press trigger, such as when playing an on-screen piano keyboard. Activation on the up-event would significantly alter the desired behaviour.
- A program for shooting skeets where waiting for the "up" event would invalidate the precise timing necessary for the activation.

I am not sure what this would be for dragging, though. 

Maybe a physics-based game where you have to drag and release, like Angry Birds. It would invalid the game if you could just type in the exact angle, velocity, etc.

Another example might be something like https://www.rightmove.co.uk/draw-a-search.html# you can click to put down notes and them drag them around for finer control.

However, in this case, it would be possible to make it work with a single pointer -- e.g. each note would have an up, down, left and right button, or an x and y input field. But I can imagine it being very tricky to make usable.

Although in this case, there are the clear and undo buttons, so the user could get the nodes to the exact position they wanted by using these buttons are trying again. But they would not have access to the "I want to adjust this slightly" functionality.

**Comment by patrickhlauke** [comment]
Only example I can think of is something like a game that tests your dexterity in following a path (like those electric rails where you have to carefully maneuver a metal ring on a handle around the track without touching it).
