### ISSUE TITLE
WCAG 2.1 Rec, 5.3.1 left-over note?

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#1340]
in [section 5.3.1 of WCAG 2.1](https://www.w3.org/TR/WCAG21/#x5-3-1-required-components-of-a-conformance-claim) , there seems to be a leftover note that should probably have been deleted after updating the text:

> 2. Guidelines title, version and URI "Web Content Accessibility Guidelines 2.1 at https://www.w3.org/TR/WCAG21/"
In WCAG 2.0 this was a dated URI, which may need to be adjusted when this becomes a Rec.

Not sure what the state of this is. There is also a stray quotation mark.

**Comment by fstrr** [comment]
closing as completed.
