### ISSUE TITLE
Cognitive function test exception is arbitrary

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#1344]
The definition of Cognative function test lists remembering name, e-mail and phone number as exceptions. This seems arbitrary, based on current (arguably even outdated) methods of communication. A lot of people use their social media accounts much more than they do e-mail. Why would remembering your Twitter handle be any more difficult then remembering your e-mail address?

My biggest concern with it isn't the arbitrary nature of it, but the problem that phone numbers and e-mail addresses aren't universal. Not everyone has an e-mail address, and a lot of people do not know their own phone number.

I think a better solution for this would be to make this abstract, something like "Except for common personal identifiers such as name, e-mail, phone number or handle on social media." That gets to the issue that someone might actually need their handle to sign in, but that shouldn't be hard to find a solution to. The platform needs to support two such identifiers, (i.e. handle and e-mail, or handle and phone number).

**Comment by alastc** [comment]
As noted in a previous issue, I think the logical line we are trying to draw is between:

- Things which are about you, and do not vary by site. E.g. Email address, Name, postal address.
- Things which vary by site (or at least should). E.g. username, password, ID for that organisation.

I think that can be clarified and updated in the definition, your suggestion works for me.

**Comment by alastc** [comment]
I've updated [#1411](https://github.com/w3c/wcag/pull/1411/files) with this wording.

**Comment by alastc** [comment]
Closing based on the changes here:
https://github.com/w3c/wcag/pull/1411/files

Minutes: https://www.w3.org/2020/09/22-ag-minutes.html#item03
