### ISSUE TITLE
Textual size fix needed 2.4.11: Focus Appearance (Minimum)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1351]
2.4.11: Focus Appearance (Minimum)

https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html

> Figure 2@@@ Update. The inner outline is slightly smaller than the outer edge of the component, but using a 2px thick indicator means it is well over the minimum requirement of 180px squared.

The following 3 examples use a 90px wide by 30px tall button, therefore the surface area requirement is 240px. 

NOT 180px

Think this must be changed to:

Figure 2@@@ Update. The inner outline is slightly smaller than the outer edge of the component, but using a 2px thick indicator means it is well over the minimum requirement of 240px surface area.

**Comment by jake-abma** [comment]
also doesn't squared mean X times X

Resulting in 180px X times 180 px = 32400 px surface area?

Think this might be changed to:

Figure 2@@@ Update. The inner outline is slightly smaller than the outer edge of the component, but using a 2px thick indicator means it is well over the minimum requirement of 240px surface area.

**Comment by patrickhlauke** [comment]
> also doesn't squared mean X times X

180 px squared is the written version of 180px²

**Comment by alastc** [comment]
I think this was dealt with in one of the items from yesterdays call, preview here:
https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html 

Diff: https://github.com/w3c/wcag/pull/1330/files

**Comment by jake-abma** [comment]
@alastc ok, clear, probably discussed when I was in the kitchen... :-) 

what about the "240px squared"? I know that "15.5 squared" is 240, but "240 squared" in this case just means surface area?

**Comment by alastc** [comment]
Yep, surface area. I think that is clear from the text above in the understanding doc?

**Comment by jake-abma** [comment]
For me yes, but the wording interpretation of 'squared' was not directly a synonym for surface area for me, closing...
