### ISSUE TITLE
Non-modal dialogues and Unobscured 2.4.11: Focus Appearance

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1352]
non-modal dialogues may be movable by users (dragged to a unknown place on screen) and thus not clear for an author where they are on the page.

The "Unobscured" component (non-modal) should not be applicable in this case as it is not possible for authors (or very hard...) to prevent focussed items to appear under such non-modal dialogs.

**Comment by jake-abma** [comment]
https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#unobscured

> Unobscured
> Where other content can overlap with a focused item, the focused element should not be hidden. Typical content which can overlap focused items are sticky footers, sticky headers, or **non-modal dialogues**.

**Comment by alastc** [comment]
If you are moving a non-modal dialogue around, wouldn't that have the focus? 

So presumably the scenario would be that you tab through a page, trigger the dialogue, move it around, then tab around the page again? So it would be a case where the user controls the block, rather than the author?

For this:

> **Unobscured:** Where other content can overlap with a focused item, the focused element should not be hidden. Typical content which can overlap focused items are sticky footers, sticky headers, or non-modal dialogues.

Remember we can't use "should not", it needs to be an "is" statement (in WCAG 2.x), E.g:

> Where other content can overlap with a focused item, the focused element is not entirely hidden.

The other aspects would go in a note or understanding doc.

If this were a big enough (/common enough) issue we could consider a more explicit exception such as:

> Where other content can overlap with a focused item, the focused element is not entirely hidden, unless the other content is moved by the user to obscure the focused element.

It like a pretty niche scenario though, I'm not sure it's worth it.

**Comment by jake-abma** [comment]
The presumably scenario is correct, tab around the page while dialog is somewhere it can block this elements focus.

It might be a niche scenario BUT  "or non-modal dialogues" are mentioned and can often be placed on different spots. We know now and should mention this case to be clear on the topic.

**Comment by alastc** [comment]
I assume we'd like a situation where:
- The default location of a non-modal dialogue does not obscure interactive items;
- If the user moves it, it is their responsibility about whether that blocks other content.

I think non-modals which are not user-moveable are more common than movable ones, but I expect some applications use them a lot.

How about an update to the understanding doc such as:
> Where other content can overlap with a focused item, the focused element should not be hidden. Typical content which can overlap focused items are sticky footers, sticky headers, or non-modal dialogues. As a user tabs through the page, these layers of content can obscure the focused item, including the focus indicator. **If the interface is configurable and the user can move non-modal dialogues around then only the default position would be considered for testing & conformance.**

**Comment by RavenAlly** [comment]
Might "initial position" be better than "default position"?

"Default position" might be interpreted as "the position of this non-modal thing regardless of device, screen size, resolution, magnification, etc." which is rarely the case.

**Comment by alastc** [comment]
Closing based on the update in #1504
