### ISSUE TITLE
ARIA13: invalid markup example

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#136]
Example 1:

<pre><code>&lt;p role="complementary" aria-labelledby="hdr1"&gt;
 &lt;h1 id="hdr1"&gt;
    Top News Stories
 &lt;/h1&gt;
&lt;/p&gt;
</code></pre>

This markup example is invalid.

**Comment by awkawk** [comment]
Addressing in https://github.com/w3c/wcag/pull/138
