### ISSUE TITLE
Pointer Target Spacing (2.5.8) understanding note gives the wrong rationale?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1362]
The first note in the understanding document https://www.w3.org/WAI/WCAG22/Understanding/pointer-target-spacing.html states

> This criterion has been formulated to increase the hit-area of small targets,...

but this is not strictly true. The whole rationale for the SC is not to "increase the hit-area" (and indeed, see https://github.com/w3c/wcag/issues/1361 for an example where to pass 2.5.8 authors may actually *decrease* the hit area), but rather

> This criterion has been formulated to decrease the likelihood of users accidentally activating the wrong target...

or similar (as is indeed stated in the actual intent later on)

> The intent of this Success Criterion is to ensure targets can easily be activated without accidentally activating an adjacent target.

**Comment by detlevhfischer** [comment]
Good point @patrickhlauke 
It would certainly better to emphasise the point of separating targets so that they don’t accidentally land under the ‘fat finger’, rather than the aim of increasing target size. I’ll draft a text change.
