### ISSUE TITLE
Comment from IBM: Make border a defined term in 2.4.11

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#1373]
The current wording of the first bullet of Focus Appearance (Minimum) is:
> Minimum area: The [focus indication area](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-focus-indication-area) is greater than or equal to a 1 [CSS pixel](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-css-pixel) border of the focused control, or has a thickness of at least 8 CSS pixels along the shortest side of the element.

The concept of "border" must be understood for users to properly interpret the resulting formula. Since the calculation itself is not part of the normative content, we recommend defining the term to make this formula clearer and to reduce translation issues. A non-normative note already exists, which we have modified as a definition.

>A border is the perimeter of the control and defines its shape. Standard formulae exist for calculating the perimeters of rectangles, circles and other geometric shapes. A border is not a reference to the CSS property of the same name.

Potentially the definition could specifically include the formula for rectangles and circles.

**Comment by 36degrees** [comment]
I think this overlaps quite a lot with #1324, as border not being clearly defined leads to the ambiguity mentioned there.

**Comment by alastc** [comment]
It looks like your re-write in #1403 included a definition of perimeter, so would close this issue?

**Comment by alastc** [comment]
We have perimeter as a defined term now, so closing this issue.
