### ISSUE TITLE
IBM Comment: Make small editorial change to Minimum Area in 2.4.11

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#1374]
The first bullet of Focus Appearance (Minimum) reads:
> Minimum area: The [focus indication area](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-focus-indication-area) is greater than or equal to a 1 [CSS pixel](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-css-pixel) border of the focused control, or has a thickness of at least 8 CSS pixels along the shortest side of the element.

The "or" conjunction can be mis-applied. We recommend restating the "focus indication area" wording to read:
> Minimum area: The [focus indication area](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-focus-indication-area) is greater than or equal to a 1 [CSS pixel](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html#dfn-css-pixel) border of the focused control, or the focus indication area has a thickness of at least 8 CSS pixels along the shortest side of the element.

**Comment by scha14** [comment]
https://github.com/w3c/wcag/pull/1471

**Comment by alastc** [comment]
It looks like #1403 addresses this?

**Comment by alastc** [comment]
@mbgower - as #1403 was merged I'm closing, but re-open if I'm mistaken.
