### ISSUE TITLE
Timeline for WCAG 2.2

### ISSUE THREAD

**Issue by PICARDBRB** [w3c/wcag#1377]
Can you provide a timeline for WCAG 2.2 Published recommendation?  
thanks

**Comment by lauracarlson** [comment]
Check:
https://www.w3.org/WAI/GL/project

**Comment by PICARDBRB** [comment]
got it, thanks

**Comment by mraccess77** [comment]
Latest here: https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/
