### ISSUE TITLE
'Understanding Findable Help 3.2.6' implicitly recommends unhelpful page formats/headings

### ISSUE THREAD

**Issue by m-green** [w3c/wcag#1380]
The current wording of [Understanding Success Criterion 3.2.6: Findable Help](https://w3c.github.io/wcag/understanding/findable-help.html) includes the following bullet point as one of the mechanisms to get help:

> Self-help option such as an up-to-date Frequently Asked Questions, How Do I page, Support page.

This may read as implicitly approving pages in ‘FAQ’ or ‘How Do I…’ as a primary help format. But pages in those formats can can make life very difficult for users, because the question format of their titles and headings makes them longer and harder to scan and understand. These formats also often lead to duplication in content and navigation.

On GOV.UK we’ve [advised against FAQs since 2013](https://gds.blog.gov.uk/2013/07/25/faqs-why-we-dont-have-them/) because of these issues. We advise front-loaded, action-focused page titles and headings instead.

So I wonder whether the bullet point might be better as:

> Self-help option, such as support pages with front-loaded, action-focused titles and headings

**Comment by patrickhlauke** [comment]
"such as..." lists are always open and incomplete, but more to your point: i think it would be a bit of a reach here to, essentially, NOT approve of FAQ/How do I/etc type pages. yes, they're likely not as good as "front-loaded, action-focused..." type pages, but it would be a bit restrictive to say that they're NOT allowed/sufficient to pass. keeping in mind that this is only a bare minimum. i'd suggest more an approach of adding to that list, and perhaps explaining how some options may be better than others, but not trying to outright disallow other, less ideal options, altogether.

(and yes, understanding is of course informative only, so whether these are in the list or not may not make a huge difference in terms of normatively passing/falling)

**Comment by scha14** [comment]
@m-green does the comment above address the initial concern? If so, could we close this issue?

**Comment by m-green** [comment]
Hi @scha14 - yes thank you, feel free to close.
