### ISSUE TITLE
Status of aria-hidden on Unicode characters technique from wiki

### ISSUE THREAD

**Issue by kantoche** [w3c/wcag#1386]
Hey,
This technique is a proposal referenced on the wiki: https://www.w3.org/WAI/GL/wiki/Using_a_Decorative_Unicode_Character

This technique would be interesting to address explicitly decorative text content, but its status seems not to have been progressed since May 2017 (last modified date on the wiki).
Could the WCAG team make an update about it?

**Comment by alastc** [comment]
Hard to say at the moment, I get a 403 forbidden error when trying to access it. I'll ask about that.

**Comment by awkawk** [comment]
Can get there from here: https://www.w3.org/WAI/GL/wiki/Using_a_Decorative_Unicode_Character

**Comment by kantoche** [comment]
Do you have any news about this issue?

**Comment by alastc** [comment]
I think that type of technique is now covered by ARIA24, see [example 4](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA24#example-4-multiple-icon-fonts-as-part-of-another-sematic-element-with-visible-text).

If you agree please close this issue. If not, it's something that can be added, but isn't high priority so will probably be left unless someone wants to create the draft technique in github.
