### ISSUE TITLE
Outdated understanding documents still linger around

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#1389]
* https://www.w3.org/WAI/WCAG21/Understanding/focus-visible-enhanced

Should be deleted and redirected to:

* https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum

**Comment by alastc** [comment]
Hi @yatil,

We will need to keep 2.1 (and 2.0) docs around for people referring to those standards and not aiming for the newer ones (yet, hopefully). 

Part of the solution to having proper information in 2.1 docs is to have multiple versions. 

However, what we are working towards is that the 2.0 & 2.1 docs use the canonical URL meta-data to put the latest docs first in search results (although that will be 2.1 until 2.2 is a recommendation).

**Comment by alastc** [comment]
Oh, and I've just realised you meant the 2.2 doc that is in 2.1.

Sorry, yep, that should disappear next time @michael-n-cooper publishes the docs there.

**Comment by yatil** [comment]
Exactly. I have no issue with 2.1 stuff being separate from 2.2 stuff. 😀

**Comment by yatil** [comment]
@alastc @michael-n-cooper Can we fix those issues in an expedited manner? People are stumbling over these documents and get confused:

From a Slack Community:

> Another issue. Must a focus ring pass color contrast requirements as per https://www.w3.org/WAI/WCAG21/Understanding/focus-visible-enhanced? This SC does not sound like it is official. SC 2.4.7 does not seem to require any minimum color contrast.

![](https://user-images.githubusercontent.com/58862/95175926-71d59180-07bc-11eb-8647-3069fd412212.png)

**Comment by yatil** [comment]
It’s also referenced from this page, without a note that it is WCAG 2.2: https://www.w3.org/WAI/WCAG21/Understanding/focus-visible

**Comment by yatil** [comment]
And another reference of the outdated page from Slack, with multiple people then referring to the future guidance as “Focus Visible (Enhanced)”. 

People will learn the wrong terminology and be confused once WCAG 2.2 launches. It also means that nobody can link to the WAI Understanding docs and techniques in good faith that the information there is accurate. This is damaging the reputation of these resources. Please push an update!

![Slack user asking “Would it fail https://www.w3.org/WAI/WCAG21/Understanding/focus-visible-enhanced”](https://user-images.githubusercontent.com/58862/96100421-a6400080-0ed4-11eb-8663-ff0cb3fad3b2.png)

**Comment by yatil** [comment]
This is also still not fixed. 6 months for deleting a page.

**Comment by alastc** [comment]
@michael-n-cooper another example, not fixed by the recent re-publish.

**Comment by yatil** [comment]
I think this was fixed a few months ago.
