### ISSUE TITLE
Editorial fix 2.5.1: Pointer Gestures

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1391]
https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures.html

Sentence need update:

Is:

> such as the drawing a specific shape

Should be:

> such as the drawing of a specific shape

Or:

> such as drawing a specific shape

**Comment by alastc** [comment]
I think " such as drawing a specific shape" would be simpler, I've just slipped that straight into the main branch.
