### ISSUE TITLE
Technique F17: procedure #4 should be reworded

### ISSUE THREAD

**Issue by webcc** [w3c/wcag#14]
In the file:

https://github.com/w3c/wcag/blob/master/wcag20/sources/failure-tech-src.xml

i.e.:

http://www.w3.org/TR/WCAG-TECHS/F17.html

"For client-side image maps, check that the value of the usemap attribute has a corresponding id value if the usemap attribute is not a URI."

According to the HTML 4.0.1 specification the usemap attribute _must_ be an URI and must match the value of the name attribute of another map element.

**Comment by joshueoconnor** [comment]
Comment was accepted and there was a WG resolution but the spec doesn't seem have to have been updated. Am looking into it. Reply sent by AWK on 4/8/2014.

Working Group Resolution (LC-2904):
Thanks for your comment. We have updated the test procedure to reflect the
HTML spec correctly:

For client-side image maps, check that the value of the usemap attribute is
a URI that references a valid name or id.

**Comment by joshueoconnor** [comment]
//James Nurthen made this suggestion on 22/7/2014

  Following the call I researched a little more. I think we should use the
    text in the HTML5 spec to give a proposed change to bullet 4 of

    "For client-side image maps, check that the value of the usemap attribute is
    a valid hash-name reference to a map element."

    Hash-name reference in html5 is defined at
    http://www.w3.org/TR/html5/infrastructure.html#syntax-references. Perhaps
    this should be added in the resources section.

    On further thoughts perhaps we should genericise this even more to cover
    other cases which use hash-name references.
    Proposed steps in a more generic test procedure are:

    1) Check that attribute values that have an idref value have a corresponding
    id value.
    2) Check that attribute values that have a hash-name reference refer to a
    valid name or id.

    If step #1 or step #2 is false, then this failure condition applies and the
    content fails the success criterion.

[Josh Notes - Jan 2015]: Loretta liked it, but the reply went to the commenter as above.
Josh to raise at next meeting (13th Jan 2015) about status to check its correct.

**Comment by joshueoconnor** [comment]
Change to techs doc did go live http://www.w3.org/TR/WCAG-TECHS/F17.html
