### ISSUE TITLE
ARIA6: Redundant markup example

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#140]
In example 3, current example:

```html
<div role="math" aria-label="6 divided by 4 equals 1.5">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    ...
  </math>
</div>
```

According to the <a href="http://www.w3.org/TR/html-aria/">ARIA in HTML</a> spec, `math` element has `role=math` as default implicit ARIA semantics. Thus, this example should be written like following markup:

```html
<math xmlns="http://www.w3.org/1998/Math/MathML" aria-label="6 divided by 4 equals 1.5">
  ...
</math>
```

**Comment by awkawk** [comment]
Does it work the same or better with assistive technologies?

**Comment by joshueoconnor** [comment]
We need some test cases with the Math role. If I have time, I'll do some and feedback.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
