### ISSUE TITLE
Suggest including the first note provided with SC 2.4.11 (AA) on SC 2.4.12 (AAA) as well.

### ISSUE THREAD

**Issue by SuzanneTaylor** [w3c/wcag#1405]
The first "Note" provided with SC 2.4.11 is:

"A keyboard focus indicator which has a pattern or gradient may have parts that do not meet the 3:1 contrast ratio for the change of contrast, as long as an area equal to the minimum does meet the contrast ratio."

This is important to allow two-tone focus indicators, which is important to allow a single high contrast focus indicator to be used throughout a product that has a variety of background colors. A single focus indicator used throughout might reduce cognitive load;  Being able to learn just one focus indicator and look for it over and over, can help a user to concentrate on the purpose of the resource. Since at level AA, an area equal to a one pixel border is the "minimum," this Note allows an example like the following to pass for all three links shown, since smallest area is covered by the darker color, which is dashed, but two pixels wide, so the equivalent of a solid one pixel wide border: http://manateeroad.com/BugReports/WCAG22AAFocusContrast.html

This Github issue is to suggest adding the same note to 2.4.12, but adapted to 4.5:1 contrast:

"A keyboard focus indicator which has a pattern or gradient may have parts that do not meet the 4.5:1 contrast ratio for the change of contrast, as long as an area equal to the minimum does meet the contrast ratio."

This would allow examples like this: 
http://manateeroad.com/BugReports/WCAG22AAAFocusContrast.html

**Comment by detlevhfischer** [comment]
Make sense - but should then all three notes be replicated in 2.4.12?

**Comment by SuzanneTaylor** [comment]
The third note probably won't be there anyway in the final version.
The second note could be repeated, or it could become a definition along these lines:

"Minimum area: The focus indication area is greater than or equal to a 1 CSS pixel border [removed: of the] [added: along the **boundary of] the focused control**, or has a thickness of at least 8 CSS pixels along the shortest side of the element."

"Minimum area: The focus indication area is greater than or equal to a 2 CSS pixel solid border around the [added:  **boundary of the focused] control."

**Boundary of the focused control:** The edge or edges of the hit area, or, if the control has a visible boundary smaller than the hit area, the edge or edges of that visual boundary.

**Comment by mraccess77** [comment]
One thing about the wording is that it may be perceived that focus area must be along the border - but it actually only needs to be that size based on that border - but the indicator could be  a square inside the control and not along the border.

**Comment by SuzanneTaylor** [comment]
Does the guideline leave wiggle room as to where the 2nd pixel would be measured from. The 1 pixel border would be the outermost pixel around the edge of the hit area or a visual boundary within the hit area. Where is the 2nd pixel for the AAA guideline? It is just inside that, or just outside?

**Comment by alastc** [comment]
The note has been added.
