### ISSUE TITLE
"Accessibility Support for WAI-ARIA" description

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#141]
In <a href=http://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/wai-aria_notes.html#wai-aria_accessibility_support>Accessibility Support for WAI-ARIA</a>:

> The WCAG Working Group plans to review which WAI-ARIA techniques are sufficient when Accessible Rich Internet Application specifications reach W3C Recommendation status. 

We know <a href="http://www.w3.org/TR/2014/REC-wai-aria-20140320/">WAI-ARIA 1.0</a> is a W3C Recommendation now.

**Comment by awkawk** [comment]
Resolved: https://github.com/w3c/wcag/commit/b86ac726cd938c6024141a93f313114b34334db6?diff=split
