### ISSUE TITLE
3.3.7 Accessible Authentication - Add mechanism text

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#1418]
I've reviewed Accessible Authentication with Adobe's security team and the team that manages our centralized login experience.

They shared concerned with this SC in that while WebAuthn is great and passwordless is the direction that we intend to be moving over the coming years, they did a review in FY19-Q4 and found that the browser support is not quite where it needs to be to depend on it yet.

They also indicated that even where passwordless authentication is in place, there is still a fallback to traditional username/password types of authentication, so we need to make sure that it is very clear that username / password is ok.

We would like to make sure that the information about passwords being ok as long as the password managers can support the end user. My suggestion is to modify the SC from:

> If an authentication process relies on a cognitive function test, at least one other method must also be available that does not rely on a cognitive function test.

to

If an authentication process relies on a cognitive function test, at least one other @@authentication@@ method must also be available that does not rely on a cognitive function test or a mechanism must be available to assist the user in completing the cognitive function test.

Note: Support for password entry by password managers and copy and paste are examples of mechanisms which can be used to help address memorization and transcription cognitive function tests.

**Comment by awkawk** [comment]
Alternative note wording:

Note: Examples of mechanisms include support for password entry by password managers to address the memorization cognitive function test and copy and paste to help address transcription cognitive function test.

**Comment by alastc** [comment]
This came in just too late for next weeks survey, but I'd be interested to know if you still think it's necessary after the changes made next week, there is quite a lot on the copy-paste aspect.

For me: If there is a mechanism to assist the user, then it does not rely on a cognitive function test.

**Comment by awkawk** [comment]
@alastc Sounds like we agree but I think that we need to have the mechanism language in there so we are saying that you either need to not have a test or there needs to be a mechanism to get around it, whereas right now it feels like we need to do more hand-waving to address this.

**Comment by alastc** [comment]
With the updated SC text, I think that would be:

> For each step in an authentication process that relies on a <a>cognitive function test</a>, at least one other authentication method is available that does not rely on a cognitive function test or a mechanism must be available to assist the user in completing the cognitive function test.
