### ISSUE TITLE
"How to Meet" Links in WCAG 2.2 All Return 404 Errors

### ISSUE THREAD

**Issue by Grunet** [w3c/wcag#1421]
When I try to navigate to any of the criteria's "How to Meet" links (e.g. https://www.w3.org/WAI/WCAG22/quickref/#non-text-content) in the 11 August 2020 version of the WCAG 2.2 pages (https://www.w3.org/TR/2020/WD-WCAG22-20200811/), I get a 404 error saying "Document Not Found"

![image](https://user-images.githubusercontent.com/29322882/93414043-24719e80-f866-11ea-8114-284fb3fd979e.png)

This is not happening in the 27 February 2020 version (https://www.w3.org/TR/2020/WD-WCAG22-20200227/) because the links still point to the 2.1 versions of the pages (e.g. https://www.w3.org/WAI/WCAG21/quickref/#non-text-content).

I am unclear on if this version is still under construction or not, but I couldn't find a duplicate issue so I figured I'd bring it up just in case it isn't.

**Comment by michael-n-cooper** [comment]
Fixed in response to an email last week, for now by loading the 2.1 quickref at the 2.2 URI.
