### ISSUE TITLE
2.4.13 Fixed reference points needs definitions

### ISSUE THREAD

**Issue by LiLoDavis** [w3c/wcag#1426]
Missing two definitions:
- electronic publication
- pagebreak locator

**Comment by alastc** [comment]
This is for the understanding document:
https://www.w3.org/WAI/WCAG22/Understanding/fixed-reference-points.html

It looks like the build-process is missing those definitions.

**Comment by michael-n-cooper** [comment]
Fixed by https://github.com/w3c/wcag/commit/adeba524d912322ed91f825250fa984fc1450035
