### ISSUE TITLE
Is a technique needed for accessible alternatives for informationally rich background images (CSS)?

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#143]
Based on the discussion in #80 it seems to me that we need to have a technique that outlines how devs may use Sprites etc as background images in a way that is accessible. We acknowledge that this isn't best practice, but we cannot deny that it isn't done.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
