### ISSUE TITLE
SC 2.5.8 Pointer Target Spacing – Shouldn’t this SC require a minimum target size and spacing requirements?

### ISSUE THREAD

**Issue by brooks-newton** [w3c/wcag#1433]
On behalf of Thomson Reuters

The current language of this proposed Success Criterion provides a loophole that another commenter has pointed out (#1361), which allows content authors to reduce the target size to smaller dimensions in order to pass the proposed Success Criterion.  Reducing the size of the target makes the target more difficult to trigger. 

In order to avoid the unintended consequence of content authors reducing target sizes to pass this new rule, shouldn’t there be a bare minimum target size included in the normative text?  Also, shouldn’t there be minimum spacing requirements in the normative text, as well?  It seems like spacing requirements are required to support users who have disabilities that make it likely to inadvertently activate the wrong target when there isn’t enough spacing between adjacent targets.

**Comment by detlevhfischer** [comment]
Proposed Working Group answer:
We agree with your concerns, which have been voiced by others in similar ways, and are retracting 'Pointer Target Spacing'. Instead, we propose a level AA SC 'Target Size'. As to requiring target spacing on top of a minimum target size, this leads to all sorts of strange scenarios. We were not sure, for example, that having a row of targets of 26x26px with an all around spacing of 4px would be preferable over having larger targets of 34x34px that sits flush next to adjacent targets. Flush targets would be preferable, for example, in a custom drop-down menus where you do not want 'dead' horizontal stripes between active targets.

The text we now propose for inclusion in WCAG 2.2 is this:

> Target Size (AA)
    The size of the target for pointer inputs is at least 26 by 26 CSS pixels except when:
> - Inline: The target is in a sentence or block of text;
> - User Agent Control: The size of the target is determined by the user agent and is not modified by the author;
> - Essential: A particular presentation of the target is essential to the information being conveyed.

**Comment by alastc** [comment]
Hi everyone, 

The [text of the success criterion](https://raw.githack.com/w3c/wcag/scha14-pointer-target-spacing/understanding/22/pointer-target-spacing.html) has been significantly updated, and the group believes it resolves the issue so this issue is being closed. There will be another review opened soon.
