### ISSUE TITLE
SC 3.2.6 Findable Help - Declaring Human Contact Details

### ISSUE THREAD

**Issue by omar-bonilla** [w3c/wcag#1437]
On Behalf of Thomson Reuters:

Provided a fully automated contact mechanism, do content authors need to clearly state that human contact details will be provided once the process is complete?

**Comment by scha14** [comment]
Draft response : 

> Clearly stating that human contact details will be provided once the process is complete would be good practice but is not a requirement of the success criterion

**Comment by alastc** [comment]
The response was accepted by the group as our response. Please re-open if you do not consider this resolved.
