### ISSUE TITLE
[LowVision] Techniques needed for Icon Fonts

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#144]
The use of Icon fonts is more prevalent, do we need techniques for Icon fonts? My sense is yes. They are semantically rich, whether in a Unicode like strings etc or whatever.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).

**Comment by lauracarlson** [comment]
Hi Andrew and Josh,

I worked on some techniques in the Wiki last February.

* [Using a Decorative Icon Font](https://www.w3.org/WAI/GL/wiki/Using_a_Decorative_Icon_Font)
* [Providing an On-Screen Text Alternative for an Icon Font](https://www.w3.org/WAI/GL/wiki/Providing_an_On-Screen_Text_Alternative_for_an_Icon_Font)
* [Providing an Off-Screen Text Alternative for an Icon Font](https://www.w3.org/WAI/GL/wiki/Providing_an_Off-Screen_Text_Alternative_for_an_Icon_Font)

Thoughts?

Thanks,
Laura

**Comment by joshueoconnor** [comment]
Good work @lauracarlson. I think they look really good, and just got missed somehow. I'd say they are ready for WG review @awkawk is this ok with you, and enough reason to not mark as deferred?

**Comment by awkawk** [comment]
Yep, this qualifies as activity!

**Comment by joshueoconnor** [comment]
Excellent, and many thanks to @lauracarlson for this - looks great.

**Comment by joshueoconnor** [comment]
Thanks for this Laura - great stuff. Please let me know when the LVTF have reviewed it and we will bring it the wider group for approval.

**Comment by patrickhlauke** [comment]
Possibly related...advice to actually not use icon fonts altogether: https://speakerdeck.com/ninjanails/death-to-icon-fonts / http://blog.cloudfour.com/seriously-dont-use-icon-fonts/

**Comment by joshueoconnor** [comment]
Thanks @patrickhlauke . @lauracarlson  that may be useful.

**Comment by lauracarlson** [comment]
Thank you very much @patrickhlauke. I added the links to the resource sections of the Wiki pages.

**Comment by joshueoconnor** [comment]
Thanks @lauracarlson are these updated technique ready for review? 
    Using aria-hidden="true" on an icon font that AT should ignore
    Providing an On-Screen Text Alternative for an Icon Font

**Comment by lauracarlson** [comment]
@ joshueoconnor  [I've asked the LVTF](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Aug/0007.html) what the next step is so you can can get them on a survey.

**Comment by lauracarlson** [comment]
Hi @joshueoconnor,

The Low Vision Task Force met today and [resolved  to accept the 2 Icon font techniques](https://www.w3.org/2016/08/18-lvtf-minutes.html#item01):

1. - [Providing an On-Screen Text Alternative for an Icon Font]( https://www.w3.org/WAI/GL/wiki/Icon_Font_with_an_On-Screen_Text_Alternative)
2. - [Using aria-hidden="true" on an icon font that AT should ignore]( https://www.w3.org/WAI/GL/wiki/Using_aria-hidden%3Dtrue_on_an_icon_font_that_AT_should_ignore)

Thanks

**Comment by joshueoconnor** [comment]
This has been taken up by the LVTF.
