### ISSUE TITLE
ARIA19: Need to update link URLs

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#146]
In <a href="https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA19.html#ARIA19-resources">resources section</a> URLs:

- http://www.w3.org/TR/2011/CR-wai-aria-20110118/states_and_properties#aria-describedby
- http://www.w3.org/TR/2011/CR-wai-aria-20110118/roles#alert
- http://www.w3.org/TR/2011/WD-html5-20110525/

Respectively as follows:

- https://www.w3.org/TR/wai-aria/states_and_properties#aria-describedby
- https://www.w3.org/TR/wai-aria/roles#alert
- https://www.w3.org/TR/html5/

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag/commit/4286b9384f88aac8fe87df837cdec322f7e79be6
