### ISSUE TITLE
"Breadcrumbs" not a term understood by users

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag#1468]
The ARIA Authoring Practices 1.1 section on breadcrumbs, under the heading "Example", links to a document at [https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html](https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html). There it says this in the Accessibility Features subsection:
> A nav element labeled "Breadcrumb" identifies the structure as a breadcrumb trail and.....

And the example HTML markup lower down includes that same text label. (This label is mentioned 4 times in all in the document.)

However the word "breadcrumbs" is a term we use in the web development industry; it means nothing to the ordinary users to whom these labels are announced so is of no use to them. 

### Solution
I suggest amending the example, in all 4 places places, to say something useful to screen reader users like "You are here:" (which is what I generally recommend in audits), or "Where you are:" or something like that. 

Or maybe "Your navigation levels:" perhaps. In fact the more I think about it the more I like this last one though I have never used it before, as it refers to navigation, which screen reader users are well used to as a result of the nav element. And breadcrumbs are about "levels" in the navigation, and I think that will be understood by users in much the same way that the way the breadcrumbs are shown visually convey the idea of levels to sighted users.

However: if we can't come to a consensus about what words are best to use, then rather than just shelving it can it be changed to one of the suggestions above temporarily until a final phrase can be decided on, rather than leave the development guidance as the totally meaningless (to users, I mean) reference to breadcrumbs?

**Comment by alastc** [comment]
Hi Guy,

The ARIA authoring practices is not edited by this group, I think the place for that would be:
https://github.com/w3c/aria-practices/issues

I don't have enough access to that repo to transfer this issue, so I think you'll need to copy-paste the issue to an issue there.

Sorry,

-Alastair

**Comment by guyhickling** [comment]
Thank you Alastair, I'll do that.
