### ISSUE TITLE
I think there's a typo on w3.org

### ISSUE THREAD

**Issue by Sylvie123** [w3c/wcag#1478]
The typo is on this page: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11.html
- typo is “navigation” in: role="navigaton"
 it is missing the “i”. It is listed more than once within the page.
Thank you
Sylvie Faulkner

**Comment by alastc** [comment]
Thanks for highlighting this, the update has been merged with master and should appear soon.

**Comment by Sylvie123** [comment]
Hello, will it take a while before the fix shows up on the website? Thank you
<div id="leftnav" role="navigaton" aria-labelledby="leftnavheading">
<div id="leftnav" role="navigaton" aria-label="Primary">
