### ISSUE TITLE
ARIA4/5: Clarification of a user interface component

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#150]
In <a href="https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA4.html#ARIA4-description">description section of ARIA4</a>, the draft says "The objective of this technique is to define the role of an element using the role attribute with one of the non-abstract values defined in the WAI-ARIA Definition of Roles." I think the scope of the role of this description is too wide. In my view, it should be limited to <a href="http://www.w3.org/TR/wai-aria/roles#widget_roles_header">WAI-ARIA Widget Roles</a>. Additionally, according to the <a href="https://www.w3.org/TR/html-aria/">ARIA in HTML</a> spec, possible combination of roles and states are limited thus it should be noted as well.

**Comment by joshueoconnor** [comment]
This is meant to be a broad technique. There are non user interface components like regions. This is intentionally broad.

**Comment by joshueoconnor** [comment]
Surveyed Jan 22nd https://www.w3.org/2002/09/wbs/35422/Jan26_2016/results

**Comment by alastc** [comment]
Surveyed - proposed response accepted.
