### ISSUE TITLE
I think the forward slash is missing

### ISSUE THREAD

**Issue by Sylvie123** [w3c/wcag#1506]
https://www.w3.org/WAI/WCAG21/Techniques/html/H65.html
I'm just learning and was wondering if the space at the end of each input needs to be removed or add a forward slash.
<input id="areaCode" name="areaCode" title="Area Code" type="text" size="3" value="" >
<input id="exchange" name="exchange" title="First three digits of phone number" type="text" size="3" value="" >
<input id="lastDigits" name="lastDigits" title="Last four digits of phone number" type="text" size="4" value="" >

**Comment by patrickhlauke** [comment]
it doesn't do any harm having that space there...just looks a bit messy. and no, slash (to make it self-closing) is not needed unless you're being strict about xhtml (which really isn't a thing anymore)
