### ISSUE TITLE
ARIA5: About jQuery code

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#151]
I think that examples of ARIA5 demonstrate JavaScript snippets with jQuery, but text of these examples don't touch jQuery. I feel that the draft should mention that using jQuery in the prose, like <a href="https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA19.html#ARIA19-ex1">example 1 of ARIA19</a>.

**Comment by awkawk** [comment]
Proposed response for WG: We keep the examples as simple as possible, and JQuery is not critical for the clarification of the important points in the technique, so we are not making a change at this time.
