### ISSUE TITLE
Pre recorded Vs. Live in 1.2.6: Sign Language (Prerecorded)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1515]
The SC text says " for all prerecorded audio content in synchronized media"

The example in the Understanding is talking about "live" though: " The live video includes a full view of the sign language interpreter as well as the person presenting."

Is my interpretation correct and is the example not correct?
(as prerecorded also specially says "information that is not live")

Ps. the second example relies on the first...

https://www.w3.org/WAI/WCAG22/Understanding/sign-language-prerecorded.html

**Comment by patrickhlauke** [comment]
Yes, I believe the examples are incorrect and need to be modified. The SC does not apply to the live announcement/webcast scenario

**Comment by patrickhlauke** [comment]
https://github.com/w3c/wcag/pull/1517

**Comment by jake-abma** [comment]
can we fix, update, and close?
