### ISSUE TITLE
ARIA15/16: Refers to a specific date

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#152]
In description of ARIA15:

>  It is worth noting that as of the time of writing **(October 2013)** some assistive technologies read aria-describedby content immediately after an image's alt attribute information without user activation - ...

In description of ARIA16:

> Note that as of **December 2013**, label has better support than aria-labelledby, especially in older browsers and assistive technologies. 

These descriptions have to be reviewed from the point of view of the present time. Because the draft should be the latest description at publication date, I feel that the draft should not be mentioned for a specific date.

**Comment by awkawk** [comment]
@momdo, the date references can be updated but that takes someone to do the research.  We are happy to accept data that would bring this up to the current state, but without that we will leave it as-is.
