### ISSUE TITLE
Non-text contrast - clarify meaning of "active user interface components"

### ISSUE THREAD

**Issue by dashouse** [w3c/wcag#1521]
On [Understanding Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) the first line of the intent section reads:

"The intent of this Success Criterion is to ensure that **active user interface components** (i.e., controls) and meaningful graphics are distinguishable by people with moderately low vision"

While I personally understand the criterion to mean "user interface components that can be interacted with" the particular wording lends itself to be misunderstood as "user interface components that ARE active".

While working on a couple of projects to help companies meet this criterion I have met the same response from a number of designers and developers that Non-text contrast is only a consideration when the component is being interacted with (when it's active), e.g. when it has `:focus` `:hover` or `:active` rather than when the component is in it's default state.

Although the examples on this page do go into specifics it could be beneficial to add a more detailed  explanation of "active user interface components"

**Comment by alastc** [comment]
Hmm, ok, good to know.

When written it was intended to mean non-disabled / inactive components, because we have exceptions for in-active components. 

Suggested update:
- Remove the word 'active' from the 1st line of the intent.
- Update the 1st line under "Active User Interface Components" to explain that it is non-disabled components.

We've had a few discussions about the overlap of 'disabled controls' and 'inactive components', so it would be worth looking that up as part of this update.

**Comment by patrickhlauke** [comment]
there's an open/hanging pull request for a clarification of "inactive" https://github.com/w3c/wcag/pull/1154, which superseded https://github.com/w3c/wcag/pull/638

that came about from https://github.com/w3c/wcag/issues/636

**Comment by patrickhlauke** [comment]
@alastc not sure that just removing the 'active' in that 1st line, and adding a clarification under "Active User Interface Components", will be sufficient to remove ambiguity/misunderstanding. If people misunderstood it when it was referenced in the 1st line, they're still going to misunderstand it when the 4-5 other mentions of "Active" are still present. Maybe quite radical...just purge the word "Active" (from that title, the caption for Figure 1, the "Active User Interface Component Examples" heading and subsequent table caption) altogether? It still has the "Inactive...." section. Maybe add an extra note just after the 1st para of the intent to explicitly say "This requirement does not apply to inactive controls" or something.

**Comment by patrickhlauke** [comment]
Made a stab at the more brutal purge here https://github.com/w3c/wcag/pull/1547

**Comment by dashouse** [comment]
> Made a stab at the more brutal purge here https://github.com/w3c/wcag/pull/1547

Obviously only answering as the issue creator and not the wg but I feel like this PR clarifies the issue originally outlined.

Also just to say I do appreciate you taking this on board, thanks.
