### ISSUE TITLE
input type="number" spinner increase/decrease fail/pass AND 2.5.2: Pointer Cancellation 

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1529]
what is the verdict on "input type="number"" / spinners, where the down-event adds / subtracts 1 (or more, depending on time down) number? (and no clear way to reset / undo)

Checking 'undo' it is possible to change again to the original number (if you remember which one) but not sure if this is covered in this scenario.

If not covered, we kind of 'brake/fail' all input number spinners?

https://broken--deque-workshop.netlify.app/#main-content
In dialogs after clicking on recipe blue button:  Rate the yumminess (0 - 50) input number spinner

https://shaack.com/projekte/bootstrap-input-spinner/

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number

**Comment by patrickhlauke** [comment]
> This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

So for native `<input type="number">` and how the UA handles that, I believe the SC excludes this scenario

**Comment by jake-abma** [comment]
@patrickhlauke that is not what the note is about, it's for UA agent usage OR AT usage, not inputs which are part of the content: "**This requirement applies to web content that interprets pointer actions**"

**Comment by patrickhlauke** [comment]
`<input type="number">` and how it manifests itself in browsers is down to the browser - it's a replaced element. so i would say this does indeed fall under the note. the same way that the SC doesn't apply to, say, how the browser treats `<select>` elements, or `alert()` type confirmation dialogs etc...that's all part of how the UA is operated

**Comment by patrickhlauke** [comment]
> This requirement applies to web content that interprets pointer actions

and indeed, when i as an author use `<input type="number">`, *I* as an author am not interpreting pointer actions. I simply use the element and it's up to the user agent how it manifests it in the page.

**Comment by patrickhlauke** [comment]
(and for clarity ... here i'm referring to exclusively to `<input type="number">`, not custom-made spinners like the bootstrap example. in *that* case yes, the SC applies, as your code is indeed interpreting the pointer actions itself)

**Comment by jake-abma** [comment]
thx @patrickhlauke made up my mind... will exempt browser behavior here 

(but again hard to draw the line and explain when we do not exempt browser behavior for focus and do for these kind of usages and not hammer shut the issue and put the user need first)

The  "execute any part of the function" is hard though and might even depend on how you look at it / the purpose of the application and its results...

**Comment by patrickhlauke** [comment]
> The "execute any part of the function" is hard though and might even depend on how you look at it / the purpose of the application and its results...

yes, i think that is something that should be clarified further. things like changing a value in a widget (but not actually triggering any action as a result) to me don't feel necessary like a "function" - though not sure if other WG members are more hardline about this or not.

**Comment by patrickhlauke** [comment]
on that last point, i put on my fireproof trousers and filed #1542 ...
