### ISSUE TITLE
ARIA20: Redundant word

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#153]
In <a href="https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA20.html#ARIA20-description">description of ARIA20</a>:

> (see <a href="http://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA11" class="tech-ref">ARIA11: Using ARIA landmarks to identify regions of a page</a> (ARIA)).

I feel that "(ARIA)" is redundant string.

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag/commit/f06bfd8c59b6f40270baafea6049266bc31c670e
