### ISSUE TITLE
Text already present in input makes 1.4.11: Non-text Contrast pass?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1530]
When text has enough contrast for buttons it will pass this SC, like:

![image](https://user-images.githubusercontent.com/6384002/99379578-2a691780-28c9-11eb-8e11-bdf8149232c1.png)

and

![image](https://user-images.githubusercontent.com/6384002/99379780-656b4b00-28c9-11eb-9003-0a6b9d20591b.png)

But will this idea also pass when text is already present in an input while the border of the input does NOT pass the contrast?

See the "29 input type number" where #ccc will not pass on #fff but the text does with #666

<img width="506" alt="Screen Shot 2020-11-17 at 11 34 50 AM" src="https://user-images.githubusercontent.com/6384002/99379924-921f6280-28c9-11eb-87f9-66d1a6f6d778.png">

Only example on https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast#intent is the cursor/caret

> Text input focus style | A focus indicator is required. While in this case the additional gray (#CCC) outline has an insufficient contrast of 1.6:1 against the white (#FFF) background, the cursor/caret which is displayed when the input receives focus does provide a sufficiently strong visual indication.

But that is the 'focus' example, not an example where you might not get the idea there is a input at all with the example I've provided, the 29 input number.

**Comment by mraccess77** [comment]
same thing would be with any placeholder text (as long as the placeholder has sufficient contrast).   Seems like the text does identify the control - but doesn't communicate it's editable - but then again text doesn't communicate a button is actionable other than the wording of the text implying an action.    As written I'd generally pass these although personally I don't think this addresses the user need.

**Comment by jake-abma** [comment]
Thanks @mraccess77 I do agree with all you say, also the last part!
