### ISSUE TITLE
Does a video with a transcript fail SC 1.2.5 in light of "Full pages" conformance requirement?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1537]
The nominal difference between SC 1.2.3 and 1.2.5 is that 1.2.3 demands *either* audio description *or* media alternative, while 1.2.5 just demands audio description.

However, what happens if a video provides a media alternative such as a transcript? nominally, you'd say it passes 1.2.3 but fails 1.2.5. And the note in the [understanding for 1.2.5](https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded.html) says indeed

> If they wish to conform at Level AA, under Success Criterion 1.2.5 authors must provide an audio description

But: is the transcript not an accessible alternative to the video, in the sense laid out in the "[Full pages](https://www.w3.org/TR/WCAG/#cc2)" section

> For the purpose of determining conformance, alternatives to part of a page's content are considered part of the page when the alternatives can be obtained directly from the page, e.g., a long description or an alternative presentation of a video.

...and thus, this would *not* fail 1.2.5 since we have to treat/consider the alternative as if it were the element?

Is 1.2.5 essentially *overriding* this aspect of the conformance requirements/mention of alternatives?

**Comment by patrickhlauke** [comment]
the answer to my question there at the end is probably "yes", having discussed this with colleagues. but just so i'm clear in my own head: the "Full pages" conformance requirement says that one *can* treat even external pages etc as being part of the currently evaluated page if they're an alternative. So things that allow or require an alternative are good even if that alternative is not directly on the same page. But it's not to be treated in the sense that one can basically ignore the actual content in the page that would fail, *if* the alternative is there and can be reached from the current page, and that alternative *does* pass the conformance requirements.

**Comment by patrickhlauke** [comment]
Going to close this again, as it seems it's not so much about 1.2.5, but rather the subtle difference of what "Full pages" conformance claim explanation actually means in practice (and that no, you can't have a page that fails but then links to the same page where the failing element is replaced with something else that doesn't fail but conveys the same content, and use that to circumvent a fail). Still feels odd since for other cases we may still take that approach (e.g. one page that is not keyboard accessible, but that links to the same page that *is* keyboard accessible ... would we fail that for 2.1.1? generally probably not, as an accessible alternative is provided?). But my brain is now sufficiently knotted up that I'll leave it ...

**Comment by mraccess77** [comment]
I would not consider a full transcript as an alternative for SC 1.2.5 whether it was on the same or different page because it's not an alternative to synchronized video.

**Comment by patrickhlauke** [comment]
i use transcript here as a generic "alternative for time-based media" stand-in. not just dialog, but also full description of what happens in the visual part, any audio cues, etc.

**Comment by mraccess77** [comment]
A full transcript would have to be synchronized to actually provide an alternative in my opinion.

**Comment by bruce-usab** [comment]
I have seen automatically scrolling transcripts, but only as an alternative to captioning.  Audio Description is a very specific technique and is explicitly required by 1.2.5.  Glad to see this issue closed!

**Comment by mraccess77** [comment]
While not practical today - some preliminary research has been done on using TTS for audio description http://ncamftp.wgbh.org/ibm/dvs/

**Comment by patrickhlauke** [comment]
just to clarify that the driver/focus of my conundrum there yesterday was more to do with the interpretation of "Full pages" and whether it absolves one type of page content from meeting accessibility requirements if there's an easily reachable alternative way to present that content in a different way that circumvents the problems of the original content. i may ponder this some more and bring up a more focused question specifically about that...

**Comment by bruce-usab** [comment]
> just to clarify that the driver/focus of my conundrum there yesterday was more to do with the interpretation...

Understood.

> Is 1.2.5 essentially overriding this aspect of the conformance requirements/mention of alternatives?

No.

**Comment by Ryladog** [comment]
+1 to Bruce. Once again, Bruce saves the day!!

** katie **

*Katie Haritos-Shea*
*Principal ICT Accessibility Architect*


*Senior Product Manager/Compliance/Accessibility **SME*
*, **Core Merchant Framework UX, Clover*


*W3C Advisory Committee Member and Representative for Knowbility *


*WCAG/Section 508/ADA/AODA/QA/FinServ/FinTech/Privacy,* *IAAP CPACC+WAS = *
*CPWA* <http://www.accessibilityassociation.org/cpwacertificants>

*Cell: **703-371-5545 <703-371-5545>** |* *ryladog@gmail.com
<ryladog@gmail.com>* *| **Seneca, SC **|* *LinkedIn Profile
<http://www.linkedin.com/in/katieharitosshea/>*

People may forget exactly what it was that you said or did, but they will
never forget how you made them feel.......

Our scars remind us of where we have been........they do not have to
dictate where we are going.
