### ISSUE TITLE
ARIA7: Improvement of ID value

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#154]
In current <a href="https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA7.html#ARIA7-ex2">example 2 of ARIA7</a>:
```
<p>Download <span id="report-title" tabindex="-1">2012 Sales Report</span>:
<a aria-labelledby="report-title pdf" href="#" id="pdf">PDF</a> |
<a aria-labelledby="report-title doc" href="#" id="doc">Word</a> |
<a aria-labelledby="report-title ppt" href="#" id="ppt">Powerpoint</a></p>
```
If the Sales Report of 2013 exists on the same page, however, these ID value would be inappropriate.
Following example would be more appropriate.

```
<p>Download <span id="report-title-2012" tabindex="-1">2012 Sales Report</span>:
<a aria-labelledby="report-title-2012 pdf-2012" href="#" id="pdf-2012">PDF</a> |
<a aria-labelledby="report-title-2012 doc-2012" href="#" id="doc-2012">Word</a> |
<a aria-labelledby="report-title-2012 ppt-2012" href="#" id="ppt-2012">Powerpoint</a></p>
```

**Comment by awkawk** [comment]
@momdo, what you are saying is true, but as the purpose of the example is to show how to concatenate a label from multiple sources we prefer to keep the markup simple. If someone copies the example and pastes in into a page 5 times without changing the id values then they will discover the issue in testing or via a validator.
