### ISSUE TITLE
Understanding 2.4.11 minimum area clarification

### ISSUE THREAD

**Issue by abijames** [w3c/wcag#1552]
It would be helpful if the understanding document could explicitly state if the minimum area is based on the size of the element in its unfocussed state. The examples imply this but it is not stated in the text. 

We've been considering if changing a border from an inside stroke to an outside stroke in a contrasting colour would meet this success criteria for buttons with a border. Visually the button gets larger with the border changing to a contrasting colour.  This would seem to pass if the minimum area is based on the unfocussed state.

Proposed edit for the understanding document would be to add "in its unfocussed state" to the end of the sentence below:
The minimum size of the focus indicator must be at least the area taken by a 1 CSS pixel border around the element in its unfocussed state.

**Comment by alastc** [comment]
Hi @abijames,

The text has changed a little, but I assume you mean the 3rd paragraph under "Minimum area"?

I've created a little PR for that in #1577

What it did trigger though is a conflict with the SC text, which sets the area to the 'focused control', so I've made a small update to that as well, I think it makes more sense that way.

**Comment by abijames** [comment]
@alastc thanks, that PR  seems would provide the clarification we were looking for. 

One of the reason the designers were keen to flip the border from inside to outside the component was that this meant that components did not change size. When the components change size due to focus area being added then we saw components being repositioned across the page as focus moved which would had a detrimental impact on users.
