### ISSUE TITLE
Change 'label' for 'name' in ARIA9

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1563]
Title of technique is:

> Using aria-labelledby to concatenate a label from several text nodes

Shouldn't 'label' be changed to 'name' as this is not clear for all and the definition is clear about:

"the name may be hidden and only exposed by assistive technology."

> Using aria-labelledby to concatenate a name from several text nodes

https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA9

**Comment by alastc** [comment]
Sure, feel free to add a PR for the change...

**Comment by jake-abma** [comment]
not sure I've even added one, do we have clear documentation for it (remember we have from / for 2.1 updates) so I do not have to learn all about Github?

**Comment by patrickhlauke** [comment]
learning git/github would be good, yes ;)

https://github.com/w3c/wcag/pull/1823
