### ISSUE TITLE
Findable help term web page at the end of the phrase is confusing

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#1574]
CURRENT LANGUAGE
For single page Web applications or any set of Web pages, if one of the following is available, then access to at least one option is included in the same relative order on each page:
...
Do we mean that in an SPA each view needs to have the information, or only the initial state of the SPA. If the former then I think we need to make a small amendment to address each view of a SPA, If the latter then we are OK with the current language.

SUGGESTION
"For single page Web applications or any set of Web pages, if one of the following is available, then access to at least one option is included in the same relative order on each page (or each view inside a single page web application)

**Comment by mraccess77** [comment]
Good catch David - I think we mean each view of the SPA.

**Comment by alastc** [comment]
Hmm, then we have to define "view", which opens up another can of worms.

**Comment by scottaohara** [comment]
FWIW, this change (using / defining 'view') would definitely have helped with my confusion re: #1347 and the related issues/PRs.

**Comment by DavidMacDonald** [comment]
Perhaps it is a can of worms to define "view". Agreed, but if we leave the SC then there is no requirement for the help to v=be persistent across views (which might be acceptable but I don't think it is the intent. How about something like this?

View

> A distinct set of content which is loaded into a single page application (SPA) which is a major change in content from other sets of content available at the same URL.

I used "major change in context" to leverage the language of "[Changes of context](https://www.w3.org/TR/WCAG21/#dfn-change-of-context)"
We could alternatively leverage "substantially different from other sets of content..."


If we want to avoid the word "view" we could perhaps say something like "persistently available in single page applications".

For single page Web applications or any set of Web pages, if one of the following is available, then access to at least one option is included in the same relative order on each page or is persistently available in single page applications.

**Comment by mbgower** [comment]
@DavidMacDonald please tell me if this PR resolves your concern https://github.com/w3c/wcag/pull/1657

**Comment by rachaelbradley** [comment]
Recent pull requests have addressed this issue.
