### ISSUE TITLE
don't point to a 6 year old document

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/wcag#158]
[RIA4: Using a WAI-ARIA role to expose the role of a user interface component](https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA4.html) references the WAI-ARIA primer, a  W3C Working Draft 16 September 2010. I have no doubt that this document contains outdated information
for example:

> 2.5. HTML 5 - A Look Ahead
> HTML 5 and the "serialized" XHTML version of HTML 5 are years away from standardization.

and strongly suggest it should not be used as a reference

**Comment by stevefaulkner** [comment]
related to https://github.com/w3c/wcag/issues/150

**Comment by joshueoconnor** [comment]
Thanks @stevefaulkner. Editorial change that can be fixed in an update to this technique.

**Comment by joshueoconnor** [comment]
@stevefaulkner If you have suggestions for an updated URI that would provide a similar example etc, please let me know.

**Comment by alastc** [comment]
I think the closest equivalent is: https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView
Although it isn't as visual as it was before.

The text would also need updating to: "The WAI-ARIA authoring practices define a tree widget."

**Comment by joshueoconnor** [comment]
I like @jnurthen suggstions as outlined in the PR here https://github.com/w3c/wcag/pull/174/commits/51dc61457402e3cf59dad71e1f1e2fda12178822?diff=split It makes sense to reference a 'living document'.

**Comment by awkawk** [comment]
addressed in PR 174
