### ISSUE TITLE
Archive of task force conversations?

### ISSUE THREAD

**Issue by robfentress** [w3c/wcag#1584]
Are there records that are publicly available somewhere that document the conversations between task force members that led to the adoption of particular Success Criteria? When people have a question about one, looking at such an archived conversation might provide useful insights.  It would be sort of like how legal scholars sometimes look at the notes taken during the US Constitutional Convention to understand the original intent of the authors.

**Comment by alastc** [comment]
If you have a look at the task force homepages:
https://www.w3.org/WAI/GL/task-forces/

Each one has a mailing list archive. 

Also, if you follow the links to their documents / publications, you'll find things like the requirements documents (e.g. from [LVTF](https://w3c.github.io/low-vision-a11y-tf/requirements.html)).
