### ISSUE TITLE
What does “Sufficient as a way to meet an unwritten technique” mean ?

### ISSUE THREAD

**Issue by robfentress** [w3c/wcag#1585]
What does _“Sufficient as a way to meet an unwritten technique”_ mean when it appears beside a listed Success Criterion under the **Applicability** section of a WCAG Technique page?  For example, in [Technique H69 Providing heading elements at the beginning of each section of content](https://www.w3.org/WAI/WCAG21/Techniques/html/H69.html), under **Applicability** it says, _“Success Criterion 2.4.1: Bypass Blocks (Sufficient as a way to meet an unwritten technique).”_  Does this mean that simply providing headings for sections of content that are repeated across multiple web pages is sufficient for meeting [2.4.1 Bypass Blocks](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks)?  This seems problematic, since, although this may work for screen reader users, keyboard users would not be able to skip these sections unless they had installed a browser extension.  I have the same issue with [Technique ARIA11 Using landmarks to identify regions of a page](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11).

**Comment by alastc** [comment]
Hi @robfentress,

We dug into this, and it's a bug in the template when it expects another technique is needed, but due to the formatting of the understanding document (the source), there isn't another technique.

We'll find the affected understanding documents and update their structure.

**Comment by joe-watkins** [comment]
@alastc Hiya Alastair! :) Regarding the 'bug' mentioned above.

Is [ARIA11](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA11) (Using ARIA landmarks to identify regions of a page) on its own sufficient to meet `2.4.1 Bypass Blocks`? Or is there a fix coming to WCAG that will associate that Technique (ARIA11) with another Technique called out in `2.4.1 Bypass Blocks`?

**Comment by michael-n-cooper** [comment]
The "unwritten technique" is the one seen in the [Understanding page](https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks#sufficient), "Grouping blocks of repeated material in a way that can be skipped, using one of the following techniques:". The pull request will put that content into the Technique document, instead of "an unwritten technique".
