### ISSUE TITLE
update links in ARIA4: Using a WAI-ARIA role to expose the role of a user interface component

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/wcag#159]
suggest updating links in https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/ARIA4.html#ARIA4-resources

old: Using WAI-ARIA in HTML
new: Notes on Using ARIA in HTML https://www.w3.org/TR/aria-in-html/

old: WAI-ARIA 1.0 Primer
new: removed

old: HTML to Platform Accessibility APIs Implementation Guide: HTML Element to Accessibility API Role Mapping Matrix
new: HTML Accessibility API Mappings 1.0 https://www.w3.org/TR/html-aam-1.0/

**Comment by jnurthen** [comment]
working on this

**Comment by jnurthen** [comment]
See https://github.com/w3c/wcag/pull/160

**Comment by awkawk** [comment]
Accepted James editorial changes, although in a circuitous way... (https://github.com/w3c/wcag/commit/d5ae848d01c49ce85e36cbfe17d56c850ce1db30)
