### ISSUE TITLE
SC 1.3.6 Identify Purpose: Incorrectly cites SC 4.1.2 (typo)

### ISSUE THREAD

**Issue by therobertrich** [w3c/wcag#1590]
On the Understanding SC 1.3.6 page, (https://w3c.github.io/wcag/understanding/identify-purpose.html) the [Intent](https://w3c.github.io/wcag/understanding/identify-purpose.html#Intent) section, cites SC 4.1.2, but contains a typo and states "as required by 4.2.1"

**Comment by alastc** [comment]
Thank you, fixed with #1593
