### ISSUE TITLE
H99 test procedure only tests for navigation aspect of page breaks and not  locators

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1592]
SC 2.4.13 indicates that "each locator maintains its place in the flow of content," as well as a navigation method.  Right now you could use H99 to pass 2.4.13 without each locator maintaining it's place in flow content.  You could just have a list that moves there but no locator actually in the content.  When a criterion requires multiple explicit things each sufficient technique must check for those.  For example a technique for 1.4.13 Content on Hover/Focus covers all aspects of that SC.

**Comment by alastc** [comment]
@DavidMacDonald - another aspect to check with the ePub folks.

**Comment by alastc** [comment]
Hi @mraccess77, I think this one has been overtaken by the [updates to the SC](https://w3c.github.io/wcag/understanding/fixed-reference-points.html), as it does not include that clause anymore.
