### ISSUE TITLE
2.4.2 Page Titled incorrectly ties programmatic requirements with content SC

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#1598]
I was helping someone complete a VPAT today for a non-web document.
When we came to 2.4.2 Page Titled, my initial feeling is that their information had a title and they should pass.
> Web pages have titles that describe topic or purpose.
But as I looked at the Understanding document, I noticed that the Sufficient Technique joins a general technique for a descriptive title with a programmatic requirement (via either H25 or PDF18).
I'm not going to go into the various considerations for a non-web document and how WCAG2ICT deals with this.
What I want to note is that the SC text contains nothing about programmatic determination, and the HTML and PDF techniques exceed the requirement (for this SC).

IMO, the way this should be handled exactly how it is for 2.4.6 Heading and Labels ("Headings and labels describe topic or purpose."), which states in the Understanding document:
>Sufficient Techniques
G130: Providing descriptive headings
G131: Providing descriptive labels
NOTE
Headings and labels must be programmatically determined, per Success Criterion 1.3.1 .

IMO H25 should appear in 1.3.1 in the list of techniques listed under #11.

**Comment by JAWS-test** [comment]
A title is automatically bound to a certain technique (in HTML e.g. `<title>`), otherwise it is not a title but e.g. only the main heading (`<h1>`). Therefore I would plead for defining the term title, so that it cannot be confused with the main heading. If the intention of SC 2.4.2 is that a main heading is also sufficient, then this should of course be explicitly formulated in the Understandig.

**Comment by mbgower** [comment]
Yes, that's a good point in HTML -- and maybe in any software there is an equivalent title that appears in the window Chrome.
The SC does address that. I think it could be clearer, but I'm closing this, as it's not that significant in the scheme of things.
