### ISSUE TITLE
Technique F24 promotes non-existing "color" attribute of body in example #2

### ISSUE THREAD

**Issue by webcc** [w3c/wcag#16]
In the file:

https://github.com/w3c/wcag/blob/master/wcag20/sources/failure-tech-src.xml

i.e., see:

http://www.w3.org/TR/WCAG-TECHS/F24.html

Example #2 is using a "color" attribute on "body" element, which does not exist in the specification. Please, modify it.

**Comment by awkawk** [comment]
Fixed in http://www.w3.org/TR/WCAG-TECHS/F24.html
