### ISSUE TITLE
Applicability Technique G174 - Question

### ISSUE THREAD

**Issue by KerstinProbiesch** [w3c/wcag#1602]
In the [quickref](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=1411#non-text-contrast) Technique G174 ist listed in the sufficient techniques for SC 1.4.11. On the [technique-page](https://www.w3.org/WAI/WCAG21/Techniques/general/G174.html) is written this technique relates to SC 1.4.3 and 1.4.6. It's just an editorial issue that SC 1.4.11 is not mentioned, or?

Cheers

Kerstin

**Comment by mbgower** [comment]
[G174 ](https://www.w3.org/WAI/WCAG22/Techniques/general/G174.html) is now listed as sufficient to meet 1.4.11, so I am closing this issue.
If you feel that I have misunderstood the issue, please feel free to reopen and comment.
