### ISSUE TITLE
1.4.11 and video scrubbing controls

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#1655]
I'm trying to decide if the entirety of a video player's timeline "scrubber" falls under non-text contrast. Here's an example:

![Screen shot of part of a video timeline control. The control's background is dark grey, the thumb is white, and the track has two colors: played content on the left of the slider is dark blue and unplayed content on the right of the slider is light blue.](https://user-images.githubusercontent.com/20049493/109195449-607f2880-774f-11eb-9ba7-b44aa9c49bbd.png)

I know that the thumb definitely needs conforming contrast, but because a user can interact with the horizontal timeline bar to jump around the content, I assume that also means that the track, in this example both the darker "played" color to the left of the thumb and the lighter "unplayed" color to the right of the thumb, also have to have conforming contrast against the thumb and the exterior adjacent color. The toggle button example in the [Active User Interface Examples](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#active-user-interface-component-examples) suggests the track needs to conform.

**Comment by JAWS-test** [comment]
The element can be recognized correctly only if not only the circle but also the line is perceptible. This refers to the operation (slider) as well as to the information (time already played, time still to be played).

**Comment by fstrr** [comment]
That works. Thanks.
