### ISSUE TITLE
Alter note for Redundant Entry

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#1660]
The current wording of the note for Redundant Entry  is:
> Security verification, such as repeating a password, is considered essential.

I believe that this wording could be misinterpreted (as talking about authentication method), and is overly general. No one has mentioned another 'security verification' where this note fits, except re-entering a new password to reduce user error (from mistyping their new password when setting it). Therefore, I recommend altering this to make the exception more clear:
> Requiring re-entry of a new password is considered essential.

This change is contained in https://github.com/w3c/wcag/pull/1659

**Comment by mraccess77** [comment]
There could be other things other than passwords such as social security numbers or bank account numbers that you may not want displayed but you want verified - so I'd rather have this more open than closed to just passwords.  Just my two cents.

**Comment by mbgower** [comment]
> so I'd rather have this more open than closed to just passwords

The text change for the note does not restrict essential to passwords. It serves as an example. There _may_ be scenarios where it is demonstrably essential to re-enter a piece of information -- but I think coming up with any such situation to the point where it is understood as essential will of necessity need to be detailed. If such a thing were listed without context as an example of essential in this note, it could be cited to require information re-entry which would be counter to the intent of this SC.

**Comment by alastc** [comment]
Given the changes merged in with #1751 I think we can close this one. Three of us (@gundulaniemann, @mbgower and me) are still down for reviewing the understanding document content though.
