### ISSUE TITLE
Pointer targets and continuous areas

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#1661]
Adding this for tracking the discussion from [today's meeting](https://www.w3.org/2021/03/02-ag-minutes.html#t05).

Several people are working in a [google doc](https://docs.google.com/document/d/1jrJDDSR4_HIsUBpL9yAEo-KdWzHhrFeKO7wXrJXY2G8/edit#heading=h.bp16dxzwyxf) (and [David's](https://docs.google.com/document/d/1yCFT34uP7hGpUpAS5SRoEjT0TPuMfqssdir0M3sg2zA/edit)), and we should convert that to a PR to put forward.

**Comment by detlevhfischer** [comment]
Going through the Google doc on pointer target spacing amendments and thinking about the proposed additions of the exceptions 'target in multipoint region' and 'equivalent function' made me wonder if these might be unnecessary if we try to further clarify '[conforming alternate version](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#conforming-alternate-versiondef)' and '[supplemental content](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#suppcontentdef)'. As far as I am aware, the WG opinion is that a conforming alternate version can live on the same page as the content to which it is an alternative. The definition however does not spell this out. And the definition of supplemental content does not clarify if that content has to meet all WCAG rwequirements or whether the content it supplements would count as conforming alternative version. Is it just me seeing some vagueness in play here?

**Comment by alastc** [comment]
Hi Detlev,

I think the alternative-target one is a separate possible addition, so I'll do a separate PR for that.

**Comment by alastc** [comment]
Closing, the group did not agree to add this exception.
