### ISSUE TITLE
Simplify, clarify, or merge G10 & G135

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#169]
From @karlgroves and @thebillygregory presentation at CSUN:

> [G10](https://www.w3.org/TR/WCAG20-TECHS/G10.html): Creating components using a technology that supports the accessibility API features of the platforms on which the user agents will be run to expose the names and roles, allow user-settable properties to be directly set, and provide notification of changes

vs.

> [G135](https://www.w3.org/TR/WCAG20-TECHS/G135.html): Using the accessibility API features of a technology to expose names and roles, to allow user-settable properties to be directly set, and to provide notification of changes

Both sound very similar and there are even sentences repeated in both, see [HTMLdiff](http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2FWCAG20-TECHS%2FG10.html&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2FWCAG20-TECHS%2FG135.html).

**Comment by awkawk** [comment]
I looked back and both have been techniques since WCAG 2.0 was published.  I think that we should merge them and remove G135.

**Comment by Ryladog** [comment]
+1

Katie Haritos-Shea
703-371-5545

**Comment by yatil** [comment]
:+1:

**Comment by DavidMacDonald** [comment]
+1

**Comment by MakotoUeki** [comment]
+1

2016年4月12日火曜日、David MacDonald<notifications@github.com>さんは書きました:

> +1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/wcag/issues/169#issuecomment-208533308>
>


-- 
-- 
<以下、署名>

株式会社インフォアクシア
植木 真
<ueki@infoaxia.co.jp>

104-0054 東京都中央区勝どき1丁目13-6 プラザタワー勝どき 3011
TEL：03-5547-5777 FAX：03-5547-5778
http://www.infoaxia.co.jp/
https://www.facebook.com/weba11y.jp

**Comment by MikeElledge** [comment]
+1

**Comment by joshueoconnor** [comment]
Suggested response:

The working group feels there is value is having these two techniques and we are looking for volunteers to suggest these changes and make this happen.

**Comment by fstrr** [comment]
Closing this as inactive. If it needs to be re-opened, please do so.
