### ISSUE TITLE
Editorial grammar/logical error in exception for Redundant entry

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#1690]
Current wording for the exception

>Exception: When re-entering the information is essential, or when previously entered information is no longer valid.

The text says "Exception" in the singular, then presents two exceptions in the same sentence
https://w3c.github.io/wcag/guidelines/22/#redundant-entry

### SOLUTION 1
Use the plural and one sentence

**Exceptions:** When re-entering the information is essential, or when previously entered information is no longer valid.

### SOLUTION 2
Provide the two exception separately

**Exceptions:** 
- re-entering the information is essential
- previously entered information is no longer valid

**Comment by alastc** [comment]
I'm happy to add an "s" as an editorial update...

**Comment by alastc** [comment]
Done: #1346 1691
