### ISSUE TITLE
Technique F17: improve formulation in the expected result

### ISSUE THREAD

**Issue by webcc** [w3c/wcag#17]
http://www.w3.org/TR/WCAG-TECHS/F17.html and https://github.com/w3c/wcag/blob/master/wcag20/sources/failure-tech-src.xml

The expected result is formulated wrongly: 

"If step #1, step #3 or step #4 is true or step #2 is false, then this failure condition applies and the content fails the success criterion."

# Proposal: 

"If step #1 is true or step #2 is false or step #3 is false or step #4 is false, then this failure condition applies and the content fails the success criterion."

**Comment by joshueoconnor** [comment]
//James Nurthen made this suggestion on 22/7/2014

Following the call I researched a little more. I think we should use the
text in the HTML5 spec to give a proposed change to bullet 4 of

"For client-side image maps, check that the value of the usemap attribute is
a valid hash-name reference to a map element."

Hash-name reference in html5 is defined at
http://www.w3.org/TR/html5/infrastructure.html#syntax-references. Perhaps
this should be added in the resources section.

On further thoughts perhaps we should genericise this even more to cover
other cases which use hash-name references.
Proposed steps in a more generic test procedure are:

1) Check that attribute values that have an idref value have a corresponding
id value.
2) Check that attribute values that have a hash-name reference refer to a
valid name or id.

If step #1 or step #2 is false, then this failure condition applies and the
content fails the success criterion.

**Comment by awkawk** [comment]
F17 was removed as a result of a separate comment: https://www.w3.org/2006/02/lc-comments-tracker/35422/NOTE-WCAG20-TECHS-20140306/2950
