### ISSUE TITLE
Resource link 404s on WCAG 2.1 target-size Understanding document 

### ISSUE THREAD

**Issue by dotjay** [w3c/wcag#1704]
One of the ['target-size' resources](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html#resources), 'Microsoft Guidelines for Building Touch Friendly Sites', no longer exists.

The [URL for the resource results]( https://docs.microsoft.com/en-us/archive/blogs/ie/guidelines-for-building-touch-friendly-sites) in a 404 / [Microsoft's "content removed" page](https://docs.microsoft.com/en-us/archive/blogs/content-removed).

**Comment by alastc** [comment]
Updated in the main and 2.1 branches, thanks.
