### ISSUE TITLE
Question 1.4.1 Use of Color - Radio button colour with label on focus

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#1730]
I was looking at a page and noticed that the radio buttons (custom design) only showed one label at a time. The user must navigate to the radio buttons in the group and the label is displayed when focused.

Is this a fail for color only because the radio button show color to indicate the phone color choice?

https://www.telstra.com.au/mobile-phones/mobiles-on-a-plan/iphone/iphone-12-pro-max

Thanks

**Comment by JAWS-test** [comment]
I would say: yes, it fails 1.4.1

**Comment by LaurenceRLewis** [comment]
I agree, However my colleague disagrees, so would like to get the opinion of a few more 😀

**Comment by mraccess77** [comment]
The most likely place for a fail would be under use of color SC 1.4.1 - but just like a color picker - once you pick the color you do get a text label - so I'd probably think while this might be poor design it would pass WCAG.

**Comment by awkawk** [comment]
That's a good point @mraccess77 - the SC indicates that it is required that color is not the only way to convey information, but it doesn't say that the information needs to be persistently visible. For a color picker, the information is the choice of color and it is conveyed in text, and the colors on the phone ordering app behave similarly. It would be better if the text was shown on hover in addition to when the radio is selected and keyboard focused, but as is I don't think that this fails the color alone SC or the labels or instructions SC.

**Comment by jake-abma** [comment]
agreed, in this case color is not the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.

So it's not only about the label appearing, but also the choices itself in combination with the label for the radio group

**Comment by jake-abma** [comment]
agreed, in this case color is not the only visual means of:

- conveying information, as the 'legend' conveys information for the choice to make
- indicating an action, as the 'legend' in combination with the 'radio buttons' focus / selected in indicative
- prompting a response, as the 'legend' asks / suggests to make a choice
- or distinguishing a visual element, as the focus / selected 'border' distinguishes that one, and the others are 'alike and round on the same line'

So it's not only about the label appearing, but also the choices itself in combination with the label for the radio group.

That the color text appears is a great thing and would be better if it was persistent, but enough for communicating that that is the color chosen.

Also the last benefit is: "Users who have problems distinguishing between colors can look or listen for text cues." as is the case in this case.

**Comment by LaurenceRLewis** [comment]
The arguments have convinced me this is not a fail.

**Comment by JAWS-test** [comment]
@bruce-usab 

>  @JAWS-test what is argument for a fail against 1.4.1?

I can't see the colors right away. I have to interact with the page to see the colors. I thus have an extra effort of operation. Similar example: I have a table where the order status of products is only transmitted color coded. In a linked detail view, the order status is also in text form. I have to open the detail view for 100 products to see the order status for each product. I would also consider this to be a violation of 1.4.1, as I have a significant additional effort.

Of course, it makes a difference whether I cannot perceive a color-coded information at all or with additional effort. The former would be a serious violation of 1.4.1 for me, the latter only a slight one. Unfortunately, there is no way to weight issues in the current WCAG, but with WCAG 3.0 I would want to make exactly this distinction.
