### ISSUE TITLE
NON default focusable elements always PASS 3.2.1 On Focus?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1736]
3.2.1 specifically talks about "user interface component" not 'component' or 'element'

Definition

> user interface component
> a part of the content that is perceived by users as a single control for a distinct function

So what about elements with a tabindex attribute which may initiate a change of context? (user need would apply here too?!)

The second sentence in the Understanding also says it:

> Any component that is able to trigger an event when it receives focus must not change the context.

so is this sanity check correct? and do we have a gap for "NON default focusable elements"

**Comment by patrickhlauke** [comment]
and i though *I* was somebody who splits hairs too much...

if the thing receives focus, and something gets triggered/the user can operate it, then it is de-facto a user interface component, so then 3.2.1 applies, I'd say.

**Comment by patrickhlauke** [comment]
...unless we want to argue the finer point of "surprising" things that receive focus that the user may not have "perceived as a control for a function". but then we're into subjectively analysing "would a user perceive this as such or not"

**Comment by patrickhlauke** [comment]
but admittedly I can see the questioning of "why did AGWG specifically talk about user interface components in the normative text ... why not just write 'if anything receives focus'"

**Comment by jake-abma** [comment]
That last one nailed it, there probably was a reason, just not sure why...

**Comment by patrickhlauke** [comment]
or it started off as something specific, was then wordsmithed back and forth, and somehow was left with an odd sounding wording that was good enough that people could "live with it"

**Comment by jake-abma** [comment]
Same is true for 2.4.11 Focus Appearance (Minimum)

It talks about

> For the keyboard focus indicator of each **User Interface Component**, all of the following are true:

**Comment by patrickhlauke** [comment]
I'd still answer this with

**Comment by alastc** [comment]
> or it started off as something specific, was then ...

I think it's more likely that as things condensed down prior to 2.0 that standard definitions were used where possible. "User interface component" is that sort of defintion, and I agree with the logic that if you can focus (or click/tap) on something, and it does something, that is defacto a UIC. The fact the definition works is a good thing about the (attempted) tech-agnostic aim originally.

@jake-abma are you happy with the answers above, or is there something you think should change in the docs?
