### ISSUE TITLE
Understanding SC WCAG 2.5.8 figures 1, 2, 3 don't match captions

### ISSUE THREAD

**Issue by MarcSolo** [w3c/wcag#1738]
The dimensions listed in the captions don't seem to match what is illustrated in figures 1, 2, or 3: https://www.w3.org/WAI/WCAG22/Understanding/pointer-target-spacing.html.

**Comment by patrickhlauke** [comment]
that version of the understanding doc is outdated - the corrected/up-to-date one is here https://w3c.github.io/wcag/understanding/target-size-minimum.html

**Comment by MarcSolo** [comment]
Thanks @patrickhlauke, the updated version looks great!
