### ISSUE TITLE
Link to existing technique instead of designating a “future link”

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#176]
In 1.4.8, there is an entry for a future technique called “Not interfering with the user agent's reflow of text as the viewing window is narrowed” in the 5th requirement although there is [technique G204](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/G204) which seems to be made to replace that “future link”.

This is the case in the [old quickref](https://www.w3.org/WAI/WCAG20/quickref/20160317/#visual-audio-contrast-visual-presentation) and in the [new one](https://w3c.github.io/wai-wcag-quickref/?showtechniques=148#visual-audio-contrast-visual-presentation) as well as in the [understanding document](http://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20160317/visual-audio-contrast-visual-presentation.html).

via w3c/wai-wcag-quickref#126

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag/commit/7924a104ae94eca2b6bbfc52a2ea4387214741ce
