### ISSUE TITLE
3.2.7 Visible Controls - The first exception is difficult to understand

### ISSUE THREAD

**Issue by LiLoDavis** [w3c/wcag#1760]
I'm struggling to understand how "the information needed to identify" one UI component could be available through a different component on another step in a multi-step process. 

Does this rewrite convey the intended meaning?
- The functionality of the interface components is available through an equivalent component that is available...

**Comment by alastc** [comment]
The reason it start off with "The information needed to identify the user interface components" is so that it matches the initial text. Otherwise you could have two hidden controls that would always pass because the other exists.

**Comment by alastc** [comment]
The response above was agreed.
