### ISSUE TITLE
2.4.2: Page Titled makes 2.4.8: Location redundant

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1763]
2.4.2: Page Titled states in the Understanding:

> Titles identify the current location without requiring users to read or interpret page content. 

So if the location is known at a AA SC, why try to fix that problem in 2.4.8 at AAA, basically making 2.4.8: Location redundant.

**Comment by jake-abma** [comment]
=REF= https://github.com/w3c/wcag/issues/1750

**Comment by yatil** [comment]
If I understand correctly — and who knows if I do at this point in time — the difference is:

* 2.4.2 Identifies the location on its own (Your location is “123-Great-Product”)
* 2.4.8 Identifies the location in a set of web pages, so how it relates to other pages of the same website (Your location is 123–Enterprises -> Products -> 123-Great-Product)

**Comment by patrickhlauke** [comment]
Related, also on the topic of 2.4.8, the normative text only talks about *information* about the user's location, while the understanding goes on to talk about "and find related information" and examples mention *links* to these other pages in the set of webpages/hierarchy.

**Comment by alastc** [comment]
Where it says " Titles identify the current location without requiring users to read or interpret page content.", that is in the context of the first paragraph of the understanding.

As @yatil said, it doesn't identify the relative location in a set, it is an identifier relative to all web pages. 

It seems to be an over-interpretation...

**Comment by jake-abma** [comment]
noted! thx
