### ISSUE TITLE
Typo in 1.4.11 Understanding doc

### ISSUE THREAD

**Issue by susanatx** [w3c/wcag#1766]
In [Understanding Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#techniques) under "Active User Interface Component Examples" there is an invalid hex code:

"**Text input** Where a text-input has an indicator such as a complete border (#76766), that indicator must meet 3:1 contrast _ratio."_

**Comment by patrickhlauke** [comment]
well spotted
