### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by kristian240** [w3c/wcag#1787]
On page https://www.w3.org/TR/WCAG21/ in section _Status of This Document_ 3rd paragraph has the same content as the 8th paragraph. 

> This document has been reviewed by W3C Members, by software developers, and by other W3C groups and interested parties, and is endorsed by the Director as a W3C Recommendation. It is a stable document and may be used as reference material or cited from another document. W3C's role in making the Recommendation is to draw attention to the specification and to promote its widespread deployment. This enhances the functionality and interoperability of the Web.

**Comment by fstrr** [comment]
This has been fixed and noted in [the changelog](https://www.w3.org/TR/WCAG21/#changelog).
