### ISSUE TITLE
Requirement and Benefits contradict at 3.3.2: Labels or Instructions

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1791]
https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html

Last sentence of Intent states:

> While this Success Criterion requires that controls and inputs have labels, whether or not these labels are sufficiently clear or descriptive is covered separately by 2.4.6: Headings and Labels.

so the exact text says: **"whether or not these labels are sufficiently clear or descriptive is covered separately by 2.4.6: Headings and Labels"**

The Benefits following this sentence says:

> **Benefits**
> - Providing clear and unambiguous labels and instructions (including examples of expected data formats) helps all users - but particularly those with cognitive, language, and learning disabilities - to enter information correctly.
> - Providing clear and unambiguous labels and instructions (including clear identification of required fields) can prevent users from making incomplete or incorrect form submissions, which prevents users from having to navigate once more through a page/form in order to fix submission errors.

Both starting with: **"Providing clear and unambiguous labels"** while this is 2.4.6 NOT 3.3.2

**Comment by patrickhlauke** [comment]
good spot, that slipped through after adding that extra "it's 2.4.6 NOT 3.3.2" addition at the time. Think this should fix it https://github.com/w3c/wcag/pull/1792

**Comment by patrickhlauke** [comment]
@jake-abma I think you had added more comments here, but then deleted them. just to say I agree that the line between 2.4.6 and 3.3.2 has been weirdly blurry from the very start - don't think there's much more panel-beating that can be done to completely extricate the two...can't fix fundamental overlap here, it's too late. best we can hope for is to at least mitigate some of the more blatantly confusing statements, sadly :(
