### ISSUE TITLE
Change 2.0 to 2.2 Intent 3.3.3: Error Suggestion

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1796]
https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion 

It's not a big thing but to be consistent and clear we should change 2.0 to 2.2, second sentence of Intent:

Change:

> The WCAG 2.0 definition of "input error" says that it is "information provided by the user that is not accepted" by the system.

To:

> The WCAG 2.2 definition of "input error" says that it is "information provided by the user that is not accepted" by the system.

**Comment by patrickhlauke** [comment]
or make it evergreen ... "The WCAG definition of ...", "Per the definiton in WCAG, an ..."

**Comment by patrickhlauke** [comment]
arguably, if you're reading a document in the 2.x series, it's implict that WCAG 2.x is meant when saying "WCAG", i'd say...heck, could even just say "The definition of...", "Per the definition, an ..."

**Comment by patrickhlauke** [comment]
https://github.com/w3c/wcag/pull/1804
