### ISSUE TITLE
WCAG 2.2 Understanding Documents AGAIN at the WCAG 2.1 URL

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#1820]
Considering I sound like a broken record, here’s the deal: https://www.w3.org/WAI/WCAG21/Understanding/ (note WCAG21 in the URL) refers to WCAG 2.2 which – to my knowledge – has not been published yet.

Yada, yada, confusion.

![Screenshot highlighting URL and several places where WCAG 2.2 is referred to.](https://user-images.githubusercontent.com/58862/118802882-f932c980-b8a2-11eb-97b8-7a1187fe9499.png)

**Comment by sophieschoice** [comment]
There are also succescriteria present in the sidebar that aren't in 2.1 , at least the following:

2.4.11 Focus Appearance (Minimum)
2.4.12 Focus Appearance (Enhanced)
2.4.13 Fixed Reference Points

Very confusing indeed.

**Comment by sophieschoice** [comment]
Asoide from the three above, the following Success Criteria are present, while they are not part of WCAG 2.1.

2.5.7 Dragging Movements
2.5.8 Pointer Target Spacing
3.2.6 Findable Help
3.2.7 Visible Controls
3.3.7 Accessible Authentication
3.3.8 Redundant entry

Some of these page lead to a 404, some do exist. Quite dangerous and confusing for people studying WCAG or referencing it while auditing.

**Comment by shawna-slh** [comment]
Hi all. Sorry about that. The person to fix it is on vacation.

**Comment by alastc** [comment]
References removed.
