### ISSUE TITLE
Is "preceding heading element" or a region landmark a programmatically determined link context?

### ISSUE THREAD

**Issue by ajanec01** [w3c/wcag#1821]
Referencing [Link in context editorial suggestions 5effbb](https://github.com/act-rules/act-rules.github.io/issues/1605) to keep track of things.

From reading [Technique 80 -Identifying the purpose of a link using link text combined with the preceding heading element](https://www.w3.org/WAI/WCAG21/Techniques/html/H80) one can assume that in HTML a proceeding descriptive heading is enough to satisfy [sc 2.4.4](https://www.w3.org/TR/WCAG21/#link-purpose-in-context). There are some good arguments for it, such as:

- It's possible to check the heading text using keyboard shortcuts after a link/ test target receives keyboard focus (thinking here about screen reader shortcuts). In hindsight, although probably a less intuitive technique, it works similarly to checking the contents of a list item with a link (there's also a need to use software specific keyboard key combinations to check the context),
- It is an advisory technique, which indicates that the authors are advised to do so. This is more complicated given the [definition of Advisory Techniques](https://www.w3.org/WAI/WCAG21/Understanding/understanding-techniques.html#advisory-techniques) but I don't think that any of the concerns inside the list are applicable to HTML or ARIA headings.
- For some people, **I think**, it might be easier to read a heading and then the actual purpose of the link, e.g. "Map" instead of repeating the same phrase for each link, e.g. `<a href="royal_palm_hotel_map.html">Royal Palm Hotel Map</a>`. 
- The description of the example (block quote below)  reads very much as if it was a pass of success criterion 2.4.4

The difficulty is with the example inside of the [definition of programmatically determined link context](https://www.w3.org/TR/WCAG21/#dfn-programmatically-determined-link-context). The example below the definition does not refer to headings. It also does not refer to landmarks, which I'm lead to believe could be a programmatically determined link context, for example:
```
<section aria-label="Royal Palm Hotel">
  <ul class="horizontal">
    <li><a href="royal_palm_hotel_map.html">Map</a></li>
    <li><a href="royal_palm_hotel_photos.html">Photos</a></li>
    <li><a href="hroyal_palm_hotel_directions.html">Directions</a></li>
    <li><a href="royal_palm_hotel_reviews.html">Guest reviews</a></li>
    <li><a href="royal_palm_hotel_book.html">Book now</a></li>
  </ul>
</section>
```
In the case of landmarks, I would argue that most, `region` landmarks with an accessible name would meet the definition. 

So, the question is, are preceding headings or `region` landmarks with accessible name considered to be a programmatically determined link context?

**Comment by patrickhlauke** [comment]
Personally, I'd say yes that code would look ok to me. But it hinges on the handwaved definition of "[programmatically determined](https://www.w3.org/TR/WCAG/#dfn-programmatically-determinable)". There's a lot of things that can technically be programmatically determined, but that AT don't currently expose (easily). But from a structural point of view, they really could, they just choose not to.

**Comment by ajanec01** [comment]
Thanks @patrickhlauke! Yep, although not sure if it can be any better given that it also needs to be technology agnostic and quite possibly future proof. Genuinely curious about the other things that could be exposed in your opinion.

Another scenario where I though this is sufficient could be iOS. Headings provide context there mainly for buttons. In some cases semantic views could be used but this feels more of a way around things that in the end results in better experience  and not the base line requirement that is to be "programmatically determined".

**Comment by ajanec01** [comment]
Ahh, sorry, just realized that the iOS example is inapplicable, since they're buttons. There is a link trait in iOS anyway and I think that a similar approach could be applied since there aren't as many things as in HTML that would fit the definition.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
