### ISSUE TITLE
WCAG 2.2 2.5.8: add the (possibly redundant) mention of "pointer inputs" to match 2.5.5

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1832]
2.5.5 uses "The size of the [target](https://www.w3.org/TR/WCAG22/#dfn-target) for [pointer inputs](https://www.w3.org/TR/WCAG22/#dfn-pointer-inputs) ...", where the "pointer inputs" may arguably be redundant since the definition of target already talks of pointers...but it helps clarify things.

2.5.8 only uses "[Targets](https://www.w3.org/TR/WCAG22/#dfn-target) have an area ..."

For consistency, it may be worth rewording the start there to also include the words and link to the pointer inputs definition, e.g. "[Targets](https://www.w3.org/TR/WCAG22/#dfn-target) for [pointer inputs](https://www.w3.org/TR/WCAG22/#dfn-pointer-inputs) have an area ..."

x-ref https://github.com/w3c/wcag/issues/1831

**Comment by jenstrickland** [comment]
Draft proposed response:
<hr>

SC 2.5.8 Target Size (Minimum) (Level AA) is a partner to SC 2.5.5 Target Size (Level AAA).

Regarding the size of 44 x 44: 

- The minimum target size to meet Level AA is 24x24 pixels and includes a target offset of at least 24 pixels, with noted exceptions. There are some interfaces where smaller sizes are appropriate and necessary, for example the toolbars at the top of certain editing interfaces. However, this SC should encourage the move towards larger target sizes and offset spacing in redesign efforts, as appropriate. 

- This SC 2.5.8 includes the range of pointer possibilities, from mouse to touch, with the mobility needs as a consideration. 

- The SC 2.5.5 Target Size (Level AAA) may be perceived as an enhancement increasing target size to 44x44 pixels where that is appropriate to the interface.

**Comment by patrickhlauke** [comment]
@jenstrickland my issue had nothing to do with the "44x44" measure or anything.

My issue is: for consistency, can the normative wording of the new AA SC be more in line with the 2.1 AAA SC?

i.e. since the 2.1 AAA SC starts with

>2.5.5 Target Size (Enhanced) (AAA)
>The size of the target for pointer inputs is at least 44 by 44 CSS pixels...

it would make sense to use the same/similar wording for the new 2.5.8 AA SC and change

> 2.5.8 Target Size (Minimum) (AA)
> Targets have an area of at least 24 by 24 CSS pixels...

to

> 2.5.8 Target Size (Minimum) (AA)
> The size of the target for pointer inputs is at least 24 by 24 CSS pixels...

**Comment by jenstrickland** [comment]
@patrickhlauke Sure, I'll take another look with this in mind. Thank you!
