### ISSUE TITLE
WCAG 2.2: 2.5.8 understanding - "magnifying glass" vs "loupe"

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1846]
In the caption for Figure 5 in https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html we start off saying "magnifying glass", but then revert to calling it a "loupe" 3 times. for consistency, pick just one - and I'd say "magnifying glass" is more familiar / general usage than "loupe"

**Comment by scottaohara** [comment]
Agree. Do not use loupe

**Comment by alastc** [comment]
Merging with main soon via another root.
