### ISSUE TITLE
WCAG 2.2 3.3.7: Accessible Authentication - confusion about "paste"

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#1855]
https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication.html gives the impression that password managers/browsers rely on pasting (actual CTRL+V) passwords into fields. 

```
does not block copy-paste then browser features or password managers can
save the user’s information and refill the login.
```

```
Copy and paste can be relied on to avoid transcription. Examples of this are password
managers automatically filling in username and passwords,
```

```
A web site uses a properly marked up username (or email) and password fields as the login
authentication (...). Copy & paste is not blocked on the inputs, so the user's browser or extension
can identify the purpose of the inputs and automatically fill in the username and password.
```

this is not the case - they generally inject the `value` straight into the DOM. this can be observed if you do something like `addEventListener('paste', function() { console.log('paste triggered'); })` on a login form field.

The "can the user paste something they copied from an email or manually from a 3rd party, non-integrated password manager on their local system" aspect, and the "it works with password managers" aspect, are two separate things and should not be conflated/mushed together like this.

**Comment by alastc** [comment]
That's probably be from me, I've seen a couple of password entries which prevented both pasting and password managers. Correlation not causation!

PR needed.

**Comment by patrickhlauke** [comment]
Parking this here for now - quick and dirty test page https://codepen.io/patrickhlauke/full/jOBepRE

**Comment by patrickhlauke** [comment]
If anybody uses some other password manager, like LastPass, it'd be interesting to see if they get different results on the above test page.

**Comment by patrickhlauke** [comment]
PR submitted https://github.com/w3c/wcag/pull/1898
