### ISSUE TITLE
F38 and 4.1.1 conflict ?

### ISSUE THREAD

**Issue by goetsu** [w3c/wcag#186]
As https://www.w3.org/TR/WCAG20-TECHS/F38.html allow to have decorative img without alt attribut if a role="presentation" is used.
I think there is a need for a note in this failure to indicate that it's not a 4.1.1 failure otherwise I don't see how this can be used.

**Comment by DavidMacDonald** [comment]
Proposed Response:

The failure does not say that it is a failure of WCAG 4.1.1, and there is not requirement to indicate every Success Criteria that does **_not_** apply to a failure. We feel this would be confusing to end users. WCAG 4.1.1 does not require alt text on images, only that if an attribute is used, that it be well formed (matching quotes, space before and after etc...). Therefore, no change will be made.

**Comment by joshueoconnor** [comment]
http://www.w3.org/2016/05/17-wai-wcag-minutes.html

**Comment by awkawk** [comment]
Approved response:
The failure does not say that it is a failure of WCAG 4.1.1, and there is not requirement to indicate every Success Criteria that is not related to a failure. We feel this would be confusing to end users, and time consuming for the group.

Also, WCAG SC 4.1.1 does not require alt text on images, only that if an attribute such as alt is used, that it be well formed (matching quotes, space before and after, etc...).

Therefore, no change will be made.

https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/0670.html
