### ISSUE TITLE
2.4.11: Typos in the text below Figure 18

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1860]
Two of the bullet points below Figure 18 in the ["Relationship to Non-text Contrast" section](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum#relation-non-text-color-contrast) of the Understanding doc begin "Ihe" instead of "The".

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
This is updated in the editorial branch, and will be merged with main soon.
