### ISSUE TITLE
2.4.11: Text below figure 2

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1863]
To aid with comprehension, we suggest that a calculation is shown to demonstrate that the inner outline is well over the minimum requirement.

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
This is updated in an editorial branch, which will be merged soon.
