### ISSUE TITLE
2.4.11: Text below figure 3

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1864]
For consistency, the following text should be edited to include the correct units of "px" and "px squared".

>Figure 3 The thick (3px) yellow underline is almost as long as the longest edge, 80px ~~x~~**is multiplied by** 3**px** exceeds the requirement of 236px **squared**.

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
This is updated in an editorial branch, which will be merged soon.
