### ISSUE TITLE
2.4.12: Adjacent Links

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1866]
Within the "minimum area" bullet two hyperlinks ("CSS pixel" and "perimeter") are adjacent to each other.  Some users may have difficulty in perceiving that they are separate links until they are focused on or activated.  This issue can be overcome by adding a word between the hyperlinks, such as "wide", so that the sentence reads "...the area of a 1 CSS pixel *wide* perimeter..."

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
We've used 'thick' in the AA version, that seems like an easy update.

**Comment by alastc** [comment]
This is updated in an editorial branch, which will be merged soon.
