### ISSUE TITLE
2.4.13: Query: are slides included?

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1867]
Would a web-based slide show be covered by this SC and thus require some form of break indication?

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
Only if it included [page break locators](https://w3c.github.io/wcag/guidelines/22/#dfn-pagebreak-locators), and then it would require a navigation mechanism rather than visual markers. 

Generally those programmatic markers are quite specific, e.g. `role="doc-pagebreak"`, so I think it's unlikely.

**Comment by DavidMacDonald** [comment]
Its a good question. This was intended for epub documents online not for slide shows, but if there are "programmatic markers that are arranged in a meaningful sequence to determine the location of a page in relation to others in the set" then the would be in scope. That's not likely and even if so slide shows have a visible and programmatic break between pages. There is usually a way to navigate to each slide so it would probably pass by default.
