### ISSUE TITLE
2.4.13: Query: are pages with print CSS that includes page breaks excepted?

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1868]
We assume so, as the author can't know exactly where they will occur.

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
A CSS page break isn't denoting a sequence (and isn't in the HTML), so I don't think it's in scope.

**Comment by DavidMacDonald** [comment]
Agree with this response by @alastc 

https://w3c.github.io/wcag/guidelines/22/#dfn-pagebreak-locators

CSS page breaks are not in a "meaningful sequence" and therefore out of scope. The SC really is to help users get to say page 53 if they are zoomed into twice the size of others in the class.
