### ISSUE TITLE
Example#2 of Understanding  SC 3.2.2 needs  modification

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag#187]
A small correction is needed to the example#2 for SC 3.2.2 which now reads:
"A form contains fields representing US phone numbers. All of the numbers have a three digit area code followed by a three digit prefix and finally a four digit number, and each part of the phone number is entered into a separate field. When the user completes the entry of one field and enter the first digit of the next field, the focus automatically moves to the next field of the phone number. This behavior of phone fields is described for the user at the beginning of the form".

The following words need to be deleted:
"and enter the first digit of the next field,", so the example reads: 

"A form contains fields representing US phone numbers. All of the numbers have a three digit area code followed by a three digit prefix and finally a four digit number, and each part of the phone number is entered into a separate field. When the user completes the entry of one field the focus automatically moves to the next field of the phone number. This behavior of phone fields is described for the user at the beginning of the form".

Explanation:
With the auto-tab feature, the focus moves to the next field automatically as soon as the last character is typed ... not when the first character for the next segment is typed. One who is informed of this behavior will indeed just type out the entire 10-digit phone# and expect all digits to be in the appropriate slots. Without this info, on completion of each segment, one will have used the tab key to advance to the next field and would not type the next character.

Thanks,
Sailesh

**Comment by alastc** [comment]
I agree, makes sense.

I created a pull request for that change: https://github.com/w3c/wcag/pull/195

**Comment by awkawk** [comment]
Editorial change in Pull 195 merged.
