### ISSUE TITLE
3.2.7: Controls that are always hidden for everyone

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1876]
We gather that fields that are always hidden from everyone—i.e. honeypot fields—would be out-of-scope. Is this correct?

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
Yes, if they are not made visible by hover or focus, they are not in scope.
