### ISSUE TITLE
Adobe Comment on 2.5.7 Dragging Movements

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#1886]
This SC is complicated to understand. The understanding document helps, but may require further work. Our core concern is that controls such as a slider (including a color slider) may need to offer a text input to support accessibility in some cases and we believe that the example of the radial control widget makes it clear that this “same page conforming alternate version” approach is sufficient. Please confirm that the Understanding document will continue to include such an example, and please consider adding this clarification to the intent section.

**Comment by alastc** [comment]
@detlevhfischer, would you like to tackle this one?

**Comment by detlevhfischer** [comment]
@awkawk Hi Andrew, you wrote
> Please confirm that the Understanding document will continue to include such an example

Can you point to a fitting example (of radial control widget)? Then I can try to work that in to the understandign doc.

**Comment by alastc** [comment]
Oh good, it wasn't just me that isn't sure what a "radial control" is then!

**Comment by patrickhlauke** [comment]
my understanding of "radial control" is something like this https://www.jqueryscript.net/demo/Circular-Slider-Plugin-With-jQuery-D3-js-Wheel/ - like a slider, just round (or at least in an arc)

for both radial, and even simple (straight) sliders, it would also be sufficient to allow users to click/tap on the track of the slider to set the value/knob directly there, no? not necessarily needing a separate text input.

**Comment by patrickhlauke** [comment]
this aspect could warrant a separate/new example, as currently the radial example there makes it sound like a slider MUST have a text field that allows numerical keyboard entry.

> A radial control widget where the value can be set by dragging includes a text field that presents the current value and offers the input of the desired value via a keyboard (including on-screen virtual keyboards).

the radial control here could also pass the SC if it just allowed the user to tap/click on the track. so would be good to provide an example along those lines as well, and for the above example clarify that that widget doesn't allow that, but has instead provided a text field (so you can either drag OR manually enter the value, but you CAN'T single-pointer tap/click on the track to set the value)

**Comment by detlevhfischer** [comment]
> not necessarily needing a separate text input.

That is also my understanding - will shortly try to add to usnderstanding text (still hope to get an image from @awkawk )

**Comment by patrickhlauke** [comment]
i might even suggest removing the "radial" aspect here. keep the two examples (slider that you drag, but you can also click/tap on the track; slider that you drag, but can also enter value in an adjacent text field) just about sliders, not radial sliders...

**Comment by detlevhfischer** [comment]
@awkawk I have added a radial control example to PR #1954  that may be further simplified to cover all slider-type things where the values could be set with a single tap. Does that address your concern? 
It could mention text input as another, possibly additional, alternative - certainly needed in cases where you need exact values as when setting color. Or this could be a further separate example.

**Comment by detlevhfischer** [comment]
In https://github.com/w3c/wcag/pull/1961 I have now also added a section on "Alternatives for dragging movements on the same page" covering the case of meeting the SC via an alternate conforming version on the same page.

**Comment by alastc** [comment]
The group agreed the response here: https://www.w3.org/2021/12/03-ag-minutes.html#t03
