### ISSUE TITLE
[WCAG 2.2 Draft Feedback] SC 2.5.7: Dragging Movements (AA)

### ISSUE THREAD

**Issue by dshoukry** [w3c/wcag#1891]
We found this version much more clear and really appreciate the new additions here. Thank you for all your efforts!

One of our UX writers found a few minor typos and ungrammatical text in the new text. Would it be helpful to send those over or is that not needed at this stage?

**Comment by alastc** [comment]
Yes, if you have a track-changes doc, that would help a lot, thank you.

**Comment by dshoukry** [comment]
Great! Please find our Tech Writer's feedback (anonymized though, so my name will appear) in our [v2 2.5.7 Dragging [external-OK] Google Doc](https://docs.google.com/document/d/1keynl0WhUXRhXC6xRKc7fA7Bh7-KlsYaI-jnNMm6A9A/edit#heading=h.bsrgwf7ggyvo)
