### ISSUE TITLE
[WCAG 2.2 Draft Feedback] Remaining Review Process/Path to Recommendation?

### ISSUE THREAD

**Issue by dshoukry** [w3c/wcag#1897]
Thank you for accepting so much feedback from us and others. We found that a nice chunk of the SC were improved for the better and greatly appreciate that. 

Would it be possible to explain more about what will happen with this round of feedback and about the expected "fall" timeline? Will there be a third call for public feedback, or will 2.2 move to Recommendation when all comments are answered/resolved?

Can you also please share more about what happens when accepting some members' or people's feedback directly conflicts with other submitted feedback? The reduction in the target spacing/size from 44 to 24 was probably the biggest unanticipated change, did that happen because the majority of comments you received expressed concern about that target size? Do you anticipate other similar changes like that to occur in this round?

Thanks again!

**Comment by alastc** [comment]
>  Will there be a third call for public feedback, or will 2.2 move to Recommendation when all comments are answered/resolved?

We are hoping to move through the [process](https://github.com/w3c/wg-effectiveness/blob/master/process.md#reviewing-documents-and-wide-review) without another wide review. We will tackle all the feedback, and if the SC don't change significantly (or are withdrawn), we can proceed to CR.

> Can you also please share more about what happens when accepting some members' or people's feedback directly conflicts with other submitted feedback? 

Each comment is dealt with in a way that the AG agrees to do. Overall, we try to aim high then overcome objections. If there is direct conflict, we try to find a 3rd way, or fall back to not including a particular criteria.

I've commented on target size in that issue, so you'll see that quite often it is practical /feasibility issues which have the biggest impact.

**Comment by alastc** [comment]
Closing this as it was a request for info on the process, not something we can address in the documentation. Feel free to email the chairs (any/all) for further info on the process.
