### ISSUE TITLE
User Agent Support Notes H44 is old and should be removed

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag#190]
Sufficient Technique [H44: Using label elements to associate text labels with form controls](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/H44) provides examples for using explicit labeling to provide a label for an element, e.g. ```<label for="firstname">First name:</label> 
<input type="text" name="firstname" id="firstname" />```. The technique refers to [UA Notes for H44](https://www.w3.org/WAI/WCAG20/Techniques/ua-notes/html#H44) which discourages the use of implicit labeling while it is not supported by JAWS 7 and Window Eyes 5.5. 
This note is old and should be removed. Implicit labeling is defined in [HTML4](https://www.w3.org/TR/html401/interact/forms.html#h-17.9.1) and [HTML5 specifications](https://www.w3.org/TR/html5/forms.html#the-label-element). Additionally the [WAI tutorials provides an example on implicit labeling.](https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly)

My team has tested implicit labeling with JAWS 17 on Firefox 45 and VoiceOver on iOS6 and have found that implicit labels are read just fine. We could test earlier versions of screen reader/browser combinations but I do not believe that should be required while implicit labeling is defined in the HTML spec. 

I recommend that we removed UA Note on implicit labeling under H44 and provide examples of implicit labeling to Sufficient Technique H44. For example, ```<label>
  First name:
  <input type="text" name="firstname">
</label>```

**Comment by alastc** [comment]
I agree, I've put in a pull request for review:
https://github.com/w3c/wcag/pull/196

NB: I also updated the description slightly, adding a paragraph about the implicit method.
