### ISSUE TITLE
3.3.7 - supporting copy-paste, example with memorable information, and specific characters

### ISSUE THREAD

**Issue by wardav** [w3c/wcag#1901]
Remembering your email, address, and name are not cognitive tests. This is suggested by ...

> The common identifiers name, e-mail, and phone number are not considered cognitive function tests as they are personal to the user and consistent across websites;

There would be a requirement from [1.3.5: Identify Input Purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html) to have `autocomplete`.

One **could** extend this to memorable answers. For example, where we you born? What is your date of birth? What was the make and model of your first car? What is the colour of your eyes? What is your mothers maiden name?

These properties about the user remain consistent across websites. However, these do not have relevant `autocomplete` values. So the requirement from 3.3.7 would be to allow users to copy and paste the information into the field. 

In this instance, the cognitive test is not **knowing** the information, the test is typing it in, spelling it correctly, and so on. The way to pass the success criterion is supporting copy-and paste. 

One assumes that this same thing would apply to memorable answers that are specfic to the website. For example "when did you open this account", "which branch (town name) did you open this account in?".

This is not consistent across websites. But users can store it in their password manager, copy it, and paste it into the field with no mess or fuss. But to take this even further, what about specific digits from a memorable answer? 

For example, "The first character of your email address", "the seventh character" ... 

Is this fine so long as you can go over ot the password manager, copy the x character and paste it in? Or is this now out of scope due to the test that requires counting the digits -- e.g. working out which is the sixth character. 

My **personal** view would be that the cognitive test int his case would be out of scope as arguably password managers should provide the functionality to easily get to x digit in a password. 

I'm not sure. I think that this could be made more clear. For example: 

>  For each step in an authentication process that relies on a cognitive function test, at least one other authentication method is available that does not rely on a cognitive function test, or a mechanism is available to assist the user in completing the cognitive function test. Except when 
> * The cognitive test can be passed by copying and pasting information from another source, such as memory information or passphrase from a password manager. 
> * The cognitive test is prompted by the operating system and is not modified by the author.

**Comment by alastc** [comment]
> users can store it in their password manager, copy it, and paste it into the field with no mess or fuss.

That's an assumption. The built-in browser password managers don't provide a mechanism for saving site-specific comments. For the password managers which do, you have to:
- Remember that you saved something for this site;
- Switch applications / tasks to go and find it;
- Remember which item you needed, and copy it;
- Switch back;
- Find the right input;
- Paste.

That's quite a few more steps than your typical password manager.

> arguably password managers should provide the functionality to easily get to x digit in a password.

But currently they do not, so I don't see a reason to update the understanding document about this.

**Comment by alastc** [comment]
Proposed response:

<hr>

> One could extend this to memorable answers

Although memorable answers are information from/of the user, memorable answers are not standardised or as consistent as name, email, and address. There is considerably more effort required by the user to complete those type of questions.

The same applies to "select X character from your password" features.

They would count as cog-fun-tests.

However, if user-agents did commonly provide functionality for filling those in automatically, it would be similar to passwords and "a mechanism is available to assist the user in completing the cognitive function test". I.e. it would not require effort from authors to pass.
