### ISSUE TITLE
3.3.7 Clarification on USB-based 2FA

### ISSUE THREAD

**Issue by JamesCatt** [w3c/wcag#1903]
> A web site that requires 2-factor authentication allows for multiple options for the 2nd factor, including a USB-based method where the user simply presses a button to enter a time-based token.

This sounds to me like it means that any website using 2FA *must* specifically support the described USB-based method. Is that the intent here? If not, then perhaps phrasing it as "_such as_ a USB-based method..." would be more appropriate?

If it _is_ the intent, then I would argue the SC should not mandate the use of a specific technology (i.e., USB), but rather a method that meets the requirement of not requiring transcription, etc.

**Comment by patrickhlauke** [comment]
examples are not exhaustive, so the intention here is to provide one (of many possible) concrete examples

**Comment by mraccess77** [comment]
I agree with @patrickhlauke the intention was to not mandate a specific 2nd method.  The including was meant to provide examples.

**Comment by alastc** [comment]
HI @JamesCatt, Patrick is correct, can we close this issue? Or is there something that you think needs to change in the document?

**Comment by JamesCatt** [comment]
@alastc so in that case my suggestion was to amend the wording slightly to something like "_such as_ a USB-based method". I'm just a sample size of one, but to me the current wording sounds like it's a requirement.

**Comment by alastc** [comment]
@JamesCatt The entire list is "such as", they are examples. It doesn't make sense to me to say "allows for multiple options, such as". That needs to be "including", because some methods won't meet the criteria, so we have to specify that one does.

**Comment by alastc** [comment]
Proposed response:

<hr>

> This sounds to me like it means that any website using 2FA must specifically support the described USB-based method.

This is one example, under a heading of "Examples". In that context it would not make sense to change the USB part of the example to "such as", because the whole item is supposed to be one concrete example.

**Comment by alastc** [comment]
The group approved the response above. Note that the examples are likely to be increased and updated based on other comments.
