### ISSUE TITLE
Broken link in Understanding 2.4.2 doc

### ISSUE THREAD

**Issue by susanatx** [w3c/wcag#1906]
The link to the test rule is broken.

Current link
https://www.w3.org/standards-guidelines/act/rules/html-page-non-empty-title-2779a5/

Correct link
https://www.w3.org/WAI/standards-guidelines/act/rules/html-page-non-empty-title-2779a5/

**Comment by patrickhlauke** [comment]
confirmed ... it's broken in the 2.1 version https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html#test-rules

fixed already in the 2.2 version https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html#test-rules

**Comment by alastc** [comment]
I think this is a case of the 2.1 docs needing an refreshed update.

**Comment by michael-n-cooper** [comment]
Fixed by https://github.com/w3c/wcag/commit/1a8cc5610ea4b641e22fa13359cf57d7be3faf52
