### ISSUE TITLE
WCAG 2.1 techniques contain links and references to WCAG 2.2 

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag#1919]
Examples of the issue:

* In [WCAG 2.1 Techniques](https://www.w3.org/WAI/WCAG21/Techniques/), the page title and the main heading say "Techniques for WCAG 2.2"
* In [WCAG 2.1 Techniques](https://www.w3.org/WAI/WCAG21/Techniques/), the WCAG 2.2 technique H99 appears in the list of techniques.
* [WCAG 2.1 H98](https://www.w3.org/WAI/WCAG21/Techniques/html/H98) has a "next technique" link to WCAG 2.2 H99.
* [WCAG 2.1 has a copy of H99](https://www.w3.org/WAI/WCAG21/Techniques/html/H99) with a broken link to the WCAG 2.2 Success Criterion 2.4.13.

**Comment by alastc** [comment]
Updated in the WCAG 2.1 branch, just needs publishing by @michael-n-cooper

**Comment by hidde** [comment]
Duplicate of https://github.com/w3c/wcag/issues/1820#issuecomment-865317827 ?

**Comment by alastc** [comment]
They will both be fixed by a clear-out & republishing of the WCAG 2.1 docs, when Michael is back.

**Comment by michael-n-cooper** [comment]
I believe this is all fixed.
