### ISSUE TITLE
Consistent Help note doesn't make sense to me

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#1924]
The following note appears underneath the normative text
> Access to help mechanisms may be provided directly on the page, or may be provided via a direct link to a different page containing the information.

I'm not sure that adds clarity, and could cause confusion to some. The normative text talks about "ways of finding help" and "access to at least one form". Would readers assume from that wording that all the help _functions_ must be located on every page? Given typical sites provide a link to a 'contact us' page, this misinterpretation seems unlikely enough that it needn't be called out in a Note at the end of the normative text. I think it should just be stated (and more clearly) in the Understanding document.

It could easily be appended or worked into the second paragraph:
> Locating the help mechanism in a consistent location across pages makes it easier for users to find it. For example, when a mechanism or link is located in the header of one Web page, it will be easier to find if it is in the header of other pages.

**Comment by mraccess77** [comment]
@mbgower I think this note is trying to communicate that if help exists it doesn't need to be directly on the page but when it exists it can be on the page or linked from the page.  I agree it does not require help on every page in a set - just that when help or a help link exists on pages in set that the relative order is consistent for that help or link to help.

**Comment by alastc** [comment]
The scenario that triggered it was confusion about whether a phone number had to be on every page, or you could link to it.

The feedback from our previous round indicated that people weren't sure if "access to" meant it could be a link and/or on the page. Therefore we added the note...

**Comment by mbgower** [comment]
Okay, if it is considered important, it might be an idea to explicitly explain or elaborate on that note in the Understanding document.

**Comment by alastc** [comment]
Closed by #1924
