### ISSUE TITLE
G220: Provide a contact-us link, technique for Consistent Help, needs a revamped test procedure (and possibly to be made more generic)

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#1926]
First, I'm wondering if [G220](https://w3c.github.io/wcag/techniques/general/G220) needs to be only about a contact-us link. Why couldn't it just be providing a link/mechanism to help of any kind in a consistent location?

Second, the test procedure in the latest editor's draft is absent. It could be something as simple as:

For every page in a set of pages that provides a way of finding help in the form of human contact details, a human contact mechanism, a self-help option or a fully automated contact mechanism:
1. One or more ways of finding help is present on all pages in the set

Check # 1 is true

**Comment by alastc** [comment]
There is a procedure in the code, it must be filtered out by the publishing process. Having a look, it's possibly the classname on the section, so I'll try updating that.
