### ISSUE TITLE
Use GitHub actions instead of Travis CI

### ISSUE THREAD

**Issue by plehegar** [w3c/wcag#1937]
Long story short: we're stopping our use of Travis CI and switching to use GitHub actions instead.

It will NOT affect nor change the current editorial/publishing workflow.

In other words, we're simply replacing one service by another service and strictly doing what the previous service used to do.

I'll submit a pull request and disable Travis CI on this repository later today.

cc @michael-n-cooper  @brewerj @alastc

**Comment by alastc** [comment]
I've merged that into main, but presumably any pre-existing branch that gets updated will need to have these changes merge in?

Also, the timing is not great, anything that needs to happen outside of github would require @michael-n-cooper, and he is on vacation.

**Comment by plehegar** [comment]
> I've merged that into main, but presumably any pre-existing branch that gets updated will need to have these changes merge in?

No. The travis was only doing the deploy on the `main` branch.

> Also, the timing is not great, anything that needs to happen outside of github would require @michael-n-cooper, and he is on vacation.

I did add Michael as a reviewer of the pull request but I see that you did the merge without him. Note that the tooling failed because `3cbot` is not yet authorized to push to the `gh-pages` branch. I suggest waiting for Michael before taking additional actions.

Apologizes about the timing but we could not pick it. Travis did their change 2 days before Michael's vacation and we didn't realize it until then.

**Comment by plehegar** [comment]
update: this is is not working properly, despite w3cbot added in the branch protection team. Will investigate tomorrow.

**Comment by plehegar** [comment]
This has been fixed. We have a [successful push](https://github.com/w3c/wcag/commit/a63934707cc9efb882080ec79fd172c84dcc628a).

The default GITHUB_TOKEN provided by GitHub cannot push on protected branches, so I switched to use a [personal access token](https://github.com/w3c/wcag/commit/3e8df5cbb8d150ec055433953bd05a44bb045e94), encoded as a [GitHub secret](https://github.com/w3c/wcag/settings/secrets/actions).
 

Feel free to re-open if you encounter an issue again.
