### ISSUE TITLE
Large Text - for mobile colour contrast

### ISSUE THREAD

**Issue by accessiblewebuk** [w3c/wcag#194]
https://www.w3.org/TR/mobile-accessibility-mapping/#h-contrast - the working draft of "Mobile Accessibility: How WCAG 2.0 and Other W3C/WAI Guidelines Apply to Mobile" says "When determining which contrast ratio to follow, developers should strive to make sure to apply the lessened contrast ratio only when text is roughly equivalent to 1.2 times bold or 1.5 times (120% bold or 150%) that of the default platform size."

Obviously it is vague and can't be tested objectively if it uses the term "roughly equivalent" but I don't know what is meany by "default platform size". 

Has anyone done any research into comparing the experience for mobile users with the experience for desktop users? There is probably more variance in the distance the device is held than for desktops, where for the majority of users keyboard usage roughly determines how far away the screen is. 

Should we be trying to define this or are there too many variables (e.g. far more mobile users will be using devices in widely different lighting conditions) to make this useful?

**Comment by awkawk** [comment]
@accessiblewebuk - this is a question for the Mobile accessibility task Force that is currently looking at these issues.  You should take a look at their work (https://github.com/w3c/Mobile-A11y-Extension) and submit the issue there.
