### ISSUE TITLE
2.2.2 Pause, Stop, Hide - Definition of term "Parallel" needed

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#1943]
There's a common phrase in 2.2.2 where the term "parallel" is used to define whether a scenario would be applicable:

> ... is presented in parallel with other content ...

I noticed that 'parallel' is not defined in the glossary, but I believe it needs some extra clarification. The reason being is that the audience of WCAG can subjectively interpret parallel in relation to position on the page. For instance, "That carousel is not directly beside the content, so it is not parallel". Also, readers may not take into account the different presentations of content, like linearizing the page. Or, a user's viewport may be large due to their portrait monitor and they may see an animation where others don't.

I believe we need a better explanation on the term 'parallel' and what we mean by saying "presented in parallel with other content". I suggest providing the following amendments:

- A new glossary term explaining what 'parallel' means in the context of WCAG
- A note/ updated verbiage on the Understanding doc explaining what is meant by "presented in parallel with other content".

I'm thinking that the word 'parallel' is used to distinguish between things like entire loading screens vs animating other objects on a normal page. Rather than the visual position of the animating thing on the page.

**Comment by alastc** [comment]
When I look it up, the English definition is "occurring or existing at the same time or in a similar way; corresponding.", which I think is reasonable.

When I look for parallel on the understanding page, the last two examples include the term and context for it. I.e. if it is the only thing on the page then it is not in parallel with other content.

I'm a little reluctant to add more to a document (everything added takes away from what's there), unless there is evidence people are getting confused. We can put it to the group (eventually), but it doesn't seem high priority given the number of open issues.

**Comment by anevins12** [comment]
As long as it's clear I'm happy to close this.

**Comment by alastc** [comment]
If you come across someone arguing that it doesn't apply because it is perpendicular to other content, then please do re-open it. It's just better to tackle demonstrated misunderstandings rather than assumed ones.

Thanks, and good to 'see' you again Andrew, I almost missed who you were from the username!
