### ISSUE TITLE
Related resource links in SC 2.4.2 understanding are 404 or not found

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1962]
The 2 links in the resources section are not longer working:
https://www.w3.org/WAI/WCAG22/Understanding/page-titled

**Comment by cstrobbe** [comment]
Are you referring to these two links? They still work for me.

- [Writing Better Web Page Titles](https://socialpatterns.com/writing-better-titles/).
- [Guidelines for Accessible and Usable Web Sites: Observing Users Who Work With Screen Readers (PDF) ](https://redish.net/wp-content/uploads/Theorfanos_Redish_InteractionsPaperAuthorsVer.pdf).

**Comment by mraccess77** [comment]
They didn't work before - but they do now!
