### ISSUE TITLE
In an age of responsive we should make clear that "full page" in Conformance Criteria 2 includes each view

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#197]
There was quite a long thread on the list, and this is the outcome of the discussion. I presented both Gregg and Loretta with this scenario

> Company X has a responsive web site. A page has 2 break points based on viewport size. A user on a mobile device gets the same page as as the desktop, except it has a Hamburger menu icon instead of the mega menu.
> 
> The mega menu conforms to WCAG, the Hamburger menu does not. On a mobile device, there is no link to the desktop version. Does this page conform to WCAG?
> 
> Some feel that it currently passes because there is one accessibility supported solution. Others think that it does not pass because the user on the mobile device doesn't have a choice about which view they get, (unless there is an accessible link to the desktop -alternative conforming- version.)
> 
> What are your thoughts? 
> 
> 1) Does it pass without a link to the conforming desktop view of the same page?
> 2) Does it pass if it has a link to the conforming desktop view of the same page
> 
> The question is important for decisions in 2.1

Loretta Answers: 

> Just a quick response because I'm on vacation and can't investigate the historical record.
> 
> We had a lot if relevant discussion when trying to define web page (or all the alternate terms we were considering). Part of the discussion was about web apps, which dynamically change what is delivered from the same URI. As I recall, we concluded that any version of the page that could be delivered from that URI had to conform in order to claim that the URI conformed.
> 
> I think this generalizes to saying that all the break points must conform to claim that the URI conforms.
> 
> But this is just my recollection. Sorry I can't point to a specific discussion.

Gregg answers:

> I would think about it like I would a site where there was an accessible alternative - but the alternative was behind a firewall and only available to some. 
> 
> Unless the accessible version is available to all - it does not qualify and an alternative for all (and fails the SC).
> 
> They essentially have a page that morphs into an inaccessible form that the user has no control of.
> 
> IN SHORT
> - it fails the conformance clause because the accessible alternative  is only available from the in accessible version under certain conditions - not at all time. 

Most others agree also. The clarification that a "full page" in Conformance Criteria 2 includes each of it's breakpoints, does not appear anywhere in the current documentation. I think in an age where most sites are responsive this is necessary. There is no proposal to change WCAG, just a statement in the Understanding Conformance Criteria 2 section about this: The proposal is a follows:

> "The full page includes each view of the page that is customized for various devices, browsers, or screen sizes. Each of these views (or their respective conforming alternate versions) would need to conform in order for the entire page to conform. On the other hand, if a user voluntarily chooses a setting on the page that optimizes or personalizes the state of the page for accessibility reasons, this new state does not necessarily need to pass every Success Criteria in order to personalize the page, because the conforming version can be reached by undoing the setting."

It would be placed after the last paragraph in the section "Understanding Requirement 2" (just before the Notes at the end of the section. https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-conformance-requirements-head

**Comment by alastc** [comment]
Agree in principle, reading it in context there is already a lot of wording on alternative versions, how about wording like:

"If the full page automatically varies content or functionality depending on the user's device characteristics then each variation must conform. For example, if functionality changes based on the screensize then each version of that functionality must conform, it is not considered an alternative version."

**Comment by patrickhlauke** [comment]
@alastc i feel the part about "(or their respective conforming alternate versions)" should still remain in there. there could well be an "automatic" variation based on the user's device characteristics (as well as their user agent, i'd add), but if those automatic variations CAN be overridden by the user to access a conforming alternate version, then that needs to be ok as well (as otherwise, as noted on the list, you're contradicting the actual definition for the conforming alternate version)

**Comment by alastc** [comment]
Good point about the over-riding. 
Isn't the user-agent a device characteristic?

I found the mixing of views & alternative versions a bit confusing, how about:
"If the full page automatically varies content or functionality depending on the user's device characteristics then each variation must conform. For example, if functionality changes based on the screensize then each version of that functionality must conform, it is not considered an alternative version. **If the user can override the variations by accessing a _conforming_alternate_version_ then the page is conformant.**"

(I hate 'conformance' language, is that a good way of phrasing it?)

**Comment by patrickhlauke** [comment]
> Isn't the user-agent a device characteristic?

I can use a device, but run different user agents (Android with Chrome, Android with Firefox, etc), so probably worth being explicit.

> If the user can override the variations by accessing a conforming alternate version (link) then the page is conformant.

this to me indicates that you can override ALL the variations with a single alternate version. that may be the case, but it also may not. "Each of these views (or their respective conforming alternate versions) " to me leaves it more open (that each view may also have its own separate/different alternate)

**Comment by alastc** [comment]
Incorporating:
"If the full page automatically varies content or functionality depending on the characteristics of the user's device or user agent then each variation must conform **unless the user can access a _conforming alternative version_**. For example, if functionality changes based on the screensize then each version of that functionality must conform, it is not considered an alternative version. If the user can override the **current variation** by accessing a _conforming alternate version_ (link) then the page is conformant."

Hmm, that's getting as complex as David's version. I can live with the original version, but I'll leave this here in case others prefer it.

**Comment by patrickhlauke** [comment]
personally, i feel the original was easier to parse (for me anyway), but including "variation" (and removing one tiny bit in the last sentence which i think is superfluous) could help

""The full page includes each *variation* of the page that is *automatically* customized for various devices, browsers, or screen sizes. Each of these *variations* (or their respective conforming alternate versions) *needs* to conform in order for the entire page to conform. *However*, f a user *actively* chooses a setting on the page that optimizes or personalizes the state of the page for accessibility reasons, this new state does not necessarily need to *conform*, because the conforming version can be reached by undoing the setting."

**Comment by alastc** [comment]
Fair enough, lets go with that.

**Comment by michael-n-cooper** [comment]
Can someone put a pointer to the referenced thread in this issue? I 
can't figure out which of many long threads might have been the one 
David referenced as triggering this issue. It's important that reviewers 
of the issue can review the whole email discussion if they want, since 
the issue says it's an outcome of that discussion.

**Comment by patrickhlauke** [comment]
@michael-n-cooper well the thread starter was https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/0889.html - it then devolved, hydra-like, into a few branches of discussion all under the same subject line. the point where i think we sort of reached some conclusion was around https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/1009.html and https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/1011.html

**Comment by DavidMacDonald** [comment]
I'm fine with that:
>>"The full page includes each variation of the page that is automatically customized for various devices, browsers, or screen sizes. Each of these variations (or their respective conforming alternate versions) needs to conform in order for the entire page to conform. However, if a user actively chooses a setting on the page that optimizes or personalizes the state of the page for accessibility reasons, this new state does not necessarily need to conform, because the conforming version can be reached by undoing the setting."

**Comment by DavidMacDonald** [comment]
Can we reopen this? @awkawk  it has not been discussed yet.

**Comment by awkawk** [comment]
Why is this not related to the technologies and user agents that are used to make a conformance claim? If I build a site that works great in IE/FF/Safari on a desktop and use that as the basis of my conformance claim but also have an adaption of the site that appears when the site is loaded into a browser that supports accessibility poorly (let's say I make it rely on Canvas in that browser), I still can say that the page conforms, but just not if I reference the "bad" browser.  

I think that the same thing applies for the breakpoint/hamburger version of the question above. 
1) in the desktop version the author needs to verify that the user can make the page view with the megamenu in an accessible manner, and that they know to do this, and then the page conforms if the user agents relied on are the desktop ones.
2) when that same page is viewed through a different browser or in a mobile browser the same questions apply - "can the user access the functionality?", "can the user get to a conforming alternative?", and "was the browser relied on for the conformance claim?" - if the answer is no to all three the page still may conform, as in #1.

**Comment by patrickhlauke** [comment]
@awkawk the crux of the problem here isn't good or bad browsers. it's that you can potentially have the exact same page, exact same URL, looking and behaving differently at different window/viewport sizes (leaving aside all the "dekstop"/"mobile" stuff).

say the user runs it in the browser when the window is set to size w1 x h1 and it's all conforming and valid. now the user simply resizes the browser window to w2 x h2 (or the user zooms the page, as in desktop browsers this results in the effective CSS width/height changing as well, triggering different media queries potentially), and it may completely change in appearance and functionality and be non-conforming and invalid.

so you'd need to write conformance claims/statements all around "as long as the user doesn't run the site below window/viewport size w1 x h1, this page passes WCAG 2.x".

is this what we want to allow?

**Comment by patrickhlauke** [comment]
or should we rather say that a single resource/web page (at a particular URI) that has responsive/adaptive features (meaning that it changes layout or functionality depending on factors such as window/viewport size) must be tested at, and conform, at all its different authored breakpoints for a claim about validity to be made for the resource/web page as a whole.

**Comment by patrickhlauke** [comment]
otherwise, it would be akin (in my mind at least) to saying that authors are free to make conformance claims purely for their site running on a full-color screen, and exempt it from greyscale displays, or similar.

**Comment by alastc** [comment]
I'd add the menu changing example is quite common, a lot of the small screen adaptations assume 'mobile / touch screen' and don't work with a keyboard, or even touch-screen AT. It is only the size of browser-width that changes, and it triggers a different layout with different widgets available.

**Comment by DavidMacDonald** [comment]
I think there is enough ambiguity, and lack of consensus the WCAG rewuires every view of the page to conform that we move this proposal to WCAG2.1 I'll ask @awkawk to reopen over there. https://github.com/w3c/wcag21/issues/19
