### ISSUE TITLE
Separate requirements from exceptions in 2.2.1 Timing Adjustable

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wcag#1971]
The list of requirements for 2.2.1 Timing Adjustable mixes requirements and exceptions together. It appears to be the only success criterion to do this, as the others have exceptions that follow the requirements.

It would be clearer if the list of exceptions were similarly separated from the list of requirements for time limits that have to conform. For example:

> Exception: Time limits are exempt from this requirement when:
> - they are a required part ...
> - they are essential ...
> - they are longer than 20hrs

**Comment by alastc** [comment]
Huh, I've read those all as sort of exceptions, just that some use the term and some don't. 

Overall though, it has been like that for 13 years now, re-structuring a WCAG 2.0 SC isn't high priority.

**Comment by patrickhlauke** [comment]
For once, I tend to agree...the apparent pain of rewording the normative part of an SC (which this would require) is possibly too great (even for purely editorial tweaks)

**Comment by mattgarrish** [comment]
Sorry, went away on vacation after opening this and forgot to follow up. It was just a suggestion, as I found it weird that exceptions were baked into that one criterion where elsewhere they were offset. If it's not worth the effort, I'll close this now.

**Comment by bruce-usab** [comment]
Late comment just to say that I wish I felt like there was clear consensus as to which style is better.  I could go either way.  But having both styles in the same document seems like the worse case scenario.
