### ISSUE TITLE
Update 3.2.6 Understanding document to clarify situations where some pages in set provide no help or when different types of help are provided.

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1972]
It would be good to state the following in the [understanding document](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html) (if my understanding is correct):
* If some pages in a set have help, the SC does not require all pages in a set contain help.
* If pages in the same set contain different types of help (page 1 only human contact details) (page 2 only automated chat bot) those do need to be in the same relative order.

**Comment by alastc** [comment]
There's a paragraph after the list of mechanisms that seems like a suitable location, how about:

> While it would be best for all pages of each web site to offer at least one of these types of help, this SC does not require help be provided. The criterion is worded so that it does not require all pages in a set contain help, or for a particular order of the types of help. The SC requires that when help is available on a page, that it be in a consistent location compared to others in the set of web pages.

**Comment by mraccess77** [comment]
Yes, that would make it clear.
