### ISSUE TITLE
SC 2.5.7 Dragging exceptions seems like example of free form paths rather than dragging

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1979]
The 2 examples given for exceptions seem more like free form rather than dragging motions which we define to be only concerned with the beginning and endpoint.  There are some types of drawing tools that are that way - such as when you draw a line and you set a target at the beginning and then move to wherever and set the end target and a line is drawn.   It might be worth clarifying this.   Although in these cases it seems like it could be done without a drag.  Simply move the pointer to the start and press a button and then locate the end point and press another button.  If we state that a particular track needs to be followed then it's by virtual not a dragging motion and thus isn't an exception - it's just not applicable.   A better example in a game might be a dragging motion where the endpoint is moving - but even then it seems like it could be met another way.

Current text
"drawing a freeform figure, or playing a game where the aim is to follow a particular track as accurately as possible. The criterion has an exception for these cases where the task requires dragging."

**Comment by detlevhfischer** [comment]
@mraccess77 I have changed the example to something in line with your suggestions see #2003  No idea whether such thing exists in real games (I know nothing about games).

**Comment by alastc** [comment]
The group agreed to remove the exception info in the understanding doc. It's a useful exception (just in case there is something), but until we find a better example it's better to remove it.
https://www.w3.org/2021/12/03-ag-minutes.html#t07
