### ISSUE TITLE
Outline a way to deal with 'definition changes'.

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#198]
On the WCAG call today, as point was raised by @jspellman around how we propose deal with any prospective 'definition changes' in a potential 2.1. [1]

This could be for items like 'what is web content', definitions of pixels/points, luminosity etc.

@awkawk  and @josh to discuss on upcoming editors call.

[1] https://www.w3.org/2016/07/05-wai-wcag-minutes.html

**Comment by joshueoconnor** [comment]
@awkawk We should discuss this on an upcoming editors call..

**Comment by alastc** [comment]
Closing - I think it has been talked about a lot in terms of backwards compatibility, and will be discussed again soon in the context of 2.2.
