### ISSUE TITLE
Does only the initial state obscured clause of SC 2.4.11 also apply to SC 2.4.12?  

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1982]
The understanding doc says everything is the same between the two - so I assume so - but I wanted to clarify.

From 2.4.11 - but not mentioned in 2.4.12
"If the interface is configurable so that the user can move toolbars and non-modal dialogs around, then only the initial positions of user-movable content would be considered for testing and conformance of the Unobscured bullet"

**Comment by alastc** [comment]
I don't see a reason we'd vary the advise/requirement from the AA version, so closing.
