### ISSUE TITLE
Understanding SC 4.1.1 mentions SC 1.4.2 'Resize text'

### ISSUE THREAD

**Issue by sander-nl** [w3c/wcag#1999]
Hi, 

On page https://www.w3.org/WAI/WCAG22/Understanding/parsing.html in the note under the heading "Intent", there is a link to SC 1.4.4 'Resize text' (https://www.w3.org/WAI/WCAG22/Understanding/resize-text). 
However, the link text is "1.4.2: Resize text". This should be "1.4.4: Resize text".  

This is also the case on page https://www.w3.org/WAI/WCAG21/Understanding/parsing.html (WCAG 2.1).

**Comment by alastc** [comment]
Thanks @sander-nl, I've updated that in a couple of branches so it should update next time the docs are published.
