### ISSUE TITLE
H45 Add longdesc spec

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#202]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H45.html

I think that we should add longdesc spec to Resources of this technique.

HTML5 Image Description Extension (longdesc)
https://www.w3.org/TR/html-longdesc/

And, which branch should I send pull request? (`Working-Branch-for-Q3-2016`?)

**Comment by awkawk** [comment]
Fixed.
