### ISSUE TITLE
Is "Not fully obscured:" from SC 2.4.11 already covered by SC 2.4.7

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#2023]
Proposed SC 2.4.11 indicates that if the component (in initial state) is fully obscured then it should fail.   This seems like it would already fail SC 2.4.7 because if the component is obscured the indicator would be not visible.  It seems like this creates a duplicate requirement and that auditors would then need to fail SC 2.4.7 and 2.4.11 for the situation there it is fully obscured.  

Putting it another way - when would SC 2.4.7 pass but this aspect of SC 2.4.11 fail?  If no then this seems like a duplication.

**Comment by alastc** [comment]
Hi Jon, we tackled this aspect a while back: https://github.com/w3c/wcag/issues/952#issuecomment-637689097
