### ISSUE TITLE
H35 & H49 tweak source markup

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#203]
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H35.html
- https://github.com/w3c/wcag/blob/master/wcag20/sources/techniques/html/H35.xml
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H49.html
- https://github.com/w3c/wcag/blob/master/wcag20/sources/techniques/html/H49.xml

These techniques have unexpected nesting `<div class="example">`.
To resolve this issue, we should remove extra `<description/>` (at line 34 of H35 & at line 90 of H49).

**Comment by awkawk** [comment]
Fixed, thanks.
