### ISSUE TITLE
Update Resources to WAI-ARIA 1.1 Authoring Practices

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#205]
Update Resources to WAI-ARIA 1.1 Authoring Practices

According to https://lists.w3.org/Archives/Public/w3c-wai-ig/2016JulSep/0053.html ,
> If you still use the 1.0 resources, you should update your references to the new WAI-ARIA Authoring Practices 1.1 <https://www.w3.org/TR/wai-aria-practices-1.1/> to ensure you are following the latest advice.

So we should update resources which refer WAI-ARIA 1.0 Authoring Practices (following pages):

- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA1.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA2.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA5.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA6.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA9.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA10.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA11.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA12.html (including prose)
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA13.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA14.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA15.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA16.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA18.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/ARIA19.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/F15.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/F59.html
- https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/F63.html

Additionally, we should remove WAI-ARIA 1.0 Primer from ARIA5.

**Comment by awkawk** [comment]
All updated.
