### ISSUE TITLE
Conformance WCAG 3: Counting passing issues and documenting is poor use of a company's budget

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#2058]
Not sure if this belongs here or in another repo. WCAG 3 conformance model currently includes the need for testers to manually count passing instances.

As a manual tester, the idea of manually counting passing instances of issues is daunting. It would result in companies spending a lot of their A11Y budget on things they have done right.

I would like to suggest that manual counting and documenting of things companies do right be off the table.  There is no mainstream Q/A methodology that I am aware of, where Q/A testers document passing issues.

We could used AI to sample etc... but without an automated way to count all passing issues, I think we adjust our conformance model so that company's budgets are not used that way.

**Comment by mraccess77** [comment]
It's also much more complicated than simply telling a tool to count all img elements.  We have img, role=img, svg, canvas, CSS background images, font icons, embed, object, video poster images, role doc-graphic, etc.  Counting them all up is likely to not be accurate.  If we do count them that information would need to be recorded as part of the audit and documented.

**Comment by jake-abma** [comment]
Also the loading of new images when scrolling the page will not help counting them... let alone the importance of images further away in the scroll.

**Comment by jongund** [comment]
One approach is to look at passing of rules, not individual elements.
This helps people see if they understand and consistently implementing a particular accessibility requirement, rather tan a specific technique.
See FAE summary reports:
https://fae.disability.illinois.edu/summary/17a397e50be195db/rc/
