### ISSUE TITLE
G18 Incorrect link to CSS3 Values

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#206]
In note of https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/G18.html#G18-description :
CSS3 Values
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/G18.html
-> https://www.w3.org/TR/css3-values/

**Comment by awkawk** [comment]
fixed: https://github.com/w3c/wcag/commit/5dcc3a1945d133aed570a5b8d0ec4abf2b959f8d 

Thanks.
