### ISSUE TITLE
Visible controls

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#2072]
The 3rd bullet says:

>A mechanism is available to make the information persistently visible;

We should probably explicitly say that this mechanism is visible something like this:

> A mechanism, which itself is visible, is available to make the information persistently visible;
OR
>A visible mechanism is available to make the information persistently visible;

**Comment by bruce-usab** [comment]
@DavidMacDonald &ndash; granted this SC is about visibility, but might that change disallow a preference setting on a previous page?  We don't qualify other uses of <q>a mechanism is available</q> as needing to be visible.  Has that been a problem?  Why a change the pattern used for other SC?

**Comment by DavidMacDonald** [comment]
Might be OK like this... it just occurred to me that it might be a bit of a circle... a mechanism is available to ensure that components are visible but that mechanism might only be available on hover... I'm guessing most authors won't be so dumb as to only make that mechanism available on hover ... but you never know...

**Comment by DavidMacDonald** [comment]
We could manage it with a note if it concerns others, or close this ...

**Comment by mraccess77** [comment]
Originally this was about processes - so I'd be worried if you have to exit out of a process in order to access a preference in settings in order to have visible controls.

**Comment by alastc** [comment]
I don't think it would help to further specify the mechanism, it would be too easy to disallow something useful.

For example, you might have a 'touch interface' setting (like in MS office) which expands target sizes and doesn't use hover. That could be set at an application/site level, so that you don't need the control on a per-page basis.

**Comment by fstrr** [comment]
Proposed response:

We don't specify visibility in other uses of "a mechanism is available", and adding the requirement here doesn't seem to improve the SC. This can be closed.

**Comment by DavidMacDonald** [comment]
I'm fine with that

**Comment by alastc** [comment]
The response above was agreed today: https://www.w3.org/2022/03/01-ag-minutes.html#t08
