### ISSUE TITLE
2.5.5 understanding doc has an empty example

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wcag#2074]
It's not clear in the 2.2 understanding document if an example is missing or if some stray example markup needs to be deleted: https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html#examples

**Comment by alastc** [comment]
@michael-n-cooper I think something is odd here, and I'm not sure which files are actually contributing, we have:

1. understanding / 21 / target-size-enhanced.html (with H1 of "Understanding SC 2.5.**4** Target Size (Enhanced)")
2. understanding / 21 / target-size-minimum.html (with H1 of "Understanding SC 2.5.**3** Target Size (Enhanced)")
3. understanding / 22 / target-size-minimum.html (with H1 of "Understanding Target Size (Minimum)")

From the content I think 2 & 3 are correct, but the H1 for 2 doesn't match the published content? I guess the template is ignoring that and using the correct SC number?

It looks like 1 is an older file: https://github.com/w3c/wcag/commits/main/understanding/21/target-size-enhanced.html 

I've created PR #2075, could you check that doesn't throw errors when building before one of us merges that?

**Comment by michael-n-cooper** [comment]
Just getting to this, #2075 looks ok though it's out of date and will need attention before merging at this point. Which files are loaded depends on the guidelines/index.html file, it's not necessary to delete older versions, though perhaps it's less confusing.

**Comment by fstrr** [comment]
Closing this as the issue has been addressed.
