### ISSUE TITLE
Resolve understanding drafts for conflicts with updates

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#2088]
The branch I created back in June now has conflicts with a number of updated files. https://github.com/w3c/wcag/tree/ReviewofUnderstandingDocs_mg

However, many of the style consistencies still need to be address. Need to make separate PRs for each Understanding doc and resolve any conflicts.

**Comment by mbgower** [comment]
@alastc I'm reopening and marking as Ready for Survey because three of these PRs remain unimplemented. 
https://github.com/w3c/wcag/pull/2092
https://github.com/w3c/wcag/pull/2094
https://github.com/w3c/wcag/pull/2095

**Comment by alastc** [comment]
These are all merged now, so either I thought they were just editorial or we surveyed them?!
