### ISSUE TITLE
H46 `noembed` is obsoleted by HTML5

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#209]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H46.html
If I remember correctly, `noembed` element never been defined in any version of the HTML standards.
The HTML5.1 spec also says "Use object instead of embed when fallback is necessary." Thus, we should use `object` instead of `noembed`.

See also:
https://www.w3.org/TR/html51/obsolete.html#elementdef-noembed
https://www.w3.org/TR/html51/semantics-embedded-content.html#the-embed-element

**Comment by awkawk** [comment]
https://github.com/w3c/wcag/pull/219/files?diff=split

**Comment by awkawk** [comment]
Thank you for the comment.  While this is not a technique that represents the most current practice, the group is keeping this technique active in support of legacy content.

**Comment by momdo** [comment]
I agree with the idea to leave this technique as-is, but I'm afraid that the technique violates the WCAG 2.0 Success Criterion 4.1.1 [1] [2]. It should be clearly described in the Notes, like "willful violation" in HTML5 [3], that the H46 technique is inconsistent with the G134 [4] and H88 [5] and doesn't  conform to any HTML specification (even in HTML5, which obsoletes the feature [6]).

Additionaly, from the fact that the technique is not standard-conformant, the usage of the technique is limited only to when the targeted plugin supports `embed` / `noembed` element but not `object`. It should be clearly noted within the document and, if possible, WCAG WG should prove clearly that there is such assistive technology or implementation.

[1] https://www.w3.org/TR/WCAG20/#ensure-compat
[2] https://www.w3.org/WAI/GL/2016/WD-UNDERSTANDING-WCAG20-20160719/ensure-compat-parses.html
[3] https://www.w3.org/TR/html5/introduction.html#compliance-with-other-specifications
[4] https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/G134.html
[5] https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H88.html
[6] https://www.w3.org/TR/html5/obsolete.html#non-conforming-features

**Comment by awkawk** [comment]
Using this technique does not violate 4.1.1.  
The use of this technique would be inconsistent with G134 and H88, but as neither of those techniques (nor any technique) is _required_ that is not a reason to remove H46.
