### ISSUE TITLE
H62 `ruby` is also defined by HTML5

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#212]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H62.html

Current applicability section is XHTML 1.1 only, so we should add HTML5.
Also, we have to refine description of HTML5 `ruby`.

Resources:
- https://www.w3.org/TR/html/textlevel-semantics.html#the-ruby-element
- https://www.w3.org/TR/html/textlevel-semantics.html#the-rb-element
- https://www.w3.org/TR/html/textlevel-semantics.html#the-rt-element
- https://www.w3.org/TR/html/textlevel-semantics.html#the-rtc-element
- https://www.w3.org/TR/html/textlevel-semantics.html#the-rp-element

**Comment by awkawk** [comment]
I'm not sure how you are proposing changing the description.  Can you be more explicit about the changes?

**Comment by momdo** [comment]
I propose that following update:

1) In Applicability section:
> XHTML 1.1

-> XHTML 1.1 and HTML 5

2) In Description section:

> Ruby Annotation is defined as a module for XHTML 1.1. 

> Simple Ruby markup also provides a "fallback" option for user agents that do not support Ruby markup (that is, user agents that do not support XHTML 1.1)

These sentense mention only XHTML 1.1. Thus, we need to update (adding HTML 5).


3) In Resources section:

At least, adding following links.

- https://www.w3.org/TR/html5/text-level-semantics.html#the-ruby-element
- https://www.w3.org/TR/html/text-level-semantics.html#the-rb-element
- https://www.w3.org/TR/html/text-level-semantics.html#the-rt-element

**Comment by awkawk** [comment]
Addressed in https://github.com/w3c/wcag/pull/230 (pending approval)
