### ISSUE TITLE
H83 `target` is now defined HTML5

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#215]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H83.html

We have to revise Applicability and Description.

Resources:
https://www.w3.org/TR/html51/sec-forms.html#element-attrdef-form-target
https://www.w3.org/TR/html51/browsers.html#browsing-context-names

**Comment by awkawk** [comment]
Pull request 218 addresses this, for HTML5, not HTML 5.1.
