### ISSUE TITLE
@@ in understanding document

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#2151]
The following Understanding document has @@ markings for future techniques. https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#techniques

This can be confusing for people as the @@ symbol is not explained. 

Either leave out the whole technique stub or remove @@ or explain the @@ symbol to readers.

**Comment by patrickhlauke** [comment]
duplicate of https://github.com/w3c/wcag/issues/1813 which has an open PR to address it https://github.com/w3c/wcag/pull/2131
