### ISSUE TITLE
H86 Improve leetspeak description

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#216]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H86.html
> Leetspeak uses various combinations of ASCII characters to replace Latinate letters.

From the view point of i18n, this proposal intends to replace the sentence to imply that the culture of leet speak is also observed outside the ASCII-only world, e.g. in CJK.

Leetspeak uses various combinations of characters, including numerals and special characters, to replace original writings.

**Comment by awkawk** [comment]
Opened pull request 217 to address.
