### ISSUE TITLE
aria-roledescription with implicit/explicit roles not read by screen readers 

### ISSUE THREAD

**Issue by elamurugan-r** [w3c/wcag#2168]
a)
```
<section aria-roledescription="carousel" aria-labelledby="carousel-header" >
        <h1 id="carousel-header" >Popular Web series and Episodes</h1>
        <button>Trigger</button>
</section>
```
b)
```
<div role="region" aria-roledescription="carousel" aria-labelledby="carousel-header" >
        <h1 id="carousel-header" >Popular Web series and Episodes</h1>
        <button>Trigger</button>
</div>
```

Screen reader (ChromeVox and voiceover) is reading the above as
**a) Section Trigger button
b) Popular Web Series and its Episodes Trigger**

Its not reading the aria-roledescription value. So i checked in axe-core-4.3.5 which gives the following error eventhough using implicit/explicit aria-role:
a & b) **aria-roledescription must be on elements with a semantic role.
Issue Description: Ensure aria-roledescription is only used on elements with an implicit or explicit role**

Please refer my work below to detect the issue:
https://wizardly-davinci-611bef.netlify.app/

Its not reading the text inside aria-roledescription.

FYI: Even the carousel design pattern examples provided in w3c is also not reading the aria-roledescription

**Comment by patrickhlauke** [comment]
wrong repository to report this, which seems a combination of lack of current support in some SRs, plus possibly a problem with axe-core. suggest filing this in bug trackers for the screen readers and opening a ticket in the axe-core repo.
