### ISSUE TITLE
MathML version of the relative luminance definition

### ISSUE THREAD

**Issue by bruce-usab** [w3c/wcag#2173]
Recently, we have been taking a closer looking at the [flash thresholds](https://w3c.github.io/wcag/guidelines/22/#dfn-general-flash-and-red-flash-thresholds).

Relatedly, can we delete the [last note](https://w3c.github.io/wcag/guidelines/22/#h-note-134) under [relative luminance](https://w3c.github.io/wcag/guidelines/22/#dfn-relative-luminance) which links to an [xml file](https://w3c.github.io/wcag/guidelines/22/relative-luminance.xml)?

If not, then probably we should update the file, at least a little bit.
- [x] delete (html style) comment
- [x] change <q>WCAG 2.0</q> (part of linked text, at top) to <q>WCAG 2.2</q>
- [x] change two URLs under references from hard-coded links (using 2.0 anchors) to relative
- [x] change one URL link 2.1 SC 1.4.3 to relative

It is all presentational MathML, but changing that to content MathML would be a pretty heavy lift.  Also lots of cruft like:  `<mn>8</mn><mi>b</mi><mi>i</mi><mi>t</mi>` which, as I understand it, should just be:  `<mi>8 bit</mi>`

I am willing to take a stab at the pull request.

**Comment by bruce-usab** [comment]
@alastc -- please let me know your initial disposition preference.

**Comment by awkawk** [comment]
This would be a normative change - is the note wrong? I don't see the argument for this being an errata...

**Comment by bruce-usab** [comment]
No, the note is not _wrong_ per se.  The .xml file is quite bad though.  My checkboxes is the minimum list of errors, but they are trivial.
