### ISSUE TITLE
Broken link in "Understanding success criterion 1.4.1"

### ISSUE THREAD

**Issue by lbuffet-pro** [w3c/wcag#2174]
In the page [Understanding Success Criterion 1.4.1: Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html), under the "Related Resources" heading, the link [The Color Tutor application](http://www.tomjewett.com/colors/tutor.html) is broken.

**Comment by alastc** [comment]
Thanks for the heads up. From a little digging it appears that this is the new link: https://colortutorial.design/tutor.html

I've updated that in the main and 2.1 branches, it will take effect next time each set of docs is published.
