### ISSUE TITLE
Success Criterion 3.3.7 Accessible Authentication A or AA?

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#2191]
There is a different level set for
- [Success Criterion 3.3.7 Accessible Authentication](https://www.w3.org/TR/WCAG22/#accessible-authentication) (Level A) [New]
- [Understanding Success Criterion 3.3.7: Accessible Authentication](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication) (Level AA)

Could someone confirm the level for this success criterion and update please.

**Comment by patrickhlauke** [comment]
https://www.w3.org/TR/WCAG22/ is badly out of date for some reason (it also lacks "3.3.8 Accessible Authentication (No Exception)" for instance), while the matching understanding document isn't.

best to look at the editor's draft https://w3c.github.io/wcag/guidelines/22/

/cc @alastc

**Comment by alastc** [comment]
This is just an artefact of the publishing process, the "TR" document doesn't get updated unless it is transitioning or going our for a wide review.

The editor's draft that Patrick linked to is a preview of what will go out later.
