### ISSUE TITLE
PDF3 comments

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#220]
From https://lists.w3.org/Archives/Public/public-comments-wcag20/2016Aug/0000.html:

I’m looking here:

https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/complete-diff.html#pdf

++ Introduction, para 2

PDF/UA was updated in 2014. The page under the links says so. The text should refer to “ISO 14289:2014” and the link should go here:

http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=64599

++ Accessibility Checking and Repair

This section could use updating! There are many other tools available. And… does Kurzweil 3000 really use tagged PDF? I’m not so sure - and if it doesn’t it should not be listed here, for obvious reasons.

++ Under “Assistive technology support” VoiceOver is listed, but it should not be (it doesn’t support tagged PDF).

++ Related References

- Update the reference to PDF/UA, as above
- Add the Matterhorn Protocol
http://www.pdfa.org/publication/the-matterhorn-protocol-1/

**Comment by awkawk** [comment]
Proposed response:
Thanks for the comments.  We have updated the links to PDF/UA and added the Matterhorn Protocol.  

The accessibility checking and repair section could undoubtedly use updating, if you would like to suggest specific edits we would be happy to review them. 

Regarding VoiceOver and PDF, this assistive technology is capable to reading PDF content, but as you point out it does not currently use the tag structure to do so.  We would agree that this makes it a non-conforming PDF/UA user agent, but it is able to read PDF content, so we are inclined to leave it on the list, but if you can offer a note to accompany the listing we can add it.

**Comment by mraccess77** [comment]
I thought tagged PDF was supported with acrobat DC on Mac - if it doesn't use tags then I'm not sure how headings and list and other structural elements are supported as of DC.

**Comment by awkawk** [comment]
@mraccess77 - you are right, my mistake.  we will resurvey with the edits made to the above response.
