### ISSUE TITLE
2.4.12 is out of sync with 2.4.11 in the editors draft

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#2205]
The editors draft of 2.4.11 has received a number of changes that should also be applied to 2.4.12:

- The "not obscured" exception is now no longer a bullet
- The "contrasting area" label was changed to just "contrast"

**Comment by alastc** [comment]
I was waiting for 2.4.11 to settle down before applying the changes to 2.4.12

**Comment by mbgower** [comment]
@WilcoFiers I have made a PR to address this https://github.com/w3c/wcag/pull/2365
I believe it is in survey for this week.

**Comment by fstrr** [comment]
Closing this as 2.4.12 has been removed.
