### ISSUE TITLE
Old link into "Understanding Success Criterion 1.3.6: Identify Purpose"

### ISSUE THREAD

**Issue by juliemoynatPro** [w3c/wcag#2208]
Hi,

In the page [Understanding Success Criterion 1.3.6: Identify Purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-purpose.html), there is an old link from 2017 in that sentence :

> A website uses [ARIA landmarks](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/index.html) to identify the regions of the page, and users can hide areas that do not have a role of `main`.

I think it should be replaced by this link which is up to date: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/index.html

**Comment by alastc** [comment]
Thanks, I've updated that in main (2.2) and 2.1, it will appear next time there is a publish of the docs.
