### ISSUE TITLE
H30: potentially confusing example - needs to be explained better

### ISSUE THREAD

**Issue by gaurav5430** [w3c/wcag#2211]
Example 4 of [H30](https://www.w3.org/WAI/WCAG21/Techniques/html/H30) (Providing link text that describes the purpose of a link for anchor elements) states that:

> A site allows users to provide feedback on products, when the user is logged in, by clicking on the "Feedback" link in a product detail page. Other users or the product manufacturer are able to provide a response to any feedback. The feedback link displays an icon before the "Feedback" text when a response to the user's feedback is available. The help information describes this icon as a talking bubble containing quotation marks and includes the icon itself as an example. The icon's text alternative in the help text is "Response received icon". The same text alternative is used in the product detail pages (when a response is available) to allow identification of this icon through multiple modalities.

```
<a href="prod_123_feedback.htm">Feedback 
         <img src="response.gif" width="15" height="15" alt="Response received icon" />
</a>
```

it is not clear what is meant by "help information" here. This also leads to confusion when deciding the alt text for the icon. Generally I would avoid using the word "icon" in the alt text, as it provides redundant information since the screenreader would have already announced "image", but in this case it seems there is a reason to add "icon" in the alt text, which is not clear from the rest of the provided context

**Comment by awkawk** [comment]
It means documentation. How about:

"The site's help document describes this icon as a talking bubble containing quotation marks and includes the icon as an example. The icon's text alternative in the help document is "Response received". The same text alternative is used in the product detail pages (when a response is available) to allow identification of this icon through multiple modalities."

(changes "help information" to "site's help document", removes "itself" from "includes the icon itself as an example", changes second "help information" to "help document", and removes "icon" from the alt in the paragraph)

And then we would remove "icon" from the alternative text.

**Comment by gaurav5430** [comment]
Sure, this is helpful.

I think we could slightly expand on "to allow identification of this icon through multiple modalities." as well 

Something like:
"...to allow identification of this icon through multiple modalities. For e.g, a mouse user who has gone through the site's help document would be able to identify this icon on the product page once they see it because they have already seen it in the help documentation, and a screenreader user would be able to identify it because the same name would be announced for the icon on the product page as mentioned in the help document"

**Comment by awkawk** [comment]
@gaurav5430 I guess, but this technique is about providing descriptive text and that doesn't impact the sighted mouse user typically.

**Comment by gaurav5430** [comment]
> @gaurav5430 I guess, but this technique is about providing descriptive text and that doesn't impact the sighted mouse user typically.

ohk, is that not what is meant by different modalities ?

**Comment by awkawk** [comment]
That last sentence is a little confusing. It could say "The same text alternative is used in the product detail pages (when a response is available) to help to ensure that users following the documentation can identify the image correctly as documented."

**Comment by fstrr** [comment]
I'll work on an update to H30 for this based on the conversation here.

@awkawk: I'd also like to remove Example 7, and it's related working example, as that's not a good example of how to mark up cards. Any opinion on that?
