### ISSUE TITLE
H64 & H70 `frame` is obsoleted by HTML5

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#222]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H64.html
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H70.html

I feel that we need to remove `frame` from H64 and H70, because `frame` is obsolete [1].
If we don't change the text, I think that we should mention "obsolete in HTML5" in the text at least.

[1] https://www.w3.org/TR/html5/obsolete.html#non-conforming-features

**Comment by awkawk** [comment]
Proposed response: Thank you for the comment. We will add a note to H64 and H70 that reads:

In HTML5 the frame element is deprecated. The iframe element remains part of the HTML5 specification.

**Comment by awkawk** [comment]
Approved by WG
