### ISSUE TITLE
H73 `summary` is obsoleted by HTML5

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#223]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H73.html

It seems to me that a lot of AT support `summary` attribute, but `summary` is oboslated by HTML5 [1].
The HTML5 spec says "Use one of the techniques for describing tables given in the table section instead." [1][2]

[1] https://www.w3.org/TR/html5/obsolete.html#attr-table-summary
[2] https://www.w3.org/TR/html5/tabular-data.html#table-descriptions-techniques

**Comment by awkawk** [comment]
Proposed response: Thank you for the comment.  We will add a note to H73 that reads:

In HTML5 the summary attribute is deprecated.  Some assistive technologies may continue support the summary attribute, but authors should consider alternatives and only use with caution.

**Comment by awkawk** [comment]
Approved by WG CfC.
