### ISSUE TITLE
ARIA tag for musical score

### ISSUE THREAD

**Issue by mscuthbert** [w3c/wcag#2231]
I was wondering what the proper "aria-role" would be for a musical score, especially one rendered as SVG etc. or one rendered in Braille Music Code?  I am thinking about content like:

```
<svg aria-role="?musical-score-img?" aria-labeledby="score1_braille">
       ... a million Path objects that convey no information to a screen-reader user...
</svg>
<pre class="sr-only" aria-role="?musical-score-braille" id="score1_braille">
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠩⠩⠩⠨⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠼⠚⠀⠨⠙⠚⠀⠪⠺⠹⠣⠇⠫⠀⠹⠺⠪⠣⠇⠹⠀⠊⠚⠳⠻⠣⠇⠪⠀⠺⠺⠻⠫⠀⠪⠺⠹⠣⠇⠹
⠀⠀⠐⠪⠺⠹⠪⠀⠳⠻⠗⠣⠇⠀⠟⠻⠻⠈⠉⠀⠻⠛⠩⠋⠻⠣⠇⠣⠅
</pre>
```

Math equations have a defined Aria role but musical scores do not.  I would like to label the musical outputs from my program properly if possible.  Thanks!

**Comment by pkra** [comment]
This seems more like a question for [ARIA Authoring Practices](https://w3c.github.io/aria-practices/) (on how to build accessible musical notation).

For the braille part, there's the proposed aria-braillelabel https://w3c.github.io/aria/#aria-braillelabel that is targeted for ARIA 1.3. As it turns out, I plan to use musical notation as an example for https://github.com/w3c/aria-practices/issues/1825 -- musical notation is one of the rare cases where braille-specific labels might be justified.

**Comment by alastc** [comment]
I agree with @pkra that this is better aimed at the ARIA practices.

From a WCAG point of view if there isn't a suitable role available (and implemented in AT), then having a good preceding heading and/or a text description of the image/pre would be appropriate.

If that makes sense can we close this issue? I can't see any changes we'd make to the WCAG documentation based on this issue.

**Comment by pkra** [comment]
@alastc if there's someone with sufficient privileges in both repositories, perhaps the issue could be transferred.

**Comment by alastc** [comment]
That isn't me, I'm not sure there is overlap. Might be easiest for @mscuthbert to just copy to the ARIA repo.

**Comment by bruce-usab** [comment]
@mscuthbert be sure to ping @JaninaSajka as she almost certainly has some practical ideas.   I agree that this is out of scope for WCAG.  I would like to promote better HTML support for both dynamic braille displays and braille hard copy but I am not sure where the opportunities are.

**Comment by mscuthbert** [comment]
Thanks for the great comments and for pointing me in the right direction and getting me in touch with a great person who may have ideas. What a wonderfully welcoming community. I'll close the comment since there's no action at least at present here.
