### ISSUE TITLE
G138 `STRONG` description

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#224]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/G138.html

In Example1,

>STRONG element for stronger emphasis. 

This description is correct from a viewpoint of HTML 4, while HTML 5 spec says "The strong element represents strong importance, seriousness, or urgency for its contents."

Additonally, we need to update the next link.

Phrase elements: EM, STRONG, DFN, CODE, SAMP, KBD, VAR, CITE, ABBR, and ACRONYM
http://www.w3.org/TR/1999/REC-html401-19991224/struct/text.html#h-9.2.1

->HTML 5.0: 4.5.2 The em element
https://www.w3.org/TR/html5/text-level-semantics.html#the-em-element

**Comment by awkawk** [comment]
Added the link tot he HTML 5 em element section.
