### ISSUE TITLE
Updates to understanding for SC 1.4.11 are in WCAG 2.2 draft but not yet WCAG 2.1 documents

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#2242]
I noticed the updates for understanding how to determine conformance for focus indicators for SC 1.4.11 appear in the WCAG 2.2 draft understanding documents but are not yet in WCAG 2.1.
Are these not yet approved?  When will they become active for WCAG 2.1 - is that when WCAG 2.2 is published?  When do separate updates to WCAG 2.1 documents get published?

Reference documents:
* https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast
* https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast
* https://w3c.github.io/wcag/understanding/

Thank you.

**Comment by patrickhlauke** [comment]
related https://github.com/w3c/wcag/pull/2233#issuecomment-1054538748

there seems to be some confusion (certainly on my part) when and where bits of 2.1 and 2.2 are updated

**Comment by alastc** [comment]
@michael-n-cooper is there something I need to be doing to ensure 2.1 docs get updated?

**Comment by michael-n-cooper** [comment]
I've pulled changes for Non Text Contrast and Visual Presentation into the 2.1 branch and republished. I'm putting into my todo list to look for other changes I missed, and come up with a reliable way to not miss them in the future.

**Comment by alastc** [comment]
Closing, the docs match now.
