### ISSUE TITLE
Private Sector Websites

### ISSUE THREAD

**Issue by officespacemike** [w3c/wcag#2247]
Hi there, 
Are these guidelines only applicable to public sector body websites?
Many thanks
Mike

**Comment by patrickhlauke** [comment]
the guidelines themselves don't set out anything regarding what sites they do or don't apply to. that's a choice that's down to individual countries/regions to decide. legal text may not necessarily mandate a specific WCAG level, but WCAG is likely to be used as a benchmark when cases are being brought against companies (e.g. in UK the general Equality Act 2010).

**Comment by patrickhlauke** [comment]
while not fully up-to-date, i'd suggest having a look at https://www.w3.org/WAI/policies/

**Comment by officespacemike** [comment]
Many thanks for this.

**Comment by bruce-usab** [comment]
@officespacemike I see you are in London, but for folks in the states follows are a couple lists where WCAG is referenced in lawsuits, most of which are are _not_ public sector:  [ada.gov](https://www.ada.gov/enforce_current.htm) [lflegal.com](https://www.lflegal.com/negotiations/#agreements)
