### ISSUE TITLE
Consider SMIL

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#225]
http://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/smil.html

It seems to me that SMIL partially is implemented as SMIL animations by some UA. [1][2]
Chrome 45 has deprecated SMIL. [3]
Thus, I propose removing SMIL techniques.

Otherwise, while we can leave the reference to SMIL techniques, they should be reformed, because the latest SMIL specification is 3.0, whereas there are references only to SIML for 1.0 and 2.0.
I think that these techniques have to be unified, from the viewpoint of SMIL 3.0, for readability.

[1] https://developer.mozilla.org/en/docs/Web/SVG/SVG_animation_with_SMIL
[2] https://css-tricks.com/smil-is-dead-long-live-smil-a-guide-to-alternatives-to-smil-features/
[3] http://blog.chromium.org/2015/07/chrome-45-beta-new-es2015-features.html

**Comment by awkawk** [comment]
Thank you for the comment.  The SMIL techniques are focused on earlier versions of SMIL, and while they are correct for the earlier versions of SMIL do need updating. This will be an additional project that we will require additional resources to take on, or will require the contribution of techniques that are updated for SMIL 3.0.  We will mark this as work that is needed on our wiki.

**Comment by awkawk** [comment]
Response approved by WG.
