### ISSUE TITLE
What's the required spacing between paragraphs vs spacing following a paragraph?

### ISSUE THREAD

**Issue by mikkorantalainen** [w3c/wcag#2252]
The section "Success Criterion 1.4.12 Text Spacing" https://www.w3.org/TR/WCAG21/#text-spacing says following:

> Line height (line spacing) to at least 1.5 times the font size;
> Spacing following paragraphs to at least 2 times the font size;

Literally read, this requires that all pages wishing to implement AA or AAA level accessibility MUST use at least following CSS styles

```
p {
    line-height: 1.5;
    margin-bottom: 2em;
}
```
(... and the legislation here in Finnish makes the AA level accessibility the minimum allowed for public content.)

However, nobody in real world wants to use such an ugly style. And this includes the WCAG spec, too! Everybody seems to *actually* use `margin: 1em 0;` where margin collapsing causes effective spacing following a paragraph to be 1 times the font size. **What's the actual intent of the above quoted text in the spec?**

Also, do you need to have the same spacing following a paragraph even if the paragraph is last item in a visual box or is the intent to define spacing *between* consequtive paragraphs?

**Comment by patrickhlauke** [comment]
that's a misunderstanding of the SC. it doesn't require *authors* to use those styles. the SC says that if a *user* sets their browser to force those particular text metrics (using an extension like stylus, custom css, a bookmarklet, whatever), that the site's content doesn't break.

see the "author responsibility" section in https://w3c.github.io/wcag/understanding/text-spacing.html

**Comment by mikkorantalainen** [comment]
I think the wording of the preceeding paragraph would need some tweaking to make it easier to understand correctly. How about following?

Original:

> In content implemented using markup languages that support the following [text](https://www.w3.org/TR/WCAG21/#dfn-text) [style properties](https://www.w3.org/TR/WCAG21/#dfn-style-properties), no loss of content or functionality occurs by setting all of the following and by changing no other style property:


Improved version:
> In content implemented using markup languages that support the following [text](https://www.w3.org/TR/WCAG21/#dfn-text) [style properties](https://www.w3.org/TR/WCAG21/#dfn-style-properties), no loss of content or functionality shall occur if end users sets all of the following styles overriding author styles and no other changes:
