### ISSUE TITLE
SC 1.4.11: Link to 'use of color' in the caption of Figure 15 leads to Document not Found 

### ISSUE THREAD

**Issue by FerJo** [w3c/wcag#2287]
**Steps to reproduce:**
1. Go to https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html
2. Locate Figure 15
3. In the caption click on the link 'Use of color'

**Result:**
Document not found

**Comment by fstrr** [comment]
[A fix for this was merged in the main branch earlier this month](https://github.com/w3c/wcag/pull/2266). I'm not sure when that will go live.
