### ISSUE TITLE
Minor typo in Understanding Success Criterion 1.4.10: Reflow

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#2294]
Vertically is misspelt for:

https://www.w3.org/WAI/WCAG21/Understanding/reflow
Avoiding scrolling in horizontally and vertically written languages
The success Criterion applies to both horizontally and **verticaly** written languages. Zooming the page for horizontally written languages where pages scroll vertically by default (e.g. English) should not require horizontal scrolling. Zooming the page for vertically written languages which scroll horizontally by default should not require vertical scrolling.

**Comment by alastc** [comment]
Thanks, I've updated that in the 2.1 and main branches, it will appear next time the docs are re-published.
