### ISSUE TITLE
Building the gh-pages on Travis-CI

### ISSUE THREAD

**Issue by nschonni** [w3c/wcag#23]
There are a few options for building out the `gh-pages` branch, but here are a few decisions to make:

1. What content branches should be built out
  - Multiple branches, with sub folders. EX: http://w3c.github.io/wcag/BRANCH_NAME
  - Single branch. EX: http://w3c.github.io/wcag
    - then what branch? master or the working branch?

1. Should the publishing be handled as an Ant target or a Bash script

1. Should history be maintained on the `gh-pages` branch or keep it as a single commit orphan branch

1. How to integrate in the required CSS/JS for the pages

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
