### ISSUE TITLE
Does 3.2.6 Consistent Help allow for content that is under disclosure widget on one page in a set but not another?

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#2303]
Does 3.2.6 Consistent Help allow for content that is under disclosure widget on one page in a set but not another in the same set?

For example, the relative order is the same but on one page you must expand a section for contacting us and on another page it's in the same order but there is no disclosure control - it's just visible.

**Comment by mraccess77** [comment]
I'm only asking for clarification as these came up in real world sites - so I'm just looking for whatever the group agrees on as an answer rather than trying to argue for a specific outcome.

**Comment by mraccess77** [comment]
I'd prefer an understanding document update - but we do have this thread to refer back to as needed if you need to close the issue.

**Comment by alastc** [comment]
Hi Jon,

I'd like to keep normative and understanding updates separate, but we can keep this open if there is a useful update for the understanding doc.

Personally, I'd rather not include something about hiding the link as that undermines the aim. What would the benefit of including an example be?

**Comment by mraccess77** [comment]
Just trying to create testing consistency - so perhaps it could go into a technique's test steps.
