### ISSUE TITLE
Link text incorrect - SC 1.4.5

### ISSUE THREAD

**Issue by bas-man-dev** [w3c/wcag#2304]
On the page explaining Success Criterion 1.4.5 Images of Text there is a link which has incorrect text
---
URL: https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html
Page title: Understanding Success Criterion 1.4.5: Images of Text
-----
**Screenshot:**
![image](https://user-images.githubusercontent.com/73193602/162425091-09c3eb05-681c-49d0-abab-655bc52dd73f.png)

-----
The text displays a link to SC 1.4.4 and says this is Images of Text (No Exception) . This is incorrect as SC 1.4.9 = Images of Text (No Exception)

Although the link does go to SC 1.4.9, the link text is a little confusing. 
---
**Code reference:**
#intent > p:nth-child(7)

```
<p>See also 
   <a href="images-of-text-no-exception">1.4.4: Images of Text (No Exception)</a>.
</p>`
```
---
**Solution:**
Typo fix :
\<a href="images-of-text-no-exception">1.4.9: Images of Text (No Exception)</a>

**Comment by patrickhlauke** [comment]
This was corrected in the repo https://github.com/w3c/wcag/commit/6d82affaf459e635c6c977d5e723cef035007976 / https://w3c.github.io/wcag/understanding/images-of-text.html but not published to https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html

/cc @alastc @michael-n-cooper
