### ISSUE TITLE
WCAG 2.1 url points to WCAG 2.2 techniques

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#2318]
The WCAG 2.1 url points to the WCAG 2.2 techniques https://www.w3.org/WAI/WCAG21/Techniques/

**Comment by alastc** [comment]
@michael-n-cooper It looks like the 2.1 resource isn't using the 2.1 branch?

**Comment by kfranqueiro** [comment]
It appears this was resolved by commit 95e70af5 a few days later but the issue was never closed (probably because it affected a non-main branch).
