### ISSUE TITLE
link rot on SC2.4.2 Page Titled

### ISSUE THREAD

**Issue by idlebee** [w3c/wcag#232]
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html

Under related resources, "Writing Better Web Page Titles" links to a 404.  

Suggest new link: http://usabilitygeek.com/15-title-tag-optimization-guidelines-for-usability-and-seo/

**Comment by awkawk** [comment]
Updated the link for the broken link.

Will discuss adding the new link with the group.

**Comment by awkawk** [comment]
Thanks for the issue.  We have fixed the broken link, and the working group at this time is declining to add the additional link.
