### ISSUE TITLE
2.4.3 focus order with non interactive element with tabindex="0"

### ISSUE THREAD

**Issue by JOP-Temesis** [w3c/wcag#2332]
Hello to all,

In a page where non-interactive elements would have a tabindex="0" attribute you invalidate 2.4.3? 
Even if the focus sequence remains consistent? 

Thank you in advance for your insights :)

**Comment by patrickhlauke** [comment]
See https://github.com/w3c/wcag/issues/1572 and a proposed note https://github.com/w3c/wcag/pull/1643 (waiting for AGWG to make a decision on this)
