### ISSUE TITLE
Advisory techniques - general text in "Expected results"

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag#234]
The general texts for advisory techniques and the general text for sufficient techniques (after the testing procedure) seems to be in all cases identical and states:

"If this is a sufficient technique for a success criterion, failing this test procedure does not necessarily mean that the success criterion has not been satisfied in some other way, only that this technique has not been successfully implemented and can not be used to claim conformance."

And the information that an advisory technique is "just" advisory is only given in overviews like https://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-refs not in the description / the page of an advisory technique itself.

**Comment by joshueoconnor** [comment]
You are right. The same string 'If this is a sufficient technique [...]' seems to be used at the beginning of these paragraphs regardless of whether it is sufficient or advisory. Also from the current format of the techniques it is certainly hard to tell them apart (whether they are advisory or sufficient). Both of these issues will be looked at by the group.

**Comment by alastc** [comment]
I think this has been dealt with as part of the 2.1 updates:

- The advisory/sufficient nature is included at the top in the Applicability section.
- There is no default text appearing after the test procedure relating to sufficient/advisory.

Closing, please re-open if you think this should be addressed in a different way.
