### ISSUE TITLE
F68 needs reference to 1.3.1

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag#237]
[F68: Failure of Success Criterion 4.1.2 due to a user interface control not having a programmatically determined name](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/F68) is listed as a [Common Failure for SC 1.3.1 ](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html#content-structure-separation-programmatic-56-head).

But, when you look directly at the F68 failure technique page, SC 1.3.1 is not referenced in the [F68 Applicability](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/F68#F68-applicability) section.

Please add Success Criterion 1.3.1 to the Applicability section of F68.

**Comment by joshueoconnor** [comment]
Actually this a failure of 4.1.2 and while a case can be made that it does also fail 1.3.1 - the current F68 relates explicitly to 4.1.2, so we will remove the reference to 1.3.1 from the Common failures for SC 1.3.1 that is listed in the understanding document.

**Comment by awkawk** [comment]
This editorial change is complete.
