### ISSUE TITLE
Definition of  "Cognitive function test" complete?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2373]
The [Definition of the Cognitive function](https://w3c.github.io/wcag/guidelines/22/#dfn-cognitive-function-test) test is:

> Cognitive function test
> [New]
> A task that requires the user to remember, manipulate, or transcribe information. Examples include, but are not limited to:
> 
> memorization, such as remembering a username, password, set of characters, images, or patterns. The common identifiers name, e-mail, and phone number are not considered cognitive function tests as they are personal to the user and consistent across websites;
> transcription, such as typing in characters;
> use of correct spelling;
> performance of calculations;
> solving of puzzles.

In the Understanding document there is a mention of:

>  remembering ..., a pattern gesture to perform on a touch screen

Does that fit the definition well? Is it 'contained' in 'remembering information' or does it need to be a bit more specific also covering 'remembering pattern gestures'?

(it is not "manipulate, or transcribe")

**Comment by jake-abma** [comment]
We might also want to add pattern gestures to the "Examples", maybe extend to:

> "A web site uses WebAuthn so the user can authenticate with their device instead of username/password. The user's device could use any available modality. Common methods on laptops and phones are facial-scan, fingerprint, and PIN (Personal Identification Number). The web site is not enforcing any particular use, it is assumed a user will setup a method that suits them."

**Comment by alastc** [comment]
Hi Jake, it got folded into the first item, memorisation.

> memorization, such as ... patterns

I've aligned the examples between the two. We don't have to include examples for everything, if you feel strongly about it please create a PR :-)

**Comment by jake-abma** [comment]
Hey @alastc , I have seen you can 'construct' it with the Examles, but the example doesn't "fit / aligns" with the first sentence / definition.

"A task that requires the user to remember information" is not remembering to applying / perform a pattern. 

So that's why I adder this issue, the example must fit the previous text.

**Comment by jake-abma** [comment]
It's a task to remember how to performance the correct gesture / pattern

**Comment by alastc** [comment]
We had this discussion ages ago and agreed that remembering a pattern is part of memorisation, i.e. remembering. You can't 'perform' a pattern without remembering it.

**Comment by jake-abma** [comment]
Ok, thx

**Comment by mbgower** [comment]
> We had this discussion ages ago and agreed that remembering a pattern is part of memorisation, i.e. remembering. You can't 'perform' a pattern without remembering it.

That can be disputed by studies on habit, where a user with zero functional memorable can nonetheless repeat patterns previously learned. I can abide by the definition, but I do think we're skating on thin ice here.

**Comment by alastc** [comment]
Sure, but the folks at COGA said that patterns were an issue (possibly not for the same people that would struggle with words). So long as it's in the definition, I don't think it's a problem.

**Comment by jake-abma** [comment]
(my 2 cents is it is **not** in the definition sentence, it's in the examples following it, but the example doesn't resonate in de sentence. Like saying "all must go right, and than having an example saying 'go left'")

**Comment by alastc** [comment]
Hi Jake, I'm just trying to work through why you don't think it's part of the initial sentence.

The relevant bits are:
> A task that requires the user to remember, manipulate, or transcribe information. Examples include, but are not limited to:
> - memorization, such as remembering a username, password, set of characters, images, or patterns.

So the initial bit include remember ("to have in or be able to bring to one's mind an awareness of (someone or something from the past").

Wouldn't you say that the act of entering a pre-defined pattern would require you to "bring to one's mind an awareness of" that pattern?

**Comment by jake-abma** [comment]
@alastc it is 'remember information' not just remember, performing the gesture, as @mbgower also mentioned, can be an automated like thing not specifically  'remember information', hope that helps, but maybe you see/read it differently

**Comment by alastc** [comment]
I think maybe how I think about information is wider, I consider the pattern to be information. 

Performing the gesture is physical, but so is typing on a keyboard, what you have to remember is the pattern, just like you have to remember a username.
