### ISSUE TITLE
Correct typo in G144

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#238]
In the Examples for [G144](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/G144), first bullet, end of the example, the last few words say "...who cannot pass the audio CAPTCHA may be able to pass the video CAPTCHA." - the 2nd last word should be "visual" not "video."
There are three other references to "visual" or "visual CAPTCHA" in the technique, and it seems clear this word should be in this occurrence as well. There is no other reference to "video" in the technique

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag/commit/41c8c9e8dc7dcfe5f1995828d3c8ad7cac980093
