### ISSUE TITLE
"single pointer" must be a link to the definition for 2.5.7 Dragging Movements

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2380]
Just as 2.5.1 Pointer Gestures and 2.5.2 Pointer Cancellation have a link to the definition of **single pointer**, 2.5.7 Dragging Movements must also have one

2.5.7 Dragging Movements
https://w3c.github.io/wcag/guidelines/22/#dragging-movements

> All functionality that uses a [dragging movement](https://w3c.github.io/wcag/guidelines/22/#dfn-dragging-movements) for operation can be achieved by a **single pointer** without dragging, unless dragging is [essential](https://w3c.github.io/wcag/guidelines/22/#dfn-essential) or the functionality is determined by the user agent and not modified by the author.

Same for the Understanding doc:
https://w3c.github.io/wcag/understanding/dragging-movements.html

**Comment by alastc** [comment]
Closed by #2390
