### ISSUE TITLE
Include C29 as a technique for 1.4.3 Contrast (Minimum) and related technique for G174

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#239]
[C29: Using a style switcher to provide a conforming alternate version](https://www.w3.org/TR/WCAG20-TECHS/C29), contains specific examples referring to contrast (e.g., "the default presentation of the content does not include sufficient contrast for some users "). At the least, it should be listed as an advisory technique for [1.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) and a related technique for [G174: Providing a control with a sufficient contrast ratio that allows users to switch to a presentation that uses sufficient contrast](https://www.w3.org/TR/WCAG20-TECHS/G174.html)

**Comment by joshueoconnor** [comment]
Thanks - I agree that C29 should be listed against 1.4.3 in some capacity. Note, it is already listed as a related technique for G174. You can see it referred to in the description:

_Note: This technique can be used in combination with a style switching technique to present a page that is a conforming alternate version for non-conforming content. Refer to C29: Using a style switcher to provide a conforming alternate version (CSS) and Understanding Conforming Alternate Versions for more information._

**Comment by mbgower** [comment]
Re: G174 cross reference: yes, C29 is mentioned in the note. It just seems it would be consistent to list it under the Related Techniques section of G174.

**Comment by joshueoconnor** [comment]
As discussed on a call with the OP @mbgower we decided to close this issue and the current reference to C29 as a note in G174 is suffcient
