### ISSUE TITLE
2.4.13 Focus Appearance (Enhanced) still got "Not obscured" 

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2392]
Maybe I missed something or it is not updated yet but  2.4.13 Focus Appearance (Enhanced) still got "Not obscured" as last bullet

https://w3c.github.io/wcag/guidelines/22/#focus-appearance-enhanced

**Comment by jake-abma** [comment]
@mbgower added:

At the AA level, we broke out the Not obscured wording into a separate SC https://w3c.github.io/wcag/guidelines/22/#focus-not-obscured

I will attempt to address this with a single PR that addresses both this and the differences in language between the minimum and enhanced versions raised in https://github.com/w3c/wcag/issues/2205

https://github.com/w3c/maturity-model/issues/59#issuecomment-1121299356

**Comment by alastc** [comment]
This is in the survey for next week: https://www.w3.org/2002/09/wbs/35422/wcag22-focus-appearance-enhanced2/#wbsq53
