### ISSUE TITLE
"points" to "point" in 2.5.1: Pointer Gestures

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2395]
The plural "points" should be "point" (single) in:
https://w3c.github.io/wcag/understanding/dragging-movements.html 

Change:
> For example, two separate single tap or click actions may define the rectangle coordinates or the start and end **points** of a connecting line.

To:
> For example, two separate single tap or click actions may define the rectangle coordinates or the start and end **point** of a connecting line.

**Comment by patrickhlauke** [comment]
debatable. start and end points...two separate points

**Comment by detlevhfischer** [comment]
Agree, I think plural is fine - may I close this (Jake reopen if you insist in needs to be changes...)
