### ISSUE TITLE
Is "Focus" the proper word 2nd example 2.5.7: Dragging Movements

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2402]
https://w3c.github.io/wcag/understanding/dragging-movements.html

Second example goes like:

> A sortable list of elements may, after focussing a list element, provide adjacent controls for moving the element up or down in the list by simply tapping/clicking on those controls.

My thoughts are keyboard focus while this SC is especially not for keyboard, so maybe change to another word?
Something like "pointer hover" or "on the down event" IF this is not against the 'other' SC where you only see action on 'hover' which is a problem of it's own... :-)

> A sortable list of elements may, after pointer hover or the down event on a list element, provide adjacent controls for moving the element up or down in the list by simply tapping/clicking on those controls.

The example in general raises some other questions too, like what/how does the adjacent controls appear? Inside the sortable list elements? Outside addition? If on key down, will they stay visible in a certain place?

We can not rely on 'focus' set by keyboard, and then use mouse to click appearing controls, can we?

**Comment by jake-abma** [comment]
Same for next example:

> A kanban implementation may provide an additional pop-up menu for focused elements

Again, is 'focussed' here a 'single click' to an element? And then it is focussed? Or is it 'activated / active' at that moment?

**Comment by jake-abma** [comment]
in ARIA it is "selected" 

> aria-selected
> The aria-selected attribute indicates the current "selected" state of various widgets.

**Comment by detlevhfischer** [comment]
The idea is tap or click focus to reveal additional controls. Since we are dealing with pointer alternatives it may indeed be clearer nit to speak about focus. One could also mention that keyboard operation may deviate from pointer operation - e.g. you may not need additional controls but simply move the element using arrow keys.

**Comment by detlevhfischer** [comment]
> in ARIA it is "selected"
> 
> > aria-selected
> > The aria-selected attribute indicates the current "selected" state of various widgets.

@jake-abma I do not find this in the understanding doc?

**Comment by detlevhfischer** [comment]
@jake-abma Have a look at PR #2401 to see if that addresses the issue...

**Comment by jake-abma** [comment]
In G219 it says:
https://w3c.github.io/wcag/techniques/general/G219

> A single tap or click may reveal controls (arrows)

This feels wonderful compared to 'focus' :-)
