### ISSUE TITLE
link to definition of dragging movement is plural

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2403]
https://w3c.github.io/wcag/guidelines/22/#dragging-movements
https://w3c.github.io/wcag/guidelines/22/#dfn-dragging-movements
https://w3c.github.io/wcag/techniques/general/G219

Small issue but the link / ID to "dragging movement" is plural.
SC name is 'movements', but definition text is always without the 's', see also G219 Heading or SC text itself:

> All functionality that uses a [dragging movement](https://w3c.github.io/wcag/guidelines/22/#dfn-dragging-movements) for

So in short, the ID should also be #dfn-dragging-movement not #dfn-dragging-movements

**Comment by alastc** [comment]
Hi Jake,

The SC is "dragging movements" plural, applying to all instances.

The defined term is "dragging movement" singular, applying to an instance.

This sounds normal/consistent to an English ear, I'm not sure about others. 

It is similar to "Pointer Gestures", which also references the individual instance as singular as well.

NB: Using the plural would also work in linking to the defined term, it includes plurals.

Overall, I don't think it is worth changing so I'll close this.
