### ISSUE TITLE
H57 and H58 linkrot

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag#241]
There is a broken link to H57 on the Understanding for 3.1.1.  Go to http://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-doc-lang-id.html and click on the link for H57 ( http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H57 ) and experience the "DOCUMENT NOT FOUND".

Same is true for H58 on the Understanding for 3.1.2. Go to http://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-other-lang-id.html and click on the link for H58 ( http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H58 ) and experience the "DOCUMENT NOT FOUND".

Thanks for looking in to this :)

**Comment by joshueoconnor** [comment]
Good catch :-)

**Comment by michael-n-cooper** [comment]
Just checked the above links, they seem ok to me.
