### ISSUE TITLE
Shall we invalidate the absence of a message submission button in a chatbox? 

### ISSUE THREAD

**Issue by JOP-Temesis** [w3c/wcag#2410]
Hi everyone,

Why is there no clear criterion for invalidating the absence of a submit button? I'm thinking for example of submitting a message in a chatbox with the ENTER key or the native keyboard in mobile or for example the search bar in the header of a website. 

Furthermore, it seems to me that the future criterion 3.2.7 of wcag 2.2 only concerns buttons that are not always visible, not the total absence of a submit button 

Thanks,
/J

**Comment by patrickhlauke** [comment]
> Why is there no clear criterion for invalidating the absence of a submit button?

is the absence of a submit button unnecessarily inconveniencing users with disabilities?

**Comment by JOP-Temesis** [comment]
Yes, this was one of the points I was wondering about

**Comment by patrickhlauke** [comment]
My take on this would be: it may be slightly confusing (for all users) if there's no explicit submit button, but it shouldn't impede usage.

For forms that have a text entry field, it's generally understood (anecdotally) that you can hit `Enter` to submit/do something. Even for users that primarily navigate with a mouse/touchscreen, they'd have to use a keyboard (physical or on-screen) to enter something into the text field, so they do have access to an actual `Enter` key.

For forms that don't have text fields (e.g. only `<select>`, radio buttons/checkboxes, etc), presumably the dev would have added some form of `onchange` handler, which then already fails 3.2.2 On Input.

**Comment by fstrr** [comment]
I'd agree with it being confusing for all users if there wasn't a submit button, but wouldn't stop someone using the app assuming that the form can be submitted using the keyboard. I've seen at least one chatbot with a submit button that would only submit the user's input if the button was clicked with a mouse, which fails 2.1.1 Keyboard.

The proposed 3.2.7 criterion has unfortunately been removed from WCAG 2.2.
