### ISSUE TITLE
Last Benefit 3.2.6: Consistent Help not for this SC

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2413]
Last Benefit for 3.2.6: Consistent Help is:

> - Enabling users (especially those with cognitive disabilities) to find solutions while expressing their question using their own words increases their chances of success for completing a task.

While this is true it is not what the SC is about ("expressing their question using their own words" is something else than "occur in the same relative order")

This benefit might be deleted or re-written to cover the benefit applicable to the SC

**Comment by alastc** [comment]
Notes from the backlog meeting:

It is a valid benefit of the last option: A fully automated contact mechanism, e.g.  chatbot.

Just need a little PR to update that benefit.
