### ISSUE TITLE
Making G53 more generic to meet 2.4.4

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#242]
Recommendation: Alter text of G53 technique to be ""G53: Identifying the purpose of a link using link text combined with programmatically determined link context.
Rationale:
Although [G53, "Identifying the purpose of a link using link text combined with the text of the enclosing sentence"](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G53) is offered as a general technique to meet 2.4.4, it arguably fails since a sentence is not programmatically determined (a requirement of 2.4.4); in HTML, for example, there is no tag for sentence, only for paragraph.
In item 8 of [2.4.4 Link Purpose SC](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html), there is a list of items prefaced by "identifying the purpose of a link using link text combined with programmatically determined link context using one of the following techniques:"
If G53 was made slightly more generic, it could encapsulate all the techniques listed in item 8. Suggested text is "G53: Identifying the purpose of a link using link text combined with programmatically determined link context." The technique for <p> ([H78](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H78)) could be expanded to include the text of G53 as it currently stands, i.e.,  that incorporating the context within the same sentence is encouraged, since it provides more precise context.

**Comment by mbgower** [comment]
In case it's not obvious, my main concern is that there is no general technique that states the main goal when the link text alone cannot provide context. G53 seems like the easiest existing technique to modify to provide that clarity, and the rewording does not seem like it would create a situation where anyone currently meeting G53 would fail with the rewording.

**Comment by joshueoconnor** [comment]
Thanks for the suggestion - the working group will review. My own opinion is that this issue of programmatic determination is very well addressed by other techniques already.

**Comment by mraccess77** [comment]
I like having separate techniques for each allowed method sentence, paragraph, table cell, etc.
