### ISSUE TITLE
Change sentence Intent 2.4.12: Focus Not obscured

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2421]
First sentence second paragraph Intent can be rewritten to more clearly indicate the situation:
https://w3c.github.io/wcag/understanding/focus-not-obscured.html

Change:

> Where other content can overlap with a focused item, the focused element should not be hidden.

To:

> Where other content overlaps a focused item, the focused element must not be entirely  hidden.

**Comment by alastc** [comment]
We should avoid RFC language (must/should/may), so I turned it around to:
"Where other content can overlap with a focused item, entirely hiding the focused item means the user does not know where the focus is located."
