### ISSUE TITLE
Change "area" to "size" for last exception  2.5.8 Target Size (Minimum)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2426]
Last exception for 2.5.8 Target Size (Minimum):
https://w3c.github.io/wcag/guidelines/22/#target-size-minimum

> Equivalent: The function can be achieved through a different control on the same page that has an area of at least 24 by 24 CSS pixels.

Now we've had enough discussion about area and what is means... in this case it's not enough to have an area of 576 (24x24) but specifically a minimum of 24 by 24.

So we should not change the word 'size' to 'area' for the exception.

Change:
> Equivalent: The function can be achieved through a different control on the same page that has an area of at least 24 by 24 CSS pixels.

To:
> Equivalent: The function can be achieved through a different control on the same page that has a size of at least 24 by 24 CSS pixels.

**Comment by patrickhlauke** [comment]
doesn't this mean exactly the same? if i have a control with a **size** of 24 by 24, it has an **area** of 24 by 24. in fact the latter is more ambiguous, because an **area** can be achieved by various different measures (576x1 would still have an **area** of 576 CSS px^2), whereas talking about the **size** gives indication of width and height

**Comment by jake-abma** [comment]
@patrickhlauke wrote: 

> whereas talking about the size gives indication of width and height

This is exactly what is needed, not the area of 576, thus need a change

**Comment by patrickhlauke** [comment]
doh, managed to read it completely opposite to what you meant. so yes, agree. oops

**Comment by alastc** [comment]
I think this discussion came up before and we short-cutted the issue by saying:

> The function can be achieved through a different control on the same page that meets this criterion.

So closing...
