### ISSUE TITLE
Adding of exceptions at explaining them in Understanding 

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2429]
In Understanding / Intent there is an explanation for all exceptions:
https://w3c.github.io/wcag/understanding/target-size-minimum.html

> The requirement is for targets to be at least 24 by 24 CSS pixels in size. There are five exceptions...:

The exception itself is not mentioned at the beginning, it would be recommended to do so for clearance on what exception is talked about

Add all 5 to the beginning of the explanation

> 1. Spacing...
> 2. Inline...
> 3. Essentail...
> 4. User agent control...
> 5. Equivalent...

**Comment by jake-abma** [comment]
(please note I also suggested to change order...! https://github.com/w3c/wcag/issues/2425)

**Comment by bruce-usab** [comment]
@jake-abma , I will take a run at Understanding for 2.5.8 by this time next week.
