### ISSUE TITLE
Consider language changes in Sufficient Techniques section of 1.3.2 SC for item 1

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#243]
Recommendation:
Modify item 1 in 1.3.2 to read "[G57: Ordering the content in a meaningful sequence](http://www.w3.org/TR/WCAG20-TECHS/G57) for all relevant content"
Rationale:
The language of the description in [1.3.2 Meaningful Sequence](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html) is "_When_ the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined." (My emphasis.) It's a conditional criterion.
However, the first item in the sufficient techniques appends the text "For all the content in the Web page" to [G57: Ordering the content in a meaningful sequence](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G57), making it applicable to _all_ content. There are many situations where a reading order does not alter the meaning, and it is not desirable to impose one.  Replacing this appended text with "for all relevant content" would bring the first technique into agreement with the conditional criterion of the SC.

**Comment by mbgower** [comment]
This may be better titled "consider language changes in Sufficient Techniques section of 1.3.2 SC for item 1, since this is actually about changing the language in the SC, not in the G57 technique itself.

**Comment by joshueoconnor** [comment]
That seems like a reasonable suggested change to the title of the technique - the issue of whether content is relevant or not is implicit but there is nothing wrong with firming this up within the language of the technique itself. I think I would prefer "G57: Ordering relevant content in a meaningful sequence" however but the group will review - thanks.

**Comment by mbgower** [comment]
> That seems like a reasonable suggested change to the title of the technique - the issue of whether content is relevant or not is implicit... 

To clarify, I think the title of G56 is fine; I agree that content's relevance is implicit. It's the text that is _appended_ to the title in item 1 of the sufficient techniques in 1.3.2 that causes misdirection. I renamed this issue to try to clarify that. Here is the proposed change for 1.3.2:
Replace

> 1. [G57: Ordering the content in a meaningful sequence](http://www.w3.org/TR/WCAG20-TECHS/G57) for all the content in the Web page 

with

> 1. [G57: Ordering the content in a meaningful sequence](http://www.w3.org/TR/WCAG20-TECHS/G57) for all relevant content

**Comment by awkawk** [comment]
The technique isn't normative, it is just highlighting one way to be sure that you have met 1.3.2.

If you order all content in a meaningful sequence, you meet 1.3.2.  I think that the test procedure does the same thing as is being suggested, and it is important to focus on the "a correct reading sequence" as there may be more than one correct linearized sequence for a given visual layout.

I think this title change would cause more confusion.

**Comment by mbgower** [comment]
Just to make sure we're talking about the same thing, I am not advocating altering the title of the technique. I am advocating a reword in the SC. The reason for this is simple. The way the language in the SC is written, I have to apply G57 to the entire page, even if only a portion of the page has content that has meaningful sequence.

**Comment by mraccess77** [comment]
Renaming this technique would be confusing.  We can't change the name of the SC.  This SC and technique allow for flexibility in different ways to order content that is not relevant to the page.

**Comment by mraccess77** [comment]
If we are asking for a survey vote can the working group member working the issue please clearly state using "proposal:" followed by the proposed response to the commenter.

**Comment by joshueoconnor** [comment]
Discussed on WG call - action on me to look at meaningful sequence Created ACTION-332 - Look at meaningful sequence may need an update [on Joshue O Connor - due 2016-11-15].

**Comment by joshueoconnor** [comment]
I'm happy to work with you @mbgower on this :-)

**Comment by alastc** [comment]
Did anything happen here? Doesn't seem like a high priority issue, marking as inactive... close soon.
