### ISSUE TITLE
Proposal to 'link' to blocks of text 2.5.8 Target Size (Minimum) AND 2.5.5 Target Size (Enhanced)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2430]
I know we had a definition for blocks of text, but without the 's' at the end of blocks, I didn't find the definition easily, people might completely miss it and have no clue what we mean...
https://w3c.github.io/wcag/guidelines/22/#target-size-minimum

Proposal: 'link' definition to SCs 2.5.8 Target Size (Minimum) AND SC 2.5.5 Target Size (Enhanced)

> Inline: The target is in a sentence or [block of text](url);

**Comment by alastc** [comment]
The SC has changed to remove the 'blocks of text', so closing.
