### ISSUE TITLE
'successfully navigate' to 'more easily proceed' Intent 3.3.9: Redundant Entry

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2436]
First sentence Intent 3.3.9: Redundant Entry:
https://w3c.github.io/wcag/understanding/redundant-entry.html

> The intent of this Success Criterion is to ensure that users can successfully navigate multi-step processes. It reduces cognitive effort where information is asked for more than once during steps in a process. It also reduces the need to recall information provided in a previous step.

1. I don't think 'navigate' is the proper way to describe the intent. It's more like 'more easily proceed'
2. 'reduces cognitive effort' seems the same as 'reduces the need to recall information' but illustrated as an 'extra' thing by the word 'also'

Change:
> The intent of this Success Criterion is to ensure that users can successfully navigate multi-step processes. It reduces cognitive effort where information is asked for more than once during steps in a process. It also reduces the need to recall information provided in a previous step.

To:
> The intent of this Success Criterion is to ensure that users can more easily proceed multi-step processes. It reduces cognitive effort by reducing the need to recall information asked for more than once during steps in a process.

**Comment by bruce-usab** [comment]
Editorial:  proceed multi-step processes.  Proceed through multistep processes?  Progress a multistep process?

I am okay with "navigate" even though it is different than navigating a webpage or menu.  It seems to me that proceed/progress/process are all very similar and linear, and "navigate" reflects that maybe the processes are not so straightforward to work through.
