### ISSUE TITLE
Add H97 to 2.4.1 Bypass Blocks

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#244]
Recommendation: Add H97 as a bulleted item in Sufficient Techniques item 2 in 2.4.1 Bypass Blocks.

[H97: Grouping related links using the nav element ](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/H97) contains  phrases such as " Use of this markup can make groups of links easier to locate and skip past by users of assistive technology such as screen readers. "
As such, it is clearly a technique that can be used to meet [2.4.1 Bypass Blocks](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html). The second item in the sufficient techniques for 2.4.1 covers "Grouping blocks of repeated material in a way that can be skipped". It list a number of techniques, and H97 makes sense to be added to that group.

**Comment by joshueoconnor** [comment]
Agreed #Add h97 to 2.4.1 d110952 #Applicability of h97 to 2.4.1 9cce010

**Comment by DavidMacDonald** [comment]
Most users of AT don't want to skip TO the NAV they want to slip over it. We already have ARIA 11 which is to use Landmarks...  I don't think this limited example of a landmark is going to add much... if anything we want to get DEV to use <main> ... they don't do that much but are almost always using <nav> these days.

**Comment by awkawk** [comment]
@DavidMacDonald some AT allow users to skip to next different element also, so it could help skip past or skip to.

**Comment by awkawk** [comment]
https://github.com/w3c/wcag/pull/250

**Comment by awkawk** [comment]
WG accepted H97 as an advisory technique for 2.4.1 on the telecon. CfC to come next.
