### ISSUE TITLE
Does 2.4.14 Page Break Navigation pass Acceptance Criteria Nr.1? Remove?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2444]
Does 2.4.14 Page Break Navigation pass Acceptance Criteria Nr.1? Remove?
https://w3c.github.io/wcag/understanding/page-break-navigation.html

Based on the first sentence AND third paragraph of the Intent I question if 2.4.14 Page Break Navigation passes Acceptance Criteria Nr.1. If not, the SC must be removed (or intent clearly re-written!)

First Sentence:

> The purpose of this Success Criterion is to let all users locate the same content using [page break locators](https://w3c.github.io/wcag/understanding/page-break-navigation.html#dfn-page-break-locators), regardless of whether they use print or digital versions of a publication.

Please note => "**all users**"

Third paragraph:

> Digital publishing, while providing greater access to information, threatens the ability for everyone to locate information by page number. This is because screen size and user preferences can alter content. In one implementation, a screen of content may be considered a page, and the pagination may be updated to match the number of screens of content on a specific device. In another, the page numbering may cease to be used at all in a digital version. In either case, a user whose page numbering no longer matches the printed version cannot easily locate information by page number references.

Please note => **"the ability for everyone"** and then it mentioned all kind of possibilities ALL USERS are affected..

Thus breaking with the First Rule Of WCAG 2.2 Success criterion acceptance requirements:
https://www.w3.org/WAI/GL/wiki/WCAG_2.2_Success_criterion_acceptance_requirements

> Success Criteria shall:
- > Address a situation where a user with a disability will be disproportionately disadvantaged (as compared to a user without a disability) if the criterion is not met.

So if all users have problems without "page break locators" it is a usability problem, not one for a SC

**Comment by alastc** [comment]
Hi Jake,

It means "all users" in that currently _most_ can do that, but not _all_ because some people have disabilities requiring adaptation of the display.

So if the SC is applied, then _all_ users can do it...

**Comment by jake-abma** [comment]
@alastc please respond to the third paragraph... it clearly states (and is applicable to all users as mentioned in sentence 1) **" threatens the ability for everyone to locate information by page number"** by different screen sizes, preferences, and cease to to be used...

**Comment by alastc** [comment]
It's the same concept, it is speaking of "all users" because if people with low-vision can't do it, that's not all users.

I see the confusion, but it's not a case of removal, it's an editorial point.

**Comment by bruce-usab** [comment]
@jake-abma can you suggest an edit that would make you happier with the prose?  I totally agree with @alastc that by meeting this SC authors are ensuring that canonical print-page-number are available to all (and not just people with good vision).

Editorial nit:
> and [print] page numbering may cease to be used at all

That would be a good outcome IMHO, so I am not sure why it's included or even hinted at.  The status quo is more like:

> and it is important to maintain magical thinking/reverence for dead-tree versions of content because reasons

**Comment by melaniephilipp** [comment]
Piggybacking on Jake's issue (let me know if this should be a separate one)... the first sentence (actually pretty much the entire Understanding doc) makes it sound like the SC is requiring that page break locators be put into qualifying documents. 

> The purpose of this Success Criterion is to let all users locate the same content using [page break locators](https://w3c.github.io/wcag/understanding/page-break-navigation#dfn-page-break-locators), regardless of whether they use print or digital versions of a publication.

But in reality, the SC is only requiring that IF programmatically determinable page break locators exist, THEN a navigation mechanism must be present. Only the middle of the 3rd note at the very bottom of the Intent section hints otherwise. 

> This Criterion applies to pages which include elements with the doc-pagebreak semantic role and an associated ID attribute... This would not apply to an element which visually shows a page number, unless it also has a recognized role.

Can we please make it clear from the start that this SC is not requiring that page break locators exist? Similar to Consistent Help where we say in the opening sentence of the Intent:

> The intent of this Success Criterion is to ensure users can find help for completing tasks on a Web site, **when it is available.**

AND later in Consistent Help

> It is not the intent of this Success Criterion to require authors to provide help / access to help. The Criterion only requires that when one of the listed forms of help is available across multiple pages that it be in a consistent location.

Thank you!

**Comment by fstrr** [comment]
Closing as SC was removed.
