### ISSUE TITLE
Add 'is' to first exception 2.4.11 Focus Appearance (Minimum)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2447]
Add 'is' to first exception 2.4.11 Focus Appearance (Minimum)
https://w3c.github.io/wcag/guidelines/22/#focus-appearance-minimum

2.4.11 first exception reads a bit 'off', doesn't flow well, adding the word 'is' might fix this

Change:

> An area of the focus indicator meets all the following:
> At least as large as the area of a 1 [CSS pixel](https://w3c.github.io/wcag/guidelines/22/#dfn-css-pixels) thick [perimeter](https://w3c.github.io/wcag/guidelines/22/#dfn-perimeter) of the unfocused component, or is at least as large as a 4 CSS pixel thick line along the shortest side of the [minimum bounding box](https://w3c.github.io/wcag/guidelines/22/#dfn-minimum-bounding-box) of the unfocused component, and

To:

> An area of the focus indicator meets all the following:
> **Is at** least as large as the area of a 1 [CSS pixel](https://w3c.github.io/wcag/guidelines/22/#dfn-css-pixels) thick [perimeter](https://w3c.github.io/wcag/guidelines/22/#dfn-perimeter) of the unfocused component, or is at least as large as a 4 CSS pixel thick line along the shortest side of the [minimum bounding box](https://w3c.github.io/wcag/guidelines/22/#dfn-minimum-bounding-box) of the unfocused component, and

**Comment by alastc** [comment]
I think the [updated SC text ](https://www.w3.org/TR/WCAG22/#focus-appearance)meets this. One of them starts 'is', the others are 'has'.
