### ISSUE TITLE
Delete Silverlight content

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#2448]
Silverlight has been EOLd, so we should remove related content, which I'll do.

**Comment by fstrr** [comment]
@alastc There are an awful lot of empty links in many of the Understanding documents. For example, in Non-Text Content, there are these:

```html
<li>
  <a href="https://www.w3.org/WAI/WCAG21/Techniques/html/H37" class="html"></a>
</li>
<li>
  <a href="https://www.w3.org/WAI/WCAG21/Techniques/html/H53" class="html"></a>
</li>
<li>
  <a href="https://www.w3.org/WAI/WCAG21/Techniques/html/H86" class="html"></a>
</li>
<li>
  <a href="https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF1" class="pdf"></a>
</li>
```
The links are there in the [live document](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html), so I'm assuming that the build process adds in the document title. Is that correct?

**Comment by alastc** [comment]
Yep, the build process grabs the title of the page (I think) to fill it in.

**Comment by fstrr** [comment]
Great. Thanks. There are an awful lot of [references to Silverlight](https://github.com/w3c/wcag/search?q=silverlight) in the site. For example: there are 84 references to it in this [wcag2.json file](https://github.com/w3c/wcag/blob/main/wcag20/sources/misc/wcag2.json). If I delete everything, that's going to remove Silverlight from everywhere. Do we want that or do we just want it removed from the current [Techniques folder](https://github.com/w3c/wcag/tree/main/wcag20/sources/techniques)?

**Comment by alastc** [comment]
Focus on the technique and understanding docs.

@michael-n-cooper, if we remove the silverlight techniques, do they need removing from the json file?
