### ISSUE TITLE
Add <code> example to H49 technique

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#245]
[H49: Using semantic markup to mark emphasized or special text](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/H49) would benefit from an example showing how to use the `code` element for code fragments. This could go in as the next subheading in the Examples section. Suggested wording is: 
### Example 4

Use the `code` element to provide visual emphasis for code rendered on a web page. Text that has a fixed width `tt` provides visual emphasis, but that information is not available to assistive technology. The next example shows how to use the `code` element to emphasize a code block embedded in text.

```
<code>
#trial {
background-image: url(30daytrial.jpg);
background-repeat: no-repeat;
background-position: left top;
padding-top: 68px;
}
</code> 
```

**Comment by patrickhlauke** [comment]
Is `<code>` announced any more semantically by AT than `<tt>`? If not, I'd remove the whole "Text that has a fixed width..." sentence...

**Comment by mbgower** [comment]
With out-of-the-box default settings, I do not know of a screenreader that will announce style change on pretty about anything (including <strong>, < emphasis>, <code>, <q>, etc.) VoiceOver breaks text in different styles into separate chunks, but I haven't found a way of having the style announced. Many screenreaders can be modified to announce some style changes. For instance both JAWS and NVDA will announce some attributes like underline or italics or bold changed by different styles. NVDA announces text within code tags as being in 10pt type (as opposed to the 12pt surrounding text). It doesn't mention fixed width or anything. Again, the user needs to infer why, which is similar to how a visual users decides what a style change. But with the reduced info from the screenreader, it's less information than is available visually. All that said, I'm not sure that _how_ a screenreader is implemented is a conclusive argument for what guidance should be provided for proper markup.

**Comment by patrickhlauke** [comment]
> I'm not sure that how a screenreader is implemented is a conclusive argument for what guidance should be provided for proper markup.

and that was not what i was getting at. in short: i agree that an example using `<code>` would be great...but leave out the sentence "Text that has a fixed width `tt` provides visual emphasis, but that information is not available to assistive technology." since it implies that `<code>`, as opposed to `<tt>`, makes information available to AT, when in fact it appears that that's not true.

**Comment by mbgower** [comment]
Thanks for that clarification. With those changes, and a bit more language, the example would now read:
### Example 4
Use the `code` element to provide visual emphasis for code rendered on a web page. The next example shows how to use the `code` element to emphasize a code block embedded in text (in this case, a block showing some CSS styling for an element with an id="trial").
```
<code>
#trial {
background-image: url(30daytrial.jpg);
background-repeat: no-repeat;
background-position: left top;
padding-top: 68px;
}
</code> 
```

**Comment by joshueoconnor** [comment]
Thanks for that @mbgower - I agree with Patrick that it is useful. We will survey this code example with the group.

**Comment by awkawk** [comment]
So the change here is to add an example 5? or to replace example 4?

**Comment by patrickhlauke** [comment]
I believe it's supposed to be example 5 ... but note that currently there's a nesting error in the markup that makes current example 4 appear as part of example 3 (which is probably what caused the confusion here)

![capture](https://cloud.githubusercontent.com/assets/895831/19690736/84cd09a8-9ac9-11e6-95fe-43c5c036abac.PNG)

**Comment by awkawk** [comment]
I don't see the nesting error.  There is an example 4.

**Comment by patrickhlauke** [comment]
Can you see the screenshot i added in my comment above? Example 4, Resources etc appear visually to be part of Example 3...

**Comment by patrickhlauke** [comment]
(screenshot likely only shows up if you actually visit github - won't show up in email)

**Comment by awkawk** [comment]
Ah, yes, but not in the current version: http://www.w3.org/TR/WCAG20-TECHS/H49.html

**Comment by patrickhlauke** [comment]
Oh, apologies, I followed the link in the thread starter https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/H49

**Comment by mbgower** [comment]
> So the change here is to add an example 5? or to replace example 4?

Sorry for confusion. This is to add a new example.

**Comment by awkawk** [comment]
Pull request:
https://github.com/w3c/wcag/pull/250

File changes: 
https://github.com/w3c/wcag/pull/250/files?diff=split

**Comment by awkawk** [comment]
Pull request 250 merged.
