### ISSUE TITLE
H62 (using the ruby element) needs updated code examples

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#2454]
The HTML spec has changed and [H62](https://www.w3.org/WAI/WCAG21/Techniques/html/H62) references an `rb` element that doesn't exist any more. The examples need re-writing and the Resources links need updating.

**Comment by fstrr** [comment]
@MakotoUeki Hey :) Could you possibly help update this document? If you can't, do you know someone who could help? Thanks.

**Comment by fstrr** [comment]
@momdo Hi :) Is there any chance you could help update this document? The HTML spec for Ruby-related elements has changed, so the document needs updating, I don't know Japanese, and don't want to mess it up!

**Comment by momdo** [comment]
@fstrr 

Exactly, `rb` element is obsolete on current HTML spec. However:

- As [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb#browser_compatibility), most modern browsers partially support `rb` element.
- [Nu Html Checker](https://validator.w3.org/nu/) doesn't detect `rb` element as invalid.
- W3C and WHATWG have signed [Agreement on HTML Ruby Markup](https://www.w3.org/2022/02/ruby-agreement).
    - `rb` element is expected to come back in the near future.

So, at least I feel that we don't need to change the code examples on H62 immediately, it is better to preferentially update other techniques which have old contents.

By the way, if you need to update this technique right now, you can simply remove `rb` element from the code examples.
