### ISSUE TITLE
"user-agent" Vs. "user agent" for SC itself AND Understanding 2.4.11: Focus Appearance (Minimum)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2460]
"user-agent" Vs. "user agent" Understanding 2.4.11: Focus Appearance (Minimum)
https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html

"user agent" is also written as "**user-agent**" in the same text, the definition writes it as "**user agent**" (https://w3c.github.io/wcag/guidelines/22/#dfn-user-agents)

We should be consistent in all our docs to have the same writing style, thus changing "user-agent" in "user agent" (?!)

ALSO the SC itself is different from other places...

**Comment by jake-abma** [comment]
@patrickhlauke did you see the SC text itself also contains user-agent... also the Note in "large scale (text)" has one... making it a normative change... always fun...

**Comment by patrickhlauke** [comment]
normative perhaps, but non-substantive ;)

**Comment by jake-abma** [comment]
Ok, but a change in the SC of 2.4.11: Focus Appearance (Minimum) itself would be preferred now 'as we still can', agreed?

First exception:

> Exceptions:
> The focus indicator is determined by the **user-agent** and cannot be adjusted by the author, or

**Comment by patrickhlauke** [comment]
have you looked at my PR? https://github.com/w3c/wcag/pull/2461/files

**Comment by jake-abma** [comment]
ahh, ok, 😘 😘 😘
