### ISSUE TITLE
 Change Focus Visible (enhanced) to Focus Appearance (Minimum) in Understanding 2.4.13: Focus Appearance (Enhanced)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2473]
Change Focus Visible (enhanced) to Focus Appearance (Minimum) in Understanding 2.4.13: Focus Appearance (Enhanced)
https://w3c.github.io/wcag/understanding/focus-appearance-enhanced.html

Change:

> In relation to **Focus Visible (enhanced)** this criterion:
> 
> Expands the minimum area to 2 CSS pixels around the perimeter.
> Increases the change of contrast to 4.5:1.
> Does not allow for any part of the focus indicator to be obscured by other, author-created content.
> The other aspects of the Success Criterion are the same as **Focus Visible (Minimum)**.

To:

> In relation to **Focus Appearance (Minimum)** this criterion:
> 
> Expands the minimum area to 2 CSS pixels around the perimeter.
> Increases the change of contrast to 4.5:1.
> Does not allow for any part of the focus indicator to be obscured by other, author-created content.
> The other aspects of the Success Criterion are the same as **Focus Appearance (Minimum)**.

**Comment by alastc** [comment]
SC removed, so closing.
