### ISSUE TITLE
Old techniques to remove

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#2482]
There are many links to the HTML 4.01 spec, references to elements that aren't part of the current spec, etc.

**Comment by fstrr** [comment]
The [`summary` attribute for tables is obsolete](https://html.spec.whatwg.org/multipage/obsolete.html#attr-table-summary), and is marked as such in [H73](https://www.w3.org/WAI/WCAG21/Techniques/html/H73.html), so I'm proposing to delete that document.

Does anyone have any opinions on doing that?

**Comment by fstrr** [comment]
[Using functions of the Document Object Model (DOM) to add content to a page](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR21) seems to be less about the the title of the document and more about certain scripting functionality that the author thinks should be avoided. For example:

> "…and the innerHTML property is not part of the DOM specification and thus should be avoided."

and the Procedure, which consists of one item:

> "Examine the source code and check that the new content is not created using document.write(), innerHTML, outerHTML, innerText or outerText."

As such:

1. Do we still this document?
2. If we do, then updating it to bring it up to date and re-writing the Procedure seems to be the way to go.

**Comment by alastc** [comment]
Noting that the WAI tutorial references H73, so we should create an issue for the tutorials, and remove Approach 4. 
https://www.w3.org/WAI/tutorials/tables/caption-summary/#using-the-summary-attribute

**Comment by alastc** [comment]
- [H4]( https://www.w3.org/WAI/WCAG21/Techniques/html/H4), is not referenced, and not good practice for manipulating focus order.

**Comment by fstrr** [comment]
@alastc here's an [initial commit of updates](https://github.com/w3c/wcag/compare/main...issue-2482).

**Comment by JAWS-test** [comment]
longdesc is still valid: https://www.w3.org/TR/html-longdesc/

Discussion about this: https://github.com/w3c/wcag/issues/950

**Comment by fstrr** [comment]
According to this [Memorandum Of Understanding](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html) from 28th May, 2019:

> "HTML and DOM shall be developed principally in the WHATWG … W3C intends to give input to and endorse WHATWG Review Drafts to become W3C Recommendations, through the W3C Process from Candidate Recommendation (CR) through Proposed Recommendation (PR) to Recommendation (REC). Our Design Goal is that the W3C CR, PR, and REC, and the WHATWG Review Draft are the same document."

As the longdesc attribute document you link to is from 2015, and the W3C is only endorsing WHATWG Review Drafts to become W3C Recommendations, I'd argue that `longdesc` is obsolete.

[I ran an updated test](https://codepen.io/fstrr/full/jOZZQMP), and there is still some support for the attribute. That said, as the attribute, which has never been well supported, is now obsolete, H45 should be removed.

**Comment by fstrr** [comment]
[H60 (Using the link element to link to a glossary)](https://www.w3.org/WAI/WCAG21/Techniques/html/H60) can be deleted as ["glossary" isn't a link type in the HTML living standard](https://html.spec.whatwg.org/multipage/links.html#linkTypes).

**Comment by fstrr** [comment]
[H46 (Using noembed with embed)](https://www.w3.org/WAI/WCAG21/Techniques/html/H46.html) can be deleted as [`noembed` is obsolete](https://html.spec.whatwg.org/multipage/obsolete.html#noembed).

**Comment by fstrr** [comment]
[H70 (Using frame elements to group blocks of repeated material)](https://www.w3.org/WAI/WCAG21/Techniques/html/H70) can be deleted as [`frameset` is obsolete in the HTML Living Standard](https://html.spec.whatwg.org/multipage/obsolete.html#frameset).

**Comment by fstrr** [comment]
I think [H75 (Ensuring that Web pages are well-formed)](https://www.w3.org/WAI/WCAG21/Techniques/html/H75) can be deleted. It's applicable to "Any XML-based markup languages" rather than web pages.

**Comment by fstrr** [comment]
[PR opened to remove reference to H73 (summary attribute)](https://github.com/w3c/wai-tutorials/pull/674)

**Comment by fstrr** [comment]
Closing this issue as some techniques have been removed and I've moved others to new, separate issues.
