### ISSUE TITLE
Generate valid HTML5 with XSLT

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#253]
According to <a href="https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE#valideHTML">Pubrules</a>, we need to generate valid HTML5.

Thus, at least, we should modify following points:
- Omitting XML Declaration
- Changing DOCTYPE
- Using `<abbr>` instead of `<acronym>` (especially in the copyright section)
- Fixing `<script>` tag (about fixup.js)

**Comment by awkawk** [comment]
The 2.1 spec is valid HTML5: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FTR%2FWCAG21%2F

**Comment by momdo** [comment]
@awkawk 

However, at least, Techniques & Understanding are missing doctype at this time.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fwcag%2Ftechniques%2F
https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fwcag%2Funderstanding%2F

**Comment by awkawk** [comment]
These aren't subject to the pubrules. I'll have @michael-n-cooper look at this but this is a low priority.
