### ISSUE TITLE
Working Draft of WCAG 2.2 has links directing to WCAG 2.1

### ISSUE THREAD

**Issue by eyalito** [w3c/wcag#2537]
[Working Draft of WCAG 2.2](https://www.w3.org/TR/WCAG22/)

In section 3 "WCAG 2.2 Supporting Documents", links to 'How to Meet WCAG 2.2', 'Understanding WCAG 2.2', and 'Techniques for WCAG 2.2' all directs to WCAG 2.1.

**Comment by alastc** [comment]
This is [correct on the main branch](https://github.com/w3c/wcag/blob/57b6dd502415cb4b7327835b506dc35e024e1836/guidelines/index.html#L66), it will show up in the final version.
