### ISSUE TITLE
Question on technique H44: Using label elements to associate text labels with form controls

### ISSUE THREAD

**Issue by sarasuri** [w3c/wcag#2538]
On the [H44](https://www.w3.org/WAI/WCAG21/Techniques/html/H44) technique, under description, it says "The id attribute may have the same value as the name attribute, but both must be provided, and the id must be unique in the Web page." 

Question is if the the "input" element doesn't provide the "name" attribute (see code snippet below), is it considered as a WCAG failure?
`<div><label for="lname1">Last name</label><input id="lname1" type="text" minlength="2" /></div>`
Further, why the "name" attribute must be provided along with the "id" attribute?

**Comment by patrickhlauke** [comment]
and if your last question is "why would you provide a `name` attribute in the first place?" ... that's basic HTML. without a name, it won't be part of the form submission (unless you're doing some weird custom javascript submit action anyway, rather than a regular GET or POST form submission)

**Comment by MelSumner** [comment]
@sarasuri I think you're mixing up Success Criteria (essential) and Techniques (meant to be informative and helpful) -- see the section [Techniques are Informative](https://www.w3.org/WAI/WCAG21/Understanding/understanding-techniques#:~:text=accessibility%20support.-,Techniques%20are%20Informative,-Techniques%20are%20informative), that may prove useful. 

I think the technique is trying to be helpful by overstating what might be obvious to some, but not obvious to others, that's all.

**Comment by JAWS-test** [comment]
@sarasuri Please look in the chapter "Test" at H44 (https://www.w3.org/WAI/WCAG21/Techniques/html/H44#tests): there is nothing about name attribute

**Comment by mmiron-HC** [comment]
@JAWS-test  in the Technique under Description it clearly states "The id attribute may have the same value as **the name attribute,** but both must be provided, and the id must be unique in the Web page."

**Comment by patrickhlauke** [comment]
note that techniques are informative, not normative. and most of them are ancient
