### ISSUE TITLE
1.4.1 Should we "use of color" for table cells?  

### ISSUE THREAD

**Issue by JOP-Temesis** [w3c/wcag#2541]
Should we distinguish between cells?

Should we distinguish th from td?

or should we only distinguish th from td in complex cases like _exemple 2 Table with an offset column of header cells_ (see https://www.w3.org/WAI/tutorials/tables/two-headers/) ? 
the positioning of th being equivocal for simple tables 

thank you in advance,

/J

**Comment by patrickhlauke** [comment]
now *if* you were using colour to highlight one specific cell for whatever reason, or to differentiate different cells, then yes, that would fail 1.4.1 ... there was a recent discussion along those lines on webAIM https://webaim.org/discussion/mail_thread?thread=10501 (though this also touched on many other aspects)

**Comment by JOP-Temesis** [comment]
In this case, what's your opinion ? 

![image](https://user-images.githubusercontent.com/102220624/177958509-7271bc55-32cc-4408-9129-9104ee8b59a6.png)

**Comment by patrickhlauke** [comment]
the convention that the first column and first row generally contains header cells is well understood and established, so i don't think there would be any problem even *if* they weren't bold. of course you're not using colour here at all, so 1.4.1 wouldn't apply either way? unless you mean the zebra stripes, which again are just a little visual aid and don't actually convey any content/meaning, so irrelevant from a 1.4.1 point of view

**Comment by JOP-Temesis** [comment]
(thank you ! I think I've earned my beer... _walks into his office: "so who was right?"_)

**Comment by bruce-usab** [comment]
> the convention that the first column and first row generally contains header cells is well understood and established, so i don't think there would be any problem even if they weren't bold.

Agreed, so much so that I am also of the opinion that items in the first column maybe do not even need to be TH or use SCOPE.  Others disagree, but that is how I (personally) make peace with spreadsheets and Word processors.  It is the convention, and well understood.

But @JOP-Temesis with your example, what if there are several more columns?  Does the entry in row one, column one, label the top row or the left-most column?

**Comment by JOP-Temesis** [comment]
@bruce-usab I hope the design would fit in a classic two-entry table 

![image](https://user-images.githubusercontent.com/102220624/177997054-92ef27b9-c3bd-4318-ac6b-a1e816b45bc8.png)

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please start a new discussion.
