### ISSUE TITLE
Technique G134: More Outdated Links

### ISSUE THREAD

**Issue by cstrobbe** [w3c/wcag#2544]
The following links in technique G134 appear to be outdated:

* [WDG HTML Validator](http://www.htmlhelp.com/tools/validator/) by the Web Design Group: "403 Forbidden"; this validator is probably no longer online.
* [Offline HTMLHelp.com Validator](https://www.htmlhelp.com/tools/validator/offline/index.html.en): same issue as above.
* [Modifying Dreamweaver to Produce Valid XHTML](http://alistapart.com/article/dreamweaver/) is an article from 2002 and is likely no longer applicable to current versions of Dreamweaver.
* "XHTML-Schemata für FrontPage 2003 und Visual Studio .NET" by Christoph Schneegans is probably no longer applicable to current versions of Visual Studio.
* [Nvu](http://www.nvu.com/) has not seen any releases since 2005; its successor Kompozer has not seen any releases since 2010.
* W3C has not released any new versions of [Amaya](https://www.w3.org/Amaya/) since 2012.
* [SCREEM](http://www.screem.org/) has not seen any new releases since 2006.
* Emacs nXML Mode: Yahoo deleted all Yahoo Groups some time ago, but more recent documentation is available in the [Emacs Wiki](https://www.emacswiki.org/emacs/NxmlMode).

(This issue is a sequel to https://github.com/w3c/wcag/issues/657.)

**Comment by alastc** [comment]
Possibly one for @fstrr's big PR?

**Comment by fstrr** [comment]
Ooh, chunky. I can update at that page. Do we need the XML content in there any more or can we remove that?

**Comment by cstrobbe** [comment]
@fstrr Since it is a general technique and not an HTML technique, I wouldn't remove the links about validating XML that still work.

**Comment by fstrr** [comment]
@cstrobbe good point. thanks.

**Comment by fstrr** [comment]
This is done. Details in the linked issue, which is lengthy. I:

1. Removed references to XHTML.
2. Updated links listed in this issue.
3. Double-checked links in issue 657.
4. Updated links that now support https.
5. Corrected a typo in Chris Pederick’s name.
6. Marked up headings as headings.
7. Removed a couple of links to tools that haven’t been updated in many years.

**Comment by cstrobbe** [comment]
I am closing this issue **in protest against the [W3C's allowing overlay vendors to set up a community group](https://adrianroselli.com/2022/09/accessibility-at-the-edge-w3c-cg-is-an-overlay-smoke-screen.html)**. Overlay vendors have been known to [make false claims about their tools](https://overlayfalseclaims.com/), their products can actually [make the web worse for people with disabilities](https://www.accessibility.org.au/accessibility-overlays-make-the-web-worse-not-better-new-york-times/), and screen reader users have even created a [Google Chrome extension to block overlays](https://www.accessibyebye.org/). My contributions to WCAG will remain on halt for as long as there is a W3C community group run by overlay vendors.

**Comment by fstrr** [comment]
[This technique](https://www.w3.org/WAI/WCAG22/Techniques/general/G134.html) is now marked as obsolete as it refers to Parsing. I'm going to close this.
