### ISSUE TITLE
Typo in Principle 4: "by by"

### ISSUE THREAD

**Issue by cstrobbe** [w3c/wcag#2559]
In WCAG 2.1, the text just below the heading for [Principle 4](https://www.w3.org/TR/WCAG21/#robust) has a typo:

> Content must be robust enough that it can be interpreted **by by** a wide variety of user agents, including assistive technologies.

In [WCAG 2.0](https://www.w3.org/TR/WCAG20/#robust), this typo was not present. (The adverb "reliably" was apparently removed in WCAG 2.1.)

**Comment by bruce-usab** [comment]
I am taking the liberty to close as this is already in [2.1 errata](https://www.w3.org/WAI/WCAG21/errata/#editorial) (6th bullet) and corrected for 2.2, see:  https://www.w3.org/TR/WCAG22/#robust
