### ISSUE TITLE
Seek horizontal reviews

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#2560]
This is a meta issue to track horizontal review steps for the specification.
See [How to do wide review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) for details.

- Accessibility
    - [ ] Work through <a rel="nofollow" class="external text" href="https://w3c.github.io/apa/fast/checklist.html">this questionnaire</a>
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/a11y-request/issues/new/choose">request a review via GitHub</a> from <a rel="nofollow" class="external text" href="https://www.w3.org/WAI/APA/">APA</a>
- Architecture
    - [ ] Ask the <a rel="nofollow" class="external text" href="https://www.w3.org/2001/tag/">TAG</a> for review; see <a rel="nofollow" class="external text" href="https://tag.w3.org/workmode/">how to work with the TAG</a>
    - [ ] If you are developing javascript APIs you may also want to ask <a rel="nofollow" class="external text" href="mailto:public-script-coord@w3.org">public-script-coord@w3.org</a>, a technical discussion list shared by W3C and ECMA's TC 39
- Internationalisation
    - [ ] Read the <a rel="nofollow" class="external text" href="https://www.w3.org/International/review-request">Request a review</a> page
    - [ ] work through the <a rel="nofollow" class="external text" href="https://www.w3.org/International/i18n-drafts/techniques/shortchecklist">Short Checklist</a>
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/i18n-request/issues/new/choose">request a review via GitHub</a>
- Privacy
    - [ ] Write a "Privacy Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>, <a rel="nofollow" class="external text" href="https://www.w3.org/TR/fingerprinting-guidance/">Mitigating Browser Fingerprinting in Web Specifications</a>, and <a rel="nofollow" class="external text" href="https://tools.ietf.org/html/rfc6973">RFC6973</a>
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3cping/privacy-request/issues/new/choose">request a review via GitHub</a> from the <a rel="nofollow" class="external text" href="https://www.w3.org/Privacy/">Privacy Interest Group</a>
- Security
    - [ ] Write a "Security Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/security-request/issues/new/choose">request a review via GitHub</a>

**Comment by michael-n-cooper** [comment]
* [I18N request](https://github.com/w3c/i18n-request/issues/187)
* [Security request](https://github.com/w3c/security-request/issues/37)
* [Privacy request](https://github.com/w3cping/privacy-request/issues/98)
* [A11Y request](https://github.com/w3c/a11y-request/issues/35)

**Comment by fstrr** [comment]
This seems to relate to publishing WCAG 2.2, so I'm closing the issue. If it's still relevant, please re-open.
