### ISSUE TITLE
2.5.8 Target Size (Minimum) - Problems with the Equivalent exception

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#2569]
This exception reads:

> * Equivalent: The function can be achieved through a different control on the same page that has an area of at least 24 by 24 CSS pixels.

That means for a "different control" it is not sufficient to have enough spacing around it for example. For some surprising, probably unintentional reason, the requirement for something that serves as an alternative version is different from the requirement if it wasn't an alternative. That seems wrong.

**Comment by alastc** [comment]
How about:

> Equivalent: The function can be achieved through a different control on the same page that meets this success criteria.

**Comment by awkawk** [comment]
We don't need to say that as this is already covered by conformance: "For Level A conformance (the minimum level of conformance), the [Web page](https://w3c.github.io/wcag/guidelines/22/#dfn-web-page-s) [satisfies](https://w3c.github.io/wcag/guidelines/22/#dfn-satisfies) all the Level A Success Criteria, or a [conforming alternate version](https://w3c.github.io/wcag/guidelines/22/#dfn-conforming-alternate-versions) is provided."

**Comment by alastc** [comment]
We did discuss the conforming alternative version, but that seems more oriented around separate pages, rather than an alternative on the same page.

**Comment by awkawk** [comment]
From Understanding Conformance Requirement 2: Alternatives can also be provided on the same page. For example creating an equivalent to a user interface control.

**Comment by alastc** [comment]
Ok, so the change would be to remove this bullet...

**Comment by bruce-usab** [comment]
> Ok, so the change would be to remove this bullet...

I agree, because:

> From Understanding Conformance Requirement 2: Alternatives can also be provided on the same page. For example creating an equivalent to a user interface control.

But I do want to note that this is subtle and probably worth highlighting with any mention of removing the bullet.
