### ISSUE TITLE
broken link to International Standard Classification of Education

### ISSUE THREAD

**Issue by himorin** [w3c/wcag#2582]
Link to `International Standard Classification of Education` points http://www.unesco.org/education/information/nfsunesco/doc/isced_1997.htm in https://w3c.github.io/wcag/guidelines/22/#bib-unesco, but target seems to be moved to [digital library](https://unesdoc.unesco.org/ark:/48223/pf0000219109).

Also referred definition in glossary are changed in the document?

**Comment by patrickhlauke** [comment]
well spotted. made a PR here https://github.com/w3c/wcag/pull/2585
