### ISSUE TITLE
Inconsistency for aria-orientation with role=tablist

### ISSUE THREAD

**Issue by AutoSponge** [w3c/wcag#259]
[Here](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel), the specification states `aria-orientation` should always appear on the `tablist` 

[Here](https://www.w3.org/TR/wai-aria/states_and_properties#aria-orientation) `tablist` is not an element that allows `aria-orientation`

The result is, this an impossible spec to meet while making a valid page. How can I resolve this?

**Comment by jnurthen** [comment]
You need to look at the ARIA 1.1 document (linked from the aria practices document) https://www.w3.org/TR/wai-aria-1.1/#tablist

**Comment by AutoSponge** [comment]
That helps, but I'm finding tools like aXe which draw from other docs: https://dequeuniversity.com/rules/axe/2.1/aria-allowed-attr?application=axeAPI how should [WAI-ARIA States and Properties Taxonomy](http://www.w3.org/TR/wai-aria/states_and_properties#state_prop_taxonomy) and [WAI-ARIA Definition of Roles](http://www.w3.org/TR/wai-aria/roles#role_definitions) relate to the other reference (especially when there's a conflict)?

**Comment by jnurthen** [comment]
Again you are referencing the ARIA 1.0 versions of those documents. the ARIA 1.1 versions are at

http://www.w3.org/TR/wai-aria-1.1/states_and_properties#state_prop_taxonomy
AND
http://www.w3.org/TR/wai-aria-1.1/roles#role_definitions

If aXe hasn't updated their rules to the latest version of the specs I suggest logging an issue against them. (which I see you have done).
Also - I'm not sure why you have raised this issue against the WCAG repository? It really doesn't seem to be WCAG related. As such I'm closing it. If you really feel there is an ARIA spec ( https://github.com/w3c/aria ) issue or an ARIA practices ( https://github.com/w3c/aria-practices ) issue then I suggest raising an issue against the correct repository.
