### ISSUE TITLE
Focus indicator definition

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#2598]
The glossary item for focus indicator reads:
the pixels that are changed to visually indicate when a user interface component is in a focused state.

The context from 2.4.11 is:
When a [user interface component] has keyboard focus, one or both of the following is true:
The [focus indicator]:

So if this definition replaces the SC content the word "the" is repeated.

I suggest either:
pixels that are changed to visually indicate when a user interface component is in a focused state
or 
collection of pixels that are changed to visually indicate when a user interface component is in a focused state

AND, since this isn't a sentence I also removed the period at the end of the definition.

**Comment by alastc** [comment]
That's odd, there's another PR somewhere to _add_ the "the" at the start. I'll investigate.
