### ISSUE TITLE
Question about perimeter definition

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#2599]
The definition for perimeter is:

continuous line forming the boundary of a shape not including shared pixels, or the [minimum bounding box], whichever is shortest. For example, the perimeter calculation for a rectangle is 2h+2w -4, where h is the height and w is the width and the corners are not counted twice. The perimeter of a circle is 2𝜋r.

Did we consider putting the example in the definition into an example box? Should we?

**Comment by alastc** [comment]
Can do, I haven't done one of those before but seems like a good idea.
