### ISSUE TITLE
Focus appearance consistency issue

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#2601]
In the 2.4.11 Focus Appearance SC the 3rd bullet in 1 and 2 are:

has a contrast ratio of at least 3:1 against adjacent colors 
and
has a contrast ratio of at least 3:1 against adjacent non-focus-indicator colors, or is no thinner than 2 CSS pixels. 

Why does the first bullet not include the "non-focus-indicator" text? Should it?

**Comment by alastc** [comment]
If you check the survey, there's a PR in there to update that.

**Comment by awkawk** [comment]
great.
