### ISSUE TITLE
3.3.7 Accessible Authentication: Ambiguity in the exception

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#2603]
The exception of 3.3.7 reads:

> When the cognitive function test is to recognize objects, or content the user provided to the website.

The difficulty is in that it is not clear that "objects" is its own thing here, and that this doesn't mean "objects the user provided to the website". The comma is meant to convey that meaning, but that's such a subtle difference it would be good to be more explicit. Perhaps by repeating the word "recognize" like so:

> When the cognitive function test is to recognize objects, or **recognize** content the user provided to the website.

**Comment by WilcoFiers** [comment]
Very related to #2592 -- apologies, didn't see it or I would've just responded.

**Comment by cstrobbe** [comment]
If you want to avoid repeating the verb, you could also change the order of the two direct objects:

> When the cognitive function test is to recognize [either] content the user provided to the website or objects.

**Comment by alastc** [comment]
Could we keep to one issue please, otherwise my sanity may suffer. Comments in #2592
