### ISSUE TITLE
Privacy considerations re: redundant entry

### ISSUE THREAD

**Issue by wseltzer** [w3c/wcag#2615]
In new [3.3.9](https://w3c.github.io/wcag/guidelines/22/#redundant-entry), redundant entry, you make exception for security considerations. I suggest also including a privacy exception. Auto-population, one of the recommended techniques, may expose information to leakage, so it should not be recommended for potentially sensitive information. 

It could also be useful to reinforce the security and privacy consideration in the associated ["understanding" document](https://w3c.github.io/wcag/understanding/redundant-entry.html), reminding developers to ensure data protection when storing information even temporarily during a process.

**Comment by yatil** [comment]
Considering the website where you have entered your private data before would show that private data again, I am not sure how privacy would be impacted. This is not about external tools auto-populating the fields but the website itself offering information it already has.

**Comment by alastc** [comment]
If it is sensitive information, why would the site ask for it again? 

To be in scope it has to be part of the same process (and session). For security it is things like password / email confirmation, but for privacy I'm struggling to think of an example.

**Comment by wseltzer** [comment]
@yatil An issue is that autofill can be hijacked to steal information, for example by a third-party script embedded in the page. (See e.g. [this paper talk](https://www.cs.uic.edu/~browser-autofill/files/autofill_slides.pdf) )

@alastc Consider for example a medical appointment booking or pharmacy, where the patient is asked to enter and confirm prescription information. 

The concerns might best be addressed by the site not asking for redundant entry in the first place, but as-is, I wouldn't want the recommendations to encourage insecure data handling as the easiest way to fix non-compliance.

**Comment by patrickhlauke** [comment]
> @yatil An issue is that autofill can be hijacked to steal information, for example by a third-party script embedded in the page. (See e.g. [this paper talk](https://www.cs.uic.edu/~browser-autofill/files/autofill_slides.pdf) )

But this isn't about autofill in the browser. This is about the website adding the `value="..."` to the HTML it sends down the wire to the user's browser.

And at the point where you have the potential for malicious third-party scripts on your site, you have bigger problems.

> The concerns might best be addressed by the site not asking for redundant entry in the first place, but as-is, I wouldn't want the recommendations to encourage insecure data handling as the easiest way to fix non-compliance.

The danger is the same as for the site offering the user a way to *edit* previously entered information. Not sure where the perceived increased risk is here.

**Comment by alastc** [comment]
> Consider for example a medical appointment booking or pharmacy, where the patient is asked to enter and confirm prescription information.

I'm still struggling with understanding the privacy concern for this. Say the patient enters their prescription information to a site, then either:

- At a later stage in the same process they are asked to re-enter it (not meeting the SC), OR
- At a later stage in the same process the site provides that information back to the user to confirm or edit.

Presumably anything which affects that scenario would also affect [3.3.4 Error prevention](https://www.w3.org/TR/WCAG21/#error-prevention-legal-financial-data) (the confirmed bullet)?

**Comment by patrickhlauke** [comment]
Wondering if there is/was a misunderstanding here that this SC is only scoped to information entered *in the same process*/session - so it's not about prompting them for info about other stuff that is already held in the system, but specifically something they've already entered in a previous step of the same process.

**Comment by wseltzer** [comment]
I'm suggesting to indicate that there are privacy considerations with how this guideline is met. It is possible to eliminate redundant entry in ways that introduce no new privacy risks, but also possible that a poor implementation could leak additional information. 

Simplest, you could add to the second bulleted exception, except when ... "the information is required to ensure the security *or privacy* of the content."

**Comment by rachaelbradley** [comment]
Would including information about the privacy concerns of autopopulation in the understanding document address this?  It seems from reading this thread that a full exception is not needed but rather that developers should remain aware of concerns around certain approaches.

**Comment by alastc** [comment]
Hi @wseltzer,

The AG group [discussed this today](https://www.w3.org/2022/09/06-ag-minutes.html#t09) and didn't agree with adding text to the criterion. It was thought to open quite a wide loophole so that anything that could be observed over a shoulder would be exempt.

However, it seemed as though that was a suggestion and what we would like to explore is an update to the understanding document to nudge people to better privacy practices.

My [initial suggestion](url) was a bit vague and could do with some work & more information / examples.

**Comment by bruce-usab** [comment]
Self-assigning because I will be working with @a11ydoer on Understanding for 3.3.7.

**Comment by wseltzer** [comment]
Inviting @pes10k to take a look, thanks!

**Comment by bruce-usab** [comment]
This issue is flagged for discussion on today's (1/28) Backlog call.

**Comment by alastc** [comment]
The update in #2946 was [agreed yesterday](https://www.w3.org/2023/01/31-ag-minutes#item11), so the issue is closed.
