### ISSUE TITLE
Accessibility guidelines for front camera (navigator.getUserMedia) ?

### ISSUE THREAD

**Issue by tahashieenavaz** [w3c/wcag#2629]
I have been searching documentations for quite a while and I couldn't find proper instructions to make front and back camera accessible.

Is there something that I'm missing ? Or due to the fact that "getUserMedia" has been removed from standards, is just being ignore ?

**Imagine we are building a face authentication and people with vision loss might find it difficult to some sort of response about it.** 

Thanks in advance.

**Comment by patrickhlauke** [comment]
there's nothing specific about making `getUserMedia` itself accessible. It depends on the actual use you're putting it to, and what the rest of the interface you're presumably creating does and whether *that* is accessible or not (which comes down to generic web accessibility, not specific to camera use).

for things like detecting a face (like an identity scan) or something like a QR code scanner, you might consider giving additional screen-reader feedback (using something like a visually hidden ARIA live region) to at least confirm when something was detected, when the face is in the proper/expected place, if the user needs to sit closer/further away from the camera, etc (assuming you're detecting that in your code). beyond that, consider perhaps using some haptic feedback with the vibration API for a similar purpose ("buzz" the device when something was detected).

**Comment by alastc** [comment]
it is a reasonable question, but not something we can/should update the guidelines to address at the moment, so closing.
