### ISSUE TITLE
Consider making Success Criterion 2.4.12 Focus Not Obscured (Minimum) a Level A criterion (instead of AA)

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#2648]
This seems to be a very important accessibility need, and while it makes almost no difference in practice if a SC is A or AA (as mostly AA is required), a hidden UI element receiving focus is a major barrier and IMHO level A worthy.

**Comment by bruce-usab** [comment]
> while it makes almost no difference in practice if a SC is A or AA

I must say, I am a little surprised that Level A (only) never got picked up anywhere AFAIK.

> a hidden UI element receiving focus is a major barrier and IMHO level A worthy

I respectfully disagree.  I don't think it rises to the bar of "essential" quite as hard as other single-A SC and it imposes on the default "look-and-feel".

Did you ever take a look at this [tally of level assignments](https://www.w3.org/WAI/GL/wiki/WCAG_2.x_Priority_levels_discussion#Tabular_View_of_Common_Factors)?  I would very much welcome your feedback!

**Comment by yatil** [comment]
I think seeing on which control you're on is essential. There is no way for AT to fix this. 

It's applicable to all content. 

It is easy to implement (CSS scroll-margin exists for most cases, and JavaScript is used for elaborate cases anyway, so the overlapping can be mitigated that way.)

It's an invisible fix insofar as that it conforms to the expected behavior that the user can see UI elements with focus. 

The listed wiki page does not include 2.2 SCs. 

I consider that the reply means that putting it on level A was considered, which was my request. This issue can hence be closed.
