### ISSUE TITLE
2.4.11 - example by 2px increase of background - is there science to support the design?

### ISSUE THREAD

**Issue by ChrisInTheWeb** [w3c/wcag#2674]
the example seen in figure 26 - [https://w3c.github.io/wcag/understanding/focus-appearance.html](https://w3c.github.io/wcag/understanding/focus-appearance.html) - seems poor to this one-person sample.

**Is there science to support** the idea that, say, a white text on black background button can show focus by making the background two pixels wider without additional visible design additions when compared to not focused buttons of the same design (without the additional 2 pixel increase in background size)?

All other examples and specifications I can support, that example and part of the specification seems a poor improvement to WCAG and inclusion to a AA criteria.

**Comment by alastc** [comment]
That example showing how to apply a general rule for this type of interface.

For example, this example with a 2px blue outline is (in terms of the criterion) just the same:
<img alt="Three green buttons, the middle one has a blue outline." src="https://user-images.githubusercontent.com/216630/191224435-e34f77ef-d5cd-4618-8cf1-c1961d731fee.png">

The outline and background (of the button) to not have sufficient contrast, so it also does not have sufficient adjacent contrast, like the black:black example.

Would you say that is not visible?

If adjacent contrast with no thickness requirement were used, then this example with a 4px outline would also fail:
<img alt="Three green buttons, the middle one has a very thick blue outline." src="https://user-images.githubusercontent.com/216630/191225133-8b1af99b-188b-4ec8-ab21-24d04922ad82.png">

It is a case of drawing a line. From testing we found that a 1px non-contrasting outline was definitely not enough, but often 2px was. The example in the understanding is the worst possible interpretation of that type that meets the SC.

A bigger factor is how close items are, but the complexity of testing that would be exponentially more difficult.

**Comment by ChrisInTheWeb** [comment]
Hello Alastair,

thanks for your reply. I can see your 1px and 4px blue around green.

However the same colour, negligible size, black around black in figure 26 is the one that concerns me and as you wrote "The example in the understanding is the worst possible interpretation of that type that meets the SC.". Yet there it is.

You wrote that you're aware of testing, **great**. That's all we non-researchers can ask for.

Regards, Chris.
