### ISSUE TITLE
4.1.3 Status Messages - example: can not reopened message

### ISSUE THREAD

**Issue by Ignacio-de-Loyola** [w3c/wcag#2675]
![image](https://user-images.githubusercontent.com/80868256/189872342-fbb134c5-c4e2-4b8b-ac52-7a599837980d.png)

As in the example, a status message is provided above the 'Send boarding pass' button. There is no mechanism to reopen the message after closing it, so the message cannot be checked again. At this time, can it be regarded as an example of failure of 4.1.3?

**Comment by patrickhlauke** [comment]
no, whether you can reopen a message or not is nothing to do with 4.1.3.

4.1.3 is concerned with whether or not a message is announced explicitly by AT when it appears

**Comment by Ignacio-de-Loyola** [comment]
If there is no way to check the message again, I think AT users will not be able to check the context change. Is this simply a problem with UX? Or can it be considered 3.2.2?

**Comment by scottaohara** [comment]
is this not just a tooltip that needs to be associated with the button?  is it not already programmatically associated?

**Comment by Ignacio-de-Loyola** [comment]
@scottaohara  The tooltip and the button are associated. However, if you close the tooltip, there is no way to check it again. Doesn't it matter if it's just a programmatically associated?
