### ISSUE TITLE
Understanding mentions issue where the SC is not closing the gap, 3.3.7 Accessible Authentication

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2691]
https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication.html

In the Understanding document it says:

> Whether it is remembering random strings of characters, a pattern gesture to perform on a touch screen, **or identifying which images include a particular object**, cognitive function tests will exclude some people. When a cognitive function test is used, at least one other authentication method must be available which is not a cognitive function test.

So "identifying which images include a particular object" is a cognitive function test, but also this is an exception:

> Object Recognition: The cognitive function test is to recognize objects.

The suggestion is made in the Understanding with the sentences that this will be tackled with the SC, while the object scenario is excepted.

**Comment by alastc** [comment]
I've added that update to #2988
