### ISSUE TITLE
Implementation experience: SC 2.4.11 & 2.5.8 (Candicate Recommendation phase)

### ISSUE THREAD

**Issue by cstrobbe** [w3c/wcag#2699]
Since the [candidate recommendation snapshot](https://www.w3.org/TR/2022/CR-WCAG22-20220906/Overview.html#sotd) provides no other mechanism for submitting implementation evidence than the GitHub issue tracker, here is my submission.

The site [Accessibility Works](https://cstrobbe.gitlab.io/A11yWorks/) meets the new success criteria 2.4.11 (Focus Appearance) and 2.5.8 (Target Size (Minimum)) in the candidate recommendation snapshot.

Links also meet success criteria 2.4.12 and 2.4.13 but these are not the type of user interface components for which these success criteria would be most helpful, since they aren't used in a context where they are at risk of being obscured by other content.

The five other new success criteria are not applicable.

For details, see the [accessibility statement](https://cstrobbe.gitlab.io/A11yWorks/accessibility-statement.html#wcag22-cr).

**Comment by cstrobbe** [comment]
Yes, that's why I submitted this :-)

**Comment by dbjorge** [comment]
@cstrobbe I think the focus indicator around the cc-by-sa logo in the page footer needs an adjustment to meet 2.4.11's requirement for 3:1 adjacent contrast between the `#325050` focus indicator and the `#000000` color of the image adjacent to the inner edge of the focus indicator on all sides.

![screenshot of cc-by-sa logo in focus state](https://user-images.githubusercontent.com/376284/199097506-26d0660f-06b8-402e-8991-c41c44c22fca.png)

**Comment by patrickhlauke** [comment]
i don't think the focus indicator needs to have increased contrast. while it's not contrasting against the actual CC-BY-SA image itself, it visually appears to "grow" when focused, which is a sufficient visual cue that the image control has focus. (see figure 26 in https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html)

**Comment by alastc** [comment]
That's sufficient if it is 2px thick, which I think it is:
<img src="https://user-images.githubusercontent.com/216630/199120264-7fa81c3e-0525-420a-9384-5e4b7e50d5a9.png" alt="overlapping screenshots showing a very blown up version with a 1px border, then a 2px outline." height="300">

**Comment by cstrobbe** [comment]
@dbjorge 

The CC image has a 2 px transparent padding in its unfocused state and a 2px `#325050` padding when focused. I thought that would be sufficient.

**Comment by dbjorge** [comment]
You're all correct, my apologies for my misunderstanding

**Comment by alastc** [comment]
I've entered the site as an [implementation](https://www.w3.org/WAI/GL/WCAG22/CR/implementations) for those two criteria, so I'll close this issue.

Again, thank you for submitting these, it really helps with the process.

**Comment by bruce-usab** [comment]
![Hat tip to @cstrobbe](https://baldwinhats.com/wp-content/uploads/2014/03/calvin-coolidge-tipping-his-hat.jpg)
