### ISSUE TITLE
Remove IE6 mention from C20

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#271]
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/C20.html

We know IE6 is end of support now. `max-width` is supported by IE7 and above [1].
Thus, I propose to delete following note.

> Note: The CSS property max-width is not supported in versions of Internet Explorer 6 and below.

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/max-width#Browser_Compatibility

**Comment by alastc** [comment]
The note is true, and the whole technique is, um, not cutting edge. Unless we're going in to completly overhaul the technique it isn't worth the time to update this.
