### ISSUE TITLE
Normative wording inconsistencies for Accessible Authentication SCs

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#2715]
For both [3.3.7](https://www.w3.org/TR/WCAG22/#accessible-authentication) and [3.3.8](https://www.w3.org/TR/WCAG22/#accessible-authentication-no-exception), there are a number of trivial language considerations that could be advanced to improve consistency.
1. In other situations where a baseline minimum requirement is introduced and more pronounced requirement is added at another level, the convention is for the first to be followed by "Minimum" and the second is followed by "Enhanced". Here, it is following a different convention of appending "No exception". This is used only in Keyboard and Images of Text, where the language of the lower bar specifically uses "except" in the wording. That word is absent in 3.3.7. As well, 3.3.8 arguably continues to provide an 'exception' through its "unless" language. Rather than reword the SC, it is probably easier to just make it "(Minimum)" and "(Enhanced)".
2. In both SCs, the wording in the bullets is not consistent. The first bullet ("Another authentication method that does not rely on a cognitive function test.") is a sentence fragment and reads as a continuation of the pre-amble. Others, such as "A mechanism is available to assist the user in completing the cognitive function test", is a full sentence.   Easiest way is to either add "exists" to the first bullet (Another authentication method exists that..) OR remove the verbs from the others ("The cognitive function test recognizes objects").
Depending on which way we want to go, I'm happy to do a PR for these

**Comment by yatil** [comment]
Thanks @mbgower. I think both suggestions make sense. I would prefer adding “exists” for the second part.

**Comment by bruce-usab** [comment]
With regard to (1), I think it may have been sub optimal for 1.4.3 to have the (minimum) qualifier.  We could go either way at this point.  To be contrary, I will point out that we could have (No Exception) variants of other SC and it seems better to me that 2.1.1 is not named Keyboard (Minimum).

For (2) I think if you add "exists" to the first bullet, I think you will find that you need to a _bunch_ more words. to qualify and provide context wrt "step in a process".

**Comment by yatil** [comment]
- 3.3.7 Accessible Authentication 
- 3.3.8 Accessible Authentication (Strict)

???

**Comment by alastc** [comment]
For (1), I agree it is odd. I think we updated the structure without re-considering the names of the SCs.

I'd suggest leaving the AA SC and adding (Enhanced).

For (2), I think it works better as-is. The preamble is asking "that step provides at least one of the following:", and you can read each as a thing provided in the authentication step.

I've created branch [Issue2715-accessible-auth-name](https://github.com/w3c/wcag/tree/Issue2715-accessible-auth-name) that includes the name-change, please use that for other updates related to this issue.
