### ISSUE TITLE
QR codes and non-text contrast

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#2717]
A QR code can be a graphical object that's required to be understood, so would fall under 1.4.11. I'm wondering about which parts of it have to have at least 3:1 contrast. For example:

This QR code uses a black and blue combination that has a contrast of greater than 3:1. However, the surrounding page color is the same blue. Is the black color enough for this to conform to 1.4.11?

![QR code with black and blue data blocks, with the surrounding page having the same blue color.](https://user-images.githubusercontent.com/20049493/194625630-9f2ded8c-ec32-4382-8cef-f43837af3828.png)

This QR code uses the same black and blue combination, but the surrounding page is white. The contrast between all three colors is greater than 3:1. Do all three colors need to have at least 3:1 to conform?

![QR code with black and blue data blocks, placed on a white page.](https://user-images.githubusercontent.com/20049493/194626268-262bd776-ebe4-4dee-87af-09ffd6776b3c.png)

**Comment by bruce-usab** [comment]
FWIW, i do not agree that much of a QR code needs to have good contrast.  Humans do not read them, we just need to recognize that it _is_ a QR code.  So what is the <q>Parts of graphics required to understand the content</q>?  I think it is just the three squares in the corners.

**Comment by fstrr** [comment]
I was thinking about common patterns like "scan the QR code on this page to sign in" or "scan the QR code on this page to set up a one-time password" where a user would have to point their handheld device at part of the screen. I think it's about there being enough contrast to recognize / understand that it's a QR code and where to point your device, rather than being able to read the pattern.

**Comment by patrickhlauke** [comment]
> This QR code uses a black and blue combination that has a contrast of greater than 3:1. However, the surrounding page color is the same blue. Is the black color enough for this to conform to 1.4.11?

whether you can tell the "boundary" around the QR code or not seems irrelevant, as the black on blue contrast is sufficient. You may not be able to immediately tell where the "box" of the QR code is, but you can still clearly discern the black squares of the QR code against the background, so this would be fine under 1.4.11? (same way you don't necessarily need to know the boundary around a graphical button, as long as the icon of the button has clear-enough contrast)

> This QR code uses the same black and blue combination, but the surrounding page is white. The contrast between all three colors is greater than 3:1. Do all three colors need to have at least 3:1 to conform?

I'd say that it's not necessary for the black and blue contrast to be above 3:1, as long as the contrast between the blue and white is sufficient. A user may not be able to discern all the details/parts of the QR code itself, but as long as they can tell that "something" is there in that case, it should be sufficient.
