### ISSUE TITLE
Unexpected background-image on Techniques via smartphone

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#272]
This is a screenshot of <a href="https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/intro.html">Introduction to Techniques for WCAG 2.0</a> displayed on the smartphone.

<img src="https://cloud.githubusercontent.com/assets/8347177/25556167/079014ec-2d33-11e7-8020-deea2539c425.png" width="320" alt="screen shot">

**Comment by alastc** [comment]
Tested now, appears to work fine. I suspect it got overhauled since the issue was raised.

**Comment by fstrr** [comment]
Closing as resolved.
