### ISSUE TITLE
Providing a description for groups of form controls using fieldset and legend elements (H71) - Must vs Should

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#2738]
In the Description section for the Sufficient Technique H71 [Providing a description for groups of form controls using fieldset and legend elements](https://www.w3.org/WAI/WCAG21/Techniques/html/H71) linked in the Understanding document for [1.3.1 Info & relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html), is the line "The first element inside the fieldset **must** be a legend element". However, the [4.10.15 The fieldset element](https://html.spec.whatwg.org/#the-fieldset-element) states that the Legend is optional.

Content model:
**Optionally** a legend element, followed by flow content. (Bolding is mine.)

I suggest that these should be aligned and the Technique document updated to "When using a Legend to name the Fieldset group the Legend must be the first element inside the fieldset." Or similar.

Aside noting that the HTML requirement that a Fieldset does not need an accName (Legend or otherwise) does not map to the ARIA grouping roles that must have an accessible name.

**Comment by JAWS-test** [comment]
No, I think that's a misunderstanding. If I want to group form elements, then I don't need legend. But if I want to label the grouping, I need a legend. This is what H71 is all about: I want to label a group with fieldset and legend (as it says in the title of H71) - and then, according to the HTML specification, the legend must be the first child element (https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element: "As the [first child](https://dom.spec.whatwg.org/#concept-tree-first-child) of a [fieldset](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element) element."). If I don't want to label the group or want to label it differently (e.g. with role=group and aria-label) then of course that is allowed too, but a different technique
