### ISSUE TITLE
Update description of tabindex value on H4

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#274]
<a href="https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H4.html#H4-description">H4 says</a>:
> The tabindex is given a value between 0 and 32767.

But, currently, the <a href="https://www.w3.org/TR/html51/editing.html#the-tabindex-attribute">HTML 5.1 spec says</a>:

> The tabindex attribute, if specified, must have a value that is a valid integer.

So, we should update this limited tabindex value on H4. See also <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex">MDN - tabindex</a>.

**Comment by alastc** [comment]
Whilst not a recommended technique these days, applying tabindex is a possible route in some scenarios. The MDN page also notes the max-value of 32767.

The [nearest I can find about browser behaviour](https://stackoverflow.com/questions/24924851/when-does-tabindex-xxxx-break) is that they deal with it in different ways, so I don't think the technique is incorrect to specify that as a maximum.
