### ISSUE TITLE
Font Readability with Font-Weight below 400

### ISSUE THREAD

**Issue by Sana-at-Wcagdesigns-dot-com** [w3c/wcag#2745]
This application has a label with background-color #FFFFFF, color #556A8C, font-size:12px, font-weight: 300, which barely passes font color and font size. It was difficult to read the label for four low vision users and two 60+ year old users who wore heavy corrective lenses. However, all testing tools passed this test for AA.

I would recommend in WCAG SC 1.4.3 (Contrast Minimum) a font-readability perspective, if the font-size is below 14, then the font-weight must be 400 or more else consider it fail for AA.

**Comment by Myndex** [comment]
> *...if the font-size is below 14, then the font-weight must be 400 or more else consider it fail for AA.*

Hi @Sana-at-Wcagdesigns-dot-com 

Yes this is certainly an issue with WCAG 2.x  1.4.3, 

The candidate contrast method being developed for WCAG 3.0 is APCA-W3, which takes font size and weight into account. See **_[Why APCA](https://git.apcacontrast.com/documentation/WhyAPCA)_** for a brief introduction with some links to some additional resources.
