### ISSUE TITLE
3.3.9 Redundant Entry out of order

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#2764]
3.3.7 is Level AA, 3.3.8 is Level AAA, and 3.3.9 (redundant entry) is Level A. We have been ordering new SC so that Level A are first, then AA, then AAA. This seems to be the only instance where this isn't followed. 

The fix would be to make 3.3.9 Redundant Entry into 3.3.7 Redundant Entry and adjust the other two SC.

**Comment by bruce-usab** [comment]
Nice catch!  Which is the file to edit to make this correction?

**Comment by awkawk** [comment]
guidelines/index.html

Not sure if the Understanding/toc.html also needs to be updated.

**Comment by yatil** [comment]
Changes here would impact the following PR and the other supporting documents, like understanding.

- #2667

Considering that users are now used to SCs being out of order, I wonder how important this change is.

**Comment by awkawk** [comment]
@yatil it does help a bit in quickly determining whether an individual SC is from 2.0/2.1/2.2

**Comment by yatil** [comment]
OK. (FWIW: I have [stopped contributing to WCAG 2](https://yatil.net/blog/lamenting-twitter-wcag) due to exhaustion and mental health concern and had unsubscribed from all issues. I would prefer to be not tagged in the future.)
