### ISSUE TITLE
Broken link in Color Viewer Slider Example

### ISSUE THREAD

**Issue by bySebastian** [w3c/wcag#2785]
There's a broken link in the APG [Color Viewer Slider Example](https://www.w3.org/WAI/ARIA/apg/example-index/slider/slider-color-viewer.html) page.

The example [Horizontal Multi-Thumb Slider Example](https://www.w3.org/WAI/ARIA/apg/example-index/slider/multithumb-slider) links to -> https://www.w3.org/WAI/ARIA/apg/example-index/slider/multithumb-slider. The "multithumb-slider" should be  "slider-multithumb".

The correct URL should be -> https://www.w3.org/WAI/ARIA/apg/example-index/slider/slider-multithumb

**Comment by cstrobbe** [comment]
I think issues related to the [ARIA Authoring Practices Guide (APG)](https://www.w3.org/WAI/ARIA/apg/) should be submitted in [WAI-ARIA APG issue tracker](https://github.com/w3c/aria-practices/issues).

**Comment by patrickhlauke** [comment]
Manually moved over https://github.com/w3c/aria-practices/issues/2539
