### ISSUE TITLE
No Diagram on the WCAG Documents page (mentioned in section 0.3 of WCAG 2.1)

### ISSUE THREAD

**Issue by Slawomir-DKl** [w3c/wcag#2786]
Point 4 in section 0.3 of WCAG 2.1 (https://www.w3.org/TR/WCAG21/) is as follows:

_"[The WCAG Documents](https://www.w3.org/WAI/standards-guidelines/wcag/docs/) - A diagram and description of how the technical documents are related and linked."_

Nevertheless, the linked document (https://www.w3.org/WAI/standards-guidelines/wcag/docs/) doesn't include any graphics/diagrams.

Polish translation (https://www.w3.org/Translations/WCAG21-pl/) indicates the graphic character of the linked website even more strictly:
_"opis dokumentów technicznych WCAG 2.1 w postaci wykresu"_
[Back translation: _"description of WCAG 2.1 technical documents in the form of diagram/graph"_]

**Comment by alastc** [comment]
@shawna-slh Do you know if / where the diagram would be?

Looks like it was [there until at least the end of 2021](https://web.archive.org/web/20211119133134/https://www.w3.org/WAI/standards-guidelines/wcag/docs/).

**Comment by shawna-slh** [comment]
Ah, it was deleted in the page update. I added it back in (and listed for EOWG review). I think that EOWG would like to update that diagram some time; however, it's not a priority.

**Comment by shawna-slh** [comment]
Clarification: I added back in one of the diagrams. Not the other.
