### ISSUE TITLE
missing opening parenthesis on F73

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#282]
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F73#F73-description

> (e.g. if surrounding text is RED and the link is PINK it would pass. Similarly a light green and a dark red differ BOTH by color AND by lightness so they would pass if the contrast (lightness) difference is 3:1 or greater) before focus or pointing. )

The number of parentheses does not match.

**Comment by awkawk** [comment]
Closing as fixed in editor's draft with 10eaf2b.
