### ISSUE TITLE
Improvement of Applicability on F77

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#283]
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F77#F77-applicability

> HTML5, and any XML-based markup languages including HTML 4 and SVG

I think that "HTML, and any XML-based markup languages including XHTML and SVG" is more accurate description.

**Comment by alastc** [comment]
We might well be dropping 4.1.1 in WCAG 2.2, but as it's a minor update I've done that. Should appear next week.
