### ISSUE TITLE
@JAWS-test, perhaps you can elaborate in the [issue](https://github.com/w3c/wcag/issues/728) (so your reasoning is captured, and so that discussion can happen in a topic)? I can make changes to the PR based on further discussion.

### ISSUE THREAD

**Issue by davecamp6808** [w3c/wcag#2834]
@JAWS-test, perhaps you can elaborate in the [issue](https://github.com/w3c/wcag/issues/728) (so your reasoning is captured, and so that discussion can happen in a topic)? I can make changes to the PR based on further discussion.

_Originally posted by @mbgower in https://github.com/w3c/wcag/issues/2827#issuecomment-1338010610_

**Comment by JAWS-test** [comment]
I already did. Please close this issue

**Comment by scottaohara** [comment]
this is just spam
