### ISSUE TITLE
ATAG documents have incorrect newer version link

### ISSUE THREAD

**Issue by backwardok** [w3c/wcag#2835]
When going to a previous version of ATAG (for example [the current version at the old link](https://www.w3.org/TR/2015/REC-ATAG20-20150924/)) or implementing ATAG ([old implementing ATAG link](https://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/)), there's a warning with the following content:

> This version is outdated! For the latest version, please look at [https://www.w3.org/TR/css-multicol-1/.](https://www.w3.org/TR/css-multicol-1/)

However, that link takes you to an entirely different page (CSS Multi-column Layout Module Level 1).

I would expect that the version it's supposed to point to is the linked "Latest version" link that's on the old url: https://www.w3.org/TR/ATAG20/ for ATAG and https://www.w3.org/TR/IMPLEMENTING-ATAG20/ for Implementing ATAG

Part of this is more noticeable because the links in each success criterion to the implementing doc from the ATAG doc and vice versa reference a specific version that's not the current version. For example, if you go to [Guideline B.1.1.1 in ATAG](https://www.w3.org/TR/ATAG20/#sc_b111), the "Implementing Guideline B.1.1.1" link has the old url format: http://www.w3.org/TR/2015/NOTE-IMPLEMENTING-ATAG20-20150924/#sc_b111. Similarly, if you go to [Implementing B.1.1.1 in Implementing ATAG](https://www.w3.org/TR/IMPLEMENTING-ATAG20/#sc_b111), the "Return to B.1.1.1 in Guidelines" link has the old url format as well: http://www.w3.org/TR/2015/REC-ATAG20-20150924/#sc_b111.

**Comment by alastc** [comment]
There was a brief time where we had a few redirect issues, I think these have been resolved, I can't see any 'outdated' messages.
