### ISSUE TITLE
IDEAL Conference Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2845]
The first Web conferencing product with integrated support for captioning viewport resource example ([IDEAL Conference](http://www.onlineconferencingsystems.com/vpat/)) of the G157: Incorporating a live audio captioning service into a Web page technique (https://www.w3.org/WAI/WCAG22/Techniques/general/G157) is a URL to a Huge Domains, for sale web page.

**Comment by alastc** [comment]
Removed, thanks.
