### ISSUE TITLE
Perceptually optimised sign language video coding based on eye tracking analysis Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2847]
The [Perceptually optimised sign language video coding based on eye tracking analysis](http://ieeexplore.ieee.org/application/enterprise/entconfirmation.jsp?arnumber=1251527&icp=false) resource's URL of the [Providing sign language versions of information, ideas, and processes that must be understood in order to use the content](https://www.w3.org/WAI/WCAG22/Techniques/general/G160) technique is a link to a 404 page.

The resource is available at this URL: https://www.researchgate.net/publication/221458250_Optimised_sign_language_video_coding_based_on_eye-tracking_analysis. I was able to download the PDF.

**Comment by alastc** [comment]
Updated, thank you.
