### ISSUE TITLE
Header design not optimal on mobile, causes horizontal scroll

### ISSUE THREAD

**Issue by lloydi** [w3c/wcag#2885]
As spotted on https://www.w3.org/WAI/WCAG21/Techniques/
Opened link on iPhone 11 Pro
Header design causes horizontal scroll that affects all page content.

**Comment by lloydi** [comment]
Tried to attach video showing behaviour but it is failing to attach

**Comment by kfranqueiro** [comment]
This was re-flagged in #3911 and resolved in #4001, and the fix has now been published for both 2.1 and 2.2.
