### ISSUE TITLE
ITC Guidance Note for Licensees on Flashing Images and Regular Patterns in Television Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2887]
The [ITC Guidance Note for Licensees on Flashing Images and Regular Patterns in Television](http://www.ofcom.org.uk/static/archive/itc/itc_publications/codes_guidance/flashing_images/index.asp.html) resource's URL of the [Technique G176:Keeping the flashing area small enough](https://www.w3.org/WAI/WCAG22/Techniques/general/G176) technique is a link that redirects to the following unrelated page: [Regulator archives](https://www.ofcom.org.uk/about-ofcom/website/regulator-archives).

The resource is available on this page: [ITC Guidance Note for Licensees on Flashing Images and Regular Patterns in Television](https://www.ofcom.org.uk/__data/assets/pdf_file/0021/16248/gn_flash.pdf).

**Comment by alastc** [comment]
Given that the new version says "legacy" all over it, I think it is best to remove. Thanks, that's merged.
