### ISSUE TITLE
ACT Rules missing from new understanding & techniques pages

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#2891]
These, and many other pages should link to ACT rules. Before this redesign was published they did:

- https://www.w3.org/WAI/WCAG22/Understanding/name-role-value
- https://www.w3.org/WAI/WCAG22/Techniques/html/H58

As far as I can tell all links to ACT rules were removed from the understanding documents & techniques.

**Comment by shawna-slh** [comment]
@michael-n-cooper I think this is an XSLT issue. Let me know if there's anything I can do to help.

**Comment by michael-n-cooper** [comment]
The PR restores ACT output in Understanding. It was always being output for Techniques, but the ACT mapping file doesn't include H58. Checking other techniques that do show up in the mapping file, like H57, I see the rules being output.
