### ISSUE TITLE
The Beware of opening links in a new window Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2894]
The [Beware of opening links in a new window](http://www.webcredible.com/blog/beware-opening-links-new-window/) resource's URL of the [G200: Opening new windows and tabs from a link only when necessary](https://www.w3.org/WAI/WCAG22/Techniques/general/G200) technique is a link that redirects to the following unrelated page: [UX agency Webcredible joins Inviqa](https://inviqa.com/ux-agency-webcredible).

**Comment by alastc** [comment]
Removed, thank you.
