### ISSUE TITLE
Code Standards

### ISSUE THREAD

**Issue by nschonni** [w3c/wcag#29]
I was looking at normalizing the formatting through out the repo.
To do this I suggest adding an http://editorconfig.org file so that going forward IDEs will self normalize.

Few questions to answer for the config file:

1. Tabs vs. Spaces since there is a mix in the repo
2. Blank line at EOF?
3. Trim trailing space?

**Comment by awkawk** [comment]
Added to Working Branch (https://github.com/w3c/wcag/commit/2adc41c152ce522121d12e07990fb49278504083)
