### ISSUE TITLE
Where is there markup rule of XML sources?

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#290]
For example, in <a href="https://github.com/w3c/wcag/blob/Working-Branch-for-Q1-2017/wcag20/sources/techniques/general/G115.xml">G115</a>:
>&lt;p>In HTML, for example, phrase-level elements such as
>&lt;code>&lt;![CDATA[
              em
            ]]>&lt;/code>,

On the other hand, in <a href="https://github.com/w3c/wcag/blob/Working-Branch-for-Q1-2017/wcag20/sources/techniques/html/H49.xml">H49</a>:

>&lt;p>Most screen readers do not provide automatic notification about &lt;el>em&lt;/el>,

Thus, an HTML element is marked up with different XML elements. Which XML element is more preferred?
And where is the editorial conventions stated? (we show <a href="https://github.com/w3c/html/blob/master/docs/contributing-documentation.md">Editorial conventions</a> of HTML spec, for reference.)

**Comment by alastc** [comment]
I'm afraid we don't use the XML versions of the source files anymore. The README of the repo has contribution advice, but we work in HTML files now.

I'm closing this, but not entirely sure I understood the question, so please re-open if that doesn't answer the question.
