### ISSUE TITLE
Revise URL for BBC Subtitle Guidelines

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/wcag#2910]
At https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded#resources the link to the BBC Subtitle Guidelines has an outdated URL. Please change it to point to https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/

**Comment by nigelmegitt** [comment]
Thank you!

**Comment by fstrr** [comment]
Thanks for the correct URL - it's much quicker to fix when those are supplied :)
