### ISSUE TITLE
Bug with highlight js

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#2914]
The redesign lets us have syntax highlighting via the Highlight JS library. It looks like all the code blocks we have need updating to add a `<code class="language-*">` attribute, which I'm happy to do. In playing around with a live page, though, it looks like there's a bug. Using [H37](https://www.w3.org/WAI/WCAG21/Techniques/html/H37) as an example:

## Current appearance and code
<img width="474" alt="screen shot of html source code for an image element. The source code is displayed in the Courier typeface in black." src="https://user-images.githubusercontent.com/20049493/211637450-db69c11b-c236-44c5-ad84-4a8a1e9a8b55.png">

```html
<pre xml:space="preserve">&lt;img src="newsletter.gif" alt="Free newsletter. 
 Get free recipes, news, and more. Learn more."&gt;</pre>
```

## Appearance and code with a `code` element and highlight js added via dev tools
<img width="953" alt="the same source code for an image, but the text is in a dark blue monospaced typeface" src="https://user-images.githubusercontent.com/20049493/211637631-3cc2a37b-0157-4d72-8e4b-c0aa323bc8b7.png">

```html
<pre xml:space="preserve"><code class="language-html hljs">&lt;img src="newsletter.gif" alt="Free newsletter. 
 Get free recipes, news, and more. Learn more."&gt;</code></pre>
```

It's clear that something is happening because the font has changed style and color, and there's a white background to the code. However, the attribute names and values aren't highlighted as they are in the [Highlight JS demo](https://highlightjs.org/static/demo/).

## Console error
<img width="417" alt="screenshot of a Dev Tools error stating Uncaught SyntaxError: Unexpected token '&' (at H37:201:59)." src="https://user-images.githubusercontent.com/20049493/211638391-8707f1dd-8751-4c06-bd46-f605da9612d9.png">

<img width="685" alt="screenshot of the JavaScript referenced in the Dev Tools image." src="https://user-images.githubusercontent.com/20049493/211638319-b08dd9d2-06ee-404e-91dc-21f45aa7caf4.png">

**Comment by patrickhlauke** [comment]
well based on the console error there, it looks like the `<script>` itself is being unnecessarily escaped (tuning the JavaScript `=>` arrow operator into the meaningly `=&gt;` construct

**Comment by fstrr** [comment]
While I'm here, how do I get the new design locally? I've been using `editors.css` to get what is now the old design, but can't work out how to get the new design running on my laptop.

**Comment by alastc** [comment]
I don't have time to check or do it right now, but I added the local styles by simply including a link to that CSS in the head, with `class="remove"` so it wasn't output when building.

`<link rel="stylesheet" type="text/css" href="../../css/editors.css" class="remove"></link>`

The `editors.css` is only for us (people editing content), so if you load a technique from the live version, grab the CSS, and replace the contents of editors.css, that would be the update...

**Comment by fstrr** [comment]
I've just tried that and it was partially successful. There's something else I'm missing though. Even though I've forked off an apparently up-to-date main branch, all Techniques pages I'm looking at don't have the new fancy header, page contents, footer, etc.

**Comment by alastc** [comment]
I don't think the old one did either, that isn't content which is in the editable files that we use?

**Comment by fstrr** [comment]
If I copy the code from `base.css`, `code.css`, `colors.css`, and `style.css` into a blank `editors.css`, I get this, which spans the width of the page (compare with the [online version of F37](https://www.w3.org/WAI/WCAG22/Techniques/failures/F37)):

<img width="1907" alt="screen shot of the top part of F37, showing text spanning the width of the browser." src="https://user-images.githubusercontent.com/20049493/211676692-da3ab07e-cc71-49f1-a535-1158ac5ff3b2.png">

With a decent amount of padding, it would probably work. We also need to script tags to highlight.js (does class="remove" work with script tags) and also have the highlight.js fonts locally as well.

**Comment by fstrr** [comment]
Two things:

1. Do we still need  `xml:space="preserve"` on the `pre` elements?
2. For testing that I'm updating code elements and blocks correctly, I can just temporarily add this onto each page to check that things are as they should be:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
```

I'll remove those lines before pushing any changes

**Comment by alastc** [comment]
@michael-n-cooper There is a PR of all the techniques waiting (Failures done so for), can you take a look at this please?
The XML encoding in the template is the main thing.

**Comment by michael-n-cooper** [comment]
@alastc I assume you meant #851 I merged that.

**Comment by bruce-usab** [comment]
@fstrr sorry to be <q>that guy</q> but by using `class` attributes on `code` are we conveying information using only color?  I am hesitant to suggest removing information, and even more hesitant if that means losing functionality.  I can imagine that some sample techniques pages could include HTML and CSS and JavaScript, so maybe it is a moot point?

**Comment by fstrr** [comment]
@bruce-usab I wouldn't say we're using color alone to convey information—the information is the code and the syntax highlighting helps to highlight different parts of it (element name, attribute name, attribute value, variable name, etc.). The syntax highlighting just adds highlighting to code so it looks similar to how code is presented in developers' IDEs.

Without syntax highlighting, the code in the Techniques pages stays like it has been for numerous years now. The syntax highlighting improves the appearance of the code and doesn't take anything away.

The use of the `class="language-*"` syntax is from the [HTML spec for the `code` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element):

> There is no formal way to indicate the language of computer code being marked up. Authors who wish to mark [code](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element) elements with the language used, e.g. so that syntax highlighting scripts can use the right rules, can use the [class](https://html.spec.whatwg.org/multipage/dom.html#classes) attribute, e.g. by adding a class prefixed with "language-" to the element.

The syntax highlighting library is currently being used in the ARIA spec (see [Example 4](https://www.w3.org/TR/wai-aria-1.2/#example-4))

**Comment by patrickhlauke** [comment]
code highlighting is a visual "nice to have" that yes, only helps sighted users that can see/differentiate the colours. but even without colours, the code still makes complete sense. and there's no non-visual equivalent for doing this (that would not also result in an extremely verbose and confusing extra output for, say, AT users).

i hope the argument is not "yes, it's only a nice to have, but why should sighted users have that bit of extra help to read the code? we should remove the visual highlighting so reading code is just as tedious for everybody"

**Comment by iadawn** [comment]
Fix should address the issue. Will need to merge in, then rebuild and redeploy the techniques. The code included in understanding docs as well so I assume those will need redeployed as well.
