### ISSUE TITLE
F104 examples and the redesign

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#2916]
I'm wondering if the redesign has impacted the examples in [F104](https://www.w3.org/WAI/WCAG21/Techniques/failures/F104) (which, as a side note, is very similar to [F69](https://www.w3.org/WAI/WCAG21/Techniques/failures/F69)).

Example 1 states: "The text renders correctly in the box and doesn't interfere with the next paragraph", but the example shows the text overflowing the box.

Example 2 states: "The text renders correctly in the box and doesn't interfere with the next paragraph" but the text inside the box is clipped.

Do those examples need re-coding so they display as described, or am I missing something obvious?

**Comment by JAWS-test** [comment]
> Do those examples need re-coding so they display as described

Yes

**Comment by fstrr** [comment]
Okay, I'll get on that then. Thanks for confirming I wasn't missing anything :)
