### ISSUE TITLE
Please don't use live project repositories to learn how to use github...

### ISSUE THREAD

**Issue by beegeezile** [w3c/wcag#2917]
Please don't use live project repositories to learn how to use github...

_Originally posted by @patrickhlauke in https://github.com/w3c/wcag/issues/2908#issuecomment-1377393679_

**Comment by beegeezile** [comment]
https://github.com/w3c/wcag/pull/2908#issuecomment-1377393679

**Comment by patrickhlauke** [comment]
congrats on getting yourself reported to github now.

**Comment by beegeezile** [comment]
> https://cwe.mitre.org/data/definitions/322.html

I didn't authorize this
