### ISSUE TITLE
Where do technique ARIA5's example 1's and 2's snippets come from?

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2924]
I tried accessing the site `oaa-accessibility.org` where the image is supposed to come from, but it directs me to "DRAGON99BET: Daftar Situs Judi Slot Online Gacor Mudah Menang" unrelated resource's URL.  The same domain name is used at the end of each example.

[Patrick: edited to remove the live link]

**Comment by patrickhlauke** [comment]
Well spotted, seems the domain's expired and been snapped up by some shady online gambling outfit. I'll do a PR that neutralises any links to the old oaa-accessibility.org

**Comment by patrickhlauke** [comment]
Ah, luckily, seems that ARIA5 is the only place where this is linked to.
