### ISSUE TITLE
Internet Explorer and the CSS box model resource should be removed

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2932]
The [Internet Explorer and the CSS box model ](http://www.456bereastreet.com/archive/200612/internet_explorer_and_the_css_box_model/) resource of the [C18: Using CSS margin and padding rules instead of spacer images for layout design](https://www.w3.org/WAI/WCAG22/Techniques/css/C18) technique directs to a blank page which automatically downloads files to my computer without asking. Attempting to access other pages from Google search produces the same results.

**Comment by detlevhfischer** [comment]
Removed the link that automatically downloads files.

**Comment by alastc** [comment]
The 456bereastreet link works fine for me now, I think perhaps it was a temporary error?
