### ISSUE TITLE
About fluid and fixed width layouts Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2933]
The URL of the [About fluid and fixed width layouts](http://www.456bereastreet.com/archive/200504/about_fluid_and_fixed_width_layouts/) resource of the [C20: Using relative measurements to set column widths so that lines can average 80 characters or less when the browser is resized](https://www.w3.org/WAI/WCAG22/Techniques/css/C20) technique is a link to a blank page.

**Comment by detlevhfischer** [comment]
this is addressed by the earlier PR #2940
