### ISSUE TITLE
Microsoft Internet Explorer Developer Toolbar Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2937]
The URL of the [Microsoft Internet Explorer Developer Toolbar](http://www.microsoft.com/en-us/download/details.aspx?id=18359) resource of the [C27: Making the DOM order match the visual order](https://www.w3.org/WAI/WCAG22/Techniques/css/C27) technique is a link to a Error 404 - Not Found page.

**Comment by detlevhfischer** [comment]
Here is a PR  https://github.com/w3c/wcag/pull/2938
[Making the DOM order match the visual order](https://raw.githack.com/w3c/wcag) (GitHack rendering)
I have edited the Technique, removed old sources and added new ones.

Closes #2937
