### ISSUE TITLE
Resources Not Available (404 links)

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2948]
The URL of the [Build your own PHP style sheet switcher](http://www.456bereastreet.com/archive/200608/build_your_own_php_style_sheet_switcher/) source of the [C30: Using CSS to replace text with images of text and providing user interface controls to switch](https://www.w3.org/WAI/WCAG22/Techniques/css/C30) technique is a link to a Page Not Found page.

It looks like this resource and some of the other sources from the [456 Berea Street](https://www.456bereastreet.com) website (used in the other techniques) I mentioned (in other issues) might be available from the [Archive](https://www.456bereastreet.com/archive/) resource, since I was able to open some blog posts using Post by category and Post by month links. 

This URL of this resource isn't in the [August 2006 | Archive](https://www.456bereastreet.com/archive/200608/) resource.

 I was unable to find a way to search for them using their website. Attempting to use the [Sitemap](https://www.456bereastreet.com/sitemap/) resource produces no results. Trying to search for this resource through Google didn't work as well.

**Comment by alastc** [comment]
Another:
<hr>
The URL of the [About.com: Unobtrusive JavaScript](http://javascript.about.com/library/blunobtrusive.htm) source in the [C30: Using CSS to replace text with images of text and providing user interface controls to switch](https://www.w3.org/WAI/WCAG22/Techniques/css/C30) technique is a link to the following unrelated resource: [Introduction to JavaScript](https://www.thoughtco.com/what-is-javascript-2037921).

**Comment by ShamarYarde** [comment]
https://github.com/w3c/wcag/issues/2965#issue-1557339822 is another one that @fstrr is working on along with some others.

**Comment by alastc** [comment]
From email:
<hr>
on - [Understanding Success Criterion 4.1.2: Name, Role, Value | WAI | W3C](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html) – this W3C link fails - [States and Adaptable Properties Module](https://www.w3.org/TR/wai-aria/%5bR,L%5d) .

It is part of: “Related Resources"

**Comment by ShamarYarde** [comment]
The URL of the [working example of contact information using a description list](https://www.w3.org/WAI/WCAG22/working-examples/description-list-contact-info/) example of [H48: Using ol, ul and dl for lists or groups of links](https://www.w3.org/WAI/WCAG22/Techniques/html/H48) technique is a link to a Error 404 - Not found page, but the source code for the example is present on the technique's page.

**Comment by ShamarYarde** [comment]
The URL of the [HTMl5 rb element](https://www.w3.org/TR/html/text-level-semantics.html#the-rb-element) source of the [H62: Using the ruby element](https://www.w3.org/WAI/WCAG22/Techniques/html/H62) technique is a link to a page without a reference to the rb element.  It could possibly be a link to the [\<rb\>: The Ruby Base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb) resource on MDN instead.

**Comment by ShamarYarde** [comment]
The URL of the [Assistive technology reading tables](http://www.eramp.com/david/tablesample2.htm) source of the [H63: Using the scope attribute to associate header cells and data cells in data tables](https://www.w3.org/WAI/WCAG22/Techniques/html/H63) technique is a link to a Server Not Found page.

I was unable to find this page through Google and to access the www.eramp.com domain name.

**Comment by ShamarYarde** [comment]
The URL of the [MSDN Accessible DHTML elements](https://msdn.microsoft.com/en-us/library/aa360193(VS.85).aspx) source of the [H91: Using HTML form controls and links](https://www.w3.org/WAI/WCAG22/Techniques/html/H91) technique is a link to the following unrelated resource: [Microsoft Learn: Build skills that open doors in your career](https://learn.microsoft.com/en-gb/).

**Comment by fstrr** [comment]
I've got a big update to H91 that I'll push in the next week or so. Much of that document has been removed, and I have removed that out-of-date link and replaced it with several working links.

**Comment by a11ydoer** [comment]
> Another:
> 
> The URL of the [About.com: Unobtrusive JavaScript](http://javascript.about.com/library/blunobtrusive.htm) source in the [C30: Using CSS to replace text with images of text and providing user interface controls to switch](https://www.w3.org/WAI/WCAG22/Techniques/css/C30) technique is a link to the following unrelated resource: [Introduction to JavaScript](https://www.thoughtco.com/what-is-javascript-2037921).

Do you have any suggestion how we can find the correct links for [C30: Using CSS to replace text with images of text and providing user interface controls to switch](https://www.w3.org/WAI/WCAG22/Techniques/css/C30)?

**Comment by a11ydoer** [comment]
Never mind about above comment. I think @fstrr is currently working on updating C30 resources link. Is that correct @fstrr ?

**Comment by a11ydoer** [comment]
> The URL of the [HTMl5 rb element](https://www.w3.org/TR/html/text-level-semantics.html#the-rb-element) source of the [H62: Using the ruby element](https://www.w3.org/WAI/WCAG22/Techniques/html/H62) technique is a link to a page without a reference to the rb element. It could possibly be a link to the [<rb>: The Ruby Base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb) resource on MDN instead.

Thanks for the correct reference to [rb element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb). Since rb element is deprecated, I would recommend to remove the link instead. what do you think @alastc and @ShamarYarde ?

**Comment by ShamarYarde** [comment]
> > The URL of the [HTMl5 rb element](https://www.w3.org/TR/html/text-level-semantics.html#the-rb-element) source of the [H62: Using the ruby element](https://www.w3.org/WAI/WCAG22/Techniques/html/H62) technique is a link to a page without a reference to the rb element. It could possibly be a link to the [: The Ruby Base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb) resource on MDN instead.
> 
> Thanks for the correct reference to [rb element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb). Since rb element is deprecated, I would recommend to remove the link instead. what do you think @alastc and @ShamarYarde ?

I thought that W3C was keeping these references for a reason.  [The FRAME element](https://www.w3.org/TR/html4/present/frames.html#h-16.2.2) is another example located on the [H70: Using frame elements to group blocks of repeated material](https://www.w3.org/WAI/WCAG22/Techniques/html/H70) technique page.

**Comment by a11ydoer** [comment]
> The URL of the [MSDN Accessible DHTML elements](https://msdn.microsoft.com/en-us/library/aa360193(VS.85).aspx) source of the [H91: Using HTML form controls and links](https://www.w3.org/WAI/WCAG22/Techniques/html/H91) technique is a link to the following unrelated resource: [Microsoft Learn: Build skills that open doors in your career](https://learn.microsoft.com/en-gb/).

MSDN resources are moved to MS and MS DHTM infor is no longer available. Also this is aged concept from novel idea since most of curent app is DHTML. I would also recommend to remove the link. What do you think @ShamarYarde and @alastc ?

**Comment by a11ydoer** [comment]
> The URL of the [HTMl5 rb element](https://www.w3.org/TR/html/text-level-semantics.html#the-rb-element) source of the [H62: Using the ruby element](https://www.w3.org/WAI/WCAG22/Techniques/html/H62) technique is a link to a page without a reference to the rb element. It could possibly be a link to the [<rb>: The Ruby Base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb) resource on MDN instead.

This is also using rb in the example code... should we also touch and update example code too @alastc ? I feel like I opened the can of worms. ;-)

**Comment by kfranqueiro** [comment]
I've re-checked all of the problems mentioned in this issue thread and I believe all of them are resolved; closing.
