### ISSUE TITLE
About.com: Unobtrusive JavaScript Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2949]
The URL of the [About.com: Unobtrusive JavaScript](http://javascript.about.com/library/blunobtrusive.htm) source in the [C30: Using CSS to replace text with images of text and providing user interface controls to switch](https://www.w3.org/WAI/WCAG22/Techniques/css/C30) technique is a link to the following unrelated resource: [Introduction to JavaScript](https://www.thoughtco.com/what-is-javascript-2037921).

**Comment by alastc** [comment]
I'm going to start stacking resource issues under one issue, otherwise we are creating a lot of hay to find things in.
