### ISSUE TITLE
GeoMap working example

### ISSUE THREAD

**Issue by gg0309** [w3c/wcag#295]
The WET 4.0 Working example for the GeoMap is not fully accessible.  Here are some of the issues that have been identified:

•	The group of checkboxes under legend should be put inside the fieldset.
•	Can’t tell what kind of contracts of the Black/White icons after the popups are closed
•	2 Popups for selected contracts on the map can’t be closed through keyboard. (popups on the map never get read by screen reader)
•	Labels should be unique, e.g.,  label for all checkboxes inside the tables, “Afficher entrées”, “Filtrer les articles”
•	Label needs to be associated with input explicitly, e.g. Filtrer les articles, Afficher  entrées
•	 Link text should be unique, e.g. Page Page 1, Zoom à l'élément

**Comment by nschonni** [comment]
Think you'll want to post that https://github.com/wet-boew/wet-boew rather than here
