### ISSUE TITLE
Understanding: All guidelines are named as SC

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2951]
Example: https://www.w3.org/WAI/WCAG21/Understanding/time-based-media:

> Understanding SC 1.2: Time-based Media. **Success Criterion (SC)**: Provide alternatives for time-based media.

Also, there are Empty page contents in these Understanding docs. Example: https://www.w3.org/WAI/WCAG21/Understanding/documenting-accessibility-support

Empty page contents should either be removed or (better) the page should have section headings (see [WCAG SC 2.4.10](https://www.w3.org/TR/WCAG21/#section-headings))

**Comment by alastc** [comment]
Took me a moment to understand, but the point being that these are understanding docs for the **_guideline_**, not a success criterion.

I think that'll be due to the redesign, so I'll tag it as such.

**Comment by kfranqueiro** [comment]
This is resolved now that WCAG 2.1 informative docs have been republished via the new build system, made possible via https://github.com/w3c/wcag/pull/4007.
