### ISSUE TITLE
Understanding of the guidelines and "other understanding documents" are not linked

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2952]
All guidelines have an [Understanding document](https://www.w3.org/WAI/WCAG21/Understanding/text-alternatives), but it is not linked on the [WCAG page](https://www.w3.org/TR/WCAG21/#text-alternatives). The Understandings can only be reached via the indirect way of an [Understanding of a SC](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html).

**Comment by alastc** [comment]
It is in progress, in #595 but pinging @michael-n-cooper as I think it was supposed to have been done already?
