### ISSUE TITLE
Double paragraph in "Status of This Document"

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2955]
Double paragraph in ["Status of This Document"](https://www.w3.org/TR/WCAG21/#sotd) - The following paragraph appears twice in the paragraph (at the beginning and at the end):

> This document has been reviewed by W3C Members, by software developers, and by other W3C groups and interested parties, and is endorsed by the Director as a W3C Recommendation. It is a stable document and may be used as reference material or cited from another document. W3C's role in making the Recommendation is to draw attention to the specification and to promote its widespread deployment. This enhances the functionality and interoperability of the Web.

**Comment by alastc** [comment]
Yes, this is known, it will disappear when the doc is re-published.
