### ISSUE TITLE
Examples not highlighted in the Understanding documents

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2958]
The examples are no longer at all different from the running text (class=example)

In the main WCAG document they are at least marked in yellow and indented, which is not perfect, but better than nothing (there is already another [issue](https://github.com/w3c/wcag/issues/634) for that)

Example at https://www.w3.org/WAI/WCAG21/Understanding/conformance#conformance-requirements

> A Web page incorporates a new interactive graphic technology called "ZAP". Although ZAP is not accessibility-supported, ...

**Comment by iadawn** [comment]
Addressed with https://github.com/w3c/wcag/commit/949c8474420e67ad3368fffa5679472a4e6aa753

**Comment by iadawn** [comment]
Closed as fixed (will be published nov 2024)
