### ISSUE TITLE
PHPBuilder Time-out Info Resource Not Available

### ISSUE THREAD

**Issue by ShamarYarde** [w3c/wcag#2965]
The URL of the [PHPBuilder Time-out Info](http://www.phpbuilder.com/tips/item.php?id=141) source of the [Allowing the user to extend the default time limit](https://www.w3.org/WAI/WCAG22/Techniques/client-side-script/SCR1) technique is a link to a page not found page.

The third sentence of this technique's description looks like it's supposed to be referring to something with the following phrase: "...is about to expire (see ),..."

**Comment by fstrr** [comment]
I'm in the process of updating the Scripting Techniques documents and have a fix in for these issues already. I just need to finish updating the last 10 techniques and will create a PR for all of them.

**Comment by ShamarYarde** [comment]
Alright, I'll close this then.
