### ISSUE TITLE
Broken link - Understanding SC 4.1.2: Name, Role, Value (Level A)

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#2968]
[Filed by email](https://lists.w3.org/Archives/Group/group-ag-chairs/2023Jan/0095.html)

Hello !

on - [Understanding Success Criterion 4.1.2: Name, Role, Value | WAI | W3C](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value..html) – this W3C link fails - [States and Adaptable Properties Module](https://www.w3.org/WAI/PF/adaptable/) .

It is part of:

“Related Resources

Resources are for information purposes only, no endorsement implied.

    [Dynamic Accessible Web Content Roadmap](https://www.w3.org/WAI/PF/roadmap/)
    [Role Taxonomy for Accessible Adaptable Applications](https://www.w3.org/WAI/PF/GUI/)
    [States and Adaptable Properties Module](https://www.w3.org/WAI/PF/adaptable/)
    [Microsoft Active Accessibility, Version 2.0](https://msdn.microsoft.com/en-us/library/ms697707.aspx)”

TIA, kind regards, Chris

**Comment by alastc** [comment]
I'll close this as I've been adding basic 404s to 1 issue:
https://github.com/w3c/wcag/issues/2948#issuecomment-1404820212
