### ISSUE TITLE
2.5.8: Target offset differ not only if the sizes of the targets differ

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2972]
[definition of target offset](https://www.w3.org/TR/WCAG22/#dfn-target-offsets):

> The target offset from A to B may be different than the target offset from B to A, if the sizes of these targets differ.

Even if the size is the same, but the objects are rotated, target offset can be different, as the example shows

![258b](https://user-images.githubusercontent.com/52748763/215317698-7a992a03-ca7a-4e80-bdf3-706217e9ed88.JPG)
Figure 1: Two identical triangles, one standing on its baseline, the other on a corner. Two arrows show target offset, which is different 

Even if they are not rotated, but positioned offset, elements of the same size can have a different target offset

![258a](https://user-images.githubusercontent.com/52748763/215317689-2f562897-9f2c-440b-a4a7-d0d1a38817e6.JPG)
Figure 2: Two identical triangles, aligned horizontally (according to the definition of target offset), but not at the same height. Two arrows show target offset, which is different

**Comment by alastc** [comment]
True, but is it worth saying that in a note on the definition?

**Comment by JAWS-test** [comment]
> True, but is it worth saying that in a note on the definition?

Yes!

Correct would be:

> The target offset from A to B may be different than the target offset from B to A

OR

> The target offset from A to B may be different than the target offset from B to A, **e.g.** if the sizes of these targets differ.

**Comment by alastc** [comment]
The update was [approved today](https://www.w3.org/2023/02/21-ag-minutes#resolution03).
