### ISSUE TITLE
New Features in WCAG 2.2: Order of SCs incorrect

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#2975]
In the [WCAG 2.2 Candidate Recommendation <s>Snapshot</s> Draft](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#new-features-in-wcag-2-2):

Current order:

> 3.3.7 [Accessible Authentication](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#accessible-authentication) (AA)
> 3.3.8 [Accessible Authentication (Enhanced)](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#accessible-authentication-enhanced) (AAA)
> 3.3.9 [Redundant Entry](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#redundant-entry) (A)

must be:

> 3.3.7 [Redundant Entry](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#redundant-entry) (A)
> 3.3.8 [Accessible Authentication](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#accessible-authentication) (AA)
> 3.3.9 [Accessible Authentication (Enhanced)](https://www.w3.org/TR/2023/CRD-WCAG22-20230125/#accessible-authentication-enhanced) (AAA)

**Comment by alastc** [comment]
Updated, thank you.
