### ISSUE TITLE
2.5.8: Is the target size measured only horizontally and vertically?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2978]
[Target size](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html):

> The size of the [target](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-target) for [pointer inputs](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-pointer-input) is at least 24 by 24 [CSS pixels](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-css-pixel), ...

Are the 24x24 px measured vertically and horizontally or would a square (24x24 px) that is on a corner (i.e. rotated 45 degrees) also pass the SC without the spacing exception (target offset)?

As I think this is neither explained in the SC nor in the Understanding, I plead for an appropriate clarification and addition.

**Comment by alastc** [comment]
This has more discussion (and a PR) in #2803, so I'll close this as a duplicate.
