### ISSUE TITLE
Weird hr styling in the understanding document.

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#299]
Reported by @patrickhlauke on twitter: https://twitter.com/patrick_h_lauke/status/895245881477300224

**Comment by koalie** [comment]
@deniak wrote about this in IRC just now:
>2017-08-09T11:49:19Z <denis> so that's a bug related to a misplaced <hr>

**Comment by alastc** [comment]
I don't think this applies anymore, can't see it in WCAG 2.0 or 2.1.

-Alastair

**Comment by patrickhlauke** [comment]
still present ... in the understanding 2.0 doc at least

https://www.w3.org/TR/UNDERSTANDING-WCAG20/

> ![hr](https://user-images.githubusercontent.com/895831/59214055-31590a00-8bae-11e9-879a-1851ad232319.png)

**Comment by patrickhlauke** [comment]
cause by this in base.css

```
:not(.head) > hr::before {
    content: "\2727\2003\2003\2727\2003\2003\2727";
}
```

**Comment by alastc** [comment]
Sorry, should have been clearer: The understanding/technique docs under /TR/ are being deprecated, either with warnings or a redirect.

I suspect we also wouldn't be able to update https://www.w3.org/StyleSheets/TR/2016/base.css if we wanted to, and it isn't worth the time to do it now.

**Comment by patrickhlauke** [comment]
> I suspect we also wouldn't be able to update https://www.w3.org/StyleSheets/TR/2016/base.css if we wanted to

just out of interest, why?

**Comment by alastc** [comment]
That's done over in this one: https://github.com/w3c/tr-design 
We could possibly add something to over-ride it in the additional.css, but it's a lot of faff publishing those docs again (it's a whole process) considering we're trying to get rid of it.
