### ISSUE TITLE
"in a language displayed top to bottom" -> "in vertically set text"

### ISSUE THREAD

**Issue by r12a** [w3c/wcag#2996]
Success Criterion 2.5.8 Target Size (Minimum)
https://www.w3.org/TR/2023/CR-WCAG22-20230124/#target-size-minimum (note)

> For example, in a language displayed top to bottom, the line-height would be horizontal.

Editorial: Arabic language in vertically set text is displayed bottom to top, but is still relevant for this guidance.  I suggest using something like:

"For example, in a language displayed vertically, the line-height would be horizontal."

This would also cover the cases where a language is displayed bottom to top, such as setting English with `writing-mode:sideways-lr`.

<img width="75" alt="Screenshot 2023-01-30 at 15 15 47" src="https://user-images.githubusercontent.com/4839211/215518880-3b2a777a-84a1-4ad9-a19b-ff46a14a49b0.png">

<img width="70" alt="Screenshot 2023-01-30 at 15 26 33" src="https://user-images.githubusercontent.com/4839211/215519631-7910c22c-620e-4a92-94df-95cbf678055d.png">

**Comment by cstrobbe** [comment]
This issue focuses on text displayed sideways, whereas the phrase "language displayed top to bottom" may refer to, or at least include, writing systems that actually write top to bottom, e.g. [Manchu script](https://en.wikipedia.org/wiki/Manchu_alphabet).

**Comment by alastc** [comment]
@cstrobbe I don't think that matters in the context of inline links for target size? The key thing is which way inter-line spacing happens.
