### ISSUE TITLE
Mismatch SC order and New Features in WCAG 2.2 order

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/wcag#3021]
In [New Features in WCAG 2.2](https://www.w3.org/TR/WCAG22/#new-features-in-wcag-2-2) order is:
* 3.3.7 [Accessible Authentication](https://www.w3.org/TR/WCAG22/#accessible-authentication) (AA)
* 3.3.8 [Accessible Authentication (Enhanced)](https://www.w3.org/TR/WCAG22/#accessible-authentication-enhanced) (AAA)
* 3.3.9 [Redundant Entry](https://www.w3.org/TR/WCAG22/#redundant-entry) (A)

while in the Table of Content and SC order is:
* 3.3.7 [Redundant Entry](https://www.w3.org/TR/WCAG22/#redundant-entry) (A)
* 3.3.8 [Accessible Authentication](https://www.w3.org/TR/WCAG22/#accessible-authentication) (AA)
* 3.3.9 [Accessible Authentication (Enhanced)](https://www.w3.org/TR/WCAG22/#accessible-authentication-enhanced) (AAA)

**Comment by alastc** [comment]
This was updated shortly after the CR publication, it is resolved for the next publication:
https://w3c.github.io/wcag/guidelines/22/#new-features-in-wcag-2-2
