### ISSUE TITLE
fix link to Input Purposes for user interface components section

### ISSUE THREAD

**Issue by robfentress** [w3c/wcag#3022]
The link to [Input Purposes for user interface components section](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose#input-purposes) on the[ Understanding SC 1.3.5](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose) now just points to a non-existent ID, whereas before it took you to a page that had a list of valid input tokens.

**Comment by alastc** [comment]
This is a duplicate of #2962, so closing.
