### ISSUE TITLE
2.4.6 Headings and Labels - inappropriate "Specific benefits" bullets?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#303]
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html contains the following bullet point under the "Specific Benefits of Success Criterion 2.4.6" section:

> * People who have difficulty using their hands or who experience pain when doing so will benefit from techniques that reduce the number of keystrokes required to reach the content they need.

I fail to see how this is related to 2.4.6, which deals solely with the quality of the text acting as headings/labels.

**Comment by patrickhlauke** [comment]
The only thing I can think of is that this is meant to mean something along the lines of "for these users, navigation can be more time consuming/difficult, so if headings are more descriptive, they're less likely to fruitlessly navigate to sections of a page that in the end don't contain the information they were after" or something...but in any case in its current state that bullet point feels more like a non-sequitur.

**Comment by patrickhlauke** [comment]
A fix would perhaps be to replace

>  that reduce the number of keystrokes required to reach the content 

with something along the lines of (admittedly verbose, but as a first stab at it)

> that will help them to more easily find the content they need, minimising the need for "wasted" keystrokes.

**Comment by devarshipant** [comment]
The fact that the third bullet refers to heading navigation and meaningful headings (when taken out of context), the second bullet, perhaps, can be rewritten to prepare readers for the third bullet as:
> People who have difficulty using their hands or experience pain when doing so will benefit when important text used to categorize a thought or an idea is constructed as a visible and structural heading. The resultant headings are discoverable using different modalities minimizing the need for keystrokes needed to reach the content users need.

**Comment by patrickhlauke** [comment]
However, this whole SC does not mandate that headings are marked as headings. This SC is purely about whether or not the text of the headings/labels is descriptive, not whether or not correct markup was used (as that's 1.3.1). So, even the third bullet

> This Success Criterion helps people who use screen readers by ensuring that labels and headings are meaningful when read out of context, for example, in a Table of Contents, or when jumping from heading to heading within a page.

is not quite appropriate here, as that's only true if headings are marked up as headings, labels as labels.

Lastly, it seems 

> This Success Criterion may also help users with low vision who can see only a few words at a time.

is meant to be a fourth bullet?

**Comment by devarshipant** [comment]
However, this whole SC does not mandate that headings are marked as headings. This SC is purely about whether or not the text of the headings/labels is descriptive, not whether or not correct markup was used (as that's 1.3.1). 

> Valid point. I do think any discussion around headings should infer that it is derived from its markup. Might help to reinforce this logic without redirecting readers to 1.3.1, meanwhile also explaining how the number of keystrokes can be reduced (original issue), if this bullet is rewritten.

> Yes, the third bullet need not be there. 

> Only a gripe, but 2.4.6 and 1.3.1 should co-exist under a single criterion to be understood properly. It can be a challenge to get the markup logic from 1.3.1 and then read 2.4.6 to receive guidance on making it descriptive.

**Comment by patrickhlauke** [comment]
To use a standards term...markup is orthogonal to the problem this SC tries to solve. i.e. I can evaluate whether or not a heading or label is good/appropriate/descriptive, regardless of whether or not it's marked up correctly. Those are two separate things to check, and I believe it's a good thing that's the case.

As an aside, I'll also note that, at least in the case of labels, there's also overlap between 2.4.6 and 3.3.2 Labels or Instructions...but that's a discussion for another day ;)

**Comment by alastc** [comment]
I think that point has been removed from the live version:
https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html  

No sign of "hands" anywhere.

**Comment by patrickhlauke** [comment]
so will the 2.0 version be fixed/made to match the 2.1 version? (i'm guessing so, based on the labels added?)

**Comment by alastc** [comment]
The WCAG 2.0 label is just to highlight which SCs something is associated with.

The 2.0 versions are going to be forwarded onto the new versions. Soon I hope, it is just a big task that is taking a while.
