### ISSUE TITLE
Editorial: dragging movement definition uses existing terms without linking & punctuation is slightly different

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#3036]
Hate opening an issue for a nit like this, but created a PR to make it easy to dispose of.

The definition "dragging movement" uses "down event" and "up event" terms without linking to the definitions that exist "down-event" and "up-event". Suggest adding the hyphen to the terms in this definition as well as links to the definitions of these events.

See pull request #3035 for the proposed changes.

**Comment by alastc** [comment]
Thanks, it's minor so I'll put it in for asynchronous approval (i.e. email).

**Comment by mbgower** [comment]
@alastc Do these links need to point to the definitions? https://www.w3.org/TR/WCAG22/#dfn-up-event
https://www.w3.org/TR/WCAG22/#dfn-down-event

I added a suggestion to the PR to address that.

**Comment by alastc** [comment]
https://github.com/w3c/wcag/pull/3035 merged
