### ISSUE TITLE
Incorrect Accessible Authentication 3.3.8 / 3.3.9 document

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#3061]
[There's an incorrect Accessible Authentication document online](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-no-exception) that needs to be removed. The correct documents are:
- [Accessible Authentication](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication)
- [Accessible Authentication (Enhanced)](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced)

I don't see the offending document [in the repo](https://github.com/w3c/wcag/tree/main/understanding/22), so can't deal with this myself.

**Comment by alastc** [comment]
If those are the old (pre-renamed) versions I think @michael-n-cooper will need to do a clear-out when publishing next time.

**Comment by michael-n-cooper** [comment]
I redirected the page to accessible-authentication.
