### ISSUE TITLE
Understanding Conformance - Missing section "Key Terms"?

### ISSUE THREAD

**Issue by luce-carevic** [w3c/wcag#3066]
On the [old Understanding Conformance page](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-conf-req1-head) there is a Key Terms section that is missing on the [new one](https://www.w3.org/WAI/WCAG21/Understanding/conformance#dfn-process).

However in the Page Content navigation the section is mentioned.

![page contents screenshot](https://user-images.githubusercontent.com/6073336/221349266-66f69e9d-c3d1-4f36-aed6-6024943574b5.png)

**Comment by alastc** [comment]
I think this is the same issue as the previous one, the anchor links are broken because the key terms section is missing.
