### ISSUE TITLE
Recommendation of EARL

### ISSUE THREAD

**Issue by rbenson** [w3c/wcag#307]
Looking at the Conformance page (http://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-conformance-claims-head) it makes reference to using EARL to report conformance. Should this be reviewed since the status of EARL is a Last Call: Working Draft vs CR/PR and the WG is [shut down](http://www.w3.org/WAI/ER/charter4)?

**Comment by alastc** [comment]
The short answer is no, the status of [EARL](https://www.w3.org/WAI/standards-guidelines/earl/) is:
> published as non-normative W3C Working Group Notes.

If there is no active work, the WG would be shut down, but that doesn't mean the note is invalid.

If there are updates to be made, that is within the scope of the [AGWG charter](https://www.w3.org/2017/01/ag-charter).
