### ISSUE TITLE
Outdated threshold for sRGB companding in the "relative luminance" definition

### ISSUE THREAD

**Issue by peteroupc** [w3c/wcag#308]
The value 0.03928 (as used in what was formerly a note to the "relative luminance" definition but what is now a "normative" part of that definition) comes from the sRGB proposal.   This is outdated and either 0.04045 or 12.92 * 0.0031308 = 0.040449936 (I don't know which is used in the IEC standard) should appear in its place.

I understand, however, that all three thresholds don't make a difference in the results if only 8-bit linear sRGB values are involved. On the other hand, if no change to the 0.03928 threshold is planned soon, a note on the origin of that threshold should be added to the document.

**Comment by awkawk** [comment]
closing because the WG will track in the WCAG21 repo (linked above)
