### ISSUE TITLE
Add "(Minimum)" to 3.3.8 Accessible Authentication?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#3087]
All other pairs of SCs use "(Minimum)" and "(Enhanced)".:

* 1.4.3 Contrast (Minimum) and 1.4.6 Contrast (Enhanced)
* 2.4.12 Focus Not Obscured (Minimum) and 2.4.13 Focus Not Obscured (Enhanced)
* 2.5.8 Target Size (Minimum) and 2.5.5 Target Size (Enhanced)

3.3.8 is currently the odd one out:

* 3.3.8 Accessible Authentication and 3.3.9 Accessible Authentication (Enhanced)

For consistency, suggest that 3.3.8 gets the "(Minimum)" postfix as well

**Comment by patrickhlauke** [comment]
adding some historical context: originally 3.3.9 was "Accessible Authentication (No Exception)", so that followed the existing pattern where only the AAA has a qualifier in brackets. but since, it has been changed to "(Enhanced)", but 3.3.8 wasn't changed at  the same time...

**Comment by patrickhlauke** [comment]
apologies @cwadamsoforacle ... only just seen https://github.com/w3c/wcag/pull/3132 ... but I think this one's more complete/supersedes it

**Comment by alastc** [comment]
Added in #3132

**Comment by patrickhlauke** [comment]
@alastc please also have a look at https://github.com/w3c/wcag/pull/3145 which I think touches/fixes a few more stray bits that #3132 doesn't
