### ISSUE TITLE
Accessible authentication and copying between devices

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#3095]
There seems to be an open question when it comes to one-time codes (OTCs) and copying between systems to authenticate. If for example I receive an OTC via text message, I could copy it to authenticate if 1. I'm authenticating on my phone, or 2. I have my devices linked such that I have a shared clipboard.

The SC doesn't provide guidance on how to decide when copying OTPs is allowed. If we take a strict reading you could argue that it's never allowed, because you can't know for sure that copying is possible. That doesn't seem right, as it basically prohibits OTPs altogether. A more generous reading would be that WCAG is about web content alone. How the OTP gets into the clipboard is out of scope and the only thing that matters for WCAG 2.2 conformance is that pasting isn't prevented by the page itself.

I'm not keen on either of these, and would hope there's some kind of middle ground I'm not thinking of. If I had to pick between the two I think the "WCAG is not about how the OTP gets into the clipboard" reading of this seems the more defensible to me. That does contradict some of the wording in the current understanding document. If we can't provide clearer guidance I think we should think of that more as advisory work, rather than required by the SC.

**Comment by patrickhlauke** [comment]
> If I had to pick between the two I think the "WCAG is not about how the OTP gets into the clipboard" reading of this seems the more defensible to me.

Agree - I quite like this approach, as it cleanly demarcates where our concern starts/ends. If a client then wants to start arguing "oh, they CAN get it to their clipboard, all they have to do is... [insert super convoluted steps to go from one device to another]" then they can defend that themselves in court when it comes to it.

> That does contradict some of the wording in the current understanding document.

happy to make a strawman PR for this to work on if the above direction is where we want to go.

**Comment by patrickhlauke** [comment]
Similarly, I probably want to revisit some of the wording about those "Log in with device" / passwordless approaches (e.g. where you need to confirm on one device that it's indeed you who is trying to log into a system/site on another device - see for instance https://bitwarden.com/blog/access-your-bitwarden-vault-without-a-password/, or the way Google lets you confirm in YouTube - which is odd - on an Android device whether or not it's you trying to log onto gmail on your laptop).

We're similarly not concerned directly whether or not that "other device" where you confirm is accessible/doing it accessibly per se, unless that app/system on that other device is also being assessed/audited. Will ruminate on this...

**Comment by rachaelbradley** [comment]
@patrickhlauke I believe we want to  propose the "WCAG is not about how the OTP gets into the clipboard" approach and update the understanding. Do you have time to make that strawman PR in the next few days? If not, I will do so.

**Comment by patrickhlauke** [comment]
> Do you have time to make that strawman PR in the next few days?

sure

**Comment by patrickhlauke** [comment]
@rachaelbradley @WilcoFiers made an initial stab https://github.com/w3c/wcag/pull/3150
