### ISSUE TITLE
metadata needs to be consistent #321

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#311]
Adding this from @lseeman to WCAG 2.0 issues and further discussion on metadata harmonisation with WCAG 2.0. [1]

Our discussion on metadata and usage on it needs to be harmonized
For example
https://www.w3.org/TR/UNDERSTANDING-WCAG20/appendixC
needs to include issue 6 OR it could limit the scope by changing the title to "about metadata in conformance claims"

[1] https://github.com/w3c/wcag21/issues/321

**Comment by alastc** [comment]
Hi @lseeman, I'm going over old issues, could you explain what issue 6 is, or is this now defunct?
