### ISSUE TITLE
Identify Input Purpose link doesn't redirect to "Input Purposes for user interface components section"

### ISSUE THREAD

**Issue by maia-miller** [w3c/wcag#3119]
In the definition of 1.3.5 Identify Input Purpose, the phrase in the second bullet "Input Purposes for user interface components section" redirects to an anchor that doesn't exist on the page.

It's supposed to link to this page: https://www.w3.org/TR/WCAG21/#input-purposes

**Comment by msayoung** [comment]
Duplicate of:  https://github.com/w3c/wcag/issues/2962

**Comment by patrickhlauke** [comment]
Indeed, duplicate. Closing this one in favour of #2962
