### ISSUE TITLE
Browser widths when testing SC 1.4.12 Text spacing

### ISSUE THREAD

**Issue by sarasuri** [w3c/wcag#3124]
Hi,

Question on SC 1.4.12 Text spacing

We are trying to determine, when testing the SC 1.4.12 Text spacing, do we need to test in different browser widths as the success criterion doesn’t explicitly mention anything on that. 

The question is when I apply required CSS rules to change the line height, letter, word spacing in the content of a web page, it looks fine in larger browser widths, However, in smaller browser widths, for example, 680px, at that point I noticed some text overlaps, text cut off on the page. 

Is it considered as a failure for SC 1.4.12 Text spacing that it has issues in smaller browser widths?

Thank you

**Comment by patrickhlauke** [comment]
As the SC does not specify any particular viewport/browser dimension, the SC must be met at all possible sizes

**Comment by patrickhlauke** [comment]
yes

**Comment by JAWS-test** [comment]
See https://www.w3.org/TR/WCAG21/#issue-container-generatedID-32

**Comment by alastc** [comment]
@sarasuri It appears your question is answered, so I'll close this.
