### ISSUE TITLE
G219 for 2.5.7 Dragging Movement is misleading

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#3128]
The title of G219 currently reads: "Ensuring that a single pointer alternative is available for dragging movements that operate on content"

This is slightly misleading, because it seems to suggest that dragging movements *aren't* single pointer, when in fact they are/can be.

Suggest rewording to be more specific/clear: "Ensuring that a non-dragging-based single pointer alternative is available for dragging movements that operate on content"

EDIT: same issue is present in the actual body of the technique, making a false dychotomy between "single pointer" and "dragging movements".

https://www.w3.org/WAI/WCAG22/Techniques/general/G219

**Comment by detlevhfischer** [comment]
@alastc I think this is a straight-forward improvement  / clarifcation - ready for survey?

**Comment by alastc** [comment]
I was going to suggest a slightly shorter title, but looking at the PR that's what Pat did. Going into survey...
