### ISSUE TITLE
Move privacy and security considerations to a separate section

### ISSUE THREAD

**Issue by pes10k** [w3c/wcag#3135]
This review is part of a requested [PING review](https://github.com/w3cping/privacy-request/issues/112)

Currently the spec identifies a number of security and privacy concerns, mostly in note-sections throughout the text. It would be good to either move these to and/or summarize them in a separate top-level Security and Privacy concerns section, to both i. match the format w3c specs and documents are moving to, and to ii. easily allow a reader to understand at a high level the privacy risks and issues dealt with.

cc @LJWatson @sandandsnow

**Comment by awkawk** [comment]
@alastc 

We could add:
5.6 Privacy Considerations
Success Criteria within this specification that have normative text or notes which relate to privacy are:

- 2.2.6 Timeouts (AAA)

5.7 Security Considerations
Success Criteria within this specification that have normative text or notes which relate to security are:

- 2.5.6 Concurrent Input Mechanisms (AAA)
- 3.3.3 Error Suggestion (AA)
- 3.3.7 Redundant Entry (A)

**Comment by alastc** [comment]
Find an [example of another spec](https://www.w3.org/TR/2023/CRD-core-aam-1.2-20230518/#privacy-considerations) which does this.

**Comment by mbgower** [comment]
Although the word "security" is not used in the normative text, I think Accessible Authentication is a possible candidate?

**Comment by patrickhlauke** [comment]
left a comment over on the PR, but worth adding a reference to it here for visibility https://github.com/w3c/wcag/pull/3215#issuecomment-1563567893

**Comment by mraccess77** [comment]
What about 1.3.5 as that comes up?

**Comment by patrickhlauke** [comment]
I was half thinking about 1.3.5, but the SC itself doesn't necessarily bring up security concerns. it's the (most common and only really viable) implementation in HTML of using the `autocomplete` that often causes (unwarranted, in my view) concern
