### ISSUE TITLE
Broken link in definition of 1.1.1 Non-text Content WCAG2.1

### ISSUE THREAD

**Issue by maia-miller** [w3c/wcag#3137]
In the definition of 1.1.1 under the heading "Controls, Input", there is a link that is probably meant to go to Success Criterion 4.1.2 (https://www.w3.org/WAI/WCAG21/Understanding/name-role-value) but instead it adds an anchor # to the url and goes nowhere (https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html#name-role-value)

**Comment by avkuo** [comment]
@bruce-usab @iadawn This issue appears fixed in WCAG2.2 but not 2.1

**Comment by bruce-usab** [comment]
On the listserv, @iadawn asks [Has it been discussed whether or not to update 2.1 understanding documents at the same time as we are updating 2.2 docs](https://lists.w3.org/Archives/Public/public-wcag2-issues/2024May/0000.html)?

Yes, and the TF would like do so.  That's contingent upon it not being a heavy lift.

**Comment by kfranqueiro** [comment]
This is resolved now that WCAG 2.1 Techniques and Understanding Docs have been republished via the new build system, made possible by https://github.com/w3c/wcag/pull/4007.
