### ISSUE TITLE
Heading and its content tagged under two anchor tag with same destination is it the issue of 3.2.4 consistent identification 

### ISSUE THREAD

**Issue by PrashantChahal1** [w3c/wcag#3142]
Let take an Example:
About Us
We are a company that specializes in creating web applications.

Is this is issue of 3.2.4 Consistent identification?

My answer is: yes, this is an issue of 3.2.4 consistent identification.
To meet the success criterion, the link text for both the heading and the content should be consistent.

To make the link text consistent, we could modify the code to use the same text for both the heading and the content links. For example:

About Us
About Us – We are a company that specializes in creating web applications.

In this modified code, the link text for both the heading and the content links is “About Us”, which makes the link text consistent.

**Comment by patrickhlauke** [comment]
if you read over https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification you'll see that no, this is not an issue of 3.2.4

**Comment by PrashantChahal1** [comment]
But there is an example 6 present in that https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification

Example 6: Icon and adjacent link to same destination

An icon with alt text and a link are next to each other and go to the same location. The best practice would be to group them into one link as per H2: Combining adjacent image and text links for the same resource. However if they are visually positioned one above the other but separated in the source, this may not be possible. To meet the Success Criterion, the link text for these two links need only be consistent, not identical. But best practice is to have identical text so that when users encounter the second one, it is clear that it goes to the same place as the first.
