### ISSUE TITLE
Guideline pages are incorrectly identified as "success criteria"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag#3160]
## Currently

Guideline example: https://www.w3.org/WAI/WCAG21/Understanding/compatible

- Text in an `<h1>` element says "Understanding SC 4.1"
- Text in a `<header>` element says "Success Criterion (SC)". This is followed by the text of the guideline.

This is inaccurate because [a guideline is not a success criterion](https://www.w3.org/TR/WCAG21/#wcag-2-layers-of-guidance).

![Screenshot of the above Guideline example](https://user-images.githubusercontent.com/3124805/234226839-b1c3c109-9571-4606-82f4-2936bf7f0bb9.png)

## Proposed

Corrections for the above example:

* Text in the `<h1>` element should be "Understanding Guideline 4.1"
* Text in the `<header>` element should be "Guideline" — or consider omitting this header from Guideline pages.

Apply similar corrections to all Guideline pages.

**Comment by awkawk** [comment]
This is something that Michael may need to address. The Understanding template (https://github.com/w3c/wcag/blob/main/understanding/understanding-template.html) hard-codes the incorrect text and will need to be adjusted.
