### ISSUE TITLE
JSON: No metadata to determine in which version an SC is removed

### ISSUE THREAD

**Issue by bramd** [w3c/wcag#3205]
Since SC 4.1.1 is removed in WCAG 2.2, it might be useful to have that in a machine readable format in the wcag.json file.

Now it is only clear from the text of the SC and the human readable name that this SC is removed. If we ever remove more criteria in WCAG 2.x, it might also be relevant in which version an SC has been removed. I would suggest adding a `removedInVersion` field to removed SCs. We could also rename version to addedInVersion to make the fields more consistant, but this may break existing software using this JSON format.

**Comment by alastc** [comment]
@michael-n-cooper - suggestion for the JSON version, I assume that would be generated?
