### ISSUE TITLE
Editorial correction in Understanding Reflow

### ISSUE THREAD

**Issue by sidnc86** [w3c/wcag#321]
Under the section "Intent of this Success Criterion", there is a text content that starts like "Avoiding the need to scroll in the direction of reading in order to reveal lines that are cut off by the viewport is important, because such scrolling signiicantly increases the effort required to read."
The spelling of "signiicantly" needs to be corrected to "significantly"

**Comment by sidnc86** [comment]
This issue is filed for the latest WCAG 2.1 guidelines. I had gone through the WCAG 2.1 repository as well but the repository mentions to file new issues out here on this repository. The readme out here suggests to find the latest working branch. That is getting confusing. Additionally, I can't find the HTML page corresponding to the Understanding Reflow page. But I found that out there in WCAG 2.1 repo. So if I were to send out a pull request to this fix, how do I go about it? WCAG 2.1 readme narates it very well. But I'm not sure whether to fix stuff in WCAG 2.1 repo or in WCAG 2.0 repo.

**Comment by sidnc86** [comment]
Optionally, I can recreate this issue on WCAG 2.1 repo if that is the way to approach it.

**Comment by awkawk** [comment]
I'll just fix it instead: https://github.com/w3c/wcag21/commit/6a54f9c3443bca9119ad786f49a98c44d9f09fee

We are in the process of moving the files to the WCAG repo, so this should become more clear soon.

**Comment by sidnc86** [comment]
Oh ok! Didn't realise that you had responded. I have created issue 953 also followed by 954 on WCAG 2.1 repo. Should I copy that one (954) back here?

**Comment by awkawk** [comment]
just opening them in the wag repo is fine.
