### ISSUE TITLE
Editorial issue with Concurrent Input Mechanisms

### ISSUE THREAD

**Issue by sidnc86** [w3c/wcag#322]
The heading level 2 ("Benefits") is appearing right after heading level 2 ("Intent of this Success Criterion") and before the paragraph corresponding to "Intent of this Success Criterion."

**Comment by alastc** [comment]
I think this was a temporary issue, it has been resolve. (I can't see it in [the understanding doc](https://www.w3.org/WAI/WCAG21/Understanding/concurrent-input-mechanisms.html).)
