### ISSUE TITLE
Minor clarity around a "change initiated by the user"

### ISSUE THREAD

**Issue by scottaohara** [w3c/wcag#3226]
In reviewing the 3.2.6 consistent help text, the question came up about what the expectations would be for the location of help / what's even offered as help when a user is interacting with a logged in version of a website vs a logged out version.   e.g., in a logged out version there's one location/form of help.  and in a logged in version that information and potentially even location changes because legit reasons.

To me, this sort of variation could be covered under "a set of web pages" - as while it's not explicitly stated there, I would infer from the e-commerce example that a logged out version of a website would be one set of pages - while a logged in version would constitute another set - so if a variance was found, that'd be ok so long as there was consistency for all logged in versions of the pages, and consistency for all logged out versions of the pages, but not necessarily with each other.  (if i'm wrong on this, please let me know, as while not the primary purpose of this issue, hey, i'd like to be corrected if needed)

But in talking through that, it was mused that logging into a website sure sounds like "a change initiated by a user".  Being an undefined term/phrase, I could see why one could reasonably come to that conclusion.  Being that this is phrase is used twice now in normative text, but its meaning is only expanded on in the understanding documents / as a note for consistent help, should this be defined as a term instead - e.g., so as to at least consistently call out its intent is around a user modifying the web page by use of zooming, orientation changing, possibly due to a browser setting of some other kind?, etc..  - And (assuming) not due to logging into a website, or changing a setting of the website itself - which are still changes initiated by the user, but not in the context of how this phrase has been described in its two uses?

**Comment by scottaohara** [comment]
thanks @alastc appreciate your thoughts here.

>Overall, the intent was for user-agent driven changes, such as zoom...

and that's what i came to realize after reviewing the notes / informative docs for these two SCs, but that's why I was wondering if it didn't make sense to formally define that.  So as to mitigate such random musings of "well, a user interacting with the website could result in / be considered a change initiated by the user"

**Comment by alastc** [comment]
Discussion in the WCAG backlog meeting:

- The second note covers the intent pretty well.
- Mixed opinions on whether a login would intrinsically count as a 'change initiated by the user'. It depends on the results rather than the action of login.
- We could add some content around 'change initiated by the user'. E.g. highlight what the changes might entail.

**Comment by bruce-usab** [comment]
Add some examples to Understanding per backlog call 8-18.

**Comment by dbjorge** [comment]
I'll create a PR that updates the understanding document with a paragraph of explanation + example

**Comment by scottaohara** [comment]
thanks @alastc - i am good with the update, it addressed the concerns of those I was filing the issue for.
