### ISSUE TITLE
.github/workflows/notification.yml

### ISSUE THREAD

**Issue by VesnaGajic** [w3c/wcag#3251]
Can I get coin 🪙 or money 💰

**Comment by VesnaGajic** [comment]
![Screenshot_20230615_160436_Document Viewer](https://github.com/w3c/wcag/assets/121808378/d2401c3d-4f89-4242-9bb7-36a0796a03d6)

**Comment by alastc** [comment]
Spam, closing.

**Comment by alastc** [comment]
@patrickhlauke I don't have blocking powers, but have reported to github.
