### ISSUE TITLE
[21 Techniques index page] fix text : Failures -> Techniques

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag#3256]
For https://www.w3.org/WAI/WCAG21/Techniques/ , in the page contents list, change
```<li><a href="#general">General Failures</a></li>```
to
```<li><a href="#general">General Techniques</a></li>```

_(as in https://github.com/w3c/wcag/pull/3109 which fixed https://www.w3.org/WAI/WCAG22/Techniques/)_

**Comment by bruce-usab** [comment]
Ping to @iadawn via @avkuo and the wcag2-issues tf.  The correction is merged, but change is not public facing.  Please advise.

**Comment by kfranqueiro** [comment]
This is resolved now that WCAG 2.1 Techniques and Understanding Docs have been republished via the new build system, made possible by https://github.com/w3c/wcag/pull/4007.
