### ISSUE TITLE
Can an icon button label a field by itself?

### ISSUE THREAD

**Issue by kimviens** [w3c/wcag#3276]
Hello everyone,

I was reading over the [Technique G167: Using an adjacent button to label the purpose of a field](https://www.w3.org/WAI/WCAG22/Techniques/general/G167#tests). I noticed that each example for the button, the button contained text. Therefore, I was wondering if a button who's only content is an icon, like a magnifying glass for "Search", would be sufficient for this technique? 

Here is a code example:
`<input type="text" name="search" id="search">`
`<button type="submit" aria-label="Search"><i class="search"></i></button>`

**Comment by patrickhlauke** [comment]
yes

**Comment by kimviens** [comment]
Excellent, thank you!
