### ISSUE TITLE
Link to "programmatically determined " not working

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#328]
[https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose)

The link to "programmatically determined" from this page doesn't work.

Probably needs to be `<a href="https://www.w3.org/TR/WCAG21/#dfn-programmatically-determinable">`  instead of `<a href="https://www.w3.org/TR/WCAG21/#dfn-programmatically-determined">`

**Comment by jake-abma** [comment]
This one still doesn't work.

**Comment by alastc** [comment]
Odd, it isn't content that is in the understanding doc itself, and if the definitiona works in the spec it should work elsewhere as well. Assigning to Michael as the XSLT master...

**Comment by patrickhlauke** [comment]
i'm guessing that when it's in the same document, it's picked up automagically that the definition is actually  anchored on "programmatically determinable" even though the visible wording is "programmatically determined"

```
<dfn data-lt="programmatically determinable">programmatically determined</dfn>
```

whereas when it's in a separate document like the understanding, it thinks it's that exact wording.

as i don't see any other place in the spec that actually tries to use make an automagic link from the wording "programmatically determinable", the simplest solution may be to just remove the `data-lt="..."` attribute and let the fragment identifier actually be `#programmatically-determined` (and update any external documents that do link to `#programmatically-determinable`)

**Comment by patrickhlauke** [comment]
or perhaps something like this (not sure how kosher that would be)

```
<dt><dfn>programmatically determined</dfn> (<dfn>programmatically determinable</dfn>)</dt>
```

to make both work

**Comment by alastc** [comment]
The bit in the XSL template that converts it is:

```
	<xsl:template match="term" mode="key-terms">
		<dt id="{id}"><xsl:value-of select="name[1]"/></dt>
		<dd><xsl:apply-templates select="definition"/></dd>
	</xsl:template>
```
And the `key-terms` is scattered throughout the understanding-doc builder, I'm not inclined to change it and hope, I don't have a local build env for my work laptop.

**Comment by alastc** [comment]
Also, noticing the duplicate issues for this page from #336, so adding:
<hr>
https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose

Link to user agents doesn't work:

    Key Terms
    programmatically determined
    determined by software from author-supplied data provided in a way that different user agents

A "s" is missing

    https://www.w3.org/TR/WCAG21/#dfn-user-agent

needs to be

    https://www.w3.org/TR/WCAG21/#dfn-user-agents

NOTE: agents in URL but agent in title

<hr>

https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose

Link to assistive technologies doesn't work:

Key Terms
programmatically determined
determined by software from author-supplied data provided in a way that different user agents, including assistive technologies, can extract and present this information to users in different modalities

A "s" is missing (dfn-assistive-technology => dfn-assistive-technologies")

https://www.w3.org/TR/WCAG21/#dfn-assistive-technology

needs to b

https://www.w3.org/TR/WCAG21/#dfn-assistive-technologies

NOTE: dfn-assistive-technologies in URL but **assistive technology ** in title

**Comment by awkawk** [comment]
@michael-n-cooper
