### ISSUE TITLE
Duplicate "Test rules" links in TOC, missing "Examples" section and TOC link

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#3285]
The understanding docs which have a 'test rules' heading (e.g. [1.2.5](https://w3c.github.io/wcag/understanding/audio-description-prerecorded)) have a duplicate 'test rules' link in the right-side table of contents links.

**Comment by patrickhlauke** [comment]
In addition, the link to "Examples" is missing.

**Comment by patrickhlauke** [comment]
@iadawn all of them, unless i'm missing something. e.g. https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html has no "Examples" section, but that is present in the source https://github.com/w3c/wcag/blob/main/understanding/20/non-text-content.html#L237

**Comment by iadawn** [comment]
Hmm... curious. I found at least one that does have the Examples section and link: https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html

Will investigate further

**Comment by patrickhlauke** [comment]
could it be that the generator script is expecting the `<ul>`, whereas we (well I ... think I have a hanging PR somewhere to change it everywhere) have switched to using `<dl>` ?

**Comment by iadawn** [comment]
Could be! ... I have updated the XSLT to accept DL as well. Just wait for someone to use something else now ;)
