### ISSUE TITLE
Understanding docs no longer link back to the spec

### ISSUE THREAD

**Issue by scottaohara** [w3c/wcag#3288]
here is a version from the [web archive where 1.1.1](http://web.archive.org/web/20190322213913/https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html) has intro text that links back to the SC,

If you look through each understanding doc from the wayback machine links, you'll find that every single Understanding Doc started with the normative text, where the first bit of text in each one was "Success Criterion [number/name] (Level X)" - and the number/name text linked back to the primary specification.

that doesn't exist in the newest versions.

Additionally, I've noticed direct links to SCs, such as 4.1.2 in the SC text of [1.1.1 in the current docs](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html#name-role-value) do not link anywhere anymore, where they used to link to the SC in the official spec.

**Comment by scottaohara** [comment]
new related issues:

- https://github.com/w3c/wcag/issues/3293
- https://github.com/w3c/wcag/issues/3292

**Comment by patrickhlauke** [comment]
Making https://github.com/w3c/wcag/issues/3289 the canonical version and closing this as a duplicate.
