### ISSUE TITLE
3.2.2 On Focus - Can changes of context include text cursor tracking?

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#3329]
Are unexpected changes in cursor position, such as text cursor, considered a change in context? Some users could have text cursor or narrator cursor tracking turned on in Windows Screen Magnifier. For example, turning on text cursor allows those users to follow each character along as it is typed. An unexpected change in text cursor can be disorienting and disruptive to that task of entering data, or any task.

Is this what is meant by a change in [ "viewport"](https://www.w3.org/WAI/WCAG21/Understanding/on-input.html#dfn-viewport)?

![Untitled](https://github.com/w3c/wcag/assets/2318561/6e00b305-ad10-4f09-9be7-1882f38e2dbd)

**Comment by patrickhlauke** [comment]
> An unexpected change in text cursor can be disorienting and disruptive

example?

**Comment by avkuo** [comment]
@anevins12 , the issue appears to be addressed in the comments. But if not, Please provide any update, or close if it is no longer an issue.
