### ISSUE TITLE
Provide exception/limitation text for visual/presentation text

### ISSUE THREAD

**Issue by aphillips** [w3c/wcag#3337]
https://www.w3.org/TR/WCAG22/#visual-presentation

Section 1.4.12 (https://www.w3.org/TR/WCAG22/#text-spacing) provides an exception that says:

> Exception: Human languages and scripts that do not make use of one or more of these text style properties in written text can conform using only the properties that exist for that combination of language and script.

Section 1.4.8 provides no exception or note about the applicability of this SC to various languages. We think this is a "root cause" for much of the discussion in #2680, since we note that WCAG maintains that pages are compliant if they allow users to override the various presentational values up to certain limits without rendering failure, but users of various writing systems do not understand the relationship of the SC to their own needs.

One question on I18N's mind is whether WCAG intends these criteria to apply primarily to the Latin-script writing system, with others adapting as needed, or whether these criteria have been successfully used in other writing systems (and which ones?)

We would suggest that 1.4.8 include a similar "exception", although given the description of this SC in #2680, perhaps just a note of explanation. Perhaps something like:

> Some writing systems have additional or different requirements or do not customarily use features such as paragraph spacing. Users thus might not use some of these mechanisms. They also might wish to apply values that are larger or smaller than those found here. Some writing systems might also benefit from additional mechanisms, such as the ability to adjust paragraph start indentation.

**Comment by aphillips** [comment]
I didn't file issues related to line and paragraph spacing, as they seemed to be addressed by the comment above. For posterity, though, we had some discussion of line/paragraph spacing:

---
> Line spacing (leading) is at least space-and-a-half within paragraphs

Some writing systems expect larger inter-line gaps than others. @kidayasuo mentioned that case for Japanese in https://github.com/w3c/wcag/issues/2680#issuecomment-1252083642 and @yyyug mentioned the case for Chinese in https://github.com/w3c/wcag/issues/2680#issuecomment-1666380598 . Moreover, for Traditional Chinese, if the Bopomofo annotation mark is taller than the base character, the line spacing may need to be increased further.

Moreover, the complexity of characters in some Brahmic scripts may affect line height settings too. See [Tamil](https://www.w3.org/International/ilreq/tamil/#baselines) and [Thai](https://www.w3.org/International/sealreq/thai/#baselines) for examples.

>    paragraph spacing is at least 1.5 times larger than the line spacing.

Some writing systems prefer to indent the first line of a paragraph, rather than leave vertical gaps between paragraphs, like [Chinese](https://www.w3.org/TR/clreq/#first_line_indents) and [Japanese](https://www.w3.org/TR/jlreq/#line_head_indent_at_the_beginning_of_paragraphs).

We should change the guideline to something like this:

>    paragraph spacing is at least 1.5 times larger than the line spacing. For languages or writing systems which don't use paragraph spacing, similar mechanisms like first-line indent should be used to make sure the user recognizes the beginning of a new paragraph.

@aphillips made a comment: 
> I am not sure about this recommendation in part because I don't know what the space is supposed to do and whether the recommendation might apply (be valuable) to other writing systems which might normally set paragraphs solid.

**Comment by alastc** [comment]
As part of discsussions between i18n and the AG chairs we're proposing to add a note (or notes) under visual presentation.

I've drafted an initial note in #3351 

Another aspect for Visual Presentation is that the groupd does not recommend requiring all level AAA criteria, that might ease the concern of some objectors.
 
As something to point to, in WCAG under conformance there is a [section on conformance levels](https://www.w3.org/TR/WCAG22/#cc1) which includes this note:
> It is not recommended that Level AAA conformance be required as a general policy for entire sites because it is not possible to satisfy all Level AAA Success Criteria for some content.
