### ISSUE TITLE
Link to understanding contrast minimum in note 3 of relative luminance definition is broken

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#3342]
https://w3c.github.io/wcag/guidelines/22/#dfn-relative-luminance

> NOTE 3
> Almost all systems used today to view Web content assume sRGB encoding. Unless it is known that another color space will be used to process and display the content, authors should evaluate using sRGB colorspace. If using other color spaces, see [Understanding Success Criterion 1.4.3](https://w3c.github.io/wcag/guidelines/22/contrast-minimum).

that last link is broken

**Comment by alastc** [comment]
I have a feeling that is one of those things that works when it is published, but hard to tell. @iadawn can you tell from a locally built versioin?
