### ISSUE TITLE
Link to user agents doesn't work

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#336]
[https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose](url)

Link to user agents doesn't work:

> Key Terms
> programmatically determined
> determined by software from author-supplied data provided in a way that different user agents

A "s" is missing

> https://www.w3.org/TR/WCAG21/#dfn-user-agent 

needs to be

> https://www.w3.org/TR/WCAG21/#dfn-user-agents

NOTE: **agents** in URL but **agent** in title

**Comment by jake-abma** [comment]
still not fixed

**Comment by alastc** [comment]
from #337 

https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose

Link to assistive technologies doesn't work:

    Key Terms
    programmatically determined
    determined by software from author-supplied data provided in a way that different user agents, including assistive technologies, can extract and present this information to users in different modalities

A "s" is missing (dfn-assistive-technology => dfn-assistive-technologies")

    https://www.w3.org/TR/WCAG21/#dfn-assistive-technology

needs to b

    https://www.w3.org/TR/WCAG21/#dfn-assistive-technologies

NOTE: dfn-assistive-technologies in URL but **assistive technology ** in title

**Comment by alastc** [comment]
Closing as duplicate.
