### ISSUE TITLE
Where is the WCAG 2.2 equivalent of WCAG 2.1 2.4.11 focus appearance minimum?

### ISSUE THREAD

**Issue by mcking65** [w3c/wcag#3368]
[WCAG 2.1 SC 2.4.11](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html), which is AA,  includes requirements for the contrast ratios of focus indicators:

>* Has a contrast ratio of at least 3:1 between its pixels in the focused and unfocused states; 
>* Has a contrast ratio of at least 3:1 against adjacent colors. 

These requirements are not present in [WCAG 2.2 SC 2.4.11](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum), nor can I find them in any other WCAG 2.2 AA SC. I assume they must exist because the paragraph about WCAG 2.2 backward compatibility does not mention removal of AA contrast requirements for focus indicators:

>WCAG 2.2 builds on and is backwards compatible with WCAG 2.1, meaning web pages that conform to WCAG 2.2 are at least as accessible as pages that conform to WCAG 2.1. Requirements have been added that build on 2.1 and 2.0. WCAG 2.2 has removed one success criterion, 4.1.1 Parsing. Authors that are required by policy to conform with WCAG 2.0 or 2.1 will be able to update content to WCAG 2.2, but may need to continue to test and report 4.1.1.

Can someone please point me to a AA requirement in WCAG 2.2 that includes contrast requirements for focus indicators?

BTW, I have always wondered why contrast for focus indicators was not baked into [2.4.8 for focus visibility](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible). For that matter, why not bake in the requirement for not being obscured into 2.4.8. It seems to me that there is a lot of unnecessary complexity created by breaking visibility into so many different constituent elements. I don't understand what value that gives to WCAG stakeholders.

**Comment by patrickhlauke** [comment]
there is no WCAG *2.1* 2.4.11 - your link goes to and outdated file from an earlier version of WCAG 2.2. which has since been abandoned (but hasn't been deleted yet, for silly technical reasons)

**Comment by patrickhlauke** [comment]
> BTW, I have always wondered why contrast for focus indicators was not baked into [2.4.8 for focus visibility](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible). For that matter, why not bake in the requirement for not being obscured into 2.4.8.

assuming you mean 2.4.7. and the reason why is that it's too late now to change that existing SC from 2008. and back then it was not considered.

**Comment by patrickhlauke** [comment]
> Can someone please point me to a AA requirement in WCAG 2.2 that includes contrast requirements for focus indicators?

1.4.11 Non-text Contrast
