### ISSUE TITLE
Link to assistive technologies doesn't work

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#337]
[https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose](url)

Link to assistive technologies doesn't work:

> Key Terms
> programmatically determined
> determined by software from author-supplied data provided in a way that different user agents, including assistive technologies, can extract and present this information to users in different modalities

A "s" is missing (dfn-assistive-technology => dfn-assistive-technologies")

> https://www.w3.org/TR/WCAG21/#dfn-assistive-technology

needs to b

> https://www.w3.org/TR/WCAG21/#dfn-assistive-technologies

NOTE: **dfn-assistive-technologies** in URL but **assistive technology ** in title

**Comment by jake-abma** [comment]
still not working

**Comment by alastc** [comment]
Same basic issue as #336 , dealing with it there.
