### ISSUE TITLE
Organization of Sections 5.4 and 5.5 

### ISSUE THREAD

**Issue by joanlambert** [w3c/wcag#3394]
It seems odd that 5.4 Statement of Partial Conformance - Third Party Content and 5.5 Statement of Partial Conformance - Language are standalone x.y-level entries. Organizationally, they should be third-level (5.3.3 and 5.3.4) under Conformance Claims or at a stretch, 5.4 should be Statements of Partial Conformance with these two nested as 5.4.1 and 5.4.2.

None of the x.y-level entries in section 5 are labeled as guidelines, presumably because section 5, although numbered in parallel with the guidelines and success criteria, doesn't contain the same type of content as sections 1-4. That is another inconsistency. The section content is short but I assume you want each paragraph to have a reference number.

**Comment by awkawk** [comment]
This is how it was organized in WCAG 2.0 and the WG felt that these sections were all important enough to be 5.x-level entries. Maybe if someone had made an impassioned case in the original drafting we would have done it differently, but with translations and other resources all referencing these numbers as they are I don't think that the benefits outweigh the costs at this point in time.

**Comment by joanlambert** [comment]
Thank you for your consideration.

Joan Lambert
Accessibility Manager, Product Experience
Pearson VUE Accessibility
________________________________
