### ISSUE TITLE
Technique C40: 'Working example of a thick two-color indicator' link not working

### ISSUE THREAD

**Issue by moloko** [w3c/wcag#3413]
'Example 1: A thick two-color indicator' in the [Examples section](https://www.w3.org/WAI/WCAG21/Techniques/css/C40#examples) contains this link:

> [Working example of a thick two-color indicator](https://www.w3.org/WAI/WCAG21/working-examples/css-two-focus-colors/)

But clicking that link results in a 'Sorry, Insufficient Access Privileges' error page:

<img width="1230" alt="Sorry, Insufficient Access Privileges error page screenshot" src="https://github.com/w3c/wcag/assets/1249597/107bd18b-3124-45e2-882c-3894a4a16d0a">

**Comment by moloko** [comment]
Also just to add that in the same section it says:
> each color band is 2 CSS pixels thick

But in the CSS example given the 'outer indicator' is set to 4px

**Comment by fstrr** [comment]
I think this is because the C40 page isn't live yet. [The page is there, in the main branch, in GitHub](https://github.com/w3c/wcag/tree/main/working-examples/css-two-focus-colors).

@alastc would you know why the working example page isn't live but the "parent" technique is?

**Comment by iadawn** [comment]
Fixed. Mix of old examples still being there and new one missing
