### ISSUE TITLE
Understanding   Identify Purpose

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#344]
_From @awkawk on March 2, 2018 14:33_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#identify-purpose"   target="_blank">1.3.5 Identify Purpose (AAA) SC</a> has   draft Understanding content that can be viewed at <a href="https://rawgit.com/w3c/wcag21/identify-purpose/understanding/21/identify-purpose.html"   target="_blank">Understanding Identify   Purpose</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

_Copied from original issue: w3c/wcag21#780_

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #755.

**Comment by michael-n-cooper** [comment]
_From @lseeman on April 22, 2018 17:49_

very confused. I added a lot of content 
where is it?

also all the content i had for the original 1.3.4 could be added
it was at 
https://rawgit.com/w3c/wcag21/purpose-of-controls/understanding/21/purpose-of-controls.html
now it is all gone. Can we find it rather then starting from scratch? It was days of work

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. Please re-open if necessary.
