### ISSUE TITLE
Understanding Reflow

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#345]
_From @awkawk on March 2, 2018 14:33_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#reflow"   target="_blank">1.4.10 Reflow (AA) SC</a> has draft   Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/reflow/understanding/21/reflow.html"   target="_blank">Understanding   Reflow</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

_Copied from original issue: w3c/wcag21#781_

**Comment by michael-n-cooper** [comment]
_From @alastc on April 18, 2018 17:3_

Actions from issue #813:

> The issue of what needs to be considered by authors when making decisions about content on a page when implementing a responsive layout needs more attention in the Understanding document.

Also, moving Laura's wiki page into a technique.

**Comment by michael-n-cooper** [comment]
_From @detlevhfischer on April 24, 2018 14:52_

I will review this one. Have created a branch for understanding reflow, working on it now:
https://rawgit.com/w3c/wcag21/reflow-comments-Detlev/understanding/21/reflow.html

**Comment by michael-n-cooper** [comment]
_From @allanj-uaag on April 24, 2018 15:6_

edits to clarify a bit based on #813 ... https://github.com/w3c/wcag21/edit/reflow-comments-jallan/understanding/21/reflow.html

**Comment by michael-n-cooper** [comment]
_From @lauracarlson on May 1, 2018 12:27_

Hello @detlevhfischer and everyone,

After [discussion on the LVTF list](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2018Apr/thread.html#msg22), I suggest adding a bit to first paragraph to make the point that that for people with low vision, enlarged text with reflow is critical. This may be accomplished by adding something such as the [following proposal]( https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2018Apr/0025.html) after the first sentence:

>For people with low vision, enlarged text with reflow enables reading. It is critical. Enlargement enables perception of characters. Reflow enables tracking. Tracking is following along lines of text, including getting from the end of one line to the beginning of the next line.

Thank you for your consideration,
Laura

CC @alastc , @WayneEDick , @Ryladog , @mraccess77 , @allanj-uaag

**Comment by michael-n-cooper** [comment]
_From @alastc on May 3, 2018 15:48_

Detlev's pull request is for review at #893

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. Please re-open if necessary.
