### ISSUE TITLE
OAuth is misspelled oAuth in Understanding

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#3457]
Considering it’s referencing a fellow web standard, using the correct casing seems good.

* https://github.com/search?q=repo%3Aw3c%2Fwcag+oAuth&type=code

--- 

[This contribution is only possible thanks to my supporters. 💙](http://steadyhq.com/yatil)

**Comment by patrickhlauke** [comment]
https://github.com/w3c/wcag/pull/3459
