### ISSUE TITLE
3.3.9 Authentication (Enhanced) lists technique as “possible future technique” which is already there in 3.3.8 (Minimum)

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#3458]
[Understanding 3.3.8 Authentication (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html#techniques) lists as the second sufficient technique:

* [H100: Providing properly marked up email and password inputs](https://www.w3.org/WAI/WCAG22/Techniques/html/H100)

While [Understanding 3.3.8 Authentication (Enhanced)](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced.html#techniques) says at the same place:

* Providing a properly marked up email and password inputs (Potential future technique)

This feels like the same techniques.

--- 

[This contribution is only possible thanks to my supporters. 💙](http://steadyhq.com/yatil)

**Comment by alastc** [comment]
Closing with #3474, thank you.
