### ISSUE TITLE
Website link in repo about is to an old version

### ISSUE THREAD

**Issue by dtex** [w3c/wcag#3461]
The website link in this repo's About section is to an old draft version. 

Three possible solutions present themselves:

1. The link just needs to be changed to https://w3c.github.io/wcag/guidelines/22/
2. The Github Action needs to be updated to generate a new index.html file in the guidelines folder. Last time, it was done by Travis (5 years ago), so that step might not have made the transition to Actions.
3. Relatively new option in Github lets you point to a folder on main instead of having a special branch for GH pages. You could switch to using the `guidelines` or `guidelines/22` folder on main and just lose the gh-pages branch

![Screenshot 2023-10-07 at 11 21 53 AM](https://github.com/w3c/wcag/assets/854911/bdabe70a-7fee-476d-b39c-799abc152c29)

**Comment by alastc** [comment]
@iadawn should the w3c.github.io/wcag/guidelines/ link automatically go to the latest version? 
(Like https://www.w3.org/TR/WCAG/)

**Comment by dtex** [comment]
It's nice having a quick link to what's currently on main (with the "Editors Draft" banner). We can always expect to find the latest recommendation on w3.org.
