### ISSUE TITLE
New WCAG 2.2 Understandings contain incorrect "Draft" status information

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#3482]
New WCAG 2.2 Understandings contain incorrect status information:

> This understanding document is part of the [draft WCAG 2.2 content](https://w3c.github.io/wcag/guidelines/22/). It may change or be removed before the final WCAG 2.2 is published.

https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html
https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-enhanced.html
https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html
...

**Comment by alastc** [comment]
Yep, that was fixed in #3452, but will show when it's republished.

Closing as there's no code-change to make.
