### ISSUE TITLE
C43 working example broken link

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#3489]
The [sufficient technique for 2.4.11](https://www.w3.org/WAI/WCAG22/Techniques/css/C43) has a [working example](https://www.w3.org/WAI/WCAG22/Techniques/css/C43#:~:text=Working%20example%3A%20Using%20CSS%20margin%20and%20scroll%2Dmargin%20to%20un%2Dobscure%20content.), which when activated gives a 404 error.

This _may_ be a result of changes made in #3455

**Comment by mbgower** [comment]
BTW, @alastc Focus Not Obscured's label numbering was off. I altered the label to be the correct number, but maybe that causes undesirable effects on the existing labels?

**Comment by fstrr** [comment]
@iadawn fixed it :)
