### ISSUE TITLE
WCAG 2.2 - 2.5.5 Target Size (Enhanced) - broken link in the Understanding of SC 2.5.8: Target Size (Minimum) - Editorial

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/wcag#3493]
In the Understanding of the success criterion [2.5.8: Target Size (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html), the link pointing to the success criterion [2.5.5 Target Size (Enhanced)](https://www.w3.org/WAI/WCAG22/21/target-size-enhanced.html) is boken.

I've opened a pull request to fix it.

**Comment by mbgower** [comment]
Reviewed Friday call. Just need to validate process from here with @alastc
