### ISSUE TITLE
Understanding   Animation from Interactions

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#350]
_From @awkawk on March 2, 2018 15:21_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#animation-from-interactions"   target="_blank">2.2.7 Animation from Interactions (AAA)   SC</a> has draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/animation-from-interactions/understanding/21/animation-from-interactions.html"   target="_blank">Understanding Animation from   Interactions</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

_Copied from original issue: w3c/wcag21#786_

**Comment by michael-n-cooper** [comment]
_From @lseeman on April 22, 2018 17:3_

a change of brighness is another good example

**Comment by michael-n-cooper** [comment]
_From @goodwitch on April 24, 2018 0:43_

I reviewed the Understanding doc for Animations from Interactions.  I made changes (with Alastair's blessing) to make it easier to read/understand (at least according to the HemingwayApp).  The pull request is awaiting Alastair's review at https://github.com/w3c/wcag21/pull/874

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. Please re-open if necessary.
