### ISSUE TITLE
4.1.2 link to States And Adaptable Properties Module has a broken redirect

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#3506]
In the [resources section](https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html#resources), there's a link to a States And Adaptable Properties Module that points to https://www.w3.org/WAI/PF/adaptable/. If you try to get to that URL, it goes to https://www.w3.org/TR/wai-aria/%5bR,L%5d, which 404s.

**Comment by patrickhlauke** [comment]
the last known good version of that seems to be from 2005 https://web.archive.org/web/20171015165036/http://www.w3.org/WAI/PF/adaptable/StatesAndProperties-20051106.html

I'd suggest that it's completely obsolete.

It should probably link to something more up-to-date like the ARIA spec https://www.w3.org/TR/wai-aria/

**Comment by fstrr** [comment]
For some reason, I thought I couldn't fix this. But it turns out that I can. So I will.
