### ISSUE TITLE
Understanding   Character Key Shortcuts

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#351]
_From @awkawk on March 2, 2018 15:22_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#character-key-shortcuts"   target="_blank">2.4.11 Character Key Shortcuts (A) SC</a>   has draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/character-key-shortcuts/understanding/21/character-key-shortcuts.html"   target="_blank">Understanding Character Key   Shortcuts</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

_Copied from original issue: w3c/wcag21#787_

**Comment by michael-n-cooper** [comment]
_From @joshueoconnor on March 8, 2018 17:15_

Too many commas. Consider writing shorter sentences.

This paragraph is duplicated:

"This success criterion is becoming increasingly important in the mobile realm as growing number of apps more fully enable keyboard controls (see resources).'

**Comment by michael-n-cooper** [comment]
_From @mbgower on March 9, 2018 1:33_

I have made various editorial changes for clarity and consistency and created [Pull Request 801](https://github.com/w3c/wcag21/pull/801).
I also removed Example 4, which does not seem to meet the requirements of the SC. I am pasting it here for reference:
<h3><strong>Example 4: Native Speech Alternate Control</strong></h3>
<p>A mechanism is provided to allow users to change character-key shortcuts including to strings of up to 25 characters. These can directly serve as native speech commands for any speech engine.</p>

**Comment by michael-n-cooper** [comment]
_From @awkawk on March 9, 2018 15:57_

@mbgower Process correction for you - don't worry about making a pull request from the Character key shortcut understanding document into the Master branch - once the group agrees with the content we will handle it.

If you feel like you have significant changes that you want to suggest, then create a branch for those changes and once people review them we can pull them into the Character-key-shortcut branch and THEN we can do the pull and merge into Master.

I think that removing example 4 is one change that I would want to make sure that the TF was in agreement on, but the way you did it here that example won't be in the rawgit version linked in this issue.

**Comment by michael-n-cooper** [comment]
_From @lauracarlson on March 26, 2018 15:3_

Editorial comment:

To match the other Understanding documents, consider starting the Intent section with, "The intent of this success criterion is..."  It is a good way to get straight to the point.

**Comment by michael-n-cooper** [comment]
_From @lseeman on April 22, 2018 17:0_

Can we add that: allowing all short cut keys to be personlized and remaped could help all users , as the same keys can have the same actions across all content. This is particularly helpful for people with impaired memory function or reduced learning speed.

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. Please re-open if necessary.
