### ISSUE TITLE
/TR/WCAG2 redirects to 2.1

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wcag#3515]
This url goes to 2.2: https://www.w3.org/TR/WCAG/

But this still goes to 2.1: https://www.w3.org/TR/WCAG2/

Shouldn't they both go to 2.2 now, since the former is the latest version of WCAG and the latter is the latest version of WCAG 2.X?

**Comment by patrickhlauke** [comment]
One for @iadawn to investigate I think

**Comment by iadawn** [comment]
Fixed

**Comment by patrickhlauke** [comment]
superstar, thanks @iadawn

**Comment by mattgarrish** [comment]
Thanks @iadawn!
