### ISSUE TITLE
Understanding Target   Size

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#353]
_From @awkawk on March 2, 2018 15:23_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#target-size"   target="_blank">2.5.3 Target Size (AAA) SC</a> has draft   Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/target-size/understanding/21/target-size.html"   target="_blank">Understanding Target   Size</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

_Copied from original issue: w3c/wcag21#789_

**Comment by michael-n-cooper** [comment]
_From @becka11y on March 5, 2018 16:41_

Does this need to be more explicit that the target size must be 44px in each direction? For example, I don't believe that a target size of 100px wide by 40px high would meet this SC since the height is less than 44px.

**Comment by michael-n-cooper** [comment]
_From @patrickhlauke on April 12, 2018 18:59_

@becka11y you mean being crystal clear that when the document and SC say "44 by 44" they don't mean the area, but rather "the width and the height must be at least 44 CSS pixels"?

**Comment by michael-n-cooper** [comment]
_From @becka11y on April 12, 2018 19:8_

Yes,  I do think that most people will interpret 44x44 pixels to mean height and width each must be at least 44 px.  I was just wondering if it needed to be more explicit? I don't see this as a critical edit.

**Comment by michael-n-cooper** [comment]
_From @alastc on May 3, 2018 15:47_

Jake reviewed, updated and put in a PR at #873

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. Please re-open if necessary.
