### ISSUE TITLE
Understanding Pointer   Gestures

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#354]
_From @awkawk on March 2, 2018 15:23_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#pointer-gestures"   target="_blank">2.5.1 Pointer Gestures (A) SC</a> has   draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/pointer-gestures/understanding/21/pointer-gestures.html"   target="_blank">Understanding Pointer   Gestures</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

_Copied from original issue: w3c/wcag21#790_

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #774 .

**Comment by michael-n-cooper** [comment]
This issue did not port properly. Check [w3c/wcag21/#790](https://github.com/w3c/wcag21/issues/790) for the remainder of the context.

**Comment by mbgower** [comment]
@michael-n-cooper closing this since it is just an orphan without meaningful content.
