### ISSUE TITLE
Understanding Pointer   Cancellation

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#355]
_From @awkawk on March 2, 2018 15:24_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#pointer-cancellation"   target="_blank">2.5.2 Pointer Cancellation (A) SC</a> has   draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/pointer-cancellation/understanding/21/pointer-cancellation.html"   target="_blank">Understanding Pointer   Cancellation</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

_Copied from original issue: w3c/wcag21#791_

**Comment by michael-n-cooper** [comment]
_From @mbgower on March 7, 2018 23:18_

I think in order to complete an analysis of this Understanding document, we must resolve the [existing issue with the SC wording](https://github.com/w3c/wcag21/issues/773). I have proposed splitting Undo/Abort into separate bullets to address.
Existing

> Abort or Undo
>    Completion of the function is on the up-event, and a mechanism is available to abort the function before completion or undo the function after completion;

Proposed:

- Undo:
    A mechanism is available to undo the function after completion;
- Abort:
     Where completion of the function is on the up-event, a mechanism is available to abort the function before completion;

**Comment by michael-n-cooper** [comment]
_From @mbgower on March 7, 2018 23:58_

I think this is a well-written Understanding document, and has real value in its current form. It would be improved if each bulleted point in the SC had an equivalently labelled section in the Understanding doc. This could be largely achieved with the existing content with the additions of some headings and a bit of shuffling of content. I'd similarly like an Example illustrating the achievement of each of the bullets.

I want more explanation of the "Up Reversal; The up-event reverses any outcome of the preceding down-event" language. This seems to heavily overlap with the 'Abort' wording, especially in the proposed rewording. I don't see anything in the Understanding document that clarifies this. Are the two fully redundant, or is there a situation where the up reversal is different than an 'abort' function?

**Comment by michael-n-cooper** [comment]
_From @joshueoconnor on March 8, 2018 16:53_

The understanding documentation is good. One suggestion, where it says:
"Despite its name, the onclick event handler works both for mouse interaction as well as for touch interaction."

that should also cover keyboard a11y:

"Despite its name, the onclick event handler works both for mouse interaction as well as for keyboard and touch interaction.

**Comment by michael-n-cooper** [comment]
_From @lauracarlson on March 26, 2018 14:58_

The understanding documentation is good.  One typo: "ony occurs " should be "only occurs ".

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #773.

**Comment by michael-n-cooper** [comment]
_From @lseeman on April 22, 2018 16:44_

I would like to add that providing an easy way for users to undo any action is a recommended practice. For example, many users with mild cognitive disabilities or learning disabilities may activate events unintentionally and need a clear way to get back to  the previous state of the content. Having an Undo button appear after every significant change that can not be undone by hitting back, should be considered best practice

**Comment by michael-n-cooper** [comment]
_From @alastc on April 23, 2018 15:53_

Adding comment from #837 from @cyns:
> Despite its name, the Click event is a device-independent up-event. Please clarify that Click/onclick are an up-event. (probably in Understanding? or linking to some of the existing onclick techniques?)

**Comment by michael-n-cooper** [comment]
_From @mbgower on May 4, 2018 22:29_

I have created a pull request which I believe addresses these concerns https://github.com/w3c/wcag21/pull/884. It is ready for WG review, so I am adding that label.

**Comment by mbgower** [comment]
@michael-n-cooper I do not see anything remaining here that is not incorporated in the current Understanding document. I believe this can be closed.
