### ISSUE TITLE
Understanding   Orientation

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#357]
_From @awkawk on March 2, 2018 15:24_

<p>The <a   href="https://www.w3.org/TR/WCAG21/#orientation"   target="_blank">2.6.2 Orientation (AA) SC</a> has draft   Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/orientation/understanding/21/orientation.html"   target="_blank">Understanding   Orientation</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

_Copied from original issue: w3c/wcag21#793_

**Comment by michael-n-cooper** [comment]
_From @bruce-usab on April 19, 2018 18:58_

Please find attached my suggested edits using MS Word Track Changes feature and comments (per the volunteer requests on the call 4/17).  Mostly minor editorial, but I I think the last line of intent goes beyond what the SC requires.  I also added a bit to the examples.

[understanding-sc-262-orientation.docx](https://github.com/w3c/wcag21/files/1929411/understanding-sc-262-orientation.docx)

**Comment by michael-n-cooper** [comment]
_From @mbgower on April 24, 2018 14:21_

@bruce-usab, I made your changes directly into the branch. Commit is here: https://github.com/w3c/wcag21/commit/1e964f320ffdc33235cb5fd6f209c5a398fbb339. There were a couple of typos in your changes that I cleared up.

**Comment by michael-n-cooper** [comment]
_From @alastc on May 3, 2018 15:56_

Suggest updating the 1st line of intent to match dicsussion on the AG calls, it isn't content & functionality per-se, it is that it doesn't lock orientation.

I.e. operation doesn't (necesarrily) mean the same functionality is there.

**Comment by michael-n-cooper** [comment]
_From @alastc on May 8, 2018 23:18_

I've made a [small update](https://github.com/w3c/wcag21/commit/7223de6d086a9bd31aee077a7122a46861a05191#diff-00a2f464afe29bb794b5b74ac21b8420) on this as-per my comment (which came from the call last week).

**Comment by michael-n-cooper** [comment]
_From @mraccess77 on June 1, 2018 15:11_

I see the updates for understanding orientation on github but not in the latest drafts of the WCAG understanding documents.  Seems like this update for understanding needs to be conveyed in the understanding docs that are being published soon.

**Comment by michael-n-cooper** [comment]
_From @awkawk on June 1, 2018 15:16_

what branch are you seeing updates in Jon?

**Comment by michael-n-cooper** [comment]
_From @mraccess77 on June 1, 2018 16:0_

This https://www.w3.org/WAI/WCAG21/Understanding/orientation.html still talks about content and functionality whereas the github page has been updated.

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. Please re-open if necessary.
