### ISSUE TITLE
SC 1.4.11 and form field with tranparent border

### ISSUE THREAD

**Issue by sarasuri** [w3c/wcag#3577]
I have a question on a form field with transparent border which is not visible on the screen (see screenhots below). Is it a failure for SC 1.4.11? Currently, the "input" element has value="---" which is displayed next to the field label.  Can this be considered as equivalent to placeholder text to meet the SC 1.4.11 requirement?

Here is code snippet:
`<input aria-label="First name" title="" placeholder="" maxlength="200" autocomplete="off" type="text" value="---">`

From SC 1.4.11
"This success criterion does not require that controls have a visual boundary indicating the hit area, but if the visual indicator of the control is the only way to identify the control, then that indicator must have sufficient contrast. If text (or an icon) within a button or placeholder text inside a text input is visible and there is no visual indication of the hit area then the Success Criterion is passed. "

![image](https://github.com/w3c/wcag/assets/12256067/192ff3ed-a837-4aa7-a7f1-83635490bfb6)
![image](https://github.com/w3c/wcag/assets/12256067/e5a24480-9d99-465b-8032-e1432da8defb)

Thanks

**Comment by JAWS-test** [comment]
I see it differently than @patrickhlauke 
* If the form field has no border, then there can be no violation of 1.4.11, as the input field is not visible to anyone. This is simply very poor usability. The contrast between white and white is not too low (1:1), but there are simply no elements that contrast with each other. This means that 1.4.11 is not applicable. 
* If the input field has a border with too little contrast, what Patrick says applies. However, I have to say that an input field usually needs a border to distinguish it from plain text. However, this can only be judged in the context of the rest of the page and not just by looking at the field.

**Comment by sarasuri** [comment]
Thank you @patrickhlauke and @JAWS-test.
