### ISSUE TITLE
Understanding 1.4.2 links to 1.4.7

### ISSUE THREAD

**Issue by kengdoj** [w3c/wcag#3581]
On https://www.w3.org/WAI/WCAG22/Understanding/audio-control, in Intent section, "See also [1.4.2: Low or No Background Audio](https://www.w3.org/WAI/WCAG22/Understanding/low-or-no-background-audio)."

It should be 1.4.7 (instead of 1.4.2)

**Comment by patrickhlauke** [comment]
Good spot
