### ISSUE TITLE
Show technique titles, not just technique numbers, for related techniques

### ISSUE THREAD

**Issue by CharlesBelov** [w3c/wcag#3583]
[Technique PDF3:Ensuring correct tab and reading order in PDF documents](https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF3) has a section [Related Techniques](https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF3#related) which provides links to related techniques. However, that section only gives the technique numbers without any context. It would be better to include the titles.

This appears to be an issue on related pages as well.

Current content:

Related Techniques
[G57](https://www.w3.org/WAI/WCAG21/Techniques/general/G57)
[G59](https://www.w3.org/WAI/WCAG21/Techniques/general/G59)
[G202](https://www.w3.org/WAI/WCAG21/Techniques/general/G202)

Expected content:

[G57: Ordering the content in a meaningful sequence](https://www.w3.org/WAI/WCAG21/Techniques/general/G57)
[G59: Placing the interactive elements in an order that follows sequences and relationships within the content](https://www.w3.org/WAI/WCAG21/Techniques/general/G59)
[G202: Ensuring keyboard control for all functionality](https://www.w3.org/WAI/WCAG21/Techniques/general/G202)

I seem to recall that techniques pages used to show the titles for related techniques, so this may be a regression.

**Comment by mbgower** [comment]
I suspect this is done for readability. Some techniques have very long names, and the list could become somewhat impenetrable, instead of easy to scan, as it is right now. However, I'll leave someone more familiar with conventions to comment on the current use.

**Comment by CharlesBelov** [comment]
It may be readable, but it is unusable for me as just the number is meaningless. I wind up having to click each item to find out whether it is relevant to me. For cross-reference lists with more than three items, it becomes tedious.

If long titles are problematic, then improved spacing between items or introducing a short title field would help.

**Comment by alastc** [comment]
I had thought that the names were automatically added as part of the build process, but it appears not.
Maybe it's just done for the understanding page? Or perhaps it's all manual, it's hard to tell without a lot of digging.

In any case, it would be a general task for someone to run through the technique an understanding documents and fill in the full titles.

> Actually, I believe just showing the technique number violates Success Criterion 2.4.4 Link Purpose (In Context), which is a level A criterion.

No, there's an exception for when a link is ambigious to all users, which is the case here. That doesn't make it good, but not a fail of that SC.

**Comment by kfranqueiro** [comment]
This has been resolved by the new Eleventy build system, which is currently used for 2.2 docs, and will be used to rebuild 2.1 docs once #4007 is merged.
