### ISSUE TITLE
"~Beginning of suite~" in navigation for understanding documents

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#3586]
![screenshot of the top of an understanding document, showing the '~Beginning of suite~' text](https://github.com/w3c/wcag/assets/895831/abae9458-d610-4a57-91c8-1faf06c77416)

all the non-SC-specific understanding documents (like https://www.w3.org/WAI/WCAG22/Understanding/intro) have a weird `~Beginning of suite~` text at the top, in the navigation.

It not only looks weird (as the text is larger than the surrounding links), but it's also non-functional and ... cryptic

**Comment by iadawn** [comment]
Fix published
