### ISSUE TITLE
Clarification: simulated pointer input does not meet the definition of "single pointer"

### ISSUE THREAD

**Issue by brothercake** [w3c/wcag#3592]
The glossary definition of single pointer:

> pointer input that operates with one point of contact with the screen, including single taps and clicks, double-taps and clicks, long presses, and path-based gestures

Simulated pointer input doesn't have a point of contact with the screen (and generally returns an `e.detail` property of `0` as it should), therefore it's not within the definition, therefore 2.5.7 doesn't apply. 

Yet the Understanding docs mention a number of input devices that simulate pointer input as part of its intent. 

So there seems to be a contradiction, and I'm thinking that the resolution would be to clarify this in the glossary definition.

**Comment by patrickhlauke** [comment]
I'd add first of all: have a look at https://github.com/w3c/wcag/pull/3536

A simulated pointer input will have simulated coordinates, which are the simulated point of contact?

**Comment by brothercake** [comment]
Ah okay, I didn't encounter that in my pre-search. 

Well then I'd agree, since the definition of "pointer" in the Pointer Events specification talks of hardware-agnostic co-ordinates, then simulated pointer input would be covered by that. 

Should I just close this ticket then?

**Comment by patrickhlauke** [comment]
@brothercake if you're satisfied that #3536's redefinition is sufficient to answer your concern, feel free to close it :)
