### ISSUE TITLE
Chore: delete all branches that have been merged into main

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#3602]
There are currently 305 branches on this repository. Among those, there are many that are hanging around after being merged ages ago. Running a naive `git branch -r --merged main | grep -v "main"` gives the following list:

```
  origin/1917-dragging-understanding
  origin/19_april_charter_discussion
  origin/2751-focus-obscured-region
  origin/3446
  origin/HEAD -> origin/main
  origin/ISsue2684-dragging-and-sliders
  origin/Issue1848-target-size
  origin/Issue2033-Contrast-Minimum-Understanding
  origin/Issue2298-set-of-web-pages
  origin/Issue2431-target-size
  origin/Issue2708-access-auth-google
  origin/Issue2809-focus-not-obscured
  origin/Issue2996-target-size
  origin/Issue3135-privacy-section
  origin/PointerTargetTweaks
  origin/TextSpacingUnderstandingEllipses
  origin/WCAG20quickAAA
  origin/coga-note
  origin/dragging-understanding-edit-ref-to-2.1.1
  origin/editorial-fixes
  origin/fixing-example-annotation
  origin/focus-appearance-wrapped-links
  origin/focus-not-obscured-failure-technique
  origin/inactive-controls-info2
  origin/issue-3197
  origin/issue1049
  origin/kw-publish-preparation
  origin/mjm-edits-for-dragging-movements
  origin/mjm-wcag-2-2-editorials
  origin/patrickhlauke-issue2457-aria-practices-repointing
  origin/shawna-slh-patch-3
  origin/shawna-slh-patch-4
  origin/tech-aria13-correction
  origin/tech-spacing-override-awk
  origin/update-wcag2ict-publication
  origin/use-of-color-visited-link
  origin/wcag21InBriefEOW
  origin/wcag22-cr3-last-updates
  origin/wcag22-typos-and-editorial
```

While it's only a drop in the ocean, suggest at some point doing a similar trawl and removing stale/unused branches (checking though if some branches have been merged, but are then still being worked on)

There are no doubt *many* other branches that belong to issues/PRs that have since been closed without merging, and possibly the command-line shenanigans above may not catch branches that were originally merged into `master` when that was the default name, or merged into another branch that *then* was merged into `main` ... but it might be a start.

/cc @iadawn

**Comment by fstrr** [comment]
Deleted all of those apart from `wcag22-typos-and-editorial`, which Alastair uses for, well, those things. That branch has been used since this issue was created.

**Comment by fstrr** [comment]
Don't know if you want to close the issue or keep it open and badger @iadawn about the similar trawl you suggested.

**Comment by patrickhlauke** [comment]
@fstrr wow, I forgot I filed this. great stuff. doing a fresh trawl, there's a few more now:

```
  origin/3864-tweak-TargetSizeEnhanced
  origin/Issue1848-target-size
  origin/Issue2708-access-auth-google
  origin/Issue2809-focus-not-obscured
  origin/kw-format-understanding-notes
  origin/link-correction
  origin/re-write-scr37-as-html-technique
```

**Comment by fstrr** [comment]
Gone!

There are a lot of branches that look like they can be deleted—the earliest are from 2018. If you run this command (thanks, ChatGPT), you get a list of all the remotes in the date order they were last committed to:
`git for-each-ref --sort=-committerdate refs/remotes/ --format='%(refname:short) %(committerdate:iso8601)' | column -t`

`
origin/1.4.1-examples-added                                                   2024-05-22  10:24:48  +0200
origin/patrickhlauke-issue3868                                                2024-05-18  10:47:41  +0100
origin/patrickhlauke-issue1839                                                2024-05-17  21:03:44  +0100
origin/in-brief-positioning                                                   2024-05-17  14:36:41  +0100
origin/3864-tweak-TargetSizeEnhanced                                          2024-05-14  10:38:58  -0700
origin                                                                        2024-05-14  10:38:58  -0700
origin/main                                                                   2024-05-14  10:38:58  -0700
origin/gh-pages                                                               2024-05-14  17:21:34  +0000
origin/patrickhlauke-issue3750                                                2024-05-14  07:14:53  -0700
origin/F26-update                                                             2024-05-13  10:18:29  -0600
origin/fstrr-patch-7                                                          2024-05-10  15:44:10  -0700
origin/patrickhlauke-css-change-tweak                                         2024-05-08  14:28:57  +0100
origin/fstrr-patch-2                                                          2024-05-06  13:55:41  -0700
origin/broken-link-fixes                                                      2024-05-06  12:05:50  -0700
origin/issue-3788                                                             2024-05-06  12:36:01  -0400
origin/update-f82                                                             2024-05-06  12:27:19  -0400
origin/patrickhlauke-understanding-useofcolor                                 2024-05-06  10:37:05  +0100
origin/patrickhlauke-f94-test-steps                                           2024-05-04  12:31:15  +0100
origin/patrickhlauke-remove-F87                                               2024-05-04  11:46:52  +0100
origin/davidc-technique-edits-f97-g214                                        2024-05-03  19:03:02  -0400
origin/patrickhlauke-issue2243                                                2024-05-03  17:01:58  +0100
origin/fstrr-patch-1                                                          2024-05-03  08:42:55  -0700
origin/Issue-3127                                                             2024-05-02  18:18:55  -0700
origin/issue-3640                                                             2024-05-02  12:19:13  +0100
origin/fixing-issues-may                                                      2024-05-02  12:01:34  +0100
origin/Issue3510-definition-removal                                           2024-05-01  09:27:10  +0100
origin/patrickhlauke-understanding-audiodescription                           2024-04-30  00:23:21  +0100
origin/patrickhlauke-understanding-reflow-fix                                 2024-04-23  10:52:48  +0100
origin/3793-fix-typo                                                          2024-04-23  10:32:34  +0100
origin/mark-input-purposes-section-as-non-normative                           2024-04-08  10:14:58  -0700
origin/cleanup-for-2.2-rec                                                    2024-04-05  15:08:04  -0700
origin/Reflow-tracking                                                        2024-04-05  07:59:54  -0700
origin/giacomo-petri-images-of-text-proposal                                  2024-04-04  11:07:15  +0200
origin/Issue-3658                                                             2024-03-27  15:55:47  -0700
origin/patrickhlauke-normative-lists                                          2024-03-23  15:58:49  +0000
origin/update-editors-css-file                                                2024-03-18  11:58:11  -0700
origin/wcag22-typos-and-editorial                                             2024-03-12  13:30:08  +0000
origin/WCAG-2.1                                                               2024-03-11  17:02:20  +0000
origin/nitedog-patch-1                                                        2024-03-11  08:10:38  +0000
origin/patrickhlauke-issue326                                                 2024-03-10  18:41:33  +0000
origin/patrickhlauke-target-size-minimum-editorial                            2024-03-10  01:03:40  +0000
origin/patrickhlauke-issue2045                                                2024-03-09  15:30:49  +0000
origin/syntax-highlighting-for-html-techniques                                2024-02-26  11:16:59  +0000
origin/3684-email-correction                                                  2024-02-22  12:02:01  -0800
origin/3487-remove-2.1-reference                                              2024-02-22  08:51:54  -0800
origin/Issue3378-reflow-intent                                                2024-02-16  16:09:49  +0000
origin/patrickhlauke-understanding-focus-order-note                           2024-02-15  13:44:05  +0000
origin/DF-modify-test-pocedure                                                2024-02-12  14:47:36  +0100
origin/detlevhfischer-patch-5                                                 2024-02-02  15:48:59  +0100
origin/detlevhfischer-patch-4                                                 2024-02-02  15:38:20  +0100
origin/ConsolidatingOnWebsite_HaTheo                                          2024-01-29  15:49:48  +0000
origin/mitchellevan-bypass-blocks                                             2024-01-26  20:48:04  +0100
origin/mgifford-patch-1                                                       2023-12-15  16:14:39  -0500
origin/new-technique-focus-not-obscured                                       2023-12-06  18:21:43  -0500
origin/patrickhlauke-issue704                                                 2023-12-06  14:44:59  -0800
origin/patrickhlauke-issue1202                                                2023-11-17  23:07:49  +0000
origin/patrickhlauke-update-input-purposes                                    2023-11-13  12:30:24  +0000
origin/patrickhlauke-update-process-definition                                2023-11-07  11:02:44  +0000
origin/fstrr-patch-3                                                          2023-11-03  14:15:29  -0700
origin/charter-2023                                                           2023-10-23  15:15:12  +0100
origin/issue3344-understanding-sliders-251v257                                2023-10-06  10:56:07  -0400
origin/mitchellevan-patch-issue-2441-audio-description                        2023-10-04  22:53:14  +0200
origin/FocusNotObscured-update                                                2023-10-03  07:00:49  -0700
origin/Issue3135-suggestions                                                  2023-09-26  11:48:05  +0100
origin/Adding-living-standard-link                                            2023-09-19  13:49:41  +0100
origin/kw-patch-3                                                             2023-09-19  12:35:58  +0100
origin/syntax-highlighting-for-input-purposes                                 2023-09-08  09:39:04  -0700
origin/so-3361                                                                2023-08-25  15:13:43  -0400
origin/WCAG-charter-2023                                                      2023-08-15  09:52:38  -0400
origin/charter-2022                                                           2023-08-15  09:52:38  -0400
origin/2023-08_Updated-Rec                                                    2023-07-31  13:28:14  +0200
origin/WCAG-2.0-catchup                                                       2023-07-28  15:54:59  -0400
origin/broken-link-identify-purpose                                           2023-07-28  07:15:48  -0700
origin/2023-09_Rec                                                            2023-07-27  13:40:42  -0400
origin/QA-2023-07                                                             2023-07-27  13:40:18  -0400
origin/WCAG-2.1-catchup                                                       2023-07-25  11:46:13  -0400
origin/patrickhlauke-issue3290-2.2.1-understanding                            2023-07-20  00:35:32  +0100
origin/2023-07_PR                                                             2023-07-18  11:41:02  -0400
origin/json-related                                                           2023-07-13  15:51:41  -0400
origin/issue-2433                                                             2023-07-13  14:48:52  +0100
origin/2023-07_build-updates                                                  2023-07-11  08:14:48  -0400
origin/patrickhlauke-understanding-resize-text                                2023-07-05  19:41:03  +0100
origin/issue2033_patch_sc143_understanding                                    2023-06-23  10:18:27  -0700
origin/proposed-charter-update-2022                                           2023-06-14  16:41:28  -0400
origin/process-included-content                                               2023-06-09  16:36:22  -0400
origin/Issue758-path-based-gestures                                           2023-06-08  12:09:46  +0100
origin/WCAG-2.0                                                               2023-06-07  07:07:42  -0400
origin/remove-broken-links                                                    2023-06-07  12:17:55  +0200
origin/wai-site-decision-policy-update                                        2023-05-31  15:56:02  +0100
origin/Issue518-focus-dialogues                                               2023-05-30  17:29:37  +0100
origin/understanding-focus-not-obscured                                       2023-05-23  21:10:03  +0100
origin/2023-05_CR                                                             2023-05-18  09:02:05  -0400
origin/Reflow-exploration                                                     2023-05-12  06:30:37  -0700
origin/Issue3180-accessible-auth                                              2023-05-09  17:19:09  +0100
origin/mikegower-inactive-controls-info2                                      2023-05-05  08:42:42  -0700
origin/focus-appearance-structure                                             2023-05-01  13:10:03  -0700
origin/mitchellevan-patch-2                                                   2023-04-25  09:54:01  +0200
origin/capitalization                                                         2023-04-19  18:19:43  -0500
origin/2.5.1-understanding-note-on-sliders                                    2023-04-14  14:30:30  +0200
origin/3075-255-258-how-useful-is-target-size-when-click-area-is-not-visible  2023-04-12  14:38:51  -0400
origin/wcag20-21-411-note                                                     2023-03-23  16:46:20  +0000
origin/411-second-branch-with-3116                                            2023-03-23  12:27:12  +0000
origin/shawna-slh-patch-2                                                     2023-03-21  11:42:21  -0500
origin/Issue3086-target-size-alignment                                        2023-03-08  17:46:25  +0000
origin/h71-legent-first-child                                                 2023-03-08  13:09:05  +0100
origin/411-parsing-errata-removal                                             2023-03-07  18:23:49  +0000
origin/fstrr-patch-9                                                          2023-02-28  11:07:24  -0800
origin/Remove-text-from-technique-header                                      2023-02-24  17:33:29  +0000
origin/Issue3001-programmatically-determined                                  2023-02-21  00:28:15  +0000
origin/mjm-wcag-editorial-suggestions                                         2023-02-19  19:44:18  -0500
origin/mitchellevan-patch-1                                                   2023-02-16  18:01:14  +0100
origin/Issue2711-focus-not-obscured-aaa                                       2023-02-07  07:41:48  -0800
origin/issue2948-editorial-404linksfix                                        2023-01-31  12:57:02  -0600
origin/awkawk-patch-1                                                         2023-01-31  12:54:58  -0500
origin/2023-01_CR                                                             2023-01-25  11:26:01  -0500
origin/changelog-2023                                                         2023-01-23  12:31:24  +0000
origin/shawna-slh-patch-1                                                     2022-12-23  10:37:51  -0600
origin/Issue2857-target-size-erratum                                          2022-12-19  17:36:18  +0000
origin/Issue2695-target-spacing-update                                        2022-12-02  16:15:33  +0000
origin/Target-size-inline-update                                              2022-12-01  22:16:01  +0000
origin/wai-site                                                               2022-11-21  08:08:17  -0500
origin/Relative-luminance-file                                                2022-11-16  11:38:03  +0000
origin/Issue2525-Parsing-syntactical                                          2022-11-15  15:51:11  +0000
origin/Issue2430-Blocks-of-text-targets                                       2022-11-10  18:39:46  +0000
origin/decision-policy-update                                                 2022-10-20  13:26:09  -0400
origin/patrickhlauke-issue2314-character-key-understanding                    2022-10-16  10:34:32  +0100
origin/pse2b                                                                  2022-09-30  12:23:54  +0100
origin/2022-09_CR                                                             2022-09-06  13:05:16  -0400
origin/2022-09_editorial                                                      2022-09-05  08:05:14  -0400
origin/target-size-editorial                                                  2022-08-31  19:52:12  +0100
origin/focus-not-obscured-opacity                                             2022-08-25  09:15:21  +0100
origin/build-local                                                            2022-08-23  11:45:36  -0400
origin/Issue2569-target-size-exception                                        2022-08-14  23:29:36  +0100
origin/fstrr-patch-11                                                         2022-08-12  13:23:19  -0700
origin/pse2                                                                   2022-08-10  22:26:53  +0100
origin/patrickhlauke-issue2256                                                2022-08-10  13:38:36  +0100
origin/patrickhlauke-wcag20-2.2.1-extension-counterproposal                   2022-08-09  23:43:42  +0100
origin/transfer-h99                                                           2022-08-08  10:49:33  -0300
origin/patrickhlauke-issue2563                                                2022-08-04  12:20:49  +0100
origin/patrickhlauke-f99-fix                                                  2022-07-18  17:21:23  +0100
origin/bruce-usab-patch-1-3-3                                                 2022-07-08  16:16:47  -0400
origin/focus-appearance-links                                                 2022-07-05  15:34:33  +0100
origin/target-size-user-agent-update                                          2022-06-30  16:03:11  +0100
origin/3.3.2-abels-or-instructions-select-example                             2022-06-24  10:29:10  +0200
origin/samuelweiler-patch-2                                                   2022-06-23  16:37:49  -0400
origin/samuelweiler-patch-1                                                   2022-06-23  16:22:43  -0400
origin/1.2.3-understanding-update-issue-2479                                  2022-06-07  07:43:07  -0400
origin/patrickhlauke-issue2310-G183                                           2022-06-04  18:54:28  +0100
origin/issue-2505                                                             2022-06-03  13:48:53  -0700
origin/detlevhfischer-patch-3                                                 2022-06-02  12:35:57  +0200
origin/3.1.2-understanding_lang-attr-added                                    2022-06-02  12:10:44  +0200
origin/charter-2022-survey-24-may                                             2022-05-24  09:59:50  -0400
origin/issue-2465                                                             2022-05-23  13:20:27  -0700
origin/Issue2162-target-size-understanding                                    2022-05-18  00:08:03  +0100
origin/Focus-appearance-enhanced-updates                                      2022-05-17  17:55:42  +0100
origin/working-example-fix                                                    2022-05-11  14:01:11  -0400
origin/issue-268                                                              2022-05-06  13:12:13  -0700
origin/fstrr-patch-6                                                          2022-05-06  10:31:29  -0700
origin/charter-2022_alternates                                                2022-05-03  18:37:31  -0400
origin/admin-list                                                             2022-05-03  14:27:05  -0400
origin/Working-Branch-for-Q1-2017                                             2022-05-03  10:37:06  -0700
origin/fstrr-patch-4                                                          2022-04-29  13:19:36  -0700
origin/Issue2162-target-size                                                  2022-04-28  01:09:26  +0100
origin/Issue2323-focus-appearance                                             2022-04-27  23:14:08  +0100
origin/Label-in-name-suggestion                                               2022-04-18  13:50:24  -0700
origin/Issue2074-target-size-understanding                                    2022-04-11  10:57:56  -0400
origin/new-supplemental-guidance                                              2022-04-02  10:44:28  -0500
origin/maryjom-wcag2ict-pages                                                 2022-03-30  07:35:42  -0400
origin/wa                                                                     2022-03-30  07:35:42  -0400
origin/Issue1888-visible-controls-exception                                   2022-03-30  09:14:21  +0100
origin/visible_control_instructions                                           2022-03-01  15:56:26  +0000
origin/Issue2219-focus-appearance                                             2022-02-14  00:46:12  +0000
origin/focus-appearance-user-agent-exception                                  2022-02-10  19:51:46  +0000
origin/pr-preview                                                             2022-02-09  08:12:11  -0500
origin/revised-understanding-1.4.4-resize-text                                2022-02-08  16:51:42  +0000
origin/Issue2201-focus-appearance                                             2022-02-04  00:57:57  +0000
origin/focus-appearance-component-update                                      2022-01-18  18:52:33  +0000
origin/2148-consistent-help                                                   2022-01-05  11:19:21  -0800
origin/Issue1890-accessible-auth-def                                          2021-12-03  19:14:16  +0000
origin/H95-update-new-links                                                   2021-12-01  20:14:00  +0100
origin/Issue1693-consistent-help                                              2021-11-30  11:22:58  +0000
origin/colorblind-update                                                      2021-11-29  17:24:48  -0600
origin/H39-test-rewrite                                                       2021-11-15  13:32:34  -0800
origin/target-size-understanding-issue-1894                                   2021-11-04  06:58:15  -0700
origin/fstorr-issue2062                                                       2021-10-26  10:52:01  -0700
origin/patrickhlauke-tweak-text-contrast-understanding                        2021-10-13  11:25:20  +0100
origin/dragging-via-click-lock                                                2021-10-01  17:42:33  +0200
origin/detlevhfischer-patch-1                                                 2021-10-01  17:41:45  +0200
origin/color-blind-patch                                                      2021-09-13  13:22:18  -0700
origin/target-size-min-styling                                                2021-07-18  21:25:51  +0100
origin/target-size-min-conf-alt-version                                       2021-07-16  18:35:11  +0200
origin/rewrite-h69-d-macdonald                                                2021-07-06  18:46:40  +0100
origin/fstorr-update-contrasts-with-video                                     2021-06-28  14:11:17  -0700
origin/ISsue1878-accessible-auth-understanding                                2021-06-21  23:24:53  +0100
origin/ReviewofUnderstandingDocs_mg                                           2021-06-21  06:22:10  -0700
origin/wcag21-editorial-updates                                               2021-06-18  00:14:41  +0100
origin/2021-05_WD                                                             2021-05-21  11:25:31  -0400
origin/bruce-usab-wcag22-contrast-technique                                   2021-04-22  22:49:22  +0100
origin/target-size-minimum-understanding-rev                                  2021-04-20  18:53:06  +0100
origin/tech-aria-current                                                      2021-03-28  21:26:05  -0700
origin/conformance-challenges-toctest                                         2021-03-26  10:54:40  -0400
origin/aria22-mod                                                             2021-03-25  11:02:29  +0100
origin/target-size-minimum-understanding                                      2021-03-16  10:59:43  +0100
origin/decision-policy-confidential                                           2021-03-03  10:31:16  -0500
origin/findable_help_february_2021                                            2021-03-03  09:43:52  +0000
origin/mikegower-findable-help-1574                                           2021-02-25  14:45:05  -0800
origin/scha14-g195-updates                                                    2021-02-17  14:58:41  -0500
origin/detlevhfischer-patch-2                                                 2021-02-05  17:19:14  +0100
origin/Issue1460-focus-appearance-editorial                                   2021-02-04  00:14:42  +0000
origin/wcag22-visible-controls-update3                                        2021-01-28  00:47:33  +0000
origin/scha14-patch-1314-1                                                    2021-01-26  20:17:03  -0500
origin/silver-decision-policy-clarification                                   2021-01-25  15:25:03  -0500
origin/wcag22-visible-controls-update2                                        2021-01-20  17:44:52  +0000
origin/Issue1531-focus-appearance-size-calc                                   2021-01-07  21:55:29  +0000
origin/Issue1364-accessible-auth                                              2020-10-31  20:53:09  +0000
origin/TextSpacingUnderstandingReword                                         2020-09-20  07:39:47  -0700
origin/gradualclearing-patch-1-1                                              2020-08-28  12:24:34  +0100
origin/gradualclearing-patch-1                                                2020-08-28  12:21:55  +0100
origin/scha14-patch-1314-2                                                    2020-08-27  08:57:35  -0400
origin/slhenry-fix                                                            2020-08-07  13:02:38  -0500
origin/issue-1187                                                             2020-08-04  08:50:38  -0700
origin/non-text-contrast-gn-update                                            2020-08-03  17:11:45  +0100
origin/input-purpose-addition                                                 2020-07-17  07:54:11  +0200
origin/F108-Dragging-failure-edit                                             2020-07-14  11:38:17  +0200
origin/dragging-understanding-edits                                           2020-07-14  11:17:00  +0200
origin/Issue101-labels-for-332                                                2020-07-09  23:09:57  +0100
origin/revising-2.4.9-Understanding                                           2020-06-17  18:26:10  +0200
origin/revised-link-purpose-in-context.html                                   2020-06-17  15:10:21  +0200
origin/WCAG22_inactive_def                                                    2020-06-16  17:08:00  +0100
origin/wcag22-findable-help                                                   2020-06-15  11:34:19  +0100
origin/koalie-patch-1                                                         2020-06-09  10:45:02  +0200
origin/wcag22-redundant-entry-nodef                                           2020-06-04  18:29:56  +0100
origin/errata-target-defintion                                                2020-04-09  18:39:34  +0100
origin/February-2020_FPWD                                                     2020-02-26  10:42:05  -0500
origin/patrickhlauke-wcag20-2.2.1-extension                                   2020-02-07  10:57:04  +0000
origin/f77_failure_examples                                                   2019-10-29  08:44:55  -0400
origin/tech-fail-text-spacing-not-allowed                                     2019-09-03  10:04:35  -0400
origin/revert-853-status_message_error                                        2019-08-27  13:01:05  -0400
origin/mike-update-tech-ensuring-single-pointer                               2019-08-09  08:46:04  -0700
origin/tech-no-reliance-on-path-or-multipoint                                 2019-08-06  10:51:53  -0400
origin/tech-ensuring-single-pointer                                           2019-07-05  17:09:52  +0200
origin/syncronised-media-exception-796                                        2019-06-28  09:44:56  +0100
origin/jake-abma-patch-1                                                      2019-06-18  09:51:27  +0200
origin/change-on-request-benefit-clarification-738                            2019-05-23  09:46:56  +0100
origin/tech-clip-box                                                          2019-05-14  11:04:52  -0400
origin/motion-actuation-update-727                                            2019-05-14  14:45:45  +0100
origin/tech-label-in-name-aria                                                2019-05-13  18:36:55  -0700
origin/example-icon-font-img-role                                             2019-04-05  15:31:08  +0200
origin/spacingEditorialFixes                                                  2019-04-03  11:26:15  -0700
origin/tech-timeout-20-hours-or-greater                                       2019-03-11  17:03:58  -0700
origin/1413_Erratum                                                           2019-01-31  09:52:18  -0800
origin/reflow-technique-list                                                  2019-01-29  23:29:06  +0000
origin/tech-change-shape-onfocus                                              2018-12-05  21:51:01  +0000
origin/tech-failure-preventing-orientation-changes                            2018-10-23  17:49:00  +0200
origin/status-messages                                                        2018-08-22  12:22:17  -0700
origin/tech-spacing-override-ac                                               2018-08-06  11:33:04  -0400
origin/drag-dop-cancel-detlev                                                 2018-07-10  09:22:05  +0200
`

**Comment by fstrr** [comment]
Well, `drag-drop-cancel-detlev` corrected a typo on an `h2` tag for [G210](https://www.w3.org/WAI/WCAG21/Techniques/general/G210), so that can be deleted.

**Comment by fstrr** [comment]
Removed some more from that table above, so we're down to 247 branches now. Will maybe talk this through at tomorrow's backlog meeting.

**Comment by kfranqueiro** [comment]
Given that #3878 leads with a remark about continuing this, and given that I just did another pass today to delete merged branches, I imagine we ought to close this.

(FWIW, as of right now there are 125 branches total including protected branches, so I'd say we've made a dent)

**Comment by patrickhlauke** [comment]
github says there's 124 (?) branches and 125 pull requests, so it definitely looks like we've made good progress removing any hanging/left-over branches at least. great stuff.
