### ISSUE TITLE
2.2.6 Timeouts: Understanding Intent section is too long

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#362]
_From @cyns on March 30, 2018 23:10_

The intent section of the Understanding Timeouts doc is a wall of text. Please tighten up the first four paragraphs, and change the options for complying into a bullet list. Some of the other understanding docs have a section of common ways to comply that is easier to parse.

_Copied from original issue: w3c/wcag21#831_

**Comment by michael-n-cooper** [comment]
_From @awkawk on April 3, 2018 14:51_

Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by fstrr** [comment]
This issue looks to be inactive and the original referenced issue has been close, so I'm closing this. Please re-open if necessary.
