### ISSUE TITLE
2.5.4 Concurrent Input Mechanism: Add mouse/keyboard menu example

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#363]
_From @cyns on March 30, 2018 23:27_

So glad to see this in there! Please add an example to the Understanding doc along the lines of:
"User opens a menu with a mouse, and then navigates between the menu items with arrow keys." This is one of the bugs I run into over and over in the wild.

_Copied from original issue: w3c/wcag21#840_

**Comment by michael-n-cooper** [comment]
_From @awkawk on April 3, 2018 14:49_

Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by michael-n-cooper** [comment]
_From @alastc on May 22, 2018 12:39_

I've created a pull request for review in #931

**Comment by alastc** [comment]
The example was added, it's the last one in the [understanding doc](https://www.w3.org/WAI/WCAG21/Understanding/concurrent-input-mechanisms.html). Closing.
