### ISSUE TITLE
Why exempt inoperable or disabled controls in 1.4.3 and not 4.1.2?

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#3631]
Success criterion 1.4.3 Contrast (Minimum) exempts the text in inoperable/ disabled controls from being perceivable to people with low vision.

Assuming WCAG is saying that moderate to low vision users do not need to perceive information in disabled controls, why not extend this to 4.1.2 Name, Role, Value? Let's say that screen reader users do not need to perceive the accessible name of the disabled control. 

```
<button aria-disabled="true" style="background: white; color: #f1f1f1">
  <span aria-hidden="true"> Submit </span>
</button>
```

I am not advocating for disabled controls, poor contrast, or controls without accessible names.

I am trying to point out a double standard.

**Comment by patrickhlauke** [comment]
for the "why" part, it's because historically, it has not been possible for authors to to fully influence/control the styling that browsers apply to `disabled` controls

**Comment by anevins12** [comment]
makes sense
