### ISSUE TITLE
WCAG 2.2: Understanding 2.5.7 Dragging Movements links to 2.1 version of the Understanding 2.5.1 Pointer Gestures

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#3634]
The Intent from Understanding 2.5.7 Dragging Movements has a link to 2.5.1 Pointer Gestures where the URL is going to the WCAG 2.1 Version of the understanding: https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html. 

This is found in the sub-section [Distinguishing dragging movements from path-based pointer gestures](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#distinguishing-dragging-movements-from-path-based-pointer-gestures)".

**Comment by bruce-usab** [comment]
Mentioned on 1/19 call, @mbgower and @alastc and @iadawn might be fodder for a facilitators' call.
