### ISSUE TITLE
Do we still need Technique SCR21 ("Using functions of the Document Object Model (DOM) to add content to a page")?

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#3652]
SCR21 [Using functions of the Document Object Model (DOM) to add content to a page](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR21) seems to be less about the title of the document and more about certain scripting functionality that the author thinks should be avoided. For example:

> "…and the innerHTML property is not part of the DOM specification and thus should be avoided."

and the Procedure, which consists of one item:

> "Examine the source code and check that the new content is not created using document.write(), innerHTML, outerHTML, innerText or outerText."

As such:

1. Do we still this document?
2. If we do, then updating it to bring it up to date and re-writing the Procedure seems to be the way to go.

**Comment by patrickhlauke** [comment]
i'd say kill it with fire. this has nothing to do with accessibility and seems purely a code preference thing (and i'd say that "some of my best friends are innerHTML")

**Comment by bruce-usab** [comment]
Discussed on backlog call 4/23 and in #4411
