### ISSUE TITLE
ACT Taskforce Clarification - Equivalent resource

### ISSUE THREAD

**Issue by tombrunet** [w3c/wcag#3655]
This is in the context of the following proposed rule: https://www.w3.org/WAI/standards-guidelines/act/rules/4b1c6c/proposed/

The rule is looking at two iframes with the same accessible name and trying to determine if the resources are 'equivalent'. When the URLs or content is the same, the answer is clear. The scenario that triggered debate was for two or more frames with a name of "advertisement" but which load different ads. Would AG consider these ads as equivalent resources that can have the same name?

**Comment by alastc** [comment]
In the context of [4.1.2 Name, Role, Value](https://www.w3.org/TR/WCAG21/#name-role-value), isn't the iframe the control and the content of that control can be different?

I.e. both iframes could be called "advert", but one could be for washing powder and the second could be an advert for toothpaste. 

So my personal response is that I think these could have the same name. 

Presumably this would apply to multiple embedded videos as well? (If they used iframes to do the embedding.)

**Comment by bruce-usab** [comment]
@tombrunet please see [H64 Using the title attribute of the iframe element](https://www.w3.org/WAI/WCAG22/Techniques/html/H64.html).

If it wasn't permissible for `iframe` names to ever be duplicative, such a detail would have been part of the test procedure.

This is analogous to how [SC 2.4.6 Headings and Labels](https://www.w3.org/TR/WCAG22/#headings-and-labels) does not preclude duplication.

@tombrunet if you are satisfied with Alastair's reply, please close this issue.

**Comment by tombrunet** [comment]
Closing - tracking with the ACT community group. If further discussion needed, will open a new issue.
