### ISSUE TITLE
i18n needed for "left navigation"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag#3658]
### Currently

Some pages in Understanding give "left navigation" as an example. Here's one I noticed:

https://github.com/w3c/wcag/blob/main/understanding/22/focus-not-obscured-minimum.html

This is not as internationally neutral as it should be. In web pages where the primary language is a right-to-left language, it is a common convention for such navigation bars to be on the right, not the left.

### Proposed

Find references to "left navigation" in non-normative content.

Change each to "side navigation", "left or right navigation", or similar, to account for both left-to-right (LTR) and right-to-left (RTL) web pages.

**Comment by rscano** [comment]
These pages are in English so left is correct. Btw I think the left and right indication inside Text could be wrong for [sensory characteristics](https://www.w3.org/TR/WCAG22/#sensory-characteristics) . Agree to have side navigation also as accessible name for aria region.

**Comment by DuffJohnson** [comment]
Left-side navigation may be more common in English as compared to right-side navigation, but that's about all one could say about it. Some websites use the right-side. Adobe's new Acrobat UI (controversially) puts navigational bookmarks on the right side. "Side navigation" is neutral and thus, preferable.

**Comment by mitchellevan** [comment]
> These pages are in English so left is correct. 

If the prose were describing the English-language W3C pages themselves then this would be true. However, the prose at issue is describing the web in general, which is in many languages.

**Comment by rscano** [comment]
I agree @mitchellevan. What i've wrote (full comments) point attention that left / right are language reading order based and that can cause violation of a WCAG SC using words like" left menu" "top link".

**Comment by mbgower** [comment]
Two of the uses of "left" are in an example that refer sto what happens on on a specific website. So I think "side" navigation is preferable in the third usage, it may or may not be as good in the example. (And of course in some situations, the 'side' navigation is repositioned 'above' the main content in top down languages, which would be better spoken of as 'before')

 it@mitchellevan or @rscano can either of you pick this up and put in a small PR to address?

**Comment by giacomo-petri** [comment]
How about employing "side navigation," specifically indicating that in the present instance it is visually positioned on the "left side"? This maintains a generic approach suitable for both left-to-right and right-to-left languages, while offering additional context for the particular example.
