### ISSUE TITLE
Provide clarification in PDF-Techniques for list of tools

### ISSUE THREAD

**Issue by KerstinProbiesch** [w3c/wcag#368]
Hi all,

in the PDF-techniques a list of tools for checking and repairing is provided. It should be become more clear that this is just a list and not an indicator for a W3C-endorsement to avoid misunderstandings. I think a short sentence after the heading "Accessibility Checking and Repair" with a link to this page: https://www.w3.org/WAI/ER/tools/#disclaimer or and much better a short version of this disclaimer will do.

Cheers

Kerstin

**Comment by fstrr** [comment]
I've checked each of the PDF Techniques documents and, under each Resources heading, is the text "Resources are for information purposes only, no endorsement implied.", which I think is what you asked for. I'm closing this issue, but if it needs re-opening, please do.
