### ISSUE TITLE
Fix typo in email address in the "Help improve this page" panel

### ISSUE THREAD

**Issue by clanceyp** [w3c/wcag#3684]
Open any page containing the "Help improve this page" panel e.g. https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced

Actual 
email shows as:  "public-agwg-comments@w3.org@w3.org"

Expected
email shows as:  "public-agwg-comments@w3.org"

Also, since the email address is a link, it makes sense that the word "GitHub" in "... or via GitHub" should also be a link.

**Comment by bruce-usab** [comment]
@clanceyp thanks for taking the time to flag and to @mikeyil for fixing.

**Comment by mbgower** [comment]
FYI, the original PR was not applied against the main repo. I have recreated properly.

**Comment by bruce-usab** [comment]
Sorry for the churn.

**Comment by mbgower** [comment]
Removed from project since we're now tracking the PR
