### ISSUE TITLE
Have the Advisory techniques that had no text been removed from WCAG 2.1?

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#369]
It seems the advisory techniques that were just a text title have been removed?

The titles were useful even though they were just a text title with no technique page or link. 

If they were removed I think we could bring them back and make that decision together.

**Comment by alastc** [comment]
I think anything marked with 'future link' was removed, as if it's been 8-10 years, we are in the future and there was no link!

I see the point that they were high-level expressions of what would be helpful, but shouldn't that be clear from the understanding text?

**Comment by alastc** [comment]
Proposed response/question (for the group):

Techniques which did not link to anything have been removed from the understanding documents, which is what drives the technique listing. 

I don't think it is good to have 'future links' for a decade, but I think there are a couple of choices:

1. Agree that's the right thing to do (and make sure it goes through to the quickref as well).
2. Establish another method of conveying these items.

That other method might simply be a new label for these non-linked techniques, or perhaps they could go somewhere else in the understanding doc. It would be good to know if other people use these items as well.

**Comment by jake-abma** [comment]
related: https://github.com/w3c/wcag/issues/729

related: https://github.com/w3c/wcag/issues/705

**Comment by alastc** [comment]
The action was for @michael-n-cooper to create a list of the removed technique statements.

**Comment by fstrr** [comment]
Closing this as inactive since 2019 and Jake's two related issues are closed. Please re-open if necessary.
