### ISSUE TITLE
صObjectors should be required to:

### ISSUE THREAD

**Issue by 15253545z** [w3c/wcag#3698]
Objectors should be required to:

* state what exactly is being objected to, including all relevant background information
* indicate how rejection of the FO would:
  * cause irreparable harm to the objector and/or the W3C; and/or
  * result in a violation of the W3C rules
* proposed concrete proposal(s) that would cure the FO
* demonstrate that no consensus could be found despite their efforts to do so

This information should be provided within a specified time period.

As it stands, anyone can formally object with a single sentence and without providing any detail.

The bar should be higher so that:

* the objector has a stake in the FO process
* the community has all the information needed to seek consensus
* the council, if convened, has detailed information on which to base its decision

_Originally posted by @palemieux in https://github.com/w3c/w3process/issues/755#issuecomment-1531706780_

**Comment by alastc** [comment]
Not relevant to the WCAG docs.
