### ISSUE TITLE
typo in Non-text contrast Understanding document

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#3704]
From the public comments
>Subject: Understanding and Techniques Feedback--Typo on page: Understanding Success Criterion 1.4.11
On the page [Understanding Success Criterion 1.4.11: Non-text Contrast | WAI | W3C](https://urldefense.com/v3/__https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html__;!!EDx7F7x-0XSOB8YS_BQ!ZJm1M7GM9lSlLE9QFcJ553p6CGFRdUH8x0Ctw4_3nduL_4GTASadPLrtorJadow_j1XSlFTLQTdd9MS-VlSeZrJjwb0$) , in the section Graphical Objects, there is a typo in the first row of the table. “Ratio” is spelled “ration”. See the attached screenshot.
 Regards,
Joseph Lakey

**Comment by bruce-usab** [comment]
Closed by #3704
