### ISSUE TITLE
Thanks for the links.

### ISSUE THREAD

**Issue by ManuuMartinez** [w3c/wcag#3731]
Thanks for the links.

I have only basic knowledge of colorimetry based on various literatures and experiences in color correction and graphic/web design. I know that one have either to use linear RGB or apply manual compensations in order to create realistic color shadows/highlights, blend colors, etc. I guess this is why SVG filter primitives operate in linear RGB by default.

I have just never come across the formal definition. Unfortunately, the "fairy tale" definition seems to be much more widespread than the formal definition and the explicit statement "(most) RGB color spaces are not additive", which yields results with the opposite statement when searching it on the web.

So the presence of the two opposing statements in the spec (before your fix) was all the more unfortunate. I am not sure the spec should ellaborate more on this though.

_Originally posted by @cdoublev in https://github.com/w3c/csswg-drafts/issues/9977#issuecomment-1966006684_

_Publicación original de @ManuuMartinez en https://github.com/ManuuMartinez/Carlos-Manuel-Martinez/issues/2_

**Comment by patrickhlauke** [comment]
@ManuuMartinez what is this bullcrap? low effort spam?
