### ISSUE TITLE
Technique F110: Add screenshots to help the user see examples

### ISSUE THREAD

**Issue by ljoakley** [w3c/wcag#3764]
In technique F110, we have two Failure examples, sticky footer and sticky header. Would it make sense to add a couple of screen shots to help the users understand what would be a failure?

**Comment by mbgower** [comment]
Please feel free to submit some screenshots as a PR. I suspect it will take more than one to properly illustrate something of this dynamic nature. A working example is another option.

**Comment by ljoakley** [comment]
I think that a working eampe would be great. I would need someone to create this as I have no idea how to do this.

**Comment by giacomo-petri** [comment]
I can take this one
