### ISSUE TITLE
Broken image in failure F69

### ISSUE THREAD

**Issue by erikgustafsson** [w3c/wcag#3772]
At the page https://www.w3.org/WAI/WCAG22/Techniques/failures/F69 the images illustrating examples does not load.

![image](https://github.com/w3c/wcag/assets/5470453/51e122b5-1d06-4ff7-9aa7-36e1846438ca)

**Comment by fstrr** [comment]
This has apparently been fixed by #3687, which was closed as completed yesterday.

@iadawn is this just waiting for a site build?

**Comment by erikgustafsson** [comment]
Illustration images are now visible! Awesome!
