### ISSUE TITLE
Understanding document - SC 1.4.12 Text Spacing

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag#378]
The sentence 

> Currently, this SC is not achievable in PDF and can not be reliably tested in PDF user agents.

is much better than former versions on how and if the SC relates or applies to PDF. But I think it's confusing.

Because the SC is not achievable it can not be tested at all. The second half of the sentence indicates that it could be "somehow" testable, which contradicts the statement of the first half of sentence.

And as mentioned in some issues before: The SC itself and therefore the normative wording applies to markup languages. One can add for many years now tags to a PDF, but PDF is not a markup language but a page description language ([information on PDF](https://opentextbc.ca/graphicdesign/chapter/6-6-page-description-languages-pdl/))

Proposal:

Change 

> Currently, this SC is not achievable in PDF and can not be reliably tested in PDF user agents.

to

> This SC does not apply to PDF

Probably followed by a short explanation about the differences between markup languages and page description languages.

**Comment by alastc** [comment]
Just cleaning up old issues: The Understanding doc now says "Currently, this SC does not apply to PDF as it is not implemented using markup. "

Please re-open this issue if I have misunderstood, but I think the comment has been addressed.
