### ISSUE TITLE
1.4.4: Resize text: acceptability of a "link to a full version" 

### ISSUE THREAD

**Issue by dan-tripp-siteimprove** [w3c/wcag#3787]
Over at the ACT rules group I [raised the question](https://github.com/act-rules/act-rules.github.io/issues/2163) of whether and how a "link to a full version" would cause clipped text (which would otherwise fail) to pass SC 1.4.4.  

In [SC 1.4.4's Understanding document](https://www.w3.org/WAI/WCAG22/Understanding/resize-text) I found these cases where it does pass: 
1. "... in Web mail applications the subject column may not be wide enough to accommodate every possible subject header, but activating the subject header takes the user to the full message with the full subject header."
2. "In Web-based spreadsheets, cell content that is too long to be displayed in a column can be truncated, and the full content of the cell is available to the user when the cell receives focus."
3. "The content of a user interface component may also become too wide in user interfaces where the user can resize the column width. In this type of user interface component, line wrapping is not required; truncation is acceptable if the component's full content is available on focus or after user activation...."

Cases 1 and 2 are about user-supplied content which has no maximum length.  Case 3 is about a user-specified column width.  I'm thinking of another case, which doesn't fit into those categories, and which I'll call "Case 4": where the content is static and supplied by the author of the web page.  There are no resizable columns.  There is just some text which, at 200% zoom, becomes clipped, and a "link to a full version" appears.  

Does Case 4 pass SC 1.4.4?  

Whatever the answer turns out to be, I would like to propose a new (Sufficient or Failing) technique for Case 4, to make it clear.

**Comment by mraccess77** [comment]
Based on the related discussions for SC 1.4.10 and examples from 1.4.4 I would generally consider that example to pass the criterion.

**Comment by dan-tripp-siteimprove** [comment]
I just spent a few minutes searching for related discussions for SC 1.4.10, and I couldn't find any definitive ones.  If you happen to have links to some, let me know.  Same for the [examples for 1.4.4](https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html#examples ) - maybe I'm missing something.

**Comment by dan-tripp-siteimprove** [comment]
I found this wording in [Understanding 1.4.10](https://www.w3.org/WAI/WCAG22/Understanding/reflow.html): 
* "The Success Criterion is met as long as all content and functionality are still fully available - either directly, or revealed via accessible controls, or accessible via direct links."
* (Example) "Note that as the zoom percentage increases, the navigation changes first to hide options behind a "More" dropdown menu. As zooming continues, most navigation options are eventually behind a "hamburger" menu button. All the information and functionality is still available from this web page. There is no horizontal scrolling."

**Comment by alastc** [comment]
1.4.10 is slightly generalized to "without loss of _information_ or functionality", whereas 1.4.4 is "without loss of _content_ or functionality", but I think the same principle holds.

I.e. the content isn't lost, but when there isn't sufficient space for it you might have to click on something to reveal it.

**Comment by mbgower** [comment]
I'll note that there is a bit of a potential catch in this line of thought. That is, truncation can be intentionally designed into the experience for everyone; as such, it does not necessarily represent an accessibility issue, per se. So, in a hypothetical, where I design a table and truncate all the column headers for everyone, it isn't a failure of WCAG as far as I can tell.

To some, it may seem difficult to argue that it would be a significant impact to most users if one more letter disappeared in that table truncation as a result of resizing text; however, it is easier to understand the impact on users if, as a result of text resizing, the truncation continued to the point where the remaining displayed letters were either meaningless or ambiguous (i.e., three of the truncated column headers had only the exact same three letters displayed).

As a result, a tight and appropriate reading of 1.4.4 or 1.4.10 not only aligns with the intent, but also provides consistency. If resizing text results in the loss of even a single character of text, it is a failure of the relevant SC (albeit it likely a very minor one) if there is not a means for the user to display the truncated information.

**Comment by mbgower** [comment]
**Draft Working Group Response**

Techniques in WCAG, whether sufficient or failures, do not represent an exhaustive list. As stated in [Understanding Techniques for WCAG Success Criteria](https://www.w3.org/WAI/WCAG22/Understanding/understanding-techniques):
> There may be other ways to meet success criteria besides the sufficient techniques... W3C's techniques are not comprehensive and may not cover newer technologies and situations.

The Working Group welcomes contributions of new techniques, but often the material in the Understanding documents provides sufficient context. This seems to be the case here.
 
 Both 1.4.4 Resize Text and 1.4.10 Reflow specify the need to meet the requirement without loss of information/content. Truncation is discussed a number of times in the  [1.4.4. Understanding document](https://www.w3.org/WAI/WCAG21/Understanding/resize-text#:~:text=truncation%20is%20acceptable%20if%20the%20component%27s%20full%20content%20is%20available%20on%20focus%20or%20after%20user%20activation%20and%20an%20indication%20that%20this%20information%20can%20be%20accessed%2C%20is%20provided%20to%20the%20user%20in%20some%20way%20besides%20the%20fact%20that%20it%20is%20truncated.), including:
>  truncation is acceptable if the component's full content is available on focus or after user activation and an indication that this information can be accessed, is provided to the user in some way besides the fact that it is truncated.

The proposed use case seems to meet this stipulation. If a PR is submitted that incorporates this use case into the existing guidance, either as a new example or as new technique, the task force will assess it.  Otherwise, the working group is of the opinion that the existing guidance sufficiently covers truncation.

**Comment by dan-tripp-siteimprove** [comment]
Thank you both.   I think I see now: I was looking at the existing guidance in "Understanding 1.4.4" as being specific to those situations i.e. user-supplied content and user-specified column width.   Now you're both saying it isn't, and I'll go with that.

I will think about submitting a PR.  First I'll ponder the question: what is the likelihood that other people will misread "Understanding 1.4.4" the same way I misread it?  

Regardless, that's enough for this issue, so I'll close it.  Thanks again.

**Comment by bruce-usab** [comment]
> ...First I'll ponder the question: what is the likelihood that other people will misread "Understanding 1.4.4" the same way I misread it?

Chances are 100%!  Please @dan-tripp-siteimprove do be encouraged to propose a PR.
