### ISSUE TITLE
Technique F106 - "Motion Actuation Success Criteria" goes to a 404

### ISSUE THREAD

**Issue by koalie** [w3c/wcag#3800]
Hello,
Please consider the issue raised here:
https://lists.w3.org/Archives/Public/public-website-redesign/2024Mar/0000.html

**Comment by patrickhlauke** [comment]
Already fixed in https://github.com/w3c/wcag/commit/dd4939bd2db3dcf1776c337f7100e6b209d38c8f#diff-764972becf3ab041dab4140606ff21a5108ae23be0729f9901282d69dd268ed9

Will go live next time this is republished /cc @iadawn
