### ISSUE TITLE
Reference to WCAG 2.0 instead WCAG 2.1

### ISSUE THREAD

**Issue by rscano** [w3c/wcag#382]
Translating WCAG 2.1 into italian, i've found some reference to old WCAG 2.0 instead to WCAG 2.1.

In 0.2. in "success criteria" and "sufficient and advisory techninques" there are 3 use of term WCAG 2.0 instead WCAG 2.1.

In 0.3. https://www.w3.org/TR/WCAG21/#wcag-2-1-supporting-documents
In the two paragraph talk about WCAG 2.0 instead of WCAG 2.1. 

In conformance section, the reference link for "understanding Conformance" is to WCAG 2.0 
https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance 

In 5.2.4 "Understanding Accessibility Support" link points to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance".

In 5.2.5. "Understanding Conformance Requirements" link points to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance".

In 5.3.1 point 2 there is an editorial text visible "In WCAG 2.0 this was a dated URI, which may need to be adjusted when this becomes a Rec."

In 5.3.2.  "Understanding Conformance Claims" link points to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance and "Understanding metadata" points to https://www.w3.org/TR/UNDERSTANDING-WCAG20/appendixC.

Glossary: 
Definition: "Accessibility supported":
note 1,  link to: Level of Assistive Technology Support Needed for "Accessibility Support" refer to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.
Note 5, point "Understanding Accessibility-Supported Web Technology Use" to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.

Definition: "Conforming alternate version"
In note 6: "Understanding Conforming Alternate Versions" link refer to 
https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance

Definition: keyboard interface
Note 2 (PDA example) in WCAG 2.0 was set as example. In WCAG 2.1 is set as "note".

Definition: relative luminance
Note 1: "Understanding Success Criterion 1.4.3" link refer to https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast. 

Definition: technology (Web Content)
Note 3 in WCAG 2.0 was set as example. In WCAG 2.1 is set as "note".

Definition: text alternative
Note 1 "Understanding Text Alternatives" refer to https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance

Editorial issue:
Status of this document
At paragraph 3 and paragraph 8, the text is the same:
"This document has been reviewed by W3C Members, by software developers, and by other W3C groups and interested parties, and is endorsed by the Director as a W3C Recommendation. It is a stable document and may be used as reference material or cited from another document. W3C's role in making the Recommendation is to draw attention to the specification and to promote its widespread deployment. This enhances the functionality and interoperability of the Web."

0.5.2 Numbering in WCAG 2.1 at line 4:
"by inserting new success critera between existing success ccriteria"
need to change: critera in criteria and ccriteria in criteria.

1.4.10 in note 1, there is the word "Note:" that is rendundant.

There are a lot of closing round parentesis with point before it  .)   instead of ).

**Comment by alastc** [comment]
Thank you for the detailed comments, I've being tracking down the sources.

Several had already been fixed in our 'Master' branch which you can see at the [editor's draft](https://w3c.github.io/wcag21/guidelines/#wcag-2-layers-of-guidance), such as the WCAG 2.0 references in text.

Everything else I've dealt with in in a branch and created a [pull request](https://github.com/w3c/wcag/pull/419) for.

**Comment by rscano** [comment]
Thank u!

Il mar 3 lug 2018, 18:16 Alastair Campbell <notifications@github.com> ha
scritto:

**Comment by awkawk** [comment]
Issue closed as #426 approved as errata
