### ISSUE TITLE
WCAG 2.1 Techniques are 404ing

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#3886]
It's not broken links from, say, WCAG 2.2 documents, pages are 404ing from Google as well. For example: [WCAG 2.1 ARIA5](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA5) vs. [WCAG 2.2 ARIA5](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA5). See also, all the links to Techniques in [2.1 Use Of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html) vs. [2.2 Use Of Color](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html).

**Comment by patrickhlauke** [comment]
in the past the server silently added the `.html` part to the url. now it doesn't anymore. has the server config changed? @iadawn

**Comment by iadawn** [comment]
Looking into it

**Comment by iadawn** [comment]
Fixed. Problem resulted from a config change with unintended consequences
