### ISSUE TITLE
2.5.8 Understanding "draw" language

### ISSUE THREAD

**Issue by jamieherrera** [w3c/wcag#3895]
When looking at the Understanding document for 2.5.8 Target Size Minimum, what are users intended to understand by "draw" when referencing a 24 px diameter or square as a means of evaluation? Draw with what? 

The examples show images and circles and boxes as if if digital content were a printed picture and the user has a drafting compass and tools. 

I would expect/suggest more "calculate" and less "draw" action verbs for the user in that document. Conceptually the idea and visual of a 24 px diameter or square makes sense, but to actually confirm components are spaced far enough apart, I'm going to calculate the difference with math from the design doc or DOM or editing document, not draw two circles on a paper.

**Comment by kiara-stewart** [comment]
I'm cautious about tweaking the language here.

"Draw" aligns with how designers often work – creating a visual frame to ensure the correct target size and then designing the icon/control within that space.

Also, it doesn't seem like this is a widely misunderstood concept. This is actually the first time I've encountered someone interpreting "draw" as a physical action in WCAG.

If we have to make a change, maybe “accommodate" would be a better fit?

> From ChatGPT: A target must be able to fit a solid 24 by 24 CSS pixel square, aligned horizontally and vertically, to meet the criteria of being 'at least 24 by 24 CSS pixels.' This square should not extend beyond the boundaries of the target.

**Comment by kiara-stewart** [comment]
> I think we can all agree that such terms can be confusing for any non-native english speakers or just peoples using translators to others languages.

I have to respectfully disagree on this point @frr-1574. The way we're using the word "draw" matches its [primary definition](https://www.collinsdictionary.com/us/dictionary/english/draw) and how most people, including those who speak English as a second language, understand it ([Reddit example](https://www.reddit.com/r/EnglishLearning/comments/10mn6ew/how_on_earth_do_you_understand_the_word_draw/)) Also, when I translate it into other languages I am proficient in, the meaning stays clear and accurate.

Looking at [our official translations](https://www.w3.org/WAI/standards-guidelines/wcag/translations/), I'm not sure if choosing a different word would help explain the SC better or just repeat what's already in the WCAG. 

With that in mind, what word would you use to make understanding this SC easier @frr-1574?

**Comment by frr-1574** [comment]
> > I think we can all agree that such terms can be confusing for any non-native english speakers or just peoples using translators to others languages.
> 
> I have to respectfully disagree on this point @frr-1574. The way we're using the word "draw" matches its [primary definition](https://www.collinsdictionary.com/us/dictionary/english/draw) and how most people, including those who speak English as a second language, understand it ([Reddit example](https://www.reddit.com/r/EnglishLearning/comments/10mn6ew/how_on_earth_do_you_understand_the_word_draw/)) Also, when I translate it into other languages I am proficient in, the meaning stays clear and accurate.
> 
> Looking at [our official translations](https://www.w3.org/WAI/standards-guidelines/wcag/translations/), I'm not sure if choosing a different word would help explain the SC better or just repeat what's already in the WCAG.
> 
> With that in mind, what word would you use to make understanding this SC easier @frr-1574?

-If a target is not large enough to allow for a 24 by 24px square to be **placed** inside it
-The rounded corners do not leave sufficient space to **place** a 24 by 24px square inside the target
-When a target is smaller than 24 by 24 CSS pixels, it is undersized. In this case, we check if it at least has sufficient spacing by **placing** a 24 CSS pixel diameter circle over the undersized target, 

This will for sure in my opinion resolve any potential issues.

**Comment by kiara-stewart** [comment]
Thank you, @frr-1574! I do think "place" is a good option!

> This will for sure in my opinion resolve any potential issues.

One thing I've learned from reviewing these tickets is that there's no perfect wording. "Place" could be misinterpreted just as "draw" was. Someone might mistake "place" for a physical location, similar to how "draw" was mistaken for a physical act.

We could consider other factors—word frequency, formal definitions, intended audience—but at the end of the day, the perfect wording is subjective. We'll see how it goes with the rest of the working group!

**Comment by frr-1574** [comment]
> Thank you, @frr-1574! I do think "place" is a good option!
> 
> > This will for sure in my opinion resolve any potential issues.
> 
> One thing I've learned from reviewing these tickets is that there's no perfect wording. "Place" could be misinterpreted just as "draw" was. Someone might mistake "place" for a physical location, similar to how "draw" was mistaken for a physical act.
> 
> We could consider other factors—word frequency, formal definitions, intended audience—but at the end of the day, the perfect wording is subjective. We'll see how it goes with the rest of the working group!

I have no issue with the word draw by itself. The issue comes when we start using translator :)
For example From English to French, the final translation results:

> Pour qu'une cible fasse "au moins 24 x 24 pixels CSS", il doit être possible de dessiner un carré solide de 24 x 24 pixels CSS, aligné sur les axes horizontal et vertical de telle sorte que le carré soit complètement à l'intérieur de la cible (ne s'étend pas en dehors de la zone cible).

It translates the word "draw" to its meaning, but the issue is that the "Draw" as of "draw as of in your head / imagine it" is not something people say in French. In French, draw just means .. draw on paper.

![drawing](https://media.tenor.com/D8UlBcYic74AAAAM/doodling-drawing.gif)

On the side I took the French as a reference besides the fact that there is already a [WCAG French Version](https://www.w3.org/Translations/WCAG21-fr/), but this could be applied to virtually any language not yet implemented, if draw is took to its absolute definition in the translation language, it may cause issue for its understanding.

**Comment by kiara-stewart** [comment]
I completely understand your point, @frr-1574 .

The term "draw," as in "imagine in your mind," is an idiomatic expression, and generally, it's best to avoid such expressions in translations. 

However, in this instance, the literal translation still holds. According to the [Cambridge Dictionary](https://dictionary.cambridge.org/us/dictionary/english-french/draw), "dessiner" translates to "draw," which is primarily defined as "to make a picture with a pencil or pen." (This definition remains accurate/valid even in the context of modern design tools like Sketch, Figma, and Adobe, which still symbolically have pencil and pen tools.) 

Therefore, a literal translation in this case would yield the correct interpretation of the text.

You can draw the target size both literally. (on paper, on a computer) and figuratively (in your head).

**Comment by kiara-stewart** [comment]
Given this discussion, it might be better to establish a clear rule? - 

In instances where the original word and its automatic translation significantly diverge in meaning across two or more of the [supported languages](https://www.w3.org/WAI/standards-guidelines/wcag/translations/), we should substitute the original term with one that is better optimized for accurate automated translations.

**Comment by frr-1574** [comment]
I think this is a great solution @kiara-stewart, adding such a rule will make it more easier to agree on such subject in the future.

**Comment by jamieherrera** [comment]
So is "calculate" not being considered? This is essentially a math problem, so we actually do want people to actually calculate whether or not a length of target is 24 or more px/pt/dp.
