### ISSUE TITLE
Understanding Reflow "out of the flow"

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#390]
Reflow page not part of Understanding flow...

From https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception.html to Reflow...

You'll see: https://www.w3.org/WAI/WCAG21/Understanding/reflow

**Comment by alastc** [comment]
Hi Jake,

Is this still an issue? The link at the top works fine for me.

**Comment by jake-abma** [comment]
Seems fixed, thx
