### ISSUE TITLE
Should there be a technique for 1.4.4 that mentions `rem` units?

### ISSUE THREAD

**Issue by backwardok** [w3c/wcag#3903]
For [technique C28](https://www.w3.org/WAI/WCAG22/Techniques/css/C28), there's an explicit mention of using `em` units to meet 1.4.4 Resize Text. Should there either be an additional technique that mentions `rem` units or an update to C28 to reference `rem` units as well? Seems like supporting `rem` units would be a similarly sufficient technique to C28.

**Comment by patrickhlauke** [comment]
techniques are not exhaustive, so don't think it'd be worth spinning up a whole new technique that is effectively the same, just using `rem` instead of `em`.

**Comment by fstrr** [comment]
Could we tweak that one to add in some `rem` content?
