### ISSUE TITLE
Understanding pages failing 1.4.10

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#3911]
@yatil's [recent issue on the position of the "In brief" sections](https://github.com/w3c/wcag/issues/3910#issuecomment-2179518592) made me aware of the fact that on narrow viewports there is horizontal scrolling on the understanding pages - just for the logo, it seems. So these pages fail 1.4.10 Reflow. I think WCAG should meet its own requirements. Who would be the one to correct this? @iadawn ?

As to what is visible in narrow viewports by default, it would certainly be a good idea to render the page contents menu as disclosure pattern so that content is not pushed down too far.

**Comment by patrickhlauke** [comment]
Confirmed, at 320 CSS px the header causes the scrollbar

![screenshot of an understanding page, at 320 CSS px width viewport](https://github.com/w3c/wcag/assets/895831/edb82c1f-440c-4c24-8e8b-784eabac8325)

**Comment by iadawn** [comment]
This presents an issue, to deal with the reflow, and a request, to change how the in-page navigation is rendered.

I will handle the former. For the latter, I am not clear on the value that it would add. Additionally, if the in-page navigation is changed then the resource navigation ('All Understanding Docs', 'Guideline: Readable', ... etc) would need to be looked at as well. This is quite a bit to change simple on a request.

Regardless, @detlevhfischer could you raise a separate issue for the feature request. Thanks!

**Comment by detlevhfischer** [comment]
@iadawn thanks for the quick response. I have second thoughts on that feature request (to turn the in-page navigation into a disclosure) - there are pros and cons (discoverability & navigation distance vs. visibility on narrow viewport without scrolling). For now I'd rather wait and see what others think.

**Comment by iadawn** [comment]
No problem... if it looks like there is weight to explore this, please do raise the separate issue.

**Comment by patrickhlauke** [comment]
just making the secondary nav stack vertically in a controlled manner would also work - which it currently does, but in a haphazard way
