### ISSUE TITLE
Benefits sometimes nested under Intent in source files (including template)

### ISSUE THREAD

**Issue by kfranqueiro** [w3c/wcag#3924]
The Benefits section in Understanding documents is always displayed as a level-2 heading and included in the table of contents, after Intent.

However, a handful of files - _including `understanding-template.html`_ - instead nest Benefits within Intent, which the build process corrects, pulling it back out to a top-level section with `h2`.

I'm not sure if there's history behind this discrepancy, but it seems like we ought to make the source files consistent - and at the very least, make the template reflect reality.

A search for `<h3>Benefits` should find the source files in question (as opposed to `<h2>Benefits` for ones that fit the current build behavior).

**Comment by Stephluvsbbymanny** [comment]
[stephanie Rodriguez ](url)
