### ISSUE TITLE
single pointer definition includes path-based gestures?

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#394]
_From @becka11y on April 18, 2018 20:54_

This relates to #634 which is closed.  I am confused by the how definition of single pointer is used in the Pointer Gestures SC because the single pointer definition includes path-based gestures?  
 The definition in the 17 April 2018 editor's draft is:

pointer input that operates with one point of contact with the screen, including single taps and clicks, double-taps and clicks, long presses, and path-based gestures

But 2.5.1 Pointer Gestures says:

All functionality that uses multipoint or path-based gestures for operation can be operated with a single pointer without a path-based gesture, unless a multipoint or path-based gesture is essential.

How can this be achieved if the definition of single pointer includes path-based gesture? 

I get the intent, the user must be able to operate using a single point of contact but without moving it along a path.  But the wording of the SC implies that a single pointer definition can be split into two parts - single point of contact with no movement and single point of contact with movement along a path.  Isn't that really two separate definitions?

I suspect I am splitting hairs. 

_Copied from original issue: w3c/wcag21#868_

**Comment by michael-n-cooper** [comment]
_From @detlevhfischer on April 19, 2018 7:39_

I think seen from the context of 2.5.1 Pointer Gestures it looks indeed odd to have path gestures included in the definition of „single pointer“. I don‘t know when that crept in, and why. Having said that, the SC text says „ single pointer without a path-based gesture“ so it can bee seen as referring to the single Pointer definition while at the same time excluding the path-based aspect of it. Is there some reason why „path-based“ must remain in the definition? I would prefer to get rid of it....

**Comment by michael-n-cooper** [comment]
_From @detlevhfischer on April 26, 2018 16:27_

Proposed WG response:
Thank you for your comment.
The Success Criterion 2.5.1 Pointer Gestures consciously refers to a subset of the single pointer definition "All functionality (...) can be operated with a single pointer **without a path-based gesture**" because this is what is targeted here. The wider definition including the path-based aspect is needed in case of SC 2.5.1 Pointer Cancellation, for example, to cover drag-and-drop actions.

**Comment by michael-n-cooper** [comment]
_From @greg-lowney on May 1, 2018 4:52_

Personally, I'd prefer that instead of talking around it, our response would be honest and straightforward enough to admit that the definition is badly written and should not include the reference to path-based gestures, even though it may be too late in the process to remove it from the document.

**Comment by michael-n-cooper** [comment]
_From @alastc on May 8, 2018 22:22_

Well, two SCs use the definition so either: It would be the current definition and take away the path-based-gestures, or you'd remove the "path based gestures" part of the definition and have to add it to the other SC.

Pointer cancellation would have to start: "For functionality that can be operated using a single pointer including path based gestures, at least one of the following is true:"

If you define 'single pointer', to me it makes logical sense to include paths, as that is a thing you can do with a single pointer.

So of the two options, this seems to be the preferable one.

**Comment by fstrr** [comment]
Hopefully, this is covered by #3536

**Comment by patrickhlauke** [comment]
@fstrr well spotted, it is indeed covered I'd say

**Comment by fstrr** [comment]
@patrickhlauke was going through issues to queue up for the backlog meetings :)

I'll close this up on the basis that 3536 is in the works.
