### ISSUE TITLE
Formatting the new WCAG 2.1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#396]
_From @DavidMacDonald on May 4, 2018 20:29_

@michael-n-cooper @awkawk 

I recommend we use the previous styling for the guidelines. @slhenry did a lot of work and study of styling...

![image](https://user-images.githubusercontent.com/2365411/39651202-f7877f6e-4fb8-11e8-8a43-a33fb230d68e.png)

![image](https://user-images.githubusercontent.com/2365411/39651136-bcd5c74a-4fb8-11e8-8ff2-2462d8d385bc.png)

_Copied from original issue: w3c/wcag21#900_

**Comment by michael-n-cooper** [comment]
_From @awkawk on May 4, 2018 20:37_

We are constrained somewhat by the templates that W3C specs use, but we will discuss...

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm going to close it. If it needs re-opening, please do so.
