### ISSUE TITLE
Bidirectional text support

### ISSUE THREAD

**Issue by avidseeker** [w3c/wcag#3983]
Proper bidirectional text navigation, editing, and typing is essential for speakers of Right-to-left languages. 

Unicode specifies [Unicode Bidirectional Algorithm](https://www.unicode.org/reports/tr9/) (UBA) for programs to automatically detect the directionality of each paragraph. Although it is properly implemented in GUI toolkits such as GTK and QT, unfortunately, this algorithm is still not implemented in many major browsers.

* [Chromium UBA](https://issues.chromium.org/u/3/issues/354513199)
* [Chromium force text direction](https://bugs.chromium.org/p/chromium/issues/detail?id=1357401)
* [Firefox UBA](https://bugzilla.mozilla.org/show_bug.cgi?id=1909120)
* [Firefox force text direction](https://bugzilla.mozilla.org/show_bug.cgi?id=1787660)
* [qtbrowser](https://bugreports.qt.io/browse/QTWB-67)
* [Webkit](https://bugs.webkit.org/show_bug.cgi?id=247334)

All of the previously listed issues are related to text fields and the alignment of text within them. However, this should also apply to HTML rendering, meaning that if two paragraphs in HTML source are:

```html
<p>
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
</p>
<p>
	قِفَا نَبْكِ مِنْ ذِكْرَى حَبِيبٍ ومَنْزِلِ، بِسِقْطِ اللِّوَى بَيْنَ الدَّخُول فَحَوْمَلِ. فَتُوْضِحَ فَالمِقْراةِ لمْ يَعْفُ
</p>
```
Then the browser would apply UBA on the second paragraph so that it renders it the same as it renders:

```html
<p>
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
</p>
<p dir="rtl">
	قِفَا نَبْكِ مِنْ ذِكْرَى حَبِيبٍ ومَنْزِلِ، بِسِقْطِ اللِّوَى بَيْنَ الدَّخُول فَحَوْمَلِ. فَتُوْضِحَ فَالمِقْراةِ لمْ يَعْفُ
</p>
```

Here is for example how it is rendered in UBA-supported text editor (GTK):

![image](https://github.com/user-attachments/assets/7c2dfe4c-e336-4e84-b92b-999d3a44a77e)

Of course, the `dir` HTML attribute would still stay as a way to force text direction, but by default, applying UBA would be more close to what the end-user would expect.

I hope that by adding Bidirectional Text Support as a WCAG standard, that'll push browsers to implement it.

Resources and readings:
-   [Comprehensive guide of RTL styling in HTML](https://rtlstyling.com/posts/rtl-styling)
- [W3C Bidi Text Basics](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics)
-  [freedesktop specification for Bidi support](https://www.freedesktop.org/wiki/Specifications/bidi-spec/): [terminal](https://terminal-wg.pages.freedesktop.org/bidi/).

**Comment by patrickhlauke** [comment]
I'd suggest taking this to https://github.com/w3c/wcag3 rather than here, as there won't be any new requirements added to 2.x. I can see how this conceptually is similar to the requirement for programmatically determined language of documents, though it would be good to demonstrate first how this is something that affects people with disabilities specifically (and isn't just a general code quality issue not specific to accessibility requirements)

**Comment by avidseeker** [comment]
Moving to https://github.com/w3c/wcag3/issues/105, then.
