### ISSUE TITLE
incorporate feedback from Review of Understanding Text Spacing

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#399]
_From @mbgower on May 10, 2018 16:18_

I will take feedback from the [survey results](https://www.w3.org/2002/09/wbs/35422/understanding_changes2/results) and make a new PR

_Copied from original issue: w3c/wcag21#911_

**Comment by michael-n-cooper** [comment]
_From @mbgower on May 10, 2018 22:55_

@awkawk, Created PR https://github.com/w3c/wcag21/pull/912

**Comment by alastc** [comment]
This was merged in the previous wcag21 repo, can close...
