### ISSUE TITLE
Broken video example in Reflow understanding

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#3992]
The embedded video in https://www.w3.org/WAI/WCAG22/Understanding/reflow.html#examples fails because it points to an external site (@alastc 's) where the https certificate fails at this moment.

![screenshot of the understanding page, with a broken video embed](https://github.com/user-attachments/assets/b99740ed-b50b-4246-bdf7-b6c1600e33fe)

Suggest moving the video itself to the repo itself, and serving it directly from w3c (like we do for images)

**Comment by alastc** [comment]
It would be great if @kfranqueiro or @iadawn could create a place for us to host larger files so they don't end up in the repo.

**Comment by patrickhlauke** [comment]
Closing this issue itself, as the video isn't broken anymore. However, leaving the PR this spawned https://github.com/w3c/wcag/pull/3993 open for further investigation.
