### ISSUE TITLE
Orientation needs clarification on locking at the OS level

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#401]
_From @mbgower on May 17, 2018 16:34_

We need language clarifying what we mean by "locking" both in the context of our understanding doc, and how this SC about author responsibilities differs from the action of a user locking the OS either through a mechanical switch or a operating system software level to  a specific orientation. 

_Copied from original issue: w3c/wcag21#928_

**Comment by michael-n-cooper** [comment]
_From @mbgower on May 17, 2018 20:59_

@alastc and @DavidMacDonald , my first crack at proposed language changes. The first section is intended to be added to the existing Intent section. The second is intended to be a note with a subheading added after the Intent section.
### [Additional content to be added to the end of the existing the Intent section]
Historically, devices tended to have a fixed-orientation display, and all content was created to match that display orientation. Today, most handhelds and many other devices (e.g., monitors) have a hardware-level ability to dynamically adjust default display orientation based on sensor information. The goal of this Success Criterion is that authors should never restrict content's orientation, thus ensuring that it always match the device display orientation.

### Locking a device to an orientation
It is important to distinguish between an author's responsibility not to restrict content to a specific orientation, and device-specific settings governing the locking of display orientation.

Many hand-held devices offer a mechanical switch or a system setting (or both) to allow the user to lock the device display to a specific orientation. Where a user decides to lock their entire device to an orientation, all applications are expected to pick up that setting and to display content accordingly.

This Success Criterion is ancillary to such device "lock orientation" settings. A web page that does not restrict its display orientation will _always_ support the system-level orientation setting, since the system setting is picked up by the user agent. Alternatively, where a device-level orientation lock is not in place, the user agent should display the page according to the orientation of the device (either its default, or the current orientation determined by any device senors).

**Comment by michael-n-cooper** [comment]
_From @mbgower on May 17, 2018 21:5_

Do we want to mention the exception of an image editor, which typically displays an image oriented according to the image's own metadata (therefore its display is essential). Even with this allowed exception, the editor typically offers its own ability for the user to rotate the image.

**Comment by michael-n-cooper** [comment]
_From @awkawk on May 23, 2018 13:45_

Mike, can this be closed now?

**Comment by mbgower** [comment]
Yes, it is addressed in the Understanding language.. Closing.
