### ISSUE TITLE
Broken link on Technique H48

### ISSUE THREAD

**Issue by anthonyiu** [w3c/wcag#4014]
A broken link found on this page: https://www.w3.org/WAI/WCAG21/Techniques/html/H48

Under Example 4, the link [working example of contact information using a description list](https://www.w3.org/WAI/WCAG21/working-examples/description-list-contact-info/) is broken.

**Comment by patrickhlauke** [comment]
@kfranqueiro this may be another new build system oddity. on the WCAG 2.2 version https://www.w3.org/WAI/WCAG22/Techniques/html/H48 the link resolves correctly to https://www.w3.org/WAI/WCAG22/working-examples/description-list-contact-info/but in the WCAG 2.1 version the target https://www.w3.org/WAI/WCAG21/working-examples/description-list-contact-info/ doesn't exist

**Comment by iadawn** [comment]
Looks like a name change quite a few PRs ago and no update to CVS. Sorted now.
