### ISSUE TITLE
Making 1.4.1 use of color info on state requirements for 1.4.11 into new sufficient and failure techniques

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#402]
_From @mbgower on May 22, 2018 15:50_

After discussion on 1.4.11 Non-Text Contrast and use of color for state indicators, the current information on use of color and relative luminence will be removed and a new success technique and failure technice, similar to https://www.w3.org/TR/WCAG20-TECHS/G183 and https://www.w3.org/TR/WCAG20-TECHS/F73.

The current text being removed from the exisiting Understanding document wording is:

> Note on SC 1.4.1 Use of Color
> 
> 1.4.1 states "Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element." Although every object on a screen is arguably created through use of color only (shapes are created by altering a bunch of pixels from white to another color), the context made clear in the Understanding document is that 1.4.1 addresses changing only the color of an object (or text) without otherwise altering the object's form. If an author adds an outline or shadow to a shape to indicate a change in state, that is not relying solely on use of color.
> Relative luminence: If the selected and unselected states of an object do vary only by color, this is still acceptable so long as the luminosity contrast ratio between the selected and unselected colors differs by at least 3:1.
> User agent enhancment: If the author-supplied visual indicators of change in state vary only by color, this is still acceptable if the user agent provides a redundant visual effect which authors do not obscure.
> 

_Copied from original issue: w3c/wcag21#933_

**Comment by michael-n-cooper** [comment]
_From @alastc on May 22, 2018 22:41_

The cross-reference text is in [this commit](https://github.com/w3c/wcag21/pull/924/commits/f60c0febf3bb754e319880a9fe24137c6599830c) and should be [preview-able on the working branch](https://rawgit.com/w3c/wcag21/non-text-contrast/understanding/21/non-text-contrast.html).

**Comment by mbgower** [comment]
The decision was made that different states of a control do not need to meet a 3:1 ratio against other states in order to meet 1.4.11 Non-Text Contrast. From the [Understanding document](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html):
> This Success Criterion does not require that changes in color that differentiate between states of an individual component meet the 3:1 contrast ratio when they do not appear next to each other. For example, there is not a new requirement that visited links contrast with the default color, or that mouse hover indicators contrast with the default state. 

This SC is a candidate to be closed. I am marking this for consideration in future versions.
