### ISSUE TITLE
"dissement": typo in "Input Purposes for User Interface Components"

### ISSUE THREAD

**Issue by remibetin** [w3c/wcag#4033]
In ["Input Purposes for User Interface Components"](<https://www.w3.org/TR/WCAG22/#input-purposes>), "`postal-code`"'s meaning is described as follows:

> Postal code, post code, ZIP code, CEDEX code (if CEDEX, append "CEDEX", and the dissement, if relevant, to the address-level2 field)

<https://github.com/w3c/wcag/blob/94c76c8af45a906445e8658d7805e1ecbae57c02/guidelines/input-purposes.html#L32>

"dissement" should be "arrondissement".

The HTML standard does use "arrondissement":
- <https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-postal-code>
- <https://html.spec.whatwg.org/dev/form-control-infrastructure.html#attr-fe-autocomplete-postal-code>

If approved, I would be happy to provide a Pull Request.

**Comment by patrickhlauke** [comment]
Ah, well spotted. I made a PR as I was already working on some stuff there https://github.com/w3c/wcag/pull/4034

**Comment by remibetin** [comment]
@patrickhlauke Thanks for your prompt reply and action!
