### ISSUE TITLE
2.5.2 Pointer Cancellation: Testing approach for content with wide accessibility baseline

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#4035]
This is a question for someone steeped in the technical details of pointer events. 
The Technique [G212](https://www.w3.org/WAI/WCAG22/Techniques/general/G212) describes the way to test whether functions are triggered by a down event (mousedown, touchstart): 
> Activate the down event then move the pointer outside the target before triggering the up-event.

What the technique doesn't specify is whether this happens in a mousing or touch environment.
Does this mean that for content with a wide accessibilty baseline that claims to meet 2.5.2, this test would always need to be carried out using both touch input  **and** mouse input? 

Or does one effectively include the other, so that when, say, nothing happened on the touchstart event, nothing will happen on a mousedown event?
Finally, if both tests are indeed necessary when covering desktop **and** mobile OSs, does it matter whether the mouse is attached to a device running Android / iOS or to a desktop OS running Windows or MacOS?

**Comment by patrickhlauke** [comment]
> Does this mean that for content with a wide accessibilty baseline that claims to meet 2.5.2, this test would always need to be carried out using both touch input and mouse input?

Yes

> Or does one effectively include the other, so that when, say, nothing happened on the touchstart event, nothing will happen on a mousedown event?

`mousedown` and `touchstart` are separate (though touch events will also trigger [compatibility mouse events](https://www.w3.org/community/reports/touchevents/CG-FINAL-touch-events-20240704/#mouse-events) but only as a result of a full down/up activation gesture / "tap"), so you'll need to test both.

also should really test `pointerdown` - the new combined event model for mouse/touch/stylus/etc.

> Finally, if both tests are indeed necessary when covering desktop and mobile OSs, does it matter whether the mouse is attached to a device running Android / iOS or to a desktop OS running Windows or MacOS?

need to test all pointer devices available on all devices/environments. so also considering potential touch on a "desktop/laptop" device (think Surface for instance) and mouse on a nominally "mobile/touchscreen" device.

**Comment by detlevhfischer** [comment]
Thanks @patrickhlauke for the quick answer (even if the effort appears prohibitive).
> also should really test pointerdown

What would that mean in practical terms?

**Comment by patrickhlauke** [comment]
from a manual testing point of view, nothing. this is all behind-the-scenes plumbing. that was more in case you're running some code analysis or other automated thing that looks for event listeners. in that case, you want to look not just for things that happen on `mousedown` or `touchstart`, but also on `pointerdown`

**Comment by detlevhfischer** [comment]
Nach Feedback von @patrickhlauke habe ich die Prüfanleitung angepasst siehe PR https://github.com/BIK-BITV/BIK-Web-Test/pull/490

Ich hoffe, dass keine wirklichen Lücken durch das Auslassen der Input-Varianten "Touch auf Desktop mit Touch-Screen" und "Maus auf Geräten mit mobil-Betriebssystem" entstehen. Sonst gerne Issue weiterspinnen...
