### ISSUE TITLE
Live form controls in understanding non text contrast

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#405]
_From @michael-n-cooper on May 24, 2018 15:36_

[Understanding Non Text Contrast](https://w3c.github.io/wcag21/understanding/non-text-contrast) has live form controls. I think they are meant to be examples, but that is not clear in all cases. In any event, in my browser they don't seem to show what they mean to. The use of live controls may cause odd side effects. I suggest using images and not live controls.

_Copied from original issue: w3c/wcag21#940_

**Comment by michael-n-cooper** [comment]
_From @alastc on May 26, 2018 0:16_

Ah, the styles are being lost in the conversion. It isn't your browser, but there were some custom styles in the head of the RAW doc that aren't coming through.

 I can add those as images.

**Comment by alastc** [comment]
Added as images a while back, closing issue.
