### ISSUE TITLE
Understanding Non-Text contrast needs update to reflect consensus.

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#406]
_From @DavidMacDonald on May 30, 2018 21:17_

Currently there are a number of things in the Understanding of Non-Text contrast that need updating: There are 2 paragraphs talking about the need to identify hit area, and our current consensus is that we need to identify the control, not the hit area. Here's the current text:

> For active controls on the page, such as buttons and form fields, any visual boundary that indicates the component's hit area (the region where a pointer can activate the control) must have sufficient contrast with the adjacent background ... This success criteria does not require that controls have a visual boundary indicating the hit area, but that if there is an indicator then it has sufficient contrast. If only the text (or icon) is visible and there is no visual indication of the hit area, then there is no contrast requirement beyond the text contrast (1.4.3 Contrast (Minimum)) or icon contrast covered by the Graphical Objects portion of this Success Criteria. Note that for people with cognitive disabilities it is recommended to delineate the boundary of controls to aid in the recognition of controls and therefore the completion of activities.

Also there is an example on an input with just an underline, but the graphic has all 4 sides with borders.

_Copied from original issue: w3c/wcag21#946_

**Comment by alastc** [comment]
Hi @DavidMacDonald,

I think this is an old issue and we've updated that text several times since. Please open if you disagree, I'm just clearing things out...
