### ISSUE TITLE
1.4.13 on Hover indicates that additional content must be dismissable without moving keyboard or hover yet understanding document indicates a close button is a solution

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#409]
_From @mraccess77 on June 6, 2018 15:21_

The understanding document may need to be updated to remove the bit about a close button being an option for dismissing since it would require the user to move the pointer hover or keyboard focus.  If there is some nuance I am missing then we should update the understanding to make that more clear.

https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

_Copied from original issue: w3c/wcag21#952_

**Comment by alastc** [comment]
This has been updated ([editors draft](https://w3c.github.io/wcag/understanding/content-on-hover-or-focus.html)), the close button aspect no longer appears in the doc.
