### ISSUE TITLE
WCAG 2.1 - Understanding intro - number of 'guidelines'

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#4097]
From Jennifer Hagedorn on email:

> Hello, I believe an edit may be needed under Layers of Guidance > The Guidelines on [this page](https://www.w3.org/WAI/WCAG21/Understanding/intro#understanding-the-four-principles-of-accessibility). It states that there are 12 guidelines, but on [the spec page](https://www.w3.org/TR/WCAG21/#wcag-2-layers-of-guidance) it says there are 13.
> 
> Not sure which is correct. Thanks!

Closed by #4007

**Comment by alastc** [comment]
@kfranqueiro I've updated [this in the WCAG 2.1 branch](https://github.com/w3c/wcag/blob/WCAG-2.1/understanding/intro.html), is that's all that is required?

**Comment by kfranqueiro** [comment]
Yes; moreover, it looks like the correct number is already reflected in this file on `main`, so this won't be an issue once we have the new build system generating 2.1 docs from the main branch (what #4007 is working towards).

**Comment by kfranqueiro** [comment]
This is resolved now that WCAG 2.1 Techniques and Understanding Docs have been republished via the new build system.
