### ISSUE TITLE
Duplicate paragraph in the "Status of This Document" section of WCAG 2.1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#410]
_From @lauracarlson on June 7, 2018 19:32_

It seems that following paragraph is repeated twice in the [Status of This Document](https://www.w3.org/TR/WCAG21/#status-of-this-document) section of 2.1:

> This document has been reviewed by W3C Members, by software developers, and by other W3C groups and interested parties, and is endorsed by the Director as a W3C Recommendation. It is a stable document and may be used as reference material or cited from another document. 
W3C's role in making the Recommendation is to draw attention to the specification and to promote its widespread deployment. This enhances the functionality and interoperability of the Web.

_Copied from original issue: w3c/wcag21#955_

**Comment by awkawk** [comment]
The first version is the one that needs to be removed.

**Comment by alastc** [comment]
@michael-n-cooper this is not apparent in the editors draft, but I'm not sure it would be, is this ready to close?

**Comment by alastc** [comment]
Closing as this is in the errata page.
