### ISSUE TITLE
Techniques for WCAG 2.0 submission results seem blank screen

### ISSUE THREAD

**Issue by hata6502** [w3c/wcag#4119]
When submit techniques via [Techniques XML Submission Form](https://www.w3.org/WAI/GL/WCAG20/TECHS-SUBMIT/), the following result screen are displayed: 
[![Image from Gyazo](https://i.gyazo.com/38d9adb1db2db97f488ab1e4bb7dac01.png)](https://gyazo.com/38d9adb1db2db97f488ab1e4bb7dac01)

HTTP POST responses are `200 OK`, but this blank screen may been seen not submitted successfully.

**Comment by mbgower** [comment]
@kfranqueiro

**Comment by hata6502** [comment]
I re-sent new issue at https://github.com/w3c/wcag/issues/4133
Instead of WCAG 2.0 submission form.

**Comment by hata6502** [comment]
I re-sent new tequnique at https://github.com/w3c/wcag/pull/4131
Instead of WCAG 2.0 submission form.

**Comment by hata6502** [comment]
@mbgower If you don't mind, I would like you to review https://github.com/w3c/wcag/pull/4131 .

**Comment by mbgower** [comment]
@hata6502 I have added your PR to the WCAG 2 Task Force project and moved to Draft. It will be reviewed as part of the TF process.

**Comment by kfranqueiro** [comment]
Kevin has updated the page in question to link to this repository's issue tracker, to avoid further confusion with the old form. With that addressed, I'll close this issue. We can focus on the submitted technique within the PR - thanks for creating it.
