### ISSUE TITLE
Small typo for Note 5.2.2 Full pages

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#413]
_From @jake-abma on June 8, 2018 16:13_

at https://www.w3.org/TR/WCAG21/#cc2 there's a Note where the note starts with the text "New A full page includes..."

> NOTE
> New A full page includes each variation of the page that is automatically presented by the page for various screen sizes (e.g. variations in a responsive Web page). 

If "New" is supposed to be present a colon ":" should be added, or the text "New" should be deleted.

_Copied from original issue: w3c/wcag21#959_

**Comment by awkawk** [comment]
fixed: 
https://github.com/w3c/wcag/commit/5d42e28f07dfcb5c0eaa8f0f5794ee133b7f6cfd
