### ISSUE TITLE
2.4.11: Focus Not Obscured and the View port

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#4138]
When navigating a listbox from a Combobox, where DOM focus is on the input, and navigation by arrow keys moves the virtual focus to the available options. If the option is off-screen due to being cut-off by the view port, and thus the selected option is completely invisible, is this a failure of 2.4.11: Focus Not Obscured (Minimum) (Level AA)?

The question is, is it the Combobox component (author-generated content) or the Browser (Viewport) that determines whether it is a violation of the success criterion? Also what is focused, the input or the option?

Personally I think this is fail as the visual point of focus is completely hidden, and is author-created content.
 
I'd appreciate the understanding of others in whether this is a violation of the SC.

**Comment by detlevhfischer** [comment]
The listbox dropping down can be seen as content opened by the author and thus exempt? If the author were to reset the page scroll state when a listbox drops down when not having sufficient space to fit into the viewport, this might be quite irritating.

**Comment by patrickhlauke** [comment]
to me it would fail focus visible, as objectively the focus is not visible when it falls outside of the viewport. it's not covered by author-generated content per se, it's literally covered by the boundaries of the viewport/user agent.

**Comment by patrickhlauke** [comment]
> Also what is focused, the input or the option?

technically, you could thinslice it by saying the actual focus (as in `document.activeElement`) is the input still, but ... that's a silly thinslicing. for the user, the focus is the option, as that's what their attention/regard is on

**Comment by LaurenceRLewis** [comment]
I understand the conclusion is not technically a failure of focus obscured because it is the viewport that is causing the option to be hidden, and not due to author-created content, just a bad user experience. 

I completely agree about being a failure of focus visible. I also am aligned on the "the focus is the option, as that's what their attention/regard is on".
