### ISSUE TITLE
Table of contents missing, big gap Understanding pages

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#415]
_From @jake-abma on June 9, 2018 7:0_

When visiting a understanding doc I see a gap / space from the left of 29em
```
@media screen and (min-width: 78em)
body:not(.toc-inline) {
    padding-left: 29em;
}
```
see: https://www.w3.org/WAI/WCAG21/Understanding/orientation.html

When I'm zoomed in (not browser zoom) this results in a 'blank' page as the content is out of view.
The 29em is for the TOC but not present.
Page should be properly left aligned without TOC.

_Copied from original issue: w3c/wcag21#962_

**Comment by alastc** [comment]
There is a project coming up to work on the design/structure of the understanding & technique documents, this aspect should be included then.

**Comment by fstrr** [comment]
Closing this issue as that large left-hand gap appears to be the design of the Understanding pages.
