### ISSUE TITLE
Understanding Success Criterion 1.3.4: Orientation

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#416]
_From @devarshipant on June 11, 2018 16:45_

https://www.w3.org/WAI/WCAG21/Understanding/orientation.html

Please refer to the following paragraphs:

> "The goal of this Success Criterion is that authors should never restrict content's orientation, thus ensuring that it always match the device display orientation."

1. Isn't "Content's Orientation" similar to "system-level orientation" setting? 

2. It is not clear what orientation settings can be controlled by content authors? I see Content, System-level, and Device-level Display orientation settings in use.

3. Should it be mentioned that restricting a display setting is fine if that specific display orientation is essential?

> " ...current orientation determined by any device senors."

senors should be sensors.

_Copied from original issue: w3c/wcag21#963_

**Comment by michael-n-cooper** [comment]
_From @NIKHILSAIREDDY on June 21, 2018 5:2_

Then what about the gaming softwares

**Comment by alastc** [comment]
I think thigs have changed anyway, the doc now starts:
> The intent of this Success Criterion is to ensure that content displays in the orientation (portrait or landscape) preferred by the user. Some websites and applications automatically set and restrict the screen to a particular display orientation and expect that users will respond by rotating their device to match, but this can create problems.

I think that clarifies 1 & 2, and the SC text itself has examples of 'essential':
> Examples where a particular display orientation may be essential are a bank check, a piano application, slides for a projector or television, or virtual reality content where binary display orientation is not applicable. 

@devarshipant does that resolve your comments/issues/questions?

**Comment by StefanSTS** [comment]
The term "binary" display orientation sounds a bit strange to me. For an easier understanding I would prefer something like: neither landscape nor portrait. Since WCAG is all about making things easy to understand.

**Comment by awkawk** [comment]
Suggest a modification that may address the issue but in a slightly different way:
Examples where a particular display orientation may be essential are a bank check, a piano application, slides for a projector or television, or virtual reality content where content is not restricted to simple landscape or portrait display orientation.

**Comment by StefanSTS** [comment]
That sounds much better. 
Though I think there are actually simple orientations for virtual reality too, if you wear VR glasses. It might not be in a 3D cinema. But that distinction might just be to much to explain in this example.
Maybe: ... where content is not - necessarily - restricted to simple ...

**Comment by mbgower** [comment]
BTW, isn't this normative language?

**Comment by awkawk** [comment]
@mbgower Whoops. I slipped into edit mode and since this issue was about the understanding doc I wasn't thinking about that yet.

**Comment by StefanSTS** [comment]
The text is a note in the WCAG 2.1 spec section 1.3.4, not the understanding documents, yes, so it is in the normative section, but in an informal note. This was the only search result I could find on the topic and since this is "w3c/wcag" I thought I was at the right place.
My suggestion was merely a request to find a clearer expression for future versions of the spec. So no editing in the REC, please, yes. ;-) And my main concern that brought me here was "binary" display orientation. I have translated some parts of the spec and I have to use this term in the translation though it does not feel right. Like which orientation is 0 and which is 1, or which one is power on and which one is power off. My concern here is to make it understandable for non native english readers too and the few more words above from awkawk did that.

**Comment by alastc** [comment]
It appears the 'to do' list for this item is:

- Small update to the SC note (for 2.2?)
- Understanding doc update to explain the VR and projector/TV aspects better.

I've done a PR for those (#724), adding text for the understanding:

> The exceptions for things considered essential is aimed at situations where the content would only be understood in a particular orientation, or where the technology restricts the possible orientations. If content is aimed at a specific environment which is only available in one orientation (such as a television) then the content can restrict the orientation. Technologies such as virtual reality use screens within goggles that cannot change orientation relative to the user's eyes.

I see @mbgower's point about VR, but I can see a scenario where the user is in a wheelchair (or has other difficulty moving their head to one side), and the 'content' includes a sign/message that is arranged to be read vertically. Most people could turn their heads, some could not. It would be an odd thing to do, but theoretically possible? 
Anyway, I'm happy with there being an exception at the moment as I don't think anyone is sure of the issues in VR yet.

That text is intended to explain why it's there, but without expanding too much yet.

**Comment by alastc** [comment]
The group [accepted the response & errata](https://www.w3.org/2002/09/wbs/35422/Tech_Und_survey/results#xq22). The understanding doc will update soon, the errata at the next main publishing point for the WCAG 2.1 page.
