### ISSUE TITLE
Enabling code-examples to reflow

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#423]
There's an issue in current technique documents where the code examples (in a `pre`) do not reflow in smaller windows or when zoomed in.

The solution *should* be simple, where the style is given this:
```
pre {
    white-space: pre-wrap;
}
```

[Pre-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Values) just means it acts like pre by default (with enough width), but does allow the lines to wrap if there is not enough space.

However, I think needs to be applied to base.css (after line 480), or somewhere that is below that in the cascade.

This issue was originally raised by @lauracarlson in #387 but might be moved to another repo 'upstream' for the general standards documentation.

**Comment by michael-n-cooper** [comment]
It might be possible to make the fix in css/additional.css which is, or should be, imported into all our publications.

If the cascade makes it not work, even with !important, it might require a pull request in https://github.com/w3c/tr-design/. But it could be a long while before that shows up in actual publications.

**Comment by alastc** [comment]
I've opened [an issue there](https://github.com/w3c/tr-design/issues/168), will see how it goes.

**Comment by alastc** [comment]
Next step: add it to the local CSS for WCAG's techniques/understanding docs.

**Comment by fstrr** [comment]
This doesn't appear to have been implemented. I did check via experimenting in dev tools, and adding `white-space:pre-wrap` to a `div.code pre` element on line 233 in additional.css worked on the [ARIA1](https://www.w3.org/TR/WCAG20-TECHS/ARIA1.html), [ARIA5](https://www.w3.org/TR/WCAG20-TECHS/ARIA5.html), and [ARIA 7](https://www.w3.org/TR/WCAG20-TECHS/ARIA7.html) Techniques:

<img width="393" alt="screenshot of dev tools with additional.css selected and edited to include the white-space rule." src="https://user-images.githubusercontent.com/20049493/167717940-ee6c8a91-ba65-4098-bd53-5298a8b15a36.png">

I don't now how I would build the site locally to do a more-thorough test, but that should happen to do a more-thorough set of testing.

**Comment by alastc** [comment]
@fstrr I think this stalled because the new design would (should) sort it out. (Same for anything under the "design & layout" tag.) 

I'll check with @michael-n-cooper about when that's rolling out.

**Comment by fstrr** [comment]
Closing this as it's not an issue any more.
