### ISSUE TITLE
Failure technique F87 contradicts the Accessible name and desc algorithm

### ISSUE THREAD

**Issue by Wildebrew** [w3c/wcag#433]
The [Accessible name and description algorithm](https://www.w3.org/TR/accname-1.1/) (v1.1) describes how content included using the CSS :before and :after pseudo classes should be included in the accessible name calculation for an element.
This actually works with most browser and screen reader combinations, see my [CSS pseudo classes for screen readers](https://codepen.io/Wildebrew/pen/yqNWXG) Code Pen example.
But [WCAG 2.0 Failure technique 87](https://www.w3.org/TR/WCAG20-TECHS/F87.html) forbids use of CSS content to communicate information.

Since CSS content is now a part of an element's accessible name, the WCAG spec can no longer outlaw its use, in my opinion.
 

I believe F87 pre dates the ANDC algorithm by a few years and the web techniques landscape has changed. In light of that I recommend updating this technique to say somethihg like "whereas CSS content can be used to communicate helpful information about an element it should not be used for essential information" altogether.
or to drop it.

**Comment by awkawk** [comment]
Thanks @Wildebrew 

Arguments to keep it: 
1. The test procedure requires that one checks whether the information is read by AT so if the content is read then the failure won't apply.

Arguments to remove it:
1. AT support is much better now than when this technique was authored.
2. The technique ignores that CSS is a technology that can be relied on, so it isn't appropriate to require that the information is available when CSS is off.

**Comment by Wildebrew** [comment]
I don't think we can consider IE11 (or MS Edge)  as the mainstay of
accessibility support anymore.
The browser landscape is changing, even for assistive technology users.
IE11 is no longer being updated and Edge is barely used (see the
WebAIM screen reader survey #7 for numbers).
From a screen reader user perspective I don't think lack of IE11
support is sufficient to mark something as a failure.

The low vision/custom CSS stylesheet argument I can definitely see the
point, but then the wording of F87 should be changed to explain that
the failure is primarily related to the problems of users relying on
custom style sheets.
I wonder if custom style sheets can be written that preserve the
content of pseudo elements. My CSS background is admittedly not strong
enough to provide the answer on that.


On 7/28/18, Jonathan Avila <notifications@github.com> wrote:
> Personal thoughts  -  I belove it is not supported by screen readers in IE.
>  Seems like pseudo elwmrns also complicates the situation for low vision
> users who use custom css fonts/color.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag/issues/433#issuecomment-408643318


-- 
Work hard. Have fun. Make history.

**Comment by awkawk** [comment]
Do we want to fail any content based on what a user style sheet does? How easy is it for a user to inadvertently cause the pseudo content to not display?

**Comment by Wildebrew** [comment]
My concerns with the user style sheet argument is that it should
equally apply to icon fonts and CSS images.

Using role="img" and aria-label you can make these images accessible
and they are frequently used (e.g. emojis).
But if CSS images are ok, can we fail use of pseudo element content?



On 7/30/18, Andrew Kirkpatrick <notifications@github.com> wrote:
> Do we want to fail any content based on what a user style sheet does? How
> easy is it for a user to inadvertently cause the pseudo content to not
> display?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag/issues/433#issuecomment-408873216


-- 
Work hard. Have fun. Make history.

**Comment by alastc** [comment]
> Since CSS content is now a part of an element's accessible name, the WCAG spec can no longer outlaw its use, in my opinion.

Except that the description does primarily aim it at people who override / don’t use CSS. The point about CSS being a tech that can be relied on is valid, but the fact the acc-name calc includes CSS content doesn’t help/affect those using customised visual access. 

Having said that, there are a couple of levels to customisation: You can start with the authored styles and over-ride them (e.g. with stylus plugin), which wouldn’t remove the before/after content. The windows high-contast mode is at the upper end of that, it does/did remove background images. Or the next level is that you can wipe out the author styles and only apply your styles, which would remove the before/after content. (I think the ‘reader’ view in some browsers would do that.)

We could update the 3rd part of the procedure to remove assistive tech, but I’m not sure that’s needed depending on your accessibility support statement? (I.e. if you’re relying on modern user-agents then it will automatically pass.)

I agree this should also apply to icon fonts & CSS images, there is a technique drafted somewhere for that... @lauracarlson?

**Comment by lauracarlson** [comment]
Hi @awkawk 

> Do we want to fail any content based on what a user style sheet does? 

I don't think so. I was thinking that the failure would be on authors for not providing role=img so that the user style sheet can hook to that. Check the draft "[Providing a Semantically Identified Icon Font with role=img](https://www.w3.org/WAI/GL/wiki/Providing_a_Semantically_Identified_Icon_Font_with_role%3Dimg)" technique is in the Wiki.

**Comment by lauracarlson** [comment]
Hi @alastc  

> I agree this should also apply to icon fonts & CSS images, there is a technique drafted somewhere for that... @lauracarlson?

Yes. It is "[Providing a Semantically Identified Icon Font with role=img](https://www.w3.org/WAI/GL/wiki/Providing_a_Semantically_Identified_Icon_Font_with_role%3Dimg)" in the Wiki.

**Comment by lauracarlson** [comment]
Hi @awkawk,

You wrote:
>How easy is it for a user to inadvertently cause the pseudo content to not display?

Pretty easily. As Alex Walker explained in [The Final Nail in the Icon Fonts Coffin?](https://www.sitepoint.com/final-nail-icon-fonts-coffin/), when a when a user overrides fonts, "they replace the alphanumeric characters but there are no replacements for these custom icons. We get left with big, ugly, unhelpful empty boxes instead."

Seren Davies goes into more detail in her [Death to icon fonts presentation (Video)](https://www.youtube.com/watch?v=9xXBYcWgCHA) and [speaker deck](https://speakerdeck.com/ninjanails/death-to-icon-fonts).

As for frequency Tyler Sticka states, [They Fail Poorly and Often](https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/).

**Comment by awkawk** [comment]
Are we talking about icon fonts or :before content more broadly?

**Comment by lauracarlson** [comment]
Hi  awkawk,

> Are we talking about icon fonts or :before content more broadly?

I am concerned about icon fonts added via generated content.  The LVTF and/or COGA may have broader concerns.

**Comment by awkawk** [comment]
I think that we should figure out the answer to the question about generated content in general first?

**Comment by lauracarlson** [comment]
Hi @awkawk,

[You wrote](https://github.com/w3c/wcag/issues/433#issuecomment-408912649):

> I think that we should figure out the answer to the question about generated content in general first?

Do mean as [F87 states](https://www.w3.org/TR/WCAG20-TECHS/F87.html) general generated content items, for

>users who need to customize or turn off style information in order to view content according to their needs, assistive technologies may not be able to access the information that is inserted using CSS 

[Alastair listed](https://github.com/w3c/wcag/issues/433#issuecomment-408877292) some examples: overriding authored styles via stylus plugin, windows high-contrast, direct application of user styles). After those he listed icon fonts & CSS images.

As @alastc  said, "the fact the acc-name calc includes CSS content doesn’t help/affect those using customised visual access."

**Comment by awkawk** [comment]
@lauracarlson What I mean is that we need to answer the question "is all non-decorative content provided as generated content in CSS a failure of WCAG's 1.3.1 SC?"

It is possible that the broad answer is no, but that some specific cases are.

This failure was easier when it was made because we didn't need to understand all of the low-vision access questions since the screen readers didn't read the content. Now that most screen readers seem to read it, we need to determine if the low vision questions suggest that it should still be a failure.

**Comment by lauracarlson** [comment]
@awkawk ,

Thank you.

**Comment by mbgower** [comment]
Adding my low-tech review, it looks like the <code>:before :after</code> pseudo elements come at the tail end (step 6 of 7) of a cumulative accessible name process, and their use is pretty contained:
> Otherwise, if the current node's role allows name from content, or if the current node is referenced by aria-labelledby, aria-describedby, or is a native host language text alternative element (e.g. label in HTML), or is a descendant of a native host language text alternative element:

Given the points raised by @Wildebrew, I think adding some additional text/explanation to the Failure is pretty crucial -- as @awkawk says, the test procedure can be passed where it is implemented properly -- and I think the wording of the title needs to be qualified.

But I'm a bit leery of it being removed entirely. At a minimum there should some solid testing to confirm AT support and determine  how frequently things can be screwed up through improper use the pseudo elements.

**Comment by mraccess77** [comment]
I don’t think you can provide role img for pseudo content only for the element as a whole.

**Comment by WayneEDick** [comment]
I use pseudo elements in my style sheets to show heading level and identify links without underlined text.
h1:before{
content:'. ';
}
h2:before{
content:'.. ';
}
h3:before{
content:'... ';
}
h4:before{
content:'... . ';
}
h5:before{
content:'.... .. ';
}
h6:before{
content:'... ... ';
}
a[href]:before{
content:'[';
}
a[href]:after{
content:']';
}

Best Wayne

**Comment by awkawk** [comment]
Wayne, here's a page with the examples in it - what happens with your stylesheet is added to the rendering? http://awkawk.github.io/f87.html

**Comment by WayneEDick** [comment]
Thanks, I need to study that page before tomorow.

Best Wayne

**Comment by WayneEDick** [comment]
I think we should remove the technique. There are problems, but most are solvable. The questions to ask are:
Drawbacks:
Are there any identified ambiguities: They would be programmatically non-deterministic constructs.
I am not sure how to insert an icon font into a pseudo element. Can someone give me an example. We cannot insert roles into inserted content. They are flat, so we cannot insert elements. This is a real problem. ARIA label and labelledby.   So, I am not sure ambiguities exist or if they do, are they in conflict with WCAG 2.1.

Advantages: if we included generated content into the  accessible domain, generated would have to obey all of WCAG 2.1. That would have many more advantages than drawbacks.

We are living in a world where, like it or not, CSS content is semantic content in web pages. Maybe it's time to figure how to include it. This is a good discussion

Best, Wayne

**Comment by WayneEDick** [comment]
I found a pseudo element with an icon value in StackOverflow.
div:before {
  content: attr(data-background-icon);
  font-family: "FontAwesome";
}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet"/>
<div data-background-icon='&#xf086;'></div>

The following code shows how role =='img' can be enforced.

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>icon psudo with div</title>
  <style>
    div[role="img"]:before {
      content: attr(data-background-icon);
      font-family: "FontAwesome";
    }
  </style>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet"/>
</head>
<body>
<div data-background-icon='&#xf086;'>  div without role.</div>
<div role="img" data-background-icon='&#xf086;'> div with role=&apos;img&apos;.</div>
</body>
</html>

Run it and see. The trick is only show the pseudo if the author added role=img to the element. 

Could our own attribute like data-pseudo-role. The key is it can be designated.
Best Wayne

**Comment by awkawk** [comment]
@WayneEDick Can you describe how the example page worked with your user styles?

**Comment by mraccess77** [comment]
Browser also don't include the text of pseudo elements in their find feature.

**Comment by Wildebrew** [comment]
I agree that CSS element content should not be used for important info
e.g. as the sole source of an elements accessible name.
The primary use cases I see for it are to indicate contextual
information about elements, e.g. links that open in a new tab, open a
PDF or point to footnotes.
Sure, the title attribute can be used, but it is poorly supported and
it requires a lot more development work to put title attributes on all
individual links to footnotes, whereas it takes one CSS class to add
this information, provided all the elements can be included with a
single CSS selector.
Visually such links often have icons or other visual cues, for a
screen reader user this is the most efficient way to provide a text
equivalent to those clues.
I understand and agree with general concerns with CSS pseudo elements,
but I personally do not agree that the solution is simply to forbid
their use because of accessibility, because I see legitimate use cases
and they are a part of the accessible name algorithm, which they
shouldn't be if WCAG outright forbids their use.



On 8/2/18, Jonathan Avila <notifications@github.com> wrote:
> Browser also don't include the text of pseudo elements in their find
> feature.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag/issues/433#issuecomment-409964191


-- 
Work hard. Have fun. Make history.

**Comment by WayneEDick** [comment]
Hi,
I've been looking at  @Wildebrew comment. On icon links with visually hidden directions for non-visual users. 

So I constructed the following:

<a href="http://www.nosetothepage.org/508/14thAmmend.html" aria-label="go to 14th Amendment"><i class="fas fa-arrow-alt-circle-right"></i> 14th Amendment, US Constitution</a>

Wouldn't this achieve the same result?

Wayne

**Comment by WayneEDick** [comment]
Oops, I forgot and used live code.

&lt;a href="http://www.nosetothepage.org/508/14thAmmend.html" aria-label="go to 14th Amendment"&gt;&lt;i class="fas fa-arrow-alt-circle-right"&lt;/i&gt; 14th Amendment, US Constitution&lt;/a&gt;

Did I get your case wrong. If I got wrong why is aria-label not OK.

Wayne

**Comment by lauracarlson** [comment]
- [Related minutes from the  Low Vision Task Force's  August 2 meeting](https://www.w3.org/2018/08/02-lvtf-minutes.html#item01)
- [Wayne's email to LVTF regarding generated content](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2018Aug/0005.html)

**Comment by WayneEDick** [comment]
Hi All,
I've been working on this problem. As I mentioned earlier, I would like generated content to be accessible. Unfortunately it is not. There are two factors that really make it inaccessible:
1) Generated content is completely flat, it has no semantic structure. A <div> has considerable  structure by comparison: class, id, role are available etc.. Pseudo elements are truly void of semantics.
2) Browsers cannot find content values for generated content. If it is anything but decorative, users will not be able to search for important information.  

These two factors eliminate generated content from pseudo elements from accessibility. The Failure 87 should stand with updated documentation.

What can be done:
The ARIA group included the generated content in pseudo elements in accessible names before there was any semantic support for the content.

I think we could include content from pseudo elements if ARIA group defined some aria-pseudo parameters. It would be important for these to be accessible from CSS so that assistive stylesheets could use them. Also, we must contact browsers to learn what is needed so that find-algorithms can find pseudo element content.

**Comment by WayneEDick** [comment]
Oops. I used and element again. The sentence above should read.
A &lt;div&gt;  
has considerable structure by comparison: class, id, role are available etc..

**Comment by alastc** [comment]
I think the change we are coming to is simply updating the 3rd part of the procedure from:

> 3. If the inserted content is not decorative, check that the information is provided to assistive technologies and is also available when CSS is turned off.

To:

> 3. If the inserted content is not decorative check that the information is also available when CSS is turned off.

Where @Wildebrew said:
> I see legitimate use cases and they are a part of the accessible name algorithm, which they shouldn't be if WCAG outright forbids their use.

That assumes that "AT" is things which use accessible name, which is not always the case. Here the AT could be (as outlined in the description) something which over-rides CSS.

**Comment by lauracarlson** [comment]
[Wayne's research](https://docs.google.com/document/d/1kvz0D3Au1R6c6q8iKZNH3KqyBt3d6WaJNUCwV35BDX8/edit?usp=sharing)

**Comment by awkawk** [comment]
Addressed in Pull request #473 - closing this issue.
