### ISSUE TITLE
Success Criterion 1.3.5: Identify Input Purpose

### ISSUE THREAD

**Issue by Decrepidos** [w3c/wcag#441]
https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html#input-purposes

Typo under the 'Benefits' heading.

Assistive technology can offer a customised way of identifying particular input fields, for example, draing on a set of symbols / icons that is familiar to the user.

draing should be drawing.

**Comment by Decrepidos** [comment]
Actually there are multiple spelling mistakes on this page:
Under 'Intent'

- adress=> address
- assisitive =>  assistive  (multiple occurrences)

Under 'Benefits'

- autofilling => auto filling 

Under 'Examples'

- An order from with separate billing **ans** shipping address  => and

**Comment by awkawk** [comment]
Thanks - fixed: 
https://github.com/w3c/wcag/commit/86c727e3e07b64b4f723cfc8663869dae236216c
