### ISSUE TITLE
Minor link errors in Understanding 1.4.12 Text spacing

### ISSUE THREAD

**Issue by plannero** [w3c/wcag#443]
In the section "Applicability" there are two different links to "Images of text", none of which are correct. 
The links should either point to the corresponding definition in the main WCAG 2.1 spec (http://www.w3.org/TR/WCAG21/#dfn-images-of-text ) or to the similar definition found at the end of the Understanding document: https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html#dfn-image-of-text

**Comment by alastc** [comment]
@michael-n-cooper I was going to do this in passing, but couldn't work out if there is a special URL for linking to definitions. It's easy to use `https://www.w3.org/TR/WCAG21/#dfn-images-of-text`, but it seems like a good place for a within-page link, e.g. `<a href="#dfn-images-of-text">images of text</a>`. Would that work?

**Comment by michael-n-cooper** [comment]
At the moment the Understanding generator understands links without href as term links, the same way Respec does for the guidelines. So <a>Images of text</a> should resolve correctly, assuming the contents of the element relate to known term. I've been debating whether to add additional patterns to recognize definitions. If you want me to remember to think about that, leave this issue open and assigned to me. If you just want to fix the issue in this file, you can fix and close this issue.

**Comment by alastc** [comment]
Ok, so working backwards from the generate-understanding.xslt, would that be like this then?

`<a>images of text</a>`

Sorry, it seems like a simple thing, but I can't see a previous example or see it in the READme.
