### ISSUE TITLE
Image problem in Understanding 1.4.11 Non-text contrast

### ISSUE THREAD

**Issue by plannero** [w3c/wcag#444]
There are two images under the heading "Infographics" (https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#infographics ) that are by far too wide (>2000 px) for display on most screens. 

The images should be scaled down or replaced in order not to conflict with SC 1.4.10 Reflow.

**Comment by patrickhlauke** [comment]
those images responsively adapt (via CSS) to screen width, so not really a problem?

**Comment by patrickhlauke** [comment]
(sorry, didn't mean to close, just comment)

**Comment by plannero** [comment]
Oh, after a little more research: When requesting the page via http it works OK. When requesting via https it works with Firefox but not with Edge. Apparently the Edge browser does not apply the css for some security reason.

**Comment by alastc** [comment]
The non-secure http version redirects to the httpS version, how did you get to the http version?

The page, images and CSS are all served over httpS, so it doesn't seem to be a mixed-security thing.

Perhaps it is a bug in Edge? (I don't have that to hand to test at the moment.)

**Comment by patrickhlauke** [comment]
confirming that Edge displays the page just fine for me (and redirects transparently to https)

**Comment by plannero** [comment]
I still experience this problem, though it seems specific to Microsoft Edge 41.16299.492.0. 
The error console says 
SEC7111: HTTPS security is compromised by http://www.w3.org/StyleSheets/TR/2016/base

Indeed, this css file is referenced from the Understanding document with http (not https). There is some kind of redirect, but my Edge version seems not to understand it.

Anyway, the error message is the same for all Understanding docs, so probably more of a browser shortcoming than a coding error. Sorry to bother you.

**Comment by alastc** [comment]
Ah, I see the http reference now, thanks for the pointer.

It does redirect, but no harm correcting the reference. FYI for @michael-n-cooper, I pushed that straight to master, a one-character change in generate-understanding.xslt for the CSS file, `http` > `https`.
