### ISSUE TITLE
Reflow understanding - Video size & location

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#445]
Just noticed that the styles don't cope with the video content very well, demonstrated in the [Reflow understanding doc](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).

The CSS for that would be simple, something like:
`video { max-width: 100%;}`

But where does that belong?

Also, @michael-n-cooper is there a folder we can put these video files in? (Currently on my site.) I'd rather not put them in git, everyone downloading the repo will have them added to the file size...

**Comment by WayneEDick** [comment]
In some ways things like videos and pictures are managed in responsive
design. People change sizes to fit in media queries... sometimes it looks
bad. Videos that run off the screen are not functional, but how often will
they occur in a responsive site. Am I missing something?

Best, Wayne

**Comment by alastc** [comment]
They should be managed, in the understanding doc though there is a video which is partially hidden. Given the content of the understanding doc, that is... ironic. It's a simple fix from a CSS point of view, but need to track down the best place to make it.

**Comment by michael-n-cooper** [comment]
For CSS, I think it should be in https://github.com/w3c/wcag/blob/master/understanding/understanding.css. 

On the whole I think videos should be stored in the repo, it's only the first time that it's a big download. Storing outside the repo risks linkrot. I would either decide vieeos are "images" and put it in the "img" directory of Understanding, or create a "video" directory in Understanding.

**Comment by alastc** [comment]
That one example is actually two files, mp4 & ogv to get browser coverage. They are about 9-10MB each, so 20MB just for the one video, and we'd like to include more. That multiplies up real quick.

Is there not a more suitable place for video content? Where does @yatil and the EO folk put them? It looks like youtube, which might be overkill, but better than putting it in git.

**Comment by yatil** [comment]
@alastc We currently use youtube and serve it through an instance of Able Player, see https://www.w3.org/WAI/perspective-videos/keyboard/ 

We need to check with @slhenry to see if we want to have a separate account for this.

**Comment by alastc** [comment]
I've pinged Shawn, will see if there are any general options.

**Comment by slhenry** [comment]
I've created a separate YouTube channel to house the videos for Understanding WCAG.

---

/me interested that AWK considers the [main WAI YouTube channel](https://www.youtube.com/channel/UCU6ljj3m1fglIPjSjs2DpRA) videos as "marketing", rather than [introducing web accessibility, WCAG, etc.](https://www.w3.org/WAI/videos/standards-and-benefits/#transcript); advocating for web accessibility; and educating on benefits of web accessibility. )

**Comment by alastc** [comment]
Thanks Shawn, 

@yatil I can see the instructions on the Able player site, presumably we can reference the same script sources as you do, is there anything else we need to worry about?

<hr>

If you live in the corporate world, anything trying to get to new audiences is 'marketing', we aren't used to the concept of outreach/education ;-)

**Comment by yatil** [comment]
@alastc Yes, this should work, but we keep updating the able player source occasionally, so stuff might break accidentally when you refer to our copy (I don’t think that that will happen, however, it seems pretty stable.)

**Comment by fstrr** [comment]
This issue looks as if it's resolved. The video resizes as it should do and I'm going to assume that @alastc is okay with the hosting arrangement.
