### ISSUE TITLE
Fix whitespace issues to match EditorConfig settings

### ISSUE THREAD

**Issue by nschonni** [w3c/wcag#464]
#29 add the [EditorConfig settings](https://github.com/w3c/wcag/blob/master/.editorconfig) for IDEs that support it to normailze whitespace issues.
This automatic cleanup causes PRs like https://github.com/w3c/wcag/pull/377 to be closed because of the included whitespace changes.
Bulk cleanup doesn't seem like the correct approach since #459 was closed, so I'm just opening this for @michael-n-cooper to figure out the right path

**Comment by alastc** [comment]
@nschonni Could you help me figure out the impact? My editor doesn't do anything with the config so I'm not sure which direction to approach it from.

Given the various people editing, many branches current open etc, I'd want values that *prevent* IDEs from automatically adjusting whitespace.

Is it better to remove whitespace settings from the config, or have them set to false? E.g.
`trim_trailing_whitespace = false`

**Comment by fstrr** [comment]
This issue looks to be inactive, so I'm closing it. If it does need to be re-opened, please do so.
