### ISSUE TITLE
Understanding 4.1.3 - wrong id reference in anchors

### ISSUE THREAD

**Issue by audreymaniez** [w3c/wcag#465]
In the sentence "Examples of status messages are given in the section titled Status Message Examples below." **Status Message** is an anchor, but the wrong id is referenced "https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html#status-examples"

Change 
`<a href="#status-examples">Status Message Examples</a>`
To 
`<a href="#status-message-examples">Status Message Examples</a>`

Same problem for the anchor **Examples of Changes That Are Not Status Messages**, wrong id. 

Change
`<a href="#excepted-examples">Examples of Changes That Are Not Status Messages</a>`
to
`<a href="#examples-of-changes-that-are-not-status-messages">Examples of Changes That Are Not Status Messages</a>`

**Comment by awkawk** [comment]
@michael-n-cooper either Master hasn't been rolled out so the published version is out of sync or the generator is overwriting ids. 

In Master (line 36 of https://github.com/w3c/wcag/edit/master/understanding/21/status-messages.html):
`<h3 id="status-examples">Status Message Examples</h3>`

In the live site:
<section class="example" id="status-message-examples">
          <h3>Status Message Examples</h3>

**Comment by patrickhlauke** [comment]
i believe (though my xslt is a bit rusty) that it's the generator (probably `base.xslt`) explicitly creating `id`s based on the heading text and overriding the `id` attribute already in the markup. cleanest fix would likely be to modify the xslt if possible NOT to generate custom `id`s if the attribute is already present.

**Comment by patrickhlauke** [comment]
even odder...in master, the understanding document has

```
<section class="example">
<h3 id="status-examples">Status Message Examples</h3>
```

(with the `id` on the `<h3>`) but in the ouput https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html it has

```
<section class="example" id="status-message-examples">
<h3>Status Message Examples</h3>
```

(with the `id` stripped from the `<h3>` and the new `id` added to the `<section>`)
