### ISSUE TITLE
Technique SCR29 needs updating

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#468]
Noticed by @detlevhfischer:
> Just noticed that the technique SCR29: Adding keyboard-accessible actions to static HTML elements https://www.w3.org/TR/WCAG20-TECHS/SCR29.html
> is a bit rusty. It shows adding tabindex and key event handler to a div, but no mention of the need to add an appropriate ARIA role. Should be straightforward to update. (And if the div is made a button with role=button, it should probably listen to space bar as well, not just
ENTER.)

**Comment by awkawk** [comment]
@mraccess77 will work on a fix to the example

**Comment by awkawk** [comment]
Closing since Pull #485 addressed this.
