### ISSUE TITLE
F69: Failure of Success Criterion 1.4.4 when resizing visually rendered text up to 200 percent causes the text, image or controls to be clipped, truncated or obscured

### ISSUE THREAD

**Issue by cleancoderocker** [w3c/wcag#48]
There is a small syntax error in both the examples: the content of the style attribute is not closed by an quotation mark.
http://www.w3.org/TR/WCAG20-TECHS/F69.html

**Comment by awkawk** [comment]
Fixed in https://github.com/w3c/wcag/commit/46886d36ccb3641ac07a10a548837a74bf8c6185
