### ISSUE TITLE
Add META tag for viewport at examples

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#480]
For at least the following examples we need to add a META tag for proper viewing on mobile:

- https://github.com/w3c/wcag/blob/master/working-examples/css-grid/index.html
- https://github.com/w3c/wcag/tree/master/working-examples/css-flexbox

created PR: https://github.com/w3c/wcag/pull/479 

Do we need to check other examples for this to be sure they work out well on mobile?

Cheers!

**Comment by alastc** [comment]
Hi Jake,

I think this one has been done, I can see the meta tags in place. Unless you're volunteering to go through the other examples I'd rather close this and tackle them individually as they come up.

Cheers,

-Alastair
