### ISSUE TITLE
Typo in 4. Robust: "...can be interpreted by by a wide variety..."

### ISSUE THREAD

**Issue by JamesDonnelly** [w3c/wcag#488]
The description for 4. Robust has a repeated "by":

> Content must be robust enough that it can be interpreted by **_by_** a wide variety of user agents, including assistive technologies.

https://www.w3.org/TR/WCAG21/#robust

**Comment by awkawk** [comment]
Accepted in CFC 9/29/2018 to make the 2.1 text match the 2.0 text for the sentence under the Robust principle: "Content must be robust enough that it can be interpreted reliably by a wide variety of user agents, including assistive technologies."
