### ISSUE TITLE
flexbox branch still present

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#498]
@michael-n-cooper I see the flexbox branch is still present, is this supposed to be?

Master: https://github.com/w3c/wcag/tree/master/working-examples/css-flexbox
Branch: https://github.com/w3c/wcag/blob/example-css-flexbox/working-examples/css-flexbox/index.html

**Comment by alastc** [comment]
I couldn't see a way to remove that via github, but I could from my local client!
If it's in master, I'm assuming it's safe to remove.

**Comment by michael-n-cooper** [comment]
I may have removed the branch when I cleaned up merged branches recently. Branch cleanup doesn't require an issue to be filed, it'll get addressed in routine maintenance.
