### ISSUE TITLE
Understanding docs and Technique docs are not identified at non-normative

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag#508]
In WCAG 2.1 a decision was made to only mark the non-normative sections of this document (https://www.w3.org/TR/WCAG21/ ) with the phrase "non-normative" as stated here: https://www.w3.org/TR/WCAG21/#interpreting-normative-requirements

But now, that could lead someone to believe that all the understanding docs and all the technique does are normative.  YIKES!  

Recommended Resolution:  Add "non-normative" (with a link to https://www.w3.org/TR/WCAG21/#interpreting-normative-requirements)  to the top of each understanding document and each technique document.

**Comment by mbgower** [comment]
I think maybe putting it at the bottom is sufficient. i think if it's at the top, it may be a bit 'in your face'

**Comment by alastc** [comment]
Wondering if the layers of guidance area would be best? https://www.w3.org/TR/WCAG21/#wcag-2-layers-of-guidance

**Comment by fstrr** [comment]
Closing this as inactive. Please re-open if necessary.
