### ISSUE TITLE
ARIA1 for 2.4.4 Link Purpose

### ISSUE THREAD

**Issue by marcjohlic** [w3c/wcag#51]
http://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-refs

ARIA1 is listed as a Sufficient Technique for 2.4.4 Link Purpose in the "How to Meet WCAG 2.0" quick reference document.

However, ARIA1 is not listed in the Understanding document for 2.4.4:
http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html

Also, 2.4.4 Link Purpose is not listed in the Applicability section for ARIA1:
http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/ARIA1

Not sure if ARIA1 just needs to be removed from 2.4.4 in the How to Meet document, or if it needs to be added to the Understanding doc for 2.4.4 and have 2.4.4 added to Applicability for ARIA1

**Comment by awkawk** [comment]
Marc will do a pull request with changes.

**Comment by marcjohlic** [comment]
It looks like this must have gotten picked up in the last publish and I no longer see ARIA1 associated w/ 2.4.4 in the Quickref.

On a related note, I need to figure out how to properly refresh my WCAG repository because I still have it in my fork.

It looks like this comment can be closed.
