### ISSUE TITLE
Bad link in G158

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#523]
From list: 

  On the technique G158 information page, the first link under "more resources" section does not go to the destination listed; this is a page for providing an alternative for time-based media. The link text reads "overcoming the challenge of podcast transcription;" but the link goes to a blank page on a the RNIP site. This issue exists under both WCAG20 and WCAG21.
 https://www.w3.org/WAI/WCAG21/Techniques/general/G158

**Comment by awkawk** [comment]
Link is bad - recommend that we remove it since I cannot find what it is supposed to point to.

**Comment by alastc** [comment]
Group agreed to remove the link: https://www.w3.org/2018/11/20-ag-minutes.html#item05

**Comment by alastc** [comment]
Actioned in PR #534 534
