### ISSUE TITLE
Advisory techniques vs Recommended techniques

### ISSUE THREAD

**Issue by StefanSTS** [w3c/wcag#527]
I could not find any discussion about this, so I am wondering if I am the only one having a problem with the word advisory.

As far as I understand from the content the techniques are recommended techniques that authors should use. I would need a clarification.
Are these recommended techniques? Yes or No.

The word advisory for me as a non native english speaker belong into an area like "advisory board", more something like consulting, giving advise.
Even if there is a meaning, that would say this word means recommended (or we advise to do it like that) it must be on page two of the list of meanings.

I would not bother about this, but the document itself talks about cognitive disabilities and learning issues. Why not use a word that everyone in the world with a basic to advanced english course would understand, like recommended?

That would be more in favour of the documents purpose to serve everyone even if that person has a disability (in this case: disability in finding a meaning in a word that normally is used in a different way).

I hope this was not chosen, because the word Recommendation is reserved as a special item in a REC, it should be use because of that, because people already know the meaning from the recommended technical report they are reading just now.

If I am totally off rails here or if you think this is too trivial, please advise.
Stefan Schumacher (the one on the translators list)

**Comment by alastc** [comment]
Hi @StefanSTS,

> The word advisory for me as a non native english speaker belong into an area like "advisory board", more something like consulting, giving advise.

Indeed, the [English definition](https://en.oxforddictionaries.com/definition/advisory) is "having or consisting in the power to make recommendations but not to take action enforcing them."

That is the intent of "advisory" techniques: They are good things to do, but they are not sufficient to meet the criteria (guideline) on their own. I'm afraid we are about 10 years to late to change that term/meaning for WCAG 2. 

It is explained in the last bullet of [Layers of Conformance](https://www.w3.org/TR/WCAG21/#wcag-2-layers-of-guidance), is that not clear?
