### ISSUE TITLE
fix CSS padding on understanding pages

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/wcag#528]
This should be padding-right instead of padding-left?

![understanding success criterion 1 3 4 orientation 2018-10-31 10-01-24](https://user-images.githubusercontent.com/870049/47777282-b022c600-dcf4-11e8-8a50-3b16f5279b35.png)

**Comment by alastc** [comment]
(Working back through the issue backlog!)

I think the short-answer is no, there are some pages like the [contents](https://www.w3.org/WAI/WCAG21/Understanding/), where there is a left-nav, so it is consistent with that.

**Comment by Veyfeyken** [comment]
I see. In that case I would suggest to show the navigation in all pages. This would also be a win for usability. Not having to go back and forth, always having an overview, ...

Is there a particular reason to hide the nav on all pages but the index that I'm not aware of?

**Comment by alastc** [comment]
I don't think having a huge amount of links on the page will be helpful, in a user-journey most people will want related techniques, not all techniques.  The rest is just noise.

Also, there's a redesign of the understanding/techniques docs going on, I'd rather not spend time on something that's going to be re-done soon...

**Comment by Veyfeyken** [comment]
> Also, there's a redesign of the understanding/techniques docs going on, I'd rather not spend time on something that's going to be re-done soon...

Never mind in that case.
