### ISSUE TITLE
New Technique draft "Making content on focus or hover hoverable, dissmissible and permanent"

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#529]
I have written a draft Sufficient Technique "Making content on focus or hover hoverable, dissmissible and permanent".
This is the Github link: 
https://github.com/w3c/wcag/blob/tech-hover-focus-hoverable/techniques/general/tech-hover-focus-hoverable.html
This is a rendered view (via raw.githack.com):
https://raw.githack.com/w3c/wcag/tech-hover-focus-hoverable/techniques/general/tech-hover-focus-hoverable.html

There is now just one example for popups offering additional info (like a preview) for links. The JS is embarrassing and should be improved by someone better versed in scripting (would be nice if it was general enough to work for any pair of consistently named link / corresponding hover content on the page).

Another example which I haven't tackled yet would be similar, but the popup content would not be nested inside the trigger but be in a separate section below (think of footnotes listed at the end of a doc which can be displayed in a popup next to the footnote in a text when hovering over it).

**Comment by detlevhfischer** [comment]
There does not seem to be a consistent way how the [practical example ](http://www.3needs.org/en/testing/code/hover-focus.html) is rendered by NVDA/Firefox: first the link plus the popup text was read of firstr kb focussin, then nothing is read, then, after back and forth, just the trigger. It seems inconsistent at best (and a bit unclear what the deisirable behaviour should be - I guess best might be the renderng of the popup with some delay (as with accDescription in some UAs), bur I am not sure. Is this an anti-pattern? How can it be improved?

**Comment by alastc** [comment]
Replacing PR #450 450

**Comment by mraccess77** [comment]
I made an example of the technique here https://labs.levelaccess.com/index.php/Additional_Content_on_Hover_or_Focus

**Comment by detlevhfischer** [comment]
Thanks, @mraccess77  - just tied it out, when I focus the trigger with a mouse it brings up th epopup but I cannot get rid of it with ESC (Win 10, Firefox).

**Comment by mraccess77** [comment]
The trigger has to be focused for escape to work.  It works for me in FF with Win 10 and Win 7.

**Comment by detlevhfischer** [comment]
@mraccess77 Should it not work as well when the popup is shown on hover? Wouldn't this be a common scenario that the SC addresses: A magnification user moves his/her mouse and the content shifts in the magnified section. Mouse hover makes the popup appear, so the user closes it with ESC. The trigger has not received keyboard focus then. (Note that [my example](http://3needs.org/en/testing/code/hover-focus.html) also closes the popup when it is brought up by cursor hover - however, it doesn't work in IE and the scripting is clumsy as hell).

**Comment by detlevhfischer** [comment]
I have created  a pull request for this Technique.

**Comment by alastc** [comment]
Discssion should be on the PR, closing this issue.
