### ISSUE TITLE
Some wording questions for 1.3.5: Identify Input Purpose

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#537]
[Understanding Success Criterion 1.3.5: Identify Input Purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose)

Wondering if the following should be adjusted:

Shouldn't:

> This success criterion defines the types of user interface component inputs

Be:

> This success criterion defines the types of user interface component input purposes 

Shouldn't:

> that must be programmatically identified

Be:

> that must be programmatically identifiable

Shouldn't:

> the field purpose must be identified programmatically.

Be:

> the field purpose must be programmatically identifiable.

Shouldn't:

> birth day

Be:

> birthday

**Comment by patrickhlauke** [comment]
agree on "birthday". for "identified" vs "identifiable" i guess it's the distinction between "identified by the author" vs "identifiable by the UA/AT" - though the end result is the same, wondering if it's intentional that the emphasis currently is on the author having done some explicit work...but if pressed, i'd lean towards "identifiable" myself (for both sentences)

**Comment by marcjohlic** [comment]
All of these changes look reasonable to me.  I'll submit a PR for them.

**Comment by marcjohlic** [comment]
@awkawk @michael-n-cooper   PR #629 submitted with these editorial changes.

**Comment by marcjohlic** [comment]
Argh!!!! GitHub diff is picking up all of the "whitespace" changes introduced from VSC auto-formatting. I'm going to close PR #629 and make the changes in the GH editor to make it easier for folks to see what's been changed.

**Comment by marcjohlic** [comment]
PR #631 has been submitted with these editorial changes along with editorial changes from Issue #536

**Comment by awkawk** [comment]
Addressed in PR #631 per Feb 26 2019 call and survey
