### ISSUE TITLE
Technique proposal - Issue 296 - Reminder

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag#547]
@ Working Group

In July 2017 (!) [proposed a sufficient technique](https://github.com/w3c/wcag/issues/296) which is still not reviewed by the WG. Just a techniques-label was added in June this year. #reminder 

Cheers

Kerstin

**Comment by alastc** [comment]
Thanks @kerstinp, we've paused on PDF techniques whilst there is some discussion with the PDF association, but this hasn't been lost.

**Comment by awkawk** [comment]
Closing this issue as we don't want to have duplicate issues
