### ISSUE TITLE
Minor issue: duplicate h2 on understanding landing page

### ISSUE THREAD

**Issue by tasnook** [w3c/wcag#548]
On [Understanding WCAG 2.1 - https://www.w3.org/WAI/WCAG21/Understanding/](https://www.w3.org/WAI/WCAG21/Understanding/)
There are two concurrent heading level twos for "Understanding Pages"
```
<nav id="toc">
<h2>Understanding Pages</h2>
<nav id="toc">
<h2 class="introductory" id="understanding-pages">Understanding Pages</h2>
<ol class="toc">
```
Keep up the great work!!

**Comment by alastc** [comment]
Thanks @tasnook, I think removing it from the index.html is the appropriate place (#554), rather than messing with the structure (as in #549), but @michael-n-cooper is best placed to confirm.
