### ISSUE TITLE
Bug: In understanding docs the SC defintitions are missing

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#569]
In the Understanding for 3.3.5: Help, the link in the normative text: "Success Criterion 3.3.5 Help (Level AAA): Context-sensitive help is available." only contains an anker tag without href / URL.

https://www.w3.org/WAI/WCAG21/Understanding/help.html

```
<p>Success Criterion <a href="https://www.w3.org/TR/WCAG21/#help" style="font-weight: bold;">3.3.5 Help</a> (Level AAA): 

            <a>Context-sensitive help</a> is available.
</p>
```

**Comment by jake-abma** [comment]
See lots more...

example: https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

**Comment by alastc** [comment]
Each of those is a definition, so in the spec they link to the glossary. It appears that the link doesn't work, and the definition is missing from the page under "Key terms" (so it has no-where to go anyway). One for Michael I'm afraid.
