### ISSUE TITLE
"Notes" not present in Understanding docs 

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#571]
In the WCAG 2.1 document we show "Notes" in green blocks, in the Understanding documents they are gone as seems to be integrated in the actual description. Not clear 9and consistent) it's a note.

More places, but here two examples:

https://www.w3.org/TR/WCAG21/#name-role-value
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

https://www.w3.org/TR/WCAG21/#parsing
https://www.w3.org/WAI/WCAG21/Understanding/parsing.html

**Comment by alastc** [comment]
FYI: I think this is a 'build' issue, which is why Michael assigned it to himself.
