### ISSUE TITLE
Use of "or" in text as against "OR" for alternative techniques

### ISSUE THREAD

**Issue by jofatmofn** [w3c/wcag#577]
https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation
And
https://www.w3.org/WAI/WCAG21/quickref

Current content: 
C19: Specifying alignment either to the left **OR** right in CSS OR
To be changed (first occurrence of "OR" to "or") to:
C19: Specifying alignment either to the left or right in CSS OR

**Comment by awkawk** [comment]
Fixed.
