### ISSUE TITLE
Uniform look for sub-headings (Grouping of Techniques)

### ISSUE THREAD

**Issue by jofatmofn** [w3c/wcag#578]
https://www.w3.org/WAI/WCAG21/quickref
There are 8 instances of grouping of techniques with `<p role="heading">` construct. If those are modified to use `<div class="panel panel-default">` construct, then they will look like "Metadata Techniques" under 1.2.6 --> Advisory Techniques OR "First/Second/Third/Fourth/Fifth Requirement" under 1.4.8 --> Sufficient Techniques.

**Comment by awkawk** [comment]
@yatil any thoughts on this?

**Comment by yatil** [comment]
Using the panels would create even more boxes inside of boxes and we decided against that for simplicity and readability.
