### ISSUE TITLE
Misleading info in "Understanding 2.4.4: Link Purpose (In Context)"

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag#581]
Please review and revise the following misleading sentence in [Understanding 2.4.4: Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html).

> It is also a best practice for links with different purposes and destinations to have different descriptions.

I believe (know) this sentence is misleading.  I think what was meant is "It is also a best practice for links with different purposes and destinations to have different **link text**."

In other words, the best practice is to meet 2.4.9 Link Purpose (Link Only).  Right?!

**Comment by mraccess77** [comment]
Glenda, I think what it's saying is that for conformance to 2.4.4 the link purpose (accessible name) only needs to be understandable in context to the surrounding list item, paragraph, sentence, or table cell.  However, it's best practice to have the accessible description points to that contextual information -- although not explicitly required as it can be access programmatically via the sentence, paragraph, list item, or table cell.

**Comment by awkawk** [comment]
Glenda, any response to Jon's comment?

**Comment by goodwitch** [comment]
@mraccess77 I disagree.  2.4.4 requires the Link Purpose to be available in context (which would include the link text AND the context of the accessible description that could be provided via the sentence, paragraph, list item or table cell.)

So...this sentence should read, "It is also a best practice for links with different purposes and destinations to have different link text."

Because in reality, it is a normative WCAG 2.0/2.1 SC 2.4.4 requirement for links with different purposes and destinations to have difference descriptions.  

So...this sentence in the understanding document is misleading and inaccurate:

> It is also a best practice for links with different purposes and destinations to have different descriptions.

**Comment by patrickhlauke** [comment]
On 01/02/2019 19:49, Glenda Sims wrote:
[...]
> Because in reality, it is a normative WCAG 2.0/2.1 SC 2.4.4 requirement 
> for links with different purposes and destinations to have difference 
> descriptions.

Where is this normative requirement?

P
-- 
Patrick H. Lauke

www.splintered.co.uk | https://github.com/patrickhlauke
http://flickr.com/photos/redux/ | http://redux.deviantart.com
twitter: @patrick_h_lauke | skype: patrick_h_lauke

**Comment by patrickhlauke** [comment]
or did you mean the normative requirement is in WCAG 2.0/2.1 SC 2.4.9? (and noting that even there there's the "unless it's ambiguous for everybody" clause)

**Comment by goodwitch** [comment]
@patrickhlauke maybe it will help if we look at this sentence together, and focus on the definition of the word "description".  

In this sentence from [Understanding 2.4.4 Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html) :

> It is also a best practice for links with different purposes and destinations to have different **descriptions**.

I interpret the word "description" as being based on the [accessible name and description computation  ](https://www.w3.org/TR/accname/#mapping_additional_nd_te).

What I think that sentence meant to say was, something along the lines of:

- At WCAG AA, it is also a best practice for each link with a different purpose and destination to have a different [accessible name](https://www.w3.org/TR/accname/#dfn-accessible-name). Based on [2.4.4 Link Purpose (In Context)](https://www.w3.org/TR/WCAG21/#link-purpose-in-context)
- At WCAG AAA, it is a requirement for each link with a different purpose and destination to have a different [accessible name](https://www.w3.org/TR/accname/#dfn-accessible-name). Based on [2.4.9 Link Purpose (Link Only)](https://www.w3.org/TR/WCAG21/#link-purpose-link-only)

**Comment by mraccess77** [comment]
@goodwitch -- Yes that it was I believe it means although I would extend that to "name or description".

**Comment by goodwitch** [comment]
But @mraccess77 , look at[ F89 Failure of Success Criteria 2.4.4, 2.4.9 and 4.1.2 due to not providing an accessible name for an image which is the only content in a link](https://www.w3.org/WAI/WCAG21/Techniques/failures/F89)

That failure technique only talks about accessible name.  There is no mention of anything about accessible description.

**Comment by mraccess77** [comment]
@goodwitch yes -- that is a failure -- because you have no name.  You can't have a description without a name so that's why it's a failure and doesn't mention description.

**Comment by goodwitch** [comment]
@mraccess77 So...can we agree...that since this sentence is talking about "best practice" we should describe a best practice that helps all disabilities (including cognitive) by focusing on the best best practice here of making the link text unique.   

In that light, I request that we change this sentence from [Understanding 2.4.4 Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html) :

> It is also a best practice for links with different purposes and destinations to have different **descriptions**.

Again, I interpret the word "description" as being based on the [accessible name and description computation ](https://www.w3.org/TR/accname/#mapping_additional_nd_te).

I really, really, really recommend we change the current sentence to the following:

* At WCAG AA, it is also a best practice for each link with a different purpose and destination to have a different [accessible name](https://www.w3.org/TR/accname/#dfn-accessible-name). Based on [2.4.4 Link Purpose (In Context)](https://www.w3.org/TR/WCAG21/#link-purpose-in-context)
* At WCAG AAA, it is a requirement for each link with a different purpose and destination to have a different [accessible name](https://www.w3.org/TR/accname/#dfn-accessible-name). Based on [2.4.9 Link Purpose (Link Only)](https://www.w3.org/TR/WCAG21/#link-purpose-link-only)

Remembering that this is a sentence about best practice...can you and I agree on this suggested change?  AWK has asked me to get this issue resolved.  

If you still think this sentence should not be changed...can you and I have a 30 minute phone call this week...so I can get this issue resolved?

**Comment by mraccess77** [comment]
@goodwitch I would agree that both are best practice but not required if the purpose in context is known.  I agree the acc name/description alone don't meet the needs of users with cognitive and learning disabilities and visible text/images when the link should provide purpose out of context as a best practice.  As for screen readers -- there are some differences in how the accessible description is announced or shown - so the name is more likely to be exposed although description can work.

I would propose something like
* At WCAG AA, it is also a best practice for each link with a different purpose and destination to have a different [accessible name or accessible description] (https://www.w3.org/TR/accname/#dfn-accessible-name). Based on [2.4.4 Link Purpose (In Context)](https://www.w3.org/TR/WCAG21/#link-purpose-in-context).   When a different accessible name or description is provided for links who's otherwise purpose can only be determined within context users of screen readers will have this information available without having to access the contextual information.
* At WCAG AA, it is also a best practice for each link with a different purpose and destination to have a different on-screen text or non-text content communicating purpose to assist users with cognitive and learning disabilities in accessing the link's purpose without having to perceive contextual information.
Note: while both of the above are best practice under WCAG AA at WCAG AAA link purpose needs to be determine without context.

**Comment by goodwitch** [comment]
@mraccess77 I like it!  +1
@patrickhlauke what do you think?

**Comment by alastc** [comment]
Um, it looks like there is a relatively short paragraph pointing to a couple of best practices, being replaced by two pretty large paragraphs!

The original was:

> It is a best practice for links with the same destination to have consistent descriptions (and this is a requirement per Success Criterion 3.2.4 for pages in a set). It is also a best practice for links with different purposes and destinations to have different descriptions. 

In the context of Link purpose (~2008), I read "description" as the text in the link, nothing more.

If we bring in accname & descriptions in, that's going to complicate this, where the actual scope and intent is simply around link text.

Having said that, I appreciate Glenda's reading of it in the ~2019 context, we should try and avoid confusion, how about a simpler update:

> It is a best practice for links with the same destination to have consistent **text** (and this is a requirement per Success Criterion 3.2.4 for pages in a set). It is also a best practice for links with different purposes and destinations to have different **link text**. 

I'm not sure why the first bullets for Jon & Glenda's additions are about 2.4.4, this is the understanding doc for 2.4.4?! Am I missing something?

Hmm, I also noticed a typo further down, "See also 2.4.2: Link Purpose (Link Only). " should be 2.4.9.

**Comment by goodwitch** [comment]
@alastc I'd be happy with your suggested (and simpler) text change.

**Comment by mraccess77** [comment]
That’s fine with me.

**Comment by awkawk** [comment]
Created Pull request #625 to address.

**Comment by alastc** [comment]
Accepted by the group, so closing this issue.
