### ISSUE TITLE
Minor editorial issue (duplicate content) in Understanding 3.2.1

### ISSUE THREAD

**Issue by plannero** [w3c/wcag#587]
The definition of "changes of context" appears twice under heading "Key terms" in https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html

**Comment by alastc** [comment]
I think this is one for @michael-n-cooper, I had a quick look, but couldn't see how the terms are brought into the page. There's only one glossary term defined in the source code, so it must be a build process issue.
