### ISSUE TITLE
Scoping of 2.5.3 Label in Name

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#591]
This issue was raised by @mbgower on the mailing list ([Some discussion points for label in name](https://lists.w3.org/Archives/Public/w3c-wai-gl/2019JanMar/0096.html)).  I am putting it here to make the discussion easier to follow (and possibly arrive at a consensus regarding the scoping of this SC).

Mike wrote:
"Success Criterion 2.5.3 Label in Name (Level A): For user interface components with labels that include text or images of text, the name contains the text that is presented visually."
Time permitting, here are some topics I'd like to delve into on our next call in relation to 2.5.3 Label in Name.

- Problem 1: When we ignore the programmatic stuff, getting agreement on what exactly constitutes a 'label' for a component isn't always simple.
- Problem 2: The Accessible Name Rec has a specific method for determining name. It affects implementation, especially when you try to satisfy various interpretations of what IS a label. (Key considerations: group role not in calculation, aria-label/labelledby have priority in calculation, aria-describedy not calculated)
- Problem 3: It is harder than anticipated to balance the needs of screen reader users with the needs of speech recognition.

Mike has then provided five examples - please see [his original mail](https://lists.w3.org/Archives/Public/w3c-wai-gl/2019JanMar/0096.html) for these. There has already been a [reply to his mail](https://lists.w3.org/Archives/Public/w3c-wai-gl/2019JanMar/0100.html) by @KimPatch and a [response by Mike](https://lists.w3.org/Archives/Public/w3c-wai-gl/2019JanMar/0103.html)

**Comment by detlevhfischer** [comment]
I think @mbgower has a point that there are situations where it will be hard to know what to do best (freom a developer perspective) and hard to assess whether something conforms (from an evaluator perspective). I have tried to explain the scoping of this SC in a draft of a test procedure as follows:

> The checkbox is usually not applicable to interface components that are labelled by several visible elements, e.g. in forms where the accessible name consists of the legend element of a fieldset and the actual label, or in cases where elements in a tabular matrix receive their accessible name via labels in column and row headers. In these cases, it is unclear to speech input users which elements act as labels for the control element and should therefore be used for speech input.

**Comment by KimPatch** [comment]
In the response linked to above, Mike said 

> If we began telling everyone to incorporate the question text into the acc name, we would make the screenreader experience untenable. Imagine having those long questions read at the start of every one of the choices for a checkbox set, etc. You wouldn't even hear the important bit until the end of a potentially very long string.

I don't think I was being clear enough in my email.  I don't think it's good to have the question text in the choices either – that wouldn't work for anyone. But if the question can take the focus, the speech user could say the first couple of words of the question to put the focus there, then use arrows or tabs from there to get to the checkboxes.

**Comment by mbgower** [comment]
Modifying the SC is one way of tackling this; however, I believe we can also just scope it within the Understanding document. Something like:

> For the purposes of this SC, the label is only considered to be the text string in close proximity to the component. The typical positioning is:
>- immediately to the left of comboboxes, dropdown lists, text inputs and other widgets (or in the absence of left-side labels, immediately above each input)
>- immediately to the right of checkboxes and radio buttons
>- inside buttons and tabs or immediately below icons serving as buttons

> For the purposes of this SC, labels are not considered to include preceding instructions, group labels, legends or headings. Such information is encouraged where appropriate; however, due to the rules for determining the name in the [Accessible Name and Description Computation 1.1](https://www.w3.org/TR/accname-1.1/), such related information is not part of the Accessible Name calculation without author intervention.  (Such textual information may constitute part of the components _description_.)

> Isolating the label to the single string in close proximity to the component makes it easier for developers, testers and end users to determine and take advantage of the intended benefit of this SC. That is, allowing users of speech recognition technologies to interact with the element via its label, and allow users of screen reading technologies to enjoy consistency between the visible label and the announced name of the component.

**Comment by mbgower** [comment]
BTW, something we may want to open as a request for version 1.2 of the Accessible Name and Description Computation is the incorporation of legends and group/radiogroup roles into the _Description_ section. I'm uncertain of why they are not there -- except that I think more attention has been focused on the name computation, rather than the description so far.

**Comment by mraccess77** [comment]
I agree that we should help define how the group information could potentially be announced -- but I don't think it should specifically be mandated in the name or description of ancestor content.  It seems like tools should have flexibility in how this is conveyed.

**Comment by mbgower** [comment]
@mraccess77
> It seems like tools should have flexibility in how this is conveyed.

I've sent an email to Bryan Garaventa, one of the editors of the spec, to get his thoughts. I agree we want to leave discretion to tools, but at the moment the info in the spec on Description is very limited. It only contains a "must" phrase about aria-describedby. Perhaps it could contain some "may" statements about group and legend which would help clarify their potential role.

**Comment by mbgower** [comment]
@KimPatch  said
>I don't think it's good to have the question text in the choices either – that wouldn't work for anyone. But if the question can take the focus, the speech user could say the first couple of words of the question to put the focus there, then use arrows or tabs from there to get to the checkboxes.

I haven't done testing with Dragon to confirm, but what I'm finding from the info supplied by Bryan Garaventa is that accessible names are defined for grouping elements in the [HTML Accessible API Mapping](https://w3c.github.io/html-aam/#accessible-name-and-description-computation), so a speech recognition should be able to leverage the legend text.

Even if such a question does not take focus, my recollection is that I used to navigate by getting DNS to select a text string on the screen (such as the question), then Press Tab to orient to the next focusable element.

**Comment by mraccess77** [comment]
FWIW.  Most of the browsers are better at allowing the Find feature to select text and then close the find dialog and press or speak "press tab" to move focus to next interactive item after the selection.

**Comment by alastc** [comment]
I think the next step would be for someone to do a pull request based on @mbgower's [comment above](https://github.com/w3c/wcag/issues/591#issuecomment-456838433), then that can be surveyed.

**Comment by mbgower** [comment]
Okay, I have a fairly revised Understanding document into which I will roll this draft text and submit today.

**Comment by mraccess77** [comment]
I agree that fieldset's/group text should not be included -- however, there might be an exception when the only visual label is the visual group name such as "Phone Number" in a set of phone number fields that has only a group name of Phone number.

**Comment by awkawk** [comment]
This issue was created to track ideas around updates to Label in Name's Understanding document. Since that update is completed and this issue and the updates all came from @mbgower I am closing this issue. Mike, if you disagree, please reopen.
