### ISSUE TITLE
This page is not functional at 320CSS px

### ISSUE THREAD

**Issue by WayneEDick** [w3c/wcag#596]
This input form runs off the right hand side of the page. 
Why does the W3C use software for its issue input that does not satisfy its criteria?
Try and submit a issue at 320CSS pixels. It is really a mess.

**Comment by awkawk** [comment]
@WayneEDick I wrote to GitHub about this and cc'd you.

**Comment by fstrr** [comment]
Closing this issue as it appears to be resolved. The page has nothing hanging off the right hand side of the page and has no horizontal scrolling at 320 CSS pixels. Please re-open if necessary.
