### ISSUE TITLE
Do the biggest sites fail Success Criterion 2.1.4 (Character Key Shortcuts)?

### ISSUE THREAD

**Issue by simevidas** [w3c/wcag#597]
The success criterion in question: https://www.w3.org/TR/WCAG21/#character-key-shortcuts

Examples of big sites using character key shortcuts:

* On Twitter, press <kbd>N</kbd> to open a dialog for writing a new tweet.
* On Facebook, press <kbd>P</kbd> to open a dialog for writing a new post.
* On GitHub, press <kbd>G</kbd> followed by <kbd>I</kbd> to view all open issues.

These sites don’t seem to have a setting that would allow users to disable or reconfigure these keyboard commands. Does this mean that all these big sites currently fail this success criterion?

**Comment by awkawk** [comment]
@simevidas if these sites do not allow users to turn the shortcuts off or remap them, then yes they would be failing to meet SC 2.1.4.

**Comment by simevidas** [comment]
Yup, that’s a good example, I think.
