### ISSUE TITLE
Exception for use of symbols as visible label in regard to 2.5.3 Label in Name

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#598]
Another consideration for what exactly should be considered relevant when figuring out success for meeting 2.5.3 is the use of symbols on buttons and icons.

An example would be buttons in a rich text editor. In github, these buttons include "AA", "B", "i", an open double quote and a set of coding brackets ("<>"). 
![git editor rich text buttons](https://user-images.githubusercontent.com/14298245/51934882-7d52a180-23b9-11e9-8ee8-3bc74fb38586.png)

Although I question the wisdom of some of the accessible names for these buttons assigned through aria-label such as "Add bold text, <ctrl+b>", I think it is nonsensical that "AA" should be required as the accessible name.

Another example would be where someone has used a ? or ! symbol as a button label. I think it is defensible that "More information" and "Caution" are not only more meaningful alternatives but should not result in a failure of 2.5.3. (This is leaving aside the question of whether the use of the symbol alone as a label is a good design decision.)

I am going to propose that the use of symbols or character keys employed as symbols should be excluded from consideration as part of the visible text label for the purposes of meeting 2.5.3.

**Comment by mbgower** [comment]
"Symbolic text characters" in [1.4.5 Images of Text](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-text-presentation.html) also addresses questions about use of text characters as symbols and the notion of the characters not forming a sequence that expresses something in human language:
> A form allows users to enter blocks of text. The form provides a number of buttons, including functions to style the text and check spelling. Some of the buttons use text characters that do not form a sequence that expresses something in human language. For example "B" to increase font weight, "I" to italicize the text and "ABC" to check the spelling. The symbolic text characters are included as gif images which do not allow the text characteristics to be changed. The buttons have text alternatives.

**Comment by mraccess77** [comment]
Interesting -- I think it's saying that these aren't text for the purposes of SC 1.4.3.  But admitted these examples in the understanding are not clear which in the bullet list is a example pass and what is an example fail.  I tend to recall that when this discussion came up with other symbols before they weren't considered text and so greater than would not be text either and thus not subject to 2.5.3.    This makes some sense because it's not the name we want but the meaning.  For example a triangle for a play button -- we don't want the acc name to be triangle -- but instead play.  we don't want to pipes to be "pipes" but instead "pause".

**Comment by alastc** [comment]
Indeed, I would not have considered those examples as 'text' (as defined in WCAG), so perhaps adding a similar disclaimer to 2.5.3 from 1.4.5 is in order. I believe you're updating this at the moment @mbgower?

There is a gap, I.e. what should the accname of those symbols be so that people can predict it, but that's best dealt with at a (localised) best-practice level rather than guidelines.

**Comment by mbgower** [comment]
The discussion in https://github.com/w3c/wcag/issues/592 is relevant to this topic as well.

**Comment by mbgower** [comment]
@mraccess77 can you please correct this in your [comment](https://github.com/w3c/wcag/issues/598#issuecomment-458758258)
>  I think it's saying that these aren't text for the purposes of SC 1.4.3.

I believe you mean SC 1.4.5.

**Comment by mbgower** [comment]
@mraccess77 
> There is a gap, I.e. what should the accname of those symbols be so that people can predict it, but that's best dealt with at a (localised) best-practice level rather than guidelines.

I don't think I'd technically describe that as a gap. If we are saying that ">" is not text, then a control labelled by it does not in face have a visible text label for the purposes of 2.5.3, and so can have any string for its accessible name.

**Comment by mbgower** [comment]
Okay, here's a similar question. What about mathematical symbols?
A>B or 5-3

I think I'd argue that when used as part of a mathematical expression, punctuation has 'human language' expression and the name should match the label.

**Comment by alastc** [comment]
> I don't think I'd technically describe that as a gap. If we are saying that ">" is not text, then a control labelled by it does not in fact have a visible text label for the purposes of 2.5.3

I didn't mean a gap for 2.5.3, but an overall gap in accessibility for people using voice input, i.e. how do they know what the accname of a symbol is?

So it's a gap in that there is nothing covering symbol usage in controls. (One that would ideally be filled by voice input have a feature to overlay the names of controls via a simple command.)

> I think I'd argue that when used as part of a mathematical expression, punctuation has 'human language' expression and the name should match the label.

I agree with that, and would hope that voice input would deal with it, there are certainly [commands for punctuation and symbols.](https://www.nuance.com/products/help/dragon/dragon-for-mac/enx/Content/Dictating/Dictating_punctuation.htm)

**Comment by mbgower** [comment]
This was addressed in updates to the Understanding Label in Name document, which was updated via https://github.com/w3c/wcag/pull/614
