### ISSUE TITLE
Example page lacks images Images for C37

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#601]
https://www.w3.org/WAI/WCAG21/Techniques/css/C37

In the example page the images are not present.

https://www.w3.org/WAI/WCAG21/working-examples/css-fitting-images/

**Comment by jake-abma** [comment]
Might be because RawGit is no more...

**Comment by alastc** [comment]
Good spot, very odd. The images are right there in the same folder, not sure why there were rawgit URls in there.

Pushed straight to master, should appear by monday.
