### ISSUE TITLE
Editorial: Glossary section of WCAG 2.1 has phrase "WCAG Working Group"

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#609]
https://w3c.github.io/wcag/21/guidelines/#dfn-accessibility-supported

> The WCAG Working group and the W3C do not specify which or how much support by assistive technologies there must be for a particular use of a Web technology in order for it to be classified as accessibility supported.

We know WCAG 2.1 was published by the Accessibility Guidelines Working Group.

**Comment by awkawk** [comment]
We will make this change, thanks.

**Comment by awkawk** [comment]
Fix ready in https://github.com/w3c/wcag/pull/611

**Comment by awkawk** [comment]
Approved as errata in #611
