### ISSUE TITLE
Typo in 0.5.2 Numbering in WCAG 2.1

### ISSUE THREAD

**Issue by eduardo-olivares1** [w3c/wcag#616]
In the sentence "This avoids the need to change the section number of success criteria from WCAG 2.0, which would be caused by inserting new success critera between existing success **ccriteria** in the guideline, but it means success criteria in each guideline are no longer grouped by conformance level." the word '**criteria**' is misspelled as '**ccriteria**'.

[https://www.w3.org/TR/WCAG21/#numbering-in-wcag-2-1](https://www.w3.org/TR/WCAG21/#numbering-in-wcag-2-1)

**Comment by awkawk** [comment]
Already listed as an erratum: https://www.w3.org/WAI/WCAG21/errata/
