### ISSUE TITLE
Understanding Conformance page is still 2.0 labelled

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#621]
The conformance section(https://www.w3.org/TR/WCAG21/#conformance)
links to a 2.0 document, which then puts the user into the 2.0 directory structure. I assume we want to avoid that and should make a 2.1 version of the conformance page
https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance

**Comment by awkawk** [comment]
Raised in #382 so closing this as a dup.
