### ISSUE TITLE
Unavailable external resources in Understanding WCAG 2.0/2.1

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#628]
Following link URLs are unavailable resources (HTTP 404/500 etc) in Understanding WCAG 2.0/2.1.
We need to remove or update these URLs:
 
1.2.9
http://www.captioningandsubtitling.com.au/work/internet/
 
1.4.1
http://www.vischeck.com/
 
1.4.3, 1.4.6
http://trace.wisc.edu/contrast-ratio-examples/
 
1.4.3
http://www.vischeck.com/daltonize/runDaltonize.php
 
1.4.6
http://www.iansyst.co.uk/articles/article/articles/2012/10/18/fonts-for-dyslexia
 
1.4.7
http://trace.wisc.edu/docs/2004-About-dB/index.htm
 
2.3.1, 2.3.2
http://trace.wisc.edu/peat/photosensitive.php
 
2.4
http://www.motive.co.nz/glossary/navigation.php
 
2.4.2
http://www.socialpatterns.com/search-engine-optimization/writing-better-web-page-titles/
 
3.1.5
http://www.textquest.de/pages/en/analysis-of-texts/readability-analysis.php
 
3.2.3
http://www-03.ibm.com/able/access_ibm/disability.html

**Comment by patrickhlauke** [comment]
for 2.3.1 / 2.3.2 PEAT is now https://trace.umd.edu/peat
