### ISSUE TITLE
Examples for "programmatically determined" are marked as notes instead of examples

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag#633]
There is a minor issue in the definition of "programmatically determined": https://www.w3.org/TR/WCAG21/#dfn-programmatically-determinable

Under the definition are two examples. In WCAG 2.0 they were marked as "Example 1" and "Example 2", but now they are both marked as "Note". A "note" implies that it is part of the definition, but these should just be examples.

Current text with the issue:

<blockquote>

<h3>NOTE</h3>

Determined in a markup language from elements and attributes that are accessed directly by commonly available assistive technology.

<h3>NOTE</h3>

Determined from technology-specific data structures in a non-markup language and exposed to assistive technology via an accessibility API that is supported by commonly available assistive technology.

</blockquote>

**Comment by alastc** [comment]
There seem to be a few issues with the notes/example labels being applied properly, so I'm assigning this to @michael-n-cooper

**Comment by michael-n-cooper** [comment]
@alastc I went through the old sources and this seems to be the only case that an example got turned into a note.
