### ISSUE TITLE
Applicability of 1.4.12 text spacing to data tables in web applications

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#641]
Following on from #620 I have a question from evaluators about the applicability of 1.4.12 Text spacing to text / numbers in data tables.
The evaluator notes that text in applications using data tables is usually not created in such a way that the cells adapt to larger text spacings via bookmarkets, own style sheets etc. She notes that for 1.4.10 Reflow, data tables are listed as possible exceptions because they have an inherent two-dimensionality, and wonders if a similar exception would apply for this SC. My hunch is that no such exceptions apply here but I am interested in views from others.

**Comment by patrickhlauke** [comment]
no exception. data tables should be created so they adapt. if they don't, they fail 1.4.12. i'd say, anyway.

**Comment by jake-abma** [comment]
Agreed, no exception here

**Comment by awkawk** [comment]
Proposed WG Response: There is no exception that applies to text in a data table so 1.4.12 applies.

**Comment by awkawk** [comment]
Agreed on March 26 call: https://www.w3.org/2019/03/26-ag-minutes.html#item09
