### ISSUE TITLE
DOCUMENT NOT FOUND - 2.4.7 Focus Visible link in SC 1.4.11: Non-text Contrast

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#644]
At: https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#techniques

there's a link to "2.4.7 Focus Visible link" in section: "Relationship with Use of Color and Focus Visible" but the link end up https://www.w3.org/WAI/WCAG21/20/focus-visible.html a DOCUMENT NOT FOUND page.

Correct link: https://www.w3.org/TR/WCAG21/#focus-visible

**Comment by awkawk** [comment]
fixed: 3941434
