### ISSUE TITLE
G209: The technique "IS" referenced from an Understanding doc

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#646]
At the technique G209 there's a sentence: "This technique is not referenced from any Understanding document." but I ended up there from Understanding doc: https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#techniques

**Also the link for "Understanding SC 1.4.3 Contrast (minimum)" is broken on that page...**

**Comment by awkawk** [comment]
Fixed. The first part was already done but hasn't been published yet. I fixed the link.
