### ISSUE TITLE
H59: outdated links

### ISSUE THREAD

**Issue by cstrobbe** [w3c/wcag#650]
[Technique H59](https://www.w3.org/TR/WCAG20-TECHS/H59.html) (for `link` elements) contains outdated links:
* Since HTML 4.10 is a "superseded specification" and some of the link types listed there have been removed in HTML5, I suggest replacing both links to HTML 4.01 with a link to [**Link types** in the HTML5 specification](https://www.w3.org/TR/html5/links.html#sec-link-types).
* As far as I can tell, the [Link Toolbar extension for Firefox](http://cdn.mozdev.org/linkToolbar/) is no longer being maintained. The most recent bug are more than 10 years old. This link can be removed.

**Comment by awkawk** [comment]
Fixed
