### ISSUE TITLE
Understanding 2.5.4 Motion Actuation's "Related Resources" are irrelevant.

### ISSUE THREAD

**Issue by kurosawa-takeshi** [w3c/wcag#652]
[Understanding 2.5.4 Motion Actuation](https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation) ([ED](https://w3c.github.io/wcag/understanding/motion-actuation)) has two "Related Resources" sections and first one is irrelevant. It might be related to [2.3.3: Animation from Interactions](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions)) ([ED](https://w3c.github.io/wcag/understanding/animation-from-interactions)). I propose removing first one.

## Current

> Related Resources
> 
> Resources are for information purposes only, no endorsement implied.
> 
> - Mozilla documentation for 'prefers-reduced-motion'
> - Demonstration of 'prefers-reduced-motion' in Webkit
> - iOS: Reduce Motion on iPhone, iPad or iPod touch
> - Mac: Reduce Motion
> - Windows 10: Reduce motion
> 
> Related Resources
> 
> Resources are for information purposes only, no endorsement implied.
> (none currently documented)

## Proposed

> Related Resources
>
> Resources are for information purposes only, no endorsement implied.
> (none currently documented)

Note: removed first "Related Resources".

**Comment by patrickhlauke** [comment]
I would actually say that all the listed resources are irrelevant to 2.5.4 motion actuation, as they all deal with the user's desire to have less motion / animation being displayed, and NOT about a desire not to have to interact with a page/site using motion.

More relevant resource would possibly be:

* [Mozilla documentation on detecting device orientation](https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation)

**Comment by mraccess77** [comment]
Maybe there are supposed to go with SC 2.3.3 instead.

**Comment by patrickhlauke** [comment]
yes, they should be moved to/added to https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions

**Comment by awkawk** [comment]
Unofficial Working Group Response: Thank you for the comment. We will move the five related resources to the 2.3.3 Understanding document. We will also add the articles https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation and https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent to the 2.5.4.

**Comment by awkawk** [comment]
Leaving open until implemented.

**Comment by awkawk** [comment]
Implemented.
