### ISSUE TITLE
Mobile browser reflow language potentially confusing

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#660]
The Reflow understanding document contains the following subsection:
> ### Browsers in Mobile Operating Systems
> The layout method of most common browsers in mobile operating systems does not offer reflow in the same way as on desktop browsers. In these browsers, content can be magnified in different ways, for example, by using a pinch gesture to scale up content, or a double tap on a particular column to make it fill the viewport width. This means that currently, mobile browsers usually exhibit horizontal scrolling regardless of what an author does.

>In principle, mobile user agents can equally offer reflow when users zoom into content, as evidenced by the Dolphin browser for Android. The lack of reflow support in mobile operating systems can therefore be regarded as a user agent support issue.

I believe this guidance is potentially confusing, as it blends the Resize requirement with Reflow without explicitly stating that. I have created pull request https://github.com/w3c/wcag/pull/659 which I believe makes this subsection clearer in its intent and guidance.

**Comment by awkawk** [comment]
Pull request #659 Accepted by WG April 9, 2019
