### ISSUE TITLE
Technique G146: outdated URL

### ISSUE THREAD

**Issue by cstrobbe** [w3c/wcag#663]
In [Technique G146](https://www.w3.org/TR/WCAG20-TECHS/G146.html), the URL for [CSS Mastery: Fixed-Width, Liquid, and Elastic Layouts and Faux Columns](http://www.webreference.com/authoring/style/sheets/css_mastery2/index.html) needs to be replaced with http://webreference.com/authoring/style/sheets/css_mastery2/index-2.html. 

(I am assuming that that the other link, http://cssliquid.com/, is only temporarily unreachable.)

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag/commit/d8111c7307acc1f2a97adda7cc41fbe653130bec The CSSLiquid resource is down now but was also converted into a personal blog (based on a wayback review) so it isn't helpful and I removed it.
