### ISSUE TITLE
Typo in F91 tests

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#67]
http://www.w3.org/TR/WCAG20-TECHS/F91.html#F91-tests

It says (replaced # with § to avoid GitHub issue confusion)

> Expected Results
> * If all checks §1 - §4 are false, then this failure condition applies and the content fails the Success Criterion.

As there are six checks, I think the correct sentence would be

> * If all checks §1 - §6 are false, then this failure condition applies and the content fails the Success Criterion.

**Comment by awkawk** [comment]
fixed, thanks.
