### ISSUE TITLE
2.5.2 Pointer cancellation - are both mouse buttons included?

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#670]
The question was raised by testers whether both mouse buttons are included in checks for down events, or just the default button (left for right-handed setting).

**Comment by patrickhlauke** [comment]
if a site has hooked some functionality to any other mouse button directly (note there's usually also middle button / wheel), then yes.

i.e. if there's an `mousedown` event listener, which does something specific for `event.button == 2` then the same test applies. also, if they've hooked into `contextmenu` event to trigger custom functionality (of course, this doesn't apply to the default browser context menu, as that can't be cancelled, but doesn't actually trigger functionality apart from showing the context menu itself)

**Comment by awkawk** [comment]
Proposed WG response: While less commonly used than the default button, use of other buttons needs to support the same users. As a result, 2.5.2 applies to any pointer being used, including left, right, center, and any others.
