### ISSUE TITLE
Large text definition should include more font weights

### ISSUE THREAD

**Issue by cyns** [w3c/wcag#671]
This is similar to #665 
The definition of large text needs more details about combinations of sizes and weights that constitute large text. 

There is no way to answer these questions:
Is 15pt demi-bold large text? Does it pass WCAG at 3:1 contrast ratio, or does it need to be 4.5:1?

**Comment by patrickhlauke** [comment]
As it's, again, dependent on the actual specific font itself, I'd say there's really no point in trying to extend the flawed definition with even more flawed definitions.

**Comment by jake-abma** [comment]
same here, see also https://github.com/w3c/wcag/issues/341 for more on bold... :-)

**Comment by awkawk** [comment]
Proposed WG response: Thank you for the comment. We are marking this as an issue for deferral and will indicate WCAG 2.2 or Silver as deemed appropriate once the WG reviews what it can do in WCAG 2.2. Any suggestions for specific language that you feel would address the issue are appreciated.
