### ISSUE TITLE
Understanding 2.5.5: Target Size - broken links to definitions

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#684]
In the SC itself at the top of https://www.w3.org/WAI/WCAG21/Understanding/target-size.html the links to `pointer inputs` and `CSS pixels` are broken (they point to https://www.w3.org/TR/WCAG21/#dfn-pointer-input and https://www.w3.org/TR/WCAG21/#dfn-css-pixel, when they should instead point to https://www.w3.org/TR/WCAG21/#dfn-pointer-inputs and https://www.w3.org/TR/WCAG21/#dfn-css-pixels - with the "s" at the end)

**Comment by michael-n-cooper** [comment]
This is an instance of the problem described in #594 so closing this specific issue.
