### ISSUE TITLE
[Comment] Merging Techniques c12,c13 and 14

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#70]
https://www.w3.org/2006/02/lc-comments-tracker/35422/NOTE-WCAG20-TECHS-20140911/2992

I always wondered why in Techniques for WCAG 2.0 there are three different techniques (c12, c13 and c14) for the same problem, ie how to specify text font size. 

My proposal is to merge them together in a single technique

Proposed Change:
A new technique that will merge c12,c13 and c14.
Its procedure will be:

1) Check that the value of the CSS property that defines the font size is a percentage.
2) Check that the value of the CSS property that defines the font size is one of xx-small, xx-small, x-small, small, medium, large, x-large, xx-large, xsmaller, or larger.
3) Check that the value of the CSS property that defines the font size is expressed in em units.

Expected Results

Check #1 or Check #2 or Check #3 is true

**Comment by joshueoconnor** [comment]
Draft Technique C31: Using percent for font sizes is related to this https://github.com/w3c/wcag/issues/71

**Comment by joshueoconnor** [comment]
I can see no good reason to NOT merge these techniques. The draft technique is ready for survey 
 [Draft Technique] C31:Using percent for font sizes #71

**Comment by joshueoconnor** [comment]
Josh to look at these again.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
