### ISSUE TITLE
Sections in Understanding docs without content should be adjusted

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#705]
Some SC Understanding docs have no meaningful content under a heading and also what is present is inconsistent. These should contain meaningful text like "no resources available yet" or be deleted till there is meaningful content.

Didn't check all Understanding docs, probably more out there but examples I came across today are:

https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html#resources

> Related Resources
> Resources are for information purposes only, no endorsement implied.

https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html#resources

> Related Resources
> Resources are for information purposes only, no endorsement implied.
> 
> Resource

**Comment by jake-abma** [comment]
https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation.html#resources

here's an example where there is content telling "none currently documented"

> Related Resources
> Resources are for information purposes only, no endorsement implied.
> 
> (none currently documented)

**Comment by mbgower** [comment]
it looks to me like someone just added in a repeat section, as there _are_ resources listed immediately above. I'll make a PR for this.

**Comment by mbgower** [comment]
https://github.com/w3c/wcag/pull/712

**Comment by michael-n-cooper** [comment]
The generator does try to suppress these sections where there is not real content. But it's heuristic and can be thrown off by stray content. I'll try to improve.

**Comment by jake-abma** [comment]
https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html#techniques

> Advisory Techniques
> Although not required for conformance, the following additional techniques should be considered in order to make content more accessible. Not all techniques can be used or would be effective in all situations.

Empty
