### ISSUE TITLE
exempt or not covered, and exempt not needed - SC 2.5.4: Motion Actuation

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#709]
When I read the 2.5.4 there's a note:

> Note: It does not cover the movement of users through space as registered by geolocation sensors or beacons, or events observed by the device other than intentional gesturing by the user. 

A bit further at the intent it says:

> Examples of content that are exempt from this requirement include a pedometer that relies on device motion to count steps.

It may just be the way I read it but if geolocation is just not covered is the next part which talks about a "exempt" a bit misplaced? Exempt feels like the exception to the rule when it is covered.

**Comment by mbgower** [comment]
So, the note is an explanation on interpretation of the language. It is not an exception but a scoping statement. 
The pedometer provides an example of something that meets the exception language "The motion is essential for the function and doing so would invalidate the activity."
I don't personally have a big problem with saying that something that meets an exception is exempt from meeting the SC. 
Do you want to propose some language so we can consider?

**Comment by jake-abma** [comment]
After re-reading the sentence still feels a bit odd, also where it is placed, it might fit better in the note after "does not cover..." But can live perfectly fine with either.
