### ISSUE TITLE
Small text change to Examples:  2.5.4: Motion Actuation

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#710]
https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation.html#examples

The following sentence reads a bit strange, may be changed to the following

Change:

> After text is input in a field, shaking

To:

> After the text has been entered in a field, shaking

**Comment by mbgower** [comment]
https://github.com/w3c/wcag/pull/712

**Comment by awkawk** [comment]
fixed in #712 so closing
