### ISSUE TITLE
Typo Understanding 2.5.3 Label in name

### ISSUE THREAD

**Issue by audreymaniez** [w3c/wcag#731]
Hi, 

I think there's a little typo in the [understanding 2.5.3](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name ), "Mathematical expressions and formulae" section: 

> For example, making the name "eleven **multipled** by three is equivalent to thirty-three" 

Isn't it "multpl**i**ed" ?

**Comment by alastc** [comment]
Thank you @audreymaniez, I've corrected that in the draft version, it will be deployed soon.
