### ISSUE TITLE
Using 'non-web document(s)' instead of 'web page(s)' in WCAG2ICT 

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#74]
https://www.w3.org/2006/02/lc-comments-tracker/35422/NOTE-UNDERSTANDING-WCAG20-20140911/2995

Comment (Including rationale for any proposed change):
I think the choice of words selected to replace 'web page' ('document' and 'program') is not the best choice of words to use. I believe the word 'screen' is much more appropriate. As we are already using that word and it is used in every software development practice and not just websites/web apps. In addition, the choice to use 'software program' I believe is too large of a unit to measure. 

Proposed Change:
use the word 'screen' and/or 'set of screens' for defining the unit of measure.

**Comment by awkawk** [comment]
Responded to Oscar by forwarding comment to the correct list.
