### ISSUE TITLE
Draft technique "Providing a control slider that offers single point activation"

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#741]
I have drafted what I hold to be a Sufficient Technique for 2.5.1 Pointer Gestures, "Providing a control slider that offers single point activation" 
Github: https://github.com/w3c/wcag/blob/tech-providing-single-point-control-sliders/techniques/general/providing-single-point-control-slider.html
Rendered version in Githack: https://raw.githack.com/w3c/wcag/tech-providing-single-point-control-sliders/techniques/general/providing-single-point-control-slider.html

Currently filed as General Technique but could equally be a SCR Technique.
(I know we are still debating whether control sliders should actually be in scope, but this Technique started much earlier, and @patrickhlauke has provided a beautiful code example that is not only swipable and draggable and single-point-activatable but can also be operated with arrow keys and screen reader AT swipe gestures. Chapeau.)

**Comment by alastc** [comment]
It might depend on the resolution of #522, but is probably a sufficient technique anyway.

**Comment by jake-abma** [comment]
The following is contradictory

> The objective of this technique is to ensure that users who have **difficulties performing path-based gestures** can operate a control slider with a single pointer (e.g., a single tap on a touch screen or a single mouseclick).

And the definition is:

> single pointer
> pointer input that.... **and path-based gestures**

------------------------

> Swiping left or right across the slider or dragging the thumb of the slider to the left or the right 
This can also be up or down, not only right left

------------------------

Not sure if "groove clickable" is a well known term

> A simple fallback for single point activation is to make the control slider groove clickable. This way, a value can be specified using single point activation over the groove.

------------------------

Small text error "otr" and also here the "single pointer"

> Providing controls (for example, arrow buttons) as alternative means of input allows incrementing otr decrementing the value with single pointer input. 

------------------------

Small error in text:

> The sider groove allows single

The slider groove allows single

------------------------

Procedure:

Would like to see the three scenarios split in three steps (maybe small rewrite needed)

1. Check that the value of the control slider (range) can be set with single point activation
2. There may be dedicated buttons to increase / decrease the value in a stepwies fashion
3. The slider grove may resond to single point activation, moving the thumb to the position activated.

**Comment by alastc** [comment]
There is a significantly updated version of this in #760, I'm closing this issue as we should be looking at the PR.
