### ISSUE TITLE
Found a undiscovered "future link" in 3.2.5 - Change on Request

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#743]
https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-no-extreme-changes-context.html#consistent-behavior-no-extreme-changes-context-techniques-head

> **Additional Techniques (Advisory) for 3.2.5**
>  ...target attribute (future link), because many ...

**Comment by alastc** [comment]
That's the WCAG 2.0 doc, it isn't in the 2.1 version:
https://www.w3.org/WAI/WCAG21/Understanding/change-on-request 

(And yes, we do need to forward on the 2.0 docs.)
