### ISSUE TITLE
links broken 2.5.3: Label in Name | single Vs. plural

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#745]
The definition links are broken for:

https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html

They are single and need to be plural

**Comment by alastc** [comment]
I think this is a build-process thing, an you confirm @michael-n-cooper ?

**Comment by awkawk** [comment]
Duplicate of https://github.com/w3c/wcag/issues/465
