### ISSUE TITLE
"(future link)" Vs. "GXXX:" (SC 2.5.1)

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#748]
So we removed all "(future links)" from the Understanding docs.

at SC 2.5.1 is seems we replaced them with "GXXX:" think also these needs to be deleted (until we have proper techniques).

ps. what is GXXX anyway? G for General and XXX for whatever may come in future?

**Comment by jake-abma** [comment]
At Failures we have a sentence without a link to the failure but also without GXXX or (future links):

- Functionality can be operated by pointer input but not with single-point activation alone

**Comment by alastc** [comment]
"Future links" were removed as they were from WCAG 2.0, and if it ain't done now, it is unlikely to ever be done.

We had multiple authors doing understanding docs without a clear format for noting un-published techniques, which is where the Gxxx came from.

There is an [open question in the survey](https://www.w3.org/2002/09/wbs/35422/Tech_Und_survey/#wbsq19) about this, so I'm closing this as a duplicate.
