### ISSUE TITLE
Understanding 4.1.2: wrong anchor

### ISSUE THREAD

**Issue by audreymaniez** [w3c/wcag#751]
Hey, 

In the text of [the criterion 4.1.2](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value)  some anchor are broken: 

- `#dfn-user-interface-component`  should be `#dfn-user-interface-component**s**` 
- `#dfn-programmatically-determined` should be `#dfn-programmatically-determinable` 
- `#dfn-user-agent` should be `#dfn-user-agents`
- `#dfn-assistive-technology` should be `#dfn-assistive-technologies`

**Comment by awkawk** [comment]
Same issue as https://github.com/w3c/wcag/issues/465 - closing this one.
