### ISSUE TITLE
H57, H58 and xml:lang

### ISSUE THREAD

**Issue by dd8** [w3c/wcag#759]
There are multiple problems relating to H57, H58 and `xml:lang`

1) `xml:lang` is forbidden in HTML5
>Authors must not use the lang attribute in the XML namespace
>on HTML elements in HTML documents.
https://www.w3.org/TR/html52/dom.html#the-lang-and-xmllang-attributes
https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes

2) Our testing shows `xml:lang` only works in Chrome, so arguably does not meet the definition for 'accessibility supported' which requires support in user agents (plural).
>The Web content technology must have accessibility-supported user
>agents that are available to users
https://www.w3.org/TR/WCAG21/#dfn-accessibility-supported

`lang` is very well supported and works in all tested browser/AT combinations
https://www.powermapper.com/tests/screen-readers/content/html-page-lang/

`xml:lang` is very poorly supported - it works in Chrome but not if you use another browser
https://www.powermapper.com/tests/screen-readers/content/html-page-xml-lang/

3) The following note is incorrect, since XHTML 1.1 First Edition did only allow `xml:lang` but XHTML 1.1 Second Edition allows both `lang` and `xml:lang`

>Note: HTML only offers the use of the lang attribute, while XHTML 1.0 (as a transitional >measure) allows both attributes, and XHTML 1.1 allows only xml:lang.

XHTML 1.0 Rec

>Use both the lang and xml:lang attributes when specifying the language of an element.
https://www.w3.org/TR/xhtml1/#C_7

XHTML 1.1 Rec - First Edition

>On every element, the lang attribute has been removed in favor of the xml:lang attribute
https://www.w3.org/TR/2001/REC-xhtml11-20010531/changes.html#a_changes

XHTML 1.1 Rec - Second Edition
The updated recommendation deleted the statement saying the `lang` attribute has been removed in favor of the `xml:lang` attribute and modified the DTD to allow `lang`
https://www.w3.org/TR/xhtml11/changes.html#a_changes

The W3 validator does not flag validation errors for XHTML 1.1 documents using `lang` because the `lang` attribute was added back to the XHTML 1.1 Second Edition DTD using the following declaration - this wasn't present in the XHTML 1.1 First Edition DTD:
```
<!ENTITY % lang.attrib
     "xml:lang     %LanguageCode.datatype;  #IMPLIED
      lang         %LanguageCode.datatype;  #IMPLIED"
>
```
https://www.w3.org/TR/xhtml11/xhtml11_dtd.html

**Comment by alastc** [comment]
I haven't come across anyone intentionally using XHTML for many years now, so I've created a version that simply removes the XML aspects of those two techniques in #766 

Does that address this for you?

**Comment by dd8** [comment]
I think that fixes it - but there's a dangling `>` after `</code>` in the H57 title

I had 2 questions when looking at the fixes:

1) H57 - what happens when the page is a SVG or MathML documents. 
I think this is out of scope because this technique only applies to HTML documents.

2) H58 - what happens when an HTML page contains embedded SVG or MathML - should you use `lang` or `xml:lang` in the embedded elements? 
Seems like `lang` is still the way to go - SVG 2 added the `lang` attribute to replace `xml:lang`
https://www.w3.org/TR/SVG2/access.html#AccessibilityAndSVG
and MDN marks xml:lang in SVG as deprecated
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:lang

**Comment by dd8** [comment]
Did some quick testing on using `lang` and `xml:lang` on a SVG embedded within HTML. The results are not encouraging. The `lang` and `xml:lang` attributes are ignored or (worse) cause elements to be skipped when reading

```
<svg role='img'>
<title>Active table</title>
<path d="...."/>
</svg>
```
`title`
VoiceOver on macOS 10.14 with Safari 12.1 - read using English voice (as expected)
NVDA 2018.3 on Win 10 with Firefox 67 - read using English voice (as expected)

`title xml:lang='fr'`
VoiceOver on macOS 10.14 with Safari 12.1 - read using English voice
NVDA 2018.3 on Win 10 with Firefox 67 - read using English voice

`title lang='fr'`
VoiceOver on macOS 10.14 with Safari 12.1 - title not read
NVDA 2018.3 on Win 10 with Firefox 67 - read using English voice

**Comment by awkawk** [comment]
@dd8 I think that for SVG or MathML in an HTML document we need a different technique. It would be great to get any additional data to support such a technique.

@alastc beat me to the punch in updating this, but I added some edits and it should be ready to survey to the group for next week.

**Comment by alastc** [comment]
The PR was merged, so I'm closing this one. If anyone wants to add a technique for SVG or other markup languages, that would be fine, but not a high priority at the moment.

**Comment by dd8** [comment]
Some more info on this - I don't think it affects the pull request, but worth flagging up.

The handling of `lang` vs `xml:lang` elements on HTML elements *depends on the HTTP Content-Type* the page is served with. There's a clear description here:
https://www.w3.org/International/questions/qa-html-language-declarations#attributes

This explains the cryptic distinction between the "the lang attribute in the XML namespace" and "the xml:lang attribute in no namespace" in the HTML Standard:
https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes

However use of `lang` vs `xml:lang` on SVG elements in HTML *does not depend on the HTTP Content-Type* because the SVG 2.0 spec always prioritises `xml:lang`. 
https://www.w3.org/TR/SVG2/struct.html#LangSpaceAttrs

So if you serve pages as `text\html` these two elements have different languages:

```
<p xml:lang='en'><!-- xml:lang ignored -->
<svg xml:lang='en'><!-- xml:lang sets language to English -->
```

The whole sorry history of `lang` vs `xml:lang` along with some test cases are here:
https://github.com/act-rules/act-rules.github.io/issues/668#issuecomment-517673702

The CSS :lang() selector follows the differences between SVG/HTML described above, but I'm pretty sure that at least one AT doesn't follow the spec.

**Comment by dd8** [comment]
Here is Common Crawl data to back up the assumption that the 'application/xhtml+xml' Content-Type (and hence pages parsed as XHTML) is rare: 

| Content-Type  | % of pages |
| ------------- | ------------- |
| text/html  | 97.61%  |
| application/xhtml+xml  | 0.038%  |
| application/xml  | 0.031%  |
| text/xml  | 0.084%  |

https://commoncrawl.github.io/cc-crawl-statistics/plots/mimetypes
