### ISSUE TITLE
Criterion 4.1.1 Parsing - Ambiguity regarding specification-conform nesting of HTML elements

### ISSUE THREAD

**Issue by MichaelKetting** [w3c/wcag#761]
There appears to be a mismatch (or loophole) in the sufficient techniques for 4.1.1 Parsing regarding the correct nesting of elements:

Success Criterion 4.1.1 Parsing states:
> In content implemented using markup languages, elements have complete start and end tags, **_elements are nested according to their specifications_**, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features. 

Sufficient Technique 4 states:
> Ensuring that Web pages can be parsed by using **_one of the following techniques_**:
> - H74: Ensuring that opening and closing tags are used according to specification (HTML) AND H93: Ensuring that id attributes are unique on a Web page (HTML) AND H94: Ensuring that elements do not contain duplicate attributes (HTML)
> - H75: Ensuring that Web pages are well-formed (HTML) 

To compound this, we have https://www.w3.org/TR/2014/NOTE-UNDERSTANDING-WCAG20-20140916/understanding-techniques.html#understanding-techniques
>  Sufficient techniques are reliable ways to meet the success criteria.
> From an author's perspective: If you use the sufficient techniques for a given criterion correctly and it is accessibility-supported for your users, you can be confident that you met the success criterion.

This means that so long as we don't violate the correct nesting of the opening and closing tags, it is perfectly valid to nest a TABLE inside a SPAN element, for instance. This appears to run completely contrary to to the success criterion itself, which requires specification conform nesting and will be flags when using an HTML validator.

Is this an oversight in the specifications or am I interpreting the standard too strict and it is actually perfectly acceptable to use non-HTML conform nesting of elements and still satisfy 4.1.1?

Note that in https://www.w3.org/TR/WCAG20-TECHS/H74.html, there could be a solution to this, depending on how you interpret the text for the procedure n H74:
> Procedure
> 1. Check that there are closing tags for all elements with required closing tags.
> 2. Check that there are no closing tags for all elements where closing tags are forbidden.
> 3. Check that opening and closing tags for all elements are correctly nested. 
>
> Expected Results
> Steps 1, 2, and 3 are true.

Step 3 states that the opening and closing tags must be correctly nested, but the entire technique H74 reads as if it applies only to correctly opening and closing HTML elements and does not refer to the nesting of different element types.

So, to my precise question: Does the WCAG specification actually require a web-page to use specification-conform nesting of HTML elements in order to satisfy SC 4.1.1?

**Comment by awkawk** [comment]
My short answer to your precise question is no. 4.1.1 doesn't require validation, although if a page validates it will pass 4.1.1.

**Comment by MichaelKetting** [comment]
Thank you, @awkawk for that quick response.

**Comment by cstrobbe** [comment]
The *intended meaning* of "elements are nested according to their specifications" is "elements are nested according to the syntactical rules of their specifications". (See, for example, my [comment from 8 November](https://github.com/w3c/wcag/issues/2525#issuecomment-1306919930))
This has been extensively discussed in [issue #2525: Proposal to Rephrase Success Criterion 4.1.1](https://github.com/w3c/wcag/issues/2525), which was marked as ["Ready for survey" yesterday](https://github.com/w3c/wcag/issues/2525#event-7775531547). The Working Group will hopefully vote on that issue in the next few weeks.
