### ISSUE TITLE
typo in 'understanding success criteria 2.4.5' 

### ISSUE THREAD

**Issue by electronicwoft** [w3c/wcag#785]
Second bullet under benefits. "Individuals with cognitive limitations may find it easier to use search features than to use a hierarchical navigation scheme that be difficult to understand." 'that be difficult' should be 'that might be difficult' or 'that is difficult'?

**Comment by alastc** [comment]
Thanks, I've updated that to:

> Individuals with cognitive limitations may find it easier to use search features than to use a hierarchical navigation scheme that is difficult to understand.
