### ISSUE TITLE
Typo in Understanding SC 1.4.11

### ISSUE THREAD

**Issue by honoka-h** [w3c/wcag#789]
Alt for image under "Text input (minimal)":

```html
<img src="img/text-input-minimal.png" alt="A label with a text input shown by a bottom border and feint grey background." />
```

Should this be "faint" instead of "feint"?

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag/commit/dde9b73df29c026fc8579c40f3b7e2799cf9d92c
