### ISSUE TITLE
Success Criterion reference error

### ISSUE THREAD

**Issue by cmunch** [w3c/wcag#801]
In the "/understanding/20/contrast-minimum.html" file, line 113, there´s a Success Criterion reference error:

`<a href="contrast-enhanced">1.4.1: Contrast (Enhanced)</a>`

The above line should be:

`<a href="contrast-enhanced">1.4.6: Contrast (Enhanced)</a>`

Replace **1.4.1** with **1.4.6**.

**Comment by awkawk** [comment]
Thanks @cmunch!
