### ISSUE TITLE
typo in understanding not text contrast

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#802]
CURRENT
 Also, the visual effects which are implemented **to** order to indicate state, such as whether a component is selected or focused, 

FIXED
 Also, the visual effects which are implemented **in** order to indicate state, such as whether a component is selected or focused,

**Comment by awkawk** [comment]
Can't locate. Can you provide a line number?

**Comment by DavidMacDonald** [comment]
It's been rewritten. I was going off of 
https://github.com/w3c/wcag21/pull/943/files
OBE
