### ISSUE TITLE
Typo Non text contrast ... understanding

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#803]
> If a button with text also has a colored border, since the border does not provide the only indication there is no contrast requirement beyond the text contrast (1.4.3 Contrast (Minimum)). 

Drop the second closing bracket.... this is in the latest version.
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html

**Comment by awkawk** [comment]
Isn't that second closing paren needed to close the opening paren?

**Comment by DavidMacDonald** [comment]
There are two closing parens and 1 opening
(1.4.3 Contrast (Minimum))

**Comment by DavidMacDonald** [comment]
OHHHH !
