### ISSUE TITLE
We need a position natural language inputs

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#824]
Examples
```I have been married for <input aria-label="number of years married" ...> years.```
VS
```<label>I have been married for <input  ...> years.</label>```

There are a few things I think we need to discuss in light of Success Criterion 2.5.3 Label in Name.

1. With these, using the onscreen label can be confusing, but doing a custom label can easily break 2.5.3.
2. Dragon completely ignores the aria-label, so saying "click foo" when this is on the page does nothing ```<input aria-label="foo">``` but the same voice command with this on the page will move the focus to the "foo" input. ```<label>foo <input ...></label>```. 
So Dragon doesn't honour the ACCNAME coming from the Accessibility Tree, it looks at the label element in the DOM instead.
3. On the other hand "Window Speech Recognition" will honour the ACCNAME and do it right.
4. Should custom labels be OK when there are inline natural language forms?
5. Should we forbid inline forms?

**Comment by patrickhlauke** [comment]
what are natural language inputs? freeform text fields?

**Comment by patrickhlauke** [comment]
or is it more the "mad libs" style inputs that are part of an overall sentence (where the sentence itself, and the input's position therein, end up giving the context)?

**Comment by DavidMacDonald** [comment]
@patrickhlauke 
> or is it more the "mad libs" style inputs that are part of an overall sentence (where the sentence itself, and the input's position therein, end up giving the context)?

Yes, that's it

**Comment by alastc** [comment]
Hmm, I would have gone for something like:
`I have been <span id="years-desc">married</span> for <input ... id="years" aria-describedby="years-desc"> <label for="years">years</label>.`

And make the label (years) bold. Would that work with dragon?

Not ideal, but the is generally a suitable label in the text, otherwise no-one knows what it's for.

**Comment by mraccess77** [comment]
iOS 13's new "show names" feature for voice support shows users the accessible name associated with a control which would help users in this situation learn what name is actually used to label something.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
