### ISSUE TITLE
How does 2.5.3 Label in Name apply to cards

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#829]
Is there a situation where a UI control's accessible name might need to summarize content rather than the text within it?

There is a common pattern of a card that may contain image, heading, and body text.  The text can be longer.  The whole card is often clickable with sometimes just the body text, heading, or and image clickable.

Having the whole card actionable makes sense as users expect that.  In this situation it would make sense to have an aria-label that was trimmed down summarizing the card as the text can be very verbose to users of screen readers and verbose text could cause speech recognition users to say one of the words in the text.

However, 2.5.3 requires the accessible name include the visible text which means that all of the text needs to be included making the card link very verbose.

While the best approach is to just make the heading as a link and perhaps reference the body text via aria-describedby (https://inclusive-components.design/cards/) -- this requires adding clickable and dealing with some messy code to address text selection in order to make the whole card clickable.

**Comment by patrickhlauke** [comment]
was there any resolution/discussion/brainstorming around this? sounds like an interesting topic...

**Comment by mraccess77** [comment]
I closed the issue because I figured people would say making the whole card a link is an anti-pattern and that the solution from Heydon is the best to link the heading and then use a redundant click hanlder on the card.  I think this issue may occur other places as well but couldn't think of other good cases at the moment and didn't want to take up the groups time to right now.
