### ISSUE TITLE
The description of the number of figures is incorrect (Understanding SC 1.4. 12)

### ISSUE THREAD

**Issue by k-octopus** [w3c/wcag#831]
> Author Responsibility 

> The author requirement is both to not interfere with a user's ability to
override the author settings, and to ensure that content thus modified does
not break content in the manners shown in figures 1 through 4 in Effects of
Not Allowing for Spacing Override.

It is written that there are four figures, but actually there are only three
figures.

I'm not good at English, so I'm sorry if my interpretation is wrong.

**Comment by alastc** [comment]
Thanks, we hadn't spotted that when removing one of the images. It will go live end of next week.
