### ISSUE TITLE
Draft of new 2.2 SC "Dragging"

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#835]
I have drafted a new SC for 2.2 that should plug the gap that was caused by narrowing the scope of 2.5.1 Pointer Gestures via a definition of 'path-based gesture' that excludes free-form dragging (and on a narrow interpretation, also what I'd call _constrained dragging_ (like sliders) that does not strictly require an intitial directionality of movement.
Here is the doc, which we have reviewed and modified in today's MATF call:
https://docs.google.com/document/d/1LaVX-RTaLQL0tN4G3NhOTlmj16swt0VzC7ssaAjqIwg/edit

**Comment by alastc** [comment]
Closing as we have a PR for this soon.
