### ISSUE TITLE
Investigate issues with CSS generated content

### ISSUE THREAD

**Issue by marcjohlic** [w3c/wcag#84]
Content injection via pseudo-elements ::before & ::after and the 'content' property:

* Authors can use the "content" property and pseudo-elements ::before and ::after to inject content into the page that could be missed by AT
* Potential impacts to WCAG SC 1.3.2 Meaningful Sequence and 2.4.3 Focus Order?
* Now dealing w/ CSSOM (CSS Object Model) vs DOM that we're used to dealing with
* Should meaningful / important content (text / images) be banned from ::before and ::after?  (keep it presentational?)
* What is the AT stance on generated content these days?  (JAWS, NVDA, VO etc)  
  * I believe VO reads it, but are other vendors working to include it?
* Do we need Techniques - or should it (for now?) always be a Failure using generated content for important information?
  * Techniques could just be around unimportant information (glyphs, icons, supplemental info etc)

Existing Techniques and Failures in this area:
* [C9] (http://www.w3.org/WAI/GL/2014/WD-WCAG20-TECHS-20140902/C9) covers CSS for decorative content
* [C6] (http://www.w3.org/WAI/GL/2014/WD-WCAG20-TECHS-20140902/C6) covers positioning content based on structural markup
* [C27] (http://www.w3.org/WAI/GL/2014/WD-WCAG20-TECHS-20140902/C27) covers DOM order matching visual order
* [F1] (http://www.w3.org/WAI/GL/2014/WD-WCAG20-TECHS-20140902/F1) covers changing the meaning by positioning via CSS
* [F3] (http://www.w3.org/WAI/GL/2014/WD-WCAG20-TECHS-20140902/F3) covers using CSS to include important images
* [F44] (http://www.w3.org/WAI/GL/2014/WD-WCAG20-TECHS-20140902/F44) covers using tabindex that does not preserve meaning - maybe a copy of this for nav-index?
* [F87] (http://www.w3.org/TR/WCAG20-TECHS/F87.html) Failure of Success Criterion 1.3.1 due to inserting non-decorative content by using :before and :after pseudo-elements and the 'content' property in CSS

Might just need some edits to these existing Techniques and Failures with language that is more specific to CSS generated content, nav-index, and 'order'.

Any other thoughts or suggestions on this topic?

**Comment by DavidMacDonald** [comment]
I have a test page here:
http://davidmacd.com/blog/inserting-content-with-css-accessibility.html
Leonie also has some information
http://tink.uk/accessibility-support-for-css-generated-content/

**Comment by joshueoconnor** [comment]
Great thanks David.

**Comment by joshueoconnor** [comment]
Marc going to follow up with that early 2016

**Comment by joshueoconnor** [comment]
@marcjohlic  Any update on this puppy?

**Comment by marcjohlic** [comment]
Suggest this be marked as Deferred  and closed (per the [Issues process] (https://www.w3.org/WAI/GL/wiki/Handling_Issues)) until such time as there are CSS SME resources available in the group that can investigate this issue further.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
