### ISSUE TITLE
Anchor link is not working due to incorrect link URL (Understanding SC 1.4.12) 

### ISSUE THREAD

**Issue by k-octopus** [w3c/wcag#847]
> Research

> As previously discussed, the ability to read text with adjusted spacing is a user responsibility. This is true no matter the language. 

The "user responsibility" link is not working.

■Link source
```
<a href="#userresp">user responsibility</a>
```

■Linked source
```
<section id="user-responsibility">
```

**Comment by awkawk** [comment]
@michael-n-cooper is this a duplicate?

**Comment by alastc** [comment]
No sign of where the link was supposed to go to, so I've removed that.
