### ISSUE TITLE
gh-pages branch contains two "understanding" folders with different character casing

### ISSUE THREAD

**Issue by EricDunsworth** [w3c/wcag#850]
I tried cloning the gh-pages branch earlier and ended up with a polluted working directory in Windows.

The following files showed up as modified - even after I tried reverting them:
* Understanding/intro.html
* Understanding/understanding-techniques.html
* understanding/conformance.html

This seems to be the result of Windows treating its file system as case-insensitive and therefore being unable to cope with the that branch's file structure.

The "gh-pages" branch currently contains "[understanding](https://github.com/w3c/wcag/tree/gh-pages/understanding)" and "[Understanding](https://github.com/w3c/wcag/tree/gh-pages/Understanding)" folders. "[Understanding](https://github.com/w3c/wcag/tree/gh-pages/Understanding)" seems to contain broken/outdated versions of the aforementioned pages and some redundant images.

@nschonni Could the "Understanding" folder be removed from the gh-pages branch?

**Comment by nschonni** [comment]
That would probably make sense. It looks like there is also a weird "WCAG20" one too. Could always send a PR to delete the folder and see if @michael-n-cooper will land it.
AFAIK, the gh-pages branch cleans itself on the build, but the odd capitalization probably isn't something that is getting cleaned by the scripts right now.

**Comment by EricDunsworth** [comment]
I was hoping to send in a PR instead of opening this issue, but can't since I'm on Windows 7 lol. Was gonna give Gitpod a shot but completely lost network access to it. Didn't want to use GitHub's web interface either since deleting directories in it would be a very painful experience (would have to individually delete every file one-by-one in separate commits).

**Comment by awkawk** [comment]
@michael-n-cooper is out this week but we will ask him to take a look when he returns.

**Comment by alastc** [comment]
The current build process doesn't use gh-pages as an end-point at all (AFAIK), I think it's rendendent. 

@EricDunsworth what was the aim?

**Comment by EricDunsworth** [comment]
@alastc IIRC my aim was to look for samples of strange link text patterns in generated files while prepping #851.

**Comment by alastc** [comment]
In which case the likely resolution would be to delete or clean up that branch, but I'll have to leave to @michael-n-cooper in case it is used for something.

**Comment by EricDunsworth** [comment]
@alastc Isn't gh-pages needed for https://w3c.github.io/wcag/ though? I can see some files in it that were last modified as recently as a few days ago. Or are you implying that https://w3c.github.io/wcag/ is no longer useful?

**Comment by alastc** [comment]
Ah, maybe it is, but I'm not sure on the process. Sorry, I'll have to leave this to Michael.

**Comment by fstrr** [comment]
Closing this due to age. If it's still an issue, please re-open.

**Comment by patrickhlauke** [comment]
the whole `gh-pages` branch looks messy and cryptic... but I guess we can leave it up to @iadawn to work out if there's a technical reason for this, or if it can be cleaned up a bit https://github.com/w3c/wcag/tree/gh-pages

**Comment by EricDunsworth** [comment]
@fstrr IMO this should probably be reopened. What's described in the OP and https://github.com/w3c/wcag/issues/850#issuecomment-519581648 are still relevant to this day.

The ``gh-pages`` branch still currently contains two top-level "**U**nderstanding" and "**u**nderstanding" folders. Former was last modified ~6 years ago and latter ~2 weeks ago. Ditto for the "WCAG20" and "wcag20" folders.

**Comment by patrickhlauke** [comment]
sure, but the `gh-pages` folder is mostly a dumping ground / temporary location before things get actually properly published/republished. they're not the actual end product here. while I agree it should be tidied, I'll leave that up to @iadawn to work out if it's worth doing or not
