### ISSUE TITLE
UA support for this technique seems to be non-existent 

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#86]
https://www.w3.org/2006/02/lc-comments-tracker/35422/NOTE-WCAG20-TECHS-20140911/2997

I was doing some research on this technique and the UA notes:
http://www.w3.org/WAI/WCAG20/Techniques/ua-notes/html#H69

Opera hasn't supported keyboard heading navigation since switching from Presto to Blink in July 2013
http://forums.opera.com/discussion/1834402/navigation-over-links/p1

The Vimium extension they mention as a replacement doesn't appear to
support heading navigation either 

The currently documented Opera keyboard shortcuts now look identical to other browsers:
http://help.opera.com/opera/Windows/1387/en/fasterBrowsing.html#keyboard

The Firefox landmark extension from TPG has been mentioned as an alternative, but this doesn't support heading navigation either. I've checked both the source code and and installed on a clean VM
https://github.com/matatk/landmarks

The other alternatives mentioned in the H69 UA notes either no longer work on current browsers  or don't have working download links.

Conclusion: there's no longer UA support for this technique

Best Regards
Mark

Proposed Change:
Given there appears to be no current UA support for this technique for keyboard users, should it be retired?

If someone does find UA support for it, then the UA notes should be updated accordingly.

**Comment by DavidMacDonald** [comment]
This is a tough one. We've had H69 as a sufficient technique for 2.4.1 for 6 years and have never had a complaint from a sighted keyboard user, nor has there been any buzz on the blogs, or complaints that I'm aware of.
It is true that there is not a plugin that I know of that can jump headings. 
I think given the long standing precedence, the lack of opposition, and the gravity of changing a requirement of WCAG by removing a sufficient technique, we should respond that we will leave it, unless we hear of some complaints by sighted keyboard users.

**Comment by MakotoUeki** [comment]
In Japan, we've done the same kind of discussion and user research on a skip link. we couldn't find any complaints from sighted keyboard users about lack of a skip link or heading markup. We found that they were using a mouse key or a mouse emulator when browsing/navigating web pages and haven't had a need for a skip link nor heading markup. So we reached a conclusion that skip link is not required to meet SC 2.4.1 and heading markup (role="main" or <main> in the future) would be sufficient for screen reader users. But it doesn't mean that we discourage providing a skip link. 

I'm wondering if a sighted keyboard user really needs a mechanism to bypass blocks of content that SC 2.4.1 requires. If so, why main stream browsers haven't provided such navigation features for a sighted keyboard users like Opera used to do.

**Comment by DavidMacDonald** [comment]
Proposed response:
We've had H69 as a sufficient technique for 2.4.1 for 6 years and have never had a complaint from a sighted keyboard user, nor has there been any buzz on the blogs, or complaints that we are aware of.
It is true that there is not a plugin or browser that we know of that can jump headings. This could be easily accomplished by amending the current Landmarks plugin. So there is not a barrier to this being accomplished. Given the long standing precedence, the lack of opposition to the status quo from end users, and the gravity of changing a requirement of WCAG by removing a sufficient technique, we will leave H69 as a sufficient technique.

**Comment by Ryladog** [comment]
+1

**Comment by lauracarlson** [comment]
The 2014 WebAIM Screen Reader Survey results may also be relevant. One question read: "When trying to find information on a lengthy web page, which of the following are you most likely to do first?"

"Reliance on headings as the predominant mechanism for finding page information continues to increase - 50.8% in October 2009, 60.8% in May 2012, and 65.6% in January 2014. While 43.8% of respondents indicate that they always or often use landmarks when they are present, only 2.8% use this method for finding information on a lengthy web page. Those with advanced screen reader proficiency are more likely to use headings (71% use headings) than those with beginner proficiency (43% use headings)."

Source:
[2014 WebAIM Screen Reader Survey](http://webaim.org/projects/screenreadersurvey5/#finding)

**Comment by marcjohlic** [comment]
+1 on keeping H69 around.  Also, I was trying out [SkipTo] (http://paypal.github.io/skipto/) yesterday and it actually works really well!  I tried both the Greasemonkey script (in FF) and the bookmarklet in Safari - and had some really good results.  

For anyone not familiar, SkipTo provides keyboard navigation to headings, landmarks, section elements and others.  http://paypal.github.io/skipto/

**Comment by Ryladog** [comment]
+1 to keeping. 

 

 

 

* katie *

 

Katie Haritos-Shea 
Senior Accessibility SME (WCAG/Section 508/ADA/AODA)

 

Cell: 703-371-5545 |  <mailto:ryladog@gmail.com> ryladog@gmail.com | Oakton, VA |  <http://www.linkedin.com/in/katieharitosshea/> LinkedIn Profile | Office: 703-371-5545

**Comment by Ryladog** [comment]
Is SkipTo a plugin for developers (as opposed to browser plugin) to use in
a site? If so, how does this help H69 - using headings won't be enough
without adding SkipTo functionality, so H69 in its present form wouldn't be
satisfied

**Comment by awkawk** [comment]
I tried the Greasemonkey user script also and found that I could still navigate by headings.  It seems that with the review by Marc and others that this is confirmed so we can say that while user agent support is not as widespread or available by default in the way that we wish, it is incorrect to say that user agent support doesn't exist. 

I'll put this on a survey for next week with this as the proposed response:

Thank you for the comment.  The Working Group finds that while it is accurate that current versions of Opera no longer support keyboard navigation by heading elements, we have found that the SkipTo plugin (http://paypal.github.io/skipto/) and Greasemonkey user script for heading navigation provided by Gez Lemon (http://juicystudio.com/article/heading-navigation-greasemonkey-user-script.php) both provide the ability to navigate by headings.

As a result, we are electing to keep technique H69, and will update the user agent notes per your suggestion.

**Comment by marcjohlic** [comment]
It's code that a developer can include on their site - or (pertaining to
H69) - a user could add either the Greasemonkey plugin and script to their
own browser (or use the bookmarklet) to enable SkipTo's functionality on
any website with no developer involvement.

On Wed, May 6, 2015 at 8:06 AM, Katie Haritos-Shea <notifications@github.com

**Comment by DavidMacDonald** [comment]
Thank you for the comment. The Working Group finds that while it is accurate that current versions of Opera no longer support keyboard navigation by heading elements, we have found that the SkipTo plugin (http://paypal.github.io/skipto/) and Greasemonkey user script for heading navigation provided by Gez Lemon (http://juicystudio.com/article/heading-navigation-greasemonkey-user-script.php) both provide the ability to navigate by headings. 

As a result, and in consideration that screen reader users use heading navigation as a core strategy, and the long standing precedence of this technique, we are electing to keep technique H69, and will update the user agent notes per your suggestion.

**Comment by DavidMacDonald** [comment]
As a result, and in consideration that screen reader users use heading navigation as a core strategy, we are electing to keep technique H69, and will update the user agent notes per your suggestion.

**Comment by awkawk** [comment]
Final response amended: 
Thank you for the comment. The Working Group finds that while it is accurate that current versions of Opera no longer support keyboard navigation by heading elements, we have found that the SkipTo plugin (http://paypal.github.io/skipto/) implemented as a bookmarklet and Greasemonkey user script for heading navigation provided by Gez Lemon (http://juicystudio.com/article/heading-navigation-greasemonkey-user-script.php) both provide the ability to navigate by headings.

As a result, we are electing to keep technique H69, and will update the user agent notes per your suggestion.

**Comment by moekraft** [comment]
Also as stated in the User Agent notes for H69, "Most screen readers provide navigation via headings". If Opera no longer supports keyboard navigation by heading, I agree we should remove that statement. However, the technique is essential to the programmatic access to the structure of the page so that assistive technologies and other programs, such as the SkipTo plugin, can provide keyboard access to the headings.
