### ISSUE TITLE
Need to clarify process for working with GitHub for WCAG

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#87]

**Comment by awkawk** [comment]
Incorporate https://help.github.com/articles/syncing-a-fork/ information

**Comment by joshueoconnor** [comment]
We have a need for this, anyone else who wants to work with AWK - please do.

**Comment by joshueoconnor** [comment]
Leonie Watson has created an IRC channel #screenreaders on the W3C server, as a
place where screen reader users can go to ask questions about scribing, participating in calls and meetings, and using tools like Github.

**Comment by awkawk** [comment]
Closing as this was my idea and we haven't done it in almost 3 years so I retract it!
