### ISSUE TITLE
In Understanding 3.3.2, a link to 2.4.6 Headings and Labels is broken

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag#874]
The problem is in https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions

The following link targets the current page (Understanding 3.3.2) instead of the related page (Understanding 2.4.6).

`While this Success Criterion requires that controls and inputs have labels, whether
               or not
               these labels are sufficiently clear or descriptive is covered separately by
               <a href="labels-or-instructions">2.4.6: Headings and Labels</a>.`

**Comment by alastc** [comment]
Thanks, I've updated that in master, you should see it update next week.
