### ISSUE TITLE
Invalid Links in Key Terms

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#883]
https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded.html#key-terms
https://w3c.github.io/wcag/understanding/captions-prerecorded.html#key-terms

All links in the "Key Terms" section refer to nonexistent link destinations on the same page. I suspect that the problem occurs on all the Understanding pages. I checked some understanding pages: the the problem occurs with everyone. The links should refer to the terms in Chapter 6 https://www.w3.org/TR/WCAG21/#glossary.

**Comment by michael-n-cooper** [comment]
Fixed by https://github.com/w3c/wcag/commit/adeba524d912322ed91f825250fa984fc1450035
