### ISSUE TITLE
Must the tooltip of icons match the accessible name? (for "Label in Name", SC 2.5.3)

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#891]
Step I of https://www.w3.org/TR/accname-1.1/ states that tooltips should be used as accessible names unless there is another label. Does this mean for 2.5.3 that tooltip and accessible name must match? Especially if there is only a tooltip as visible label.

With an icon, a user of speech input software will trust that the accessible name matches the title attribute or a custom-made tooltip.

If that's how many people see it, please include a note about tooltips in the Understanding document (https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html).

**Comment by patrickhlauke** [comment]
> Step I of https://www.w3.org/TR/accname-1.1/ states that tooltips should be used as accessible names unless there is another label. Does this mean for 2.5.3 that tooltip and accessible name must match? Especially if there is only a tooltip as visible label.

if the only thing giving the element an accessible name is a tooltip attribute (i.e. `title`), then the accessible name will already be that, so 2.5.3 will be fulfilled.

So i'm assuming your actual question is: if a control has no other visible label than a tooltip (either a `title` or custom tooltip), does the accessible name have to contain that visible tooltip text? and the answer, i would say, is yes (note it's not "matching" ... the accessible name can contain far more text, but the visible label text needs to be contained/present in the accessible name.

generally, i'd say it's not possible to add notes/examples for every possible situation in the understanding document. this one could make sense to be added, as it requires a small leap in interpretation.

**Comment by jake-abma** [comment]
If the tooltip is generated by a title element then 2.5.3 is not applicable.

The title attribution is not a label according to the definition for WCAG as it's **not** presented to all users, for instance keyboard only users, see  Note:

> NOTE
> A label is presented to **all users** whereas the name may be hidden and only exposed by assistive technology. In many (but not all) cases the name and the label are the same.

https://www.w3.org/TR/WCAG21/#dfn-labels

The title is a name though

**Comment by patrickhlauke** [comment]
then that's a pretty silly shortcoming, i'd say (pretty sure that when some of these SCs are written, not everybody involved is aware of the full ramifications of some of these definitions/exceptions).

**Comment by patrickhlauke** [comment]
also, reading that definition of label, i'm not sold on your take that because a tooltip/title isn't shown to ALL users, it stops being a label (as it's not hidden and ONLY exposed by assistive technology)

**Comment by jake-abma** [comment]
that is the whole issue with labels , isn't it? Otherwise we would probably not have the title discussion at all. We would love the attribute and promote it till the day we go and enjoy our pensions... :-)

**Comment by jake-abma** [comment]
> also, reading that definition of label, i'm not sold on your take that because a tooltip/title isn't shown to ALL users

Seems very clear to me though, it's the only difference, ALL users OR a name, why your perspective?

**Comment by patrickhlauke** [comment]
you omitted the "and ONLY exposed by assistive technology" there... (of course, tooltip/title things fall squarely between the fake dychotomy of that definition

**Comment by jake-abma** [comment]
haha, and you omitted the may be part which serves as an example only: "...may be hidden and only exposed by assistive technology..."

**Comment by patrickhlauke** [comment]
and, in the wider sense, this SC is about speech users and them getting an idea of what to say to focus/trigger a control. so you'd contend that from the point of this SC

```
<button title="CHICKEN" aria-label="PORK"> <svg ...> ... </svg> </button>
```

would be fine, since it's exempted and there's no visible label?

**Comment by jake-abma** [comment]
what is clear though is that in this case at least 2 persons have 2 (understandable) views of the definition.

For me it has always been ALL or nothing, simply because of the definition. would be great to settle the examples and intent so we're on 1 straight line!

**Comment by jake-abma** [comment]
ow, great example Patrick, indeed, not applicable

**Comment by jake-abma** [comment]
In your last example, someone ONLY using dictation will not be able to use the proper ACC name, only the numbers generated by the specific dictation software for buttons OR use dictation 'grids'

**Comment by jake-abma** [comment]
and please note the following sentence in intent: 

> Note that where a visible text label does not exist for a component, this Success Criterion does not apply to that component.

**Comment by patrickhlauke** [comment]
well that's the thing...it's visible for some users (mouse users). so a user that does both mouse and speech will have the same issue with this...

**Comment by jake-abma** [comment]
hovering over the UIC with mouse and then dictate the UIC? haha, interesting use case...

but he, all comes down to our lovely 'title' friend, want to do a general discussion on what we do with it? For me it's clear though (at the moment), a "grey area name" not label. And it's always the same with "The Greys", you believe it or not... :-)

**Comment by patrickhlauke** [comment]
well, not just `title` friend. any situation similar to this (could have been implemented using CSS, or JS, or whatever). same difference.

**Comment by jake-abma** [comment]
correct, same, not applicable also, if you only see something on CSS widget 'hover' and will not be perceivable by all. as soon as you add keyboard focus, pop, applicable... don't shoot the messenger

**Comment by patrickhlauke** [comment]
just clarifying that the problem goes beyond `title`, and related to any type of such hover-based solutions. 

so, widening the question: if the tooltip appeared on hover and keyboard focus, would it be a clearer case of 2.5.3 applying? is the contention here about "ALL" users?

**Comment by jake-abma** [comment]
See correction...

**Comment by patrickhlauke** [comment]
dictation only users may also go to previous/next control via voice. would that focus things, and would that then result in "on focus and hover" tooltips to show, giving them a visible "label" at that point, that they may then assume next time they want to trigger that control, they can just speak the text they saw?

**Comment by jake-abma** [comment]
Let's start with the title attribute first, my simple statement is that it's NOT a label. Would like to see this one clear from within the group what we think / support in this case. See from there...

**Comment by JAWS-test** [comment]
The title attribute is visible for keyboard user, e.g. with IE. One could say: all other browsers have a bug...

**Comment by jake-abma** [comment]
That's not how it works, we will be completely lost soon if we go that way, they can delete the tooltip any moment, or add it, or show aria-label soon, or not, or only chrome or... 

my simple statement is that it's NOT a label

**Comment by patrickhlauke** [comment]
> That's not how it works, we will be completely lost soon if we go that way

agree on this as well.

> my simple statement is that the 'title' attribute is NOT a label

yes, that would be a good first clarification. to me then, this also brings a second question closer to the original question: did authors of the normative SC here really think through that they meant "label" in this sense, and that they explicitly didn't intend other forms like tooltips. (i only ask because in the discussions around the SC at the time of its creation, i don't recall any explicit talk about this sort of scenario. and from my own experience, sometimes when wordsmithing the normative language you don't always think through all implications of a particular choice of words - not to move too much into a tangent, but when we devised the whole "pointer gestures" wording, I proposed the use of "path-based", and I intended it to mean any kind of movement involving a gesture...not working through the fact that "path-based" is normatively defined as an actual specific path of 3 points or more, which then led us to that whole discussion...)

**Comment by jake-abma** [comment]
@patrickhlauke without going into a discussion again, does it still matter right now? The SC is there already and also the terms... but also have been there when discussing, and pop up text and only in certain circumstances (hover) and not others, was not the aim of the label in name as I recall.

**Comment by patrickhlauke** [comment]
> was not the aim of the label in name as I recall

it's more that i don't recall that scenario being explicitly brought up when deciding on the use of "label" in the normative wording. i mean the "does it matter now" is probably academic thanks to the "once it's been released, it's set in stone" approach... but it would be good to tease this out for future reference if nothing else, and to see if we need an additional SC to cover this particular scenario/gap.

**Comment by JAWS-test** [comment]
https://www.w3.org/TR/WCAG21/#dfn-labels

> A label is presented to all users whereas the name may be hidden and only exposed by assistive technology. In many (but not all) cases the name and the label are the same. 

This definition is, of course, wrong. If the label were actually presented to all users, SC 2.5.3 would not exist because there would be no difference between label (which is presented only to sighted users  in the unchanged standard view of the page) and name (which is presented to users of assistive technology). Furthermore, there are still sighted users who do not use the standard view and see neither label nor name, but something third, which is unfortunately not covered by SC 2.5.3 at the moment (e.g. visually impaired users who use HCM, userstyles or no CSS).

**Comment by JAWS-test** [comment]
If 2.5.3 excludes tooltips (title and custom made), I suggest the following:

1. describe this in the Understanding
2. change this in WCAG 3.0 so that tooltips are included, because tooltips also belong to the label and are the only labels for icons

**Comment by detlevhfischer** [comment]
I would have thought 2.5.3 applies to always visible, visually associated (not necessarily programmatically associated) labels. If the use case is speech input users then it is unlikely that they will mouse over or to tab through elements to discover visible names before they speak the name.

**Comment by JAWS-test** [comment]
> I would have thought 2.5.3 applies to always visible, visually associated (not necessarily programmatically associated) labels. If the use case is speech input users then it is unlikely that they will mouse over or to tab through elements to discover visible names before they speak the name

I don't think so for two reasons:
* "Benefits: ... Text-to-speech users will have a better experience because the labels that they hear match the visible text labels that they see on the screen" (https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#benefits)
* As a keyboard user you may use the keyboard input device and thus know the labels in the tooltips. If you don't have a keyboard on your mobile device, you would like to switch to speech input and want to use the tooltips as the name. As far as I know, this is exactly how it is often used.

**Comment by jake-abma** [comment]
> https://www.w3.org/TR/WCAG21/#dfn-labels
This definition is, of course, wrong. If the label were actually presented to all users, SC 2.5.3 would not exist because there would be no difference between label (which is presented only to sighted users in the unchanged standard view of the page) and name (which is presented to users of assistive technology). 

Wrong is a bit too harsh, "visually" might / should have been added probably, so it will become:

> A label is **"visually"** presented to all (to sighted users?!) users whereas the name may be hidden and only exposed by assistive technology. In many (but not all) cases the name and the label are the same.

**Comment by JAWS-test** [comment]
> Wrong is a bit too harsh, "visually" might / should have been added probably

A user who uses HCM is also a sighted user, but one who may not see the label.

**Comment by jake-abma** [comment]
That is a problem which should be fixed by the HCM makers, not WCAG. Or tweaked properly by the end user if he tweaks HCM.

**Comment by JAWS-test** [comment]
> That is a problem which should be fixed by the HCM makers, not WCAG

For the definition of label: It doesn't matter what's responsible. Fact: A label can be invisible for sighted users for dozens of reasons:
* Too little contrast between font and background color
* HCM
* User Styles
* No CSS
* Foreground color defined in CSS, but no background color
* Sunshine
* Zoom scales the label text, but not the element which has overflow:hidden
* etc.
And with the exception of sunshine, all of them have to do with accessibility.

**Comment by jake-abma** [comment]
True, but those circumstances are not a proper reason to change / not have a definition for 'label'.So I say 'yes' it does matter what's responsible.

- Too little contrast / Foreground color defined in CSS  but no background color / zoom, are covered by another SC

HCM, user styles, no CSS, Sunshine are NOT the responsibility of the author

**Comment by mraccess77** [comment]
For purposes of label under 3.3.2 it was determined that a label could be an icon or even another control such as a search button next to a search input field.  A label under 3.3.2 was not limited to text labels only.

**Comment by jake-abma** [comment]
@mraccess77 true, but the icon is not applicable for 2.5.3. (unless it contains image of text), a "search"text for the button serving as label for an input DOES, but that's not the question of this issue.:

> ...that include text or images of text...

**Comment by mraccess77** [comment]
Hi @jake-abma    I agree - I was just providing context around the definition

**Comment by mraccess77** [comment]
I agree that A tooltip is not a label.

**Comment by awkawk** [comment]
I would say that the label is presented to all users, but some users cannot perceive the label, which is why we have requirements to ensure programmatic access to the label text or alternative.

In a note in 2.5.3 we refer to tooltips as "additional content" - I don't believe that we at any point considered tooltips to be labels. In WCAG we regard the icon as a label, and in 2.5.3 we apply the additional requirement on labels that include text or images of text.
