### ISSUE TITLE
Structure of 1.4.11 Non-Text-Contrast Understanding inconsistent with existing formatting

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#903]
The techniques in the Non-Text Contrast Understanding document are grouped under H4 headings. This seems to be a departure from other Understanding docs.
Following existing conventions, these should likely be given Situations (A, B, C, etc) and organized that way. See 1.1.1 for an example, where the situations have the H4s and the technique groupings are simply bold.
Low priority, IMO, but thought I'd capture.

**Comment by alastc** [comment]
Closing having updated NTC in #931
