### ISSUE TITLE
Wrong link in Understanding 3.3.2

### ISSUE THREAD

**Issue by cmuncharaz** [w3c/wcag#906]
In the "Understanding Success Criterion 3.3.2: Labels or Instructions" document, the last paragraph of the Intent section is supposed to link with the "2.4.6: Headings and Labels" SC, however the link is reloading the 3.3.2 SC:

`<a href="labels-or-instructions">2.4.6: Headings and Labels</a>`

**Comment by alastc** [comment]
Thanks, I fixed that this morning, someone else had noticed it as well.
