### ISSUE TITLE
predicted amount change a status message? 4.1.3: Status Messages

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#911]
Feature: "predicted balance"

- For an application there's a predicted amount / balance visible at the bottom of the page / dialog / view and is "fixed, like a fixed footer / snackbar" (always present / visible).

- The "main area" consists of multiple transactions divided by headings with the date when the transactions will possibly take place (based on historic data).

- When scrolling the main content, the predicted balance will adjust in the "fixed footer".

- This is clearly visible present, but with a screen reader NO indication is present and the changing of the predicted balance is not mentioned.

- The only way with a screen reader to know about the predicted balance is to place the finger / mouse at the bottom of the screen in the fixed footer to hear what the new balance is.

- using swipe on mobile, or linear keyboard action will not be possible due to the fact you go through the list and 'other' predicted amount will change 'on the fly'

QUESTION:
- Is there a need to mention the updated predicted balance under 4.1.3.?
- the amount changes constantly when scrolling, so the live mentioning would get triggered a lot
- Is the scrolling an "action" in this case according to: 

> status message
> **change in content** that is not a change of context, and that **provides information to the user on** the success or **results of an action**, on the waiting state of an application, on the progress of a process, or on the existence of errors

**Comment by detlevhfischer** [comment]
When you say "scrolling" do you mean moving screen reader focus in browser / read mode through the list of transactions? I guess if the updated balance would be announced after each transaction (politely), it could be reasoably non-intrusive (you just press arrow down when you do nt want to hear it)?

**Comment by jake-abma** [comment]
Hi @detlevhfischer 
See screenshot, the 'bottom' / orange "Voorspeld saldo 5943,81 EURO" is fixed, the middle part, 30th oktober, 28th oktober etc. is a scrolling part predicting what amount you'll possibly have (based on past data) at that date.

When scrolling the "Voorspeld data ... EURO" changes constantly when new predicted write-down happens.

<img width="478" alt="Screenshot 2019-10-06 at 08 09 53" src="https://user-images.githubusercontent.com/6384002/66265133-65b59d80-e811-11e9-8f92-493c3fe45212.png">

**Comment by alastc** [comment]
I was confused why the balance would change as you scroll, but I guess it is showing something like your bank balance at that time?

E.g. When you have 30th Sept at the top, it is showing you the balance from 30th Sept? My Monzo bank account app does that.

Personally, I think the best approach would be to use something like `aria-describedby` attached to each day's balance, so it announces something like: "Gemeente Baan; -65,96; Oct 30th Balance 5.943,81 EUR" (I don't know the word for balance!)

That would meet 4.1.3, but would be less flaky & annoying than constant updates. Might be a good technique to do?

**Comment by jake-abma** [comment]
@alastc thanks, indeed the simple but powerful solution, `aria-describedby` it will be (or similar native description)

Cheers!
