### ISSUE TITLE
Broken link on documentation page

### ISSUE THREAD

**Issue by ginestra** [w3c/wcag#913]
I am not sure where the link for  for the text "WAI-ARIA Definition of Roles" should point to, but at the moment it returns a 404.

The page and section in question:
https://www.w3.org/TR/WCAG20-TECHS/ARIA4#ARIA4-description

The text:

> The objective of this technique is to define the role of an element using the role attribute with one of the non-abstract values defined in the **WAI-ARIA Definition of Roles**. The WAI-ARIA specification provides an informative description of each role, how it relates to other roles, and the states and properties for each role. When rich internet applications define new user interface widgets, exposing the roles enables users to understand the widget and how to interact with it.

**Comment by JAWS-test** [comment]
Correct link: https://www.w3.org/TR/wai-aria-1.1/#role_definitions

**Comment by alastc** [comment]
Indeed, we (ahem @michael-n-cooper) have a task to mark/redirect the old docs. It would certainly help with people googling things, as most of the WCAG 2.0 docs sitll come up first.

**Comment by alastc** [comment]
Closing as we can't update the old docs. The re-directs / canonical URLs is still an active thing though.
