### ISSUE TITLE
quickref: Sufficient Techniques & Failures not correct for 1.3.4 Orientation Level AA

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#927]
The Sufficient Techniques & Failures showing in the quickref are not corresponding to the Understanding doc.

https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=133#orientation
https://www.w3.org/WAI/WCAG21/Understanding/orientation.html#techniques

@yatil not sure if this is correct place... not even sure you're the person to mention this to... but you're my best guess :-)

**Comment by yatil** [comment]
@jake-abma Thanks for reporting this, I wonder if those techniques have been added recently. If so, I need to get the new data from @michael-n-cooper :-)

I also generated an issue in the quickref repo to keep track: https://github.com/w3c/wai-wcag-quickref/issues/201

**Comment by jake-abma** [comment]
This one is not fixed yet, asked if we can get a fix at w3c/wai-wcag-quickref#201

**Comment by yatil** [comment]
As written over there, as soon as the data JSON is generated by the WCAG repository, or someone takes the time to incorporate the changes by hand, it can be really easily updated in the Quickref. This is on the WG to prioritize.

**Comment by fstrr** [comment]
This looks to be completed.
