### ISSUE TITLE
Does the WebAim search input fails 1.4.11: Non-text Contrast?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#934]
Does the WebAim search input fails 1.4.11: Non-text Contrast?

https://webaim.org/

**Comment by patrickhlauke** [comment]
Interesting...i'd say in isolation it would, but because of the strong border around the label/input/submit button icon itself, it's still visually clear that there's "something" there.

**Comment by jake-abma** [comment]
@patrickhlauke a strong border for you maybe, but with a 2.3:1 also a fail... :-)

**Comment by patrickhlauke** [comment]
ah sorry, hadn't checked the actual values of that one. subjectively it seemed strong enough, yes. this is one where i'd say it's a nominal fail then (though feels borderline)

**Comment by jake-abma** [comment]
And also the blue border is not the "User Interface Components" also the examples show text with enough contrast next to the inputs, but again, according to the WCAG law...

**Comment by jake-abma** [comment]
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#active-user-interface-component-examples

**Comment by patrickhlauke** [comment]
understanding doc can't show examples of every possible variation, of course. while that blue border is not around just the input, it is around the overall component, and since the Search text and the submit icon both have sufficient contrast, and that blue border (if it were nudged to 3:1) makes it clear they're part of the overall control/widget, i'd argue that it hints at the fact there's an input there.

but yes, per law, probably a very mild failure.

**Comment by jake-abma** [comment]
agreed, this should do the trick as it makes sense, but for now, if I use WebAim as a reference (and I do) I also do have to admit that according to WCAG 2.1 they do not have a 100% score... 

So will / can we extend this to include such a case OR is this definitely a fail?

@jared-w-smith are you aware of this and will there be a possible update?

**Comment by jared-w-smith** [comment]
I'm not entirely sure why an accessibility issue on the WebAIM site would be filed as an issue against WCAG, but you're correct that this likely does not pass. I've implemented a fix.

>  I also do have to admit that according to WCAG 2.1 they do not have a 100% score...

If such a thing existed, we're certainly not there, but I appreciate any tips for improving our site's accessibility.

**Comment by patrickhlauke** [comment]
> I'm not entirely sure why an accessibility issue on the WebAIM site would be filed as an issue against WCAG

I took this more as a "here's an interesting example...do things like this pass/fail?" in the first instance

**Comment by jake-abma** [comment]
Indeed it's about the example and interpretation of 1.4.11.

I'm still wondering if, when you group content, like the blue line wrapping the search elements, is sufficient for 1.4.11. Especially since it is not the UIC.

@alastc what's your view on this?

**Comment by alastc** [comment]
Um, did I miss it? The input border is #777 with a white background, so just under 4.5:1.

> I'm not entirely sure why an accessibility issue on the WebAIM site would be filed as an issue against WCAG

I'd take that as a compliment, if WebAim does it then WCAG must be wrong ;-)

> I'm still wondering if, when you group content, like the blue line wrapping the search elements, is sufficient for 1.4.11. Especially since it is not the UIC.

In that case there is one input and two links:

- The input _and_ label are wrapped in the blue outline, the input has it's own border so the blue one is suplimentary.
- The links have context (position, clear text label & assoicated icons), so again I'd say the blue outline is stylistic and supplimentary.

I wouldn't put the blue outlines as in-scope of 1.411.

**Comment by jake-abma** [comment]
ok, but the border is #ccc NOT #777 ?

**Comment by jared-w-smith** [comment]
> Um, did I miss it? The input border is #777 with a white background, so just under 4.5:1.

The border was #ccc and is now #777. The #777 puts it well above the 3:1 threshold.

> I wouldn't put the blue outlines as in-scope of 1.411.

I wouldn't either because it does not define the input but a container for the input and other stuff.

**Comment by jake-abma** [comment]
Solved then... :-) thank you all

**Comment by patrickhlauke** [comment]
well, solved for this one particular case on the WebAIM site. but the underlying question was not solved as such... (@jake-abma should have taken a screenshot ;) )

**Comment by lauracarlson** [comment]
> should have taken a screenshot ;) )

Via the Wayback machine:

- [WebAIM November 6 ](https://web.archive.org/web/20191106084500/https://webaim.org/) 
- [WebAIM November 13](https://web.archive.org/web/20191113155355/https://webaim.org/)
