### ISSUE TITLE
Users Don't See Partially Constructed Web Content

### ISSUE THREAD

**Issue by sajkaj** [w3c/wcag#941]
Shawn Lauriat on October 11 commented on:
[https://w3c.github.io/wcag/conformance-challenges/#challenge-2-large-complex-and-dynamic-websites-are-always-under-construction](Challenge #2)
   I suggest using a different way to communicate this challenge. I very much agree with the description, but even in those cases, the users don't see literally "partially constructed" things unless the large site has a
   release management problem. Even experiments, which will show users different things depending on which experiment they've fallen into, should have some quality assessments done with the designs and code before
   releasing to the outside world.

**Comment by sajkaj** [comment]
Resolved in the [Working Draft](https://github.com/w3c/wcag/tree/conformance-challenges-working-draft/conformance-challenges) where the analogy to urban ifrastructures has been removed.

**Comment by sajkaj** [comment]
Reopened for a better explanation in the doc.

**Comment by peterkorn** [comment]
Shawn makes a good point that website publishers generally strive to avoid publishing partial updates to a page or set of pages.  However, just as with native software or web apps, updates to the logic of dynamically generated pages can introduce bugs that weren't foreseen.  Hence the final sentence of Challenge #2: "It may not be possible to validate every possible publishing permutation, each of which can have an impact on whether that particular rendering of the content at that particular moment conforms under the WCAG 2.x conformance model."

**Comment by peterkorn** [comment]
Further addressing the topic of the section title (private e-mail discussion), I propose changing the title to: "Challenge #2: Large, complex, and dynamic websites may have too many changing permutations to validate effectively"

**Comment by alastc** [comment]
It appears to be saying that pages with many permutations are impossible to test. However, like testing CSS and browser rendering, those pages are taking a modular approach and work within certain contraints. The same principles can be applied to accessibilty, but (I'm assuming) it is the page-level conformance that is the issue?

Within that section, I suggest updating:
"It may not be possible to validate every possible publishing permutation, each of which can have an impact on whether that particular rendering of the content at that particular moment conforms under the WCAG 2.x conformance model."
to:
"It may not be possible to validate every possible publishing permutation **with a page level test.** Each permutation can have an impact on whether that particular rendering of the content at that particular moment conforms under the WCAG 2.x conformance model."

We need to leave open the routes to a solutions, or at least pin down the aspect of the conformance model which is the issue.

**Comment by sajkaj** [comment]
Addressed in revised introductory paragraph for [Challenge #2](https://w3c.github.io/wcag/conformance-challenges/#Challenge-2).
