### ISSUE TITLE
+copyrighted, etc. challenges -issue raissed at TPAC 2019

### ISSUE THREAD

**Issue by sajkaj** [w3c/wcag#944]
Shawn Lauriat on September 17 commented on: +copyrighted, etc. challenges. || || Peter Korn on October 15 Can I invite you to take a stab at drafting that text Shawn? || || Shawn Lauriat on October 18 Not my own comment, I added this during TPAC from issues someone else mentioned just so we wouldn't lose the point. || || Shawn Lauriat on October 18 Added!

**Comment by alastc** [comment]
If no-one knows what this comment is about, can we close this?

**Comment by sajkaj** [comment]
Copyright is now addressed under Challenge #3
