### ISSUE TITLE
Is Challenge #3 also about user provided content?

### ISSUE THREAD

**Issue by sajkaj** [w3c/wcag#947]
Shawn Lauriat commented on:a October 11
[https://w3c.github.io/wcag/conformance-challenges/#challenge-3-3rd-party-content](Challenge #3)
   Does this include user-generated content?

**Comment by sajkaj** [comment]
Yes. "Third parties" is intended as an umbrella for everyone from individual users to various sized organizations that contribute.

**Comment by alastc** [comment]
The document clarifies that now, saying: "Many of these are third parties with the ability to add content directly to the website – including potentially every website visitor."

Please re-open if not addressed.
