### ISSUE TITLE
[LowVis] graphics contrast is unmentioned (except as exceptions) 

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#96]
Name: Chaals McCathie Nevile
Email: chaals@yandex-team.ru
Affiliation: Yandex
Document: W2
Item Number: Guideline 1.4: Make it easier for users to see and hear content...
Part of Item: 
Comment Type: technical
Summary of Issue: graphics contrast is unmentioned (except as exceptions)
Comment (Including rationale for any proposed change):
None of the contrast requirements in guideline 1.4 apply to graphics, except where specific types of graphics are specifically exempted.

This fails to account for primarily graphic applications, such as maps, traffic indication, wayfinding tools, and many others.

People have a primarily visual interaction with the Web. Where graphics are presented as a key part of an interface, even given a text-based alternative, many people will rely on the graphics.

It is therefore important to require sufficient accessibility of graphics content for visual users.

Proposed Change:
Add requirements for appropriate visual contrast in graphics used to provide functionality of a site or application.

**Comment by joshueoconnor** [comment]
https://lists.w3.org/Archives/Public/public-comments-wcag20/2015May/0008.html

**Comment by WayneEDick** [comment]
This extension is critical. Most people with low vision have a narrower contrast tolerance.  Graphics often favor visual design over separation of figure from ground.  Since 1.4 specifically call out "distinguishable" as its purpose, so extending the 1.4 contrast success criteria to is necessary. For active images this can save a [zoom operation/ return to normal] operation.

**Comment by WayneEDick** [comment]
More: This is extremely subtle.  Is iconic representation text as image is it just image? It at an abbreviation? My intuition to both questions is no, but icons are used as language.  I believe that icons that are not text exceed the scope of 1.4.3 and 1.4.6, but this is an accessibility gap in the guidelines. No change recommended to Understanding WCAG or Techniques. May be a future extension.

**Comment by WobleDuck** [comment]
Michael,
I am not quite up to speed on the github stuff. Do I just post them and you
moderate, or is there a way to just pop them to the list when I'm done?

Wayne

**Comment by joshueoconnor** [comment]
@WayneEDick Please post any suggestions, drafts, comments or questions here in the relevant thread. You can add things to the wiki also, and add the URI here, if that helps. Thanks

**Comment by WayneEDick** [comment]
I have one additional thought on this. Iconic Fonts should be a different story.  Use of Iconic fonts that do not include enough internal contrast or do not contrast enough from the background should be a failure. These are being used as letters and should be treated like alphabetic objects. 1.4.3 and 1.4.6 apply.

**Comment by WobleDuck** [comment]
I done with this without more comment.

**Comment by WayneEDick** [comment]
There is one issue that should be addressed.  If the contrast ratio is too low for anyone with low vision to see then it should simply be accompanied by a text alternative.  Below 4.5:1 is pretty low, so this would qualify in most cases.  Currently the only way to read with text alternatives is with screen magnifiers and screen readers, both of which do not serve the population adequately, but the real solution is to improve the technology for delivering alt-text to people with low vision.

**Comment by kwahlbin** [comment]
Images that convey information and are not accompanying by text should have a 3:1 color contrast ratio.  The challenge here is if the images have multiple colors.  The image needs to be differentiated from other icons on the page and one of the colors in the icon need to meet the 3:1 color contrast ratio.

**Comment by srinivasuchakravarthula** [comment]
+1 to Kathy. Unless they are photographs (natural), it's advisable to use right set of colors while designing images if there is an intention to embed text on it.

**Comment by MikeElledge** [comment]
Wayne, do you agree that icons without text should have a 3:1 contrast ratio? I've been using 4.5:1 for our icons, which limits the color pallet, but is quite readable.

**Comment by lauracarlson** [comment]
As stated in the November 20, 2015 [Accessibility Requirements for Low Vision Users](http://w3c.github.io/low-vision-a11y-tf/requirements.html#contrast-adjacent) Editor's Draft:

> ### 2.1.3 Contrast Adjacent
> 
> Sometimes adjacent colors need to be distinguished, for example, colors next to each other in a pie chart. Such colors should have sufficient contrast and be distinguishable by people who are color blind and have reduced contrast sensitivity.
> 
> #### User Requirement:
> 
> Users can distinguish between adjacent colors when needed for meaning.

**Comment by awkawk** [comment]
1.4.3: The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following: (Level AA)

What is not covered currently is graphic information that is not text. I think that we need to defer the gap to the LVTF to address.

**Comment by michael-n-cooper** [comment]
I see separate threads here:

1) Extending contrast requirements currently applicable only to text, to graphics;
2) Changing contrast threshold required for conformance;
3) Classifying graphics to specify what contrast requirements might be applicable, e.g., text-in-images vs. photographs that don't primarily convey text meaning, perhaps others.

All of those are in scope. But they should be handled separately. Otherwise you end up with requirements that are too specific to certain use cases considered by the group, not generalized, and might also have too much divergence from the core guidelines.

**Comment by DavidMacDonald** [comment]
If text that is part of the page content is in a graphic, 1.4.2 applies to that text

**Comment by MikeElledge** [comment]
I agree that this should be forwarded to the LVTF so they can recommend appropriate criteria.

**Comment by WobleDuck** [comment]
Wobble Duck is me. I posted this on the use cases of LVTF

**Comment by chaals** [comment]
I agree with Michael that there are several threads here.

The point is not about adjacent colours - anti-aliasing and so on can confuse this endlessly, but that the important features of a graphic should be distinguishable without relying on high-contrast separation.

Thus icon fonts need to use something better than two shades of grey - but also something clearer than a single row of pixels...

**Comment by WayneEDick** [comment]
We will address this in the LVTF.

It is clear that icons are being used like hieroglyphs and so the
requirement of visibility is more urgent. It is time to collect a
vocabulary of icons and insist on visible (1.4.3) and consistent (3.2.3,
3.2.4) usage. I am sure there will be a recommendation regarding these
items because the usage is more linguistic than graphic.

Wayne

**Comment by joshueoconnor** [comment]
@lauracarlson has kindly agreed to draft a technique that outlines requirements for appropriate visual contrast in graphics used to provide functionality (in a website or application).

**Comment by lauracarlson** [comment]
I drafted a [Using sufficient contrast for images that convey information](https://www.w3.org/WAI/GL/wiki/Using_sufficient_contrast_for_images_that_convey_information) technique. 

Ideas for improvement are welcome and appreciated.  cc/@chaals

Thanks!

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).

**Comment by lauracarlson** [comment]
@chaals any thoughts on the draft [Using sufficient contrast for images that convey information](https://www.w3.org/WAI/GL/wiki/Using_sufficient_contrast_for_images_that_convey_information) technique?

**Comment by lauracarlson** [comment]
Hi @joshueoconnor and @awkawk,

I worked on a technique in the Wiki last February. It is [Using sufficient contrast for images that convey information](https://www.w3.org/WAI/GL/wiki/Using_sufficient_contrast_for_images_that_convey_information).
 
Does that qualify as activity? Thoughts?

Thanks,
Laura

**Comment by joshueoconnor** [comment]
@lauracarlson it sure does :-)

**Comment by joshueoconnor** [comment]
@lauracarlson  - we did survey this right? And IIRC, there was some more work/edits to be done?

**Comment by lauracarlson** [comment]
@joshueoconnor Yes. I also need to consult with the LVTF.

**Comment by lauracarlson** [comment]
[New proposed LVTF  SC: Issue 3](https://github.com/w3c/low-vision-SC/issues/3)

**Comment by joshueoconnor** [comment]
@lauracarlson Thanks for the new proposed SC. Is this ready for survey?

**Comment by lauracarlson** [comment]
Hi Josh,

I will ask the LVTF. I'm wondering if it should be put into the SC template along with the rest of the new LVTF SCs for 2.1?

**Comment by lauracarlson** [comment]
Hi @joshueoconnor ,

Here is an update:

The LVTF discussed  this WCAG issue 96/ LVTF Issue 3 [in today's teleconference](
https://www.w3.org/2016/08/18-lvtf-minutes.html#item02).

@allanj-uaag has started a [Wiki page for a new LVTF Contrast (Minimum) SC]( https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum)).

@slhenry has an [action to include coverage of contrast of info in graphics](https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/69 ) in our [Accessibility Requirements for People with Low Vision](http://w3c.github.io/low-vision-a11y-tf/requirements.html) Document.

**Comment by lauracarlson** [comment]
First draft of [new Contrast (Minimum) SC](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/index.php?title=Contrast_(Minimum)&oldid=1359) and [related email](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0015.html).

**Comment by joshueoconnor** [comment]
Taken up by LVTF - closing.
