### ISSUE TITLE
Language for 1.13 Reflow challenges (SC 1.4.10) needs more description.

### ISSUE THREAD

**Issue by peterkorn** [w3c/wcag#960]
The text for why SC 1.4.10 requires human involvement doesn't sufficiently explain where and why this cannot be programmatically tested.

**Comment by detlevhfischer** [comment]
Can you add a link to the conformance challenges draft text? Can't find it at the moment...

**Comment by peterkorn** [comment]
Please see your edits in https://raw.githack.com/w3c/wcag/conformance-challenges-working-draft_Detlev1/conformance-challenges/  We haven't managed to get them into https://w3c.github.io/wcag/conformance-challenges/ yet.

**Comment by detlevhfischer** [comment]
There is is the requirement for reflow "without loss of information or functionality" - so at times this will require checks if content that is removed / collapsed is still accessible after an interaction (say, via a nav menu). IMO, this seems impossible to test automatically - even if the mere exisitance of scrolling in more than one directions is detectable automatically.

**Comment by sajkaj** [comment]
I see Alastair's low priority tagging, but I think Joe can pretty easily give us a useful explanation. So, I'm assigning to him for FPWD milestone even though I don't see @joecron as an available assignee.

**Comment by sajkaj** [comment]
@michael-n-cooper, can you please add @joecron to the repository? He should be assigned on this issue. Thanks!

**Comment by joecron** [comment]
I took swing at editing the text for SC 1.4.10, @peterkorn take a look and let me know what you think after the branch is merged.

**Comment by sajkaj** [comment]
See new paragraph beginning: "While automated tests can detect the presence of vertical and horizontal scroll bars" to [Appendix A.13: "Reflow"](https://w3c.github.io/wcag/conformance-challenges/#reflow).
