### ISSUE TITLE
Editorial change to Conformance Challenges, 1.24 Focus Order (Success Criterion 2.4.3)

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#964]
> Focus handling with dynamic content (move content to custom dialog, keep focus in dialog, return to trigger) do not look like they will be automatable any time soon.

Should be:
Focus handling with dynamic content (move **focus** to custom dialog, keep focus in dialog, return to trigger) does not look like it will be automatable any time soon.

**Comment by sajkaj** [comment]
FThe fix is in the [Working Draft](https://raw.githack.com/w3c/wcag/conformance-challenges-working-draft/conformance-challenges/)
