### ISSUE TITLE
Wrong linking Understanding pages WCAG 2.1

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#966]
https://www.w3.org/WAI/WCAG21/Understanding/conformance

At the top the: "Previous GL: Compatible" goes to: https://www.w3.org/WAI/WCAG21/Understanding/status-messages

And the: "Previous SC: Status Messages" goes to: https://www.w3.org/WAI/WCAG21/Understanding/compatible

They are turned around

**Comment by alastc** [comment]
I don't think that's part of the content, it's a build/XSL thing so assigning to Michael...
