### ISSUE TITLE
Link for Understanding Conformance goes to 2.0 version, NOT the 2.1

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#968]
https://www.w3.org/TR/WCAG21/#conformance

The link in the first paragraph: " Understanding Conformance" goes to: "https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance"

Not to: https://www.w3.org/WAI/WCAG21/Understanding/conformance

**Comment by jake-abma** [comment]
Also the link at: **5.2.4 Only Accessibility-Supported Ways of Using Technologies**

**Comment by jake-abma** [comment]
5.2.5 Non-Interference: Understanding Conformance Requirements also goes to: https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance

**Comment by jake-abma** [comment]
(still not updated yet...)

**Comment by alastc** [comment]
This was fixed ages ago, which you can confirm in the WCAG 2.1 branch:
https://github.com/w3c/wcag/blob/WCAG-2.1/guidelines/index.html

Unfortunately those links will only be updated in the public version if we can publish an update to the guidelines.

I've just updated the WCAG 2.2 index to point to the 2.2 versions, so we won't have that problem in the next one.
