### ISSUE TITLE
accessibility supported and accessibility-supported are used interchangeably

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#969]
https://www.w3.org/TR/WCAG21/#conformance

https://www.w3.org/WAI/WCAG21/Understanding/conformance

accessibility supported and accessibility-supported are used interchangeably. Which is good and do we want to implement consistently? Or doesn't it matter?

**Comment by alastc** [comment]
From a quick skim, (almost) every instance without the hyphen is using the concept on it's own. E.g. he "method used to set the preferences is accessibility supported".

When a hyphen is used it is (usually) to dis-ambiguate it from a nearby concept, e.g. "have accessibility-supported user agents". It is not a supported-user agent (where the user gets support), but an accessibility-supported user-agent.

It isn't entirely consistent, but that's the general pattern and I'd rather not spend time on it unless there is a cause for thinking it is confusing someone. Please close if you agree, or keep open if you are happy to do a PR for this ;-)

**Comment by jake-abma** [comment]
ok, closing, thanks
