### ISSUE TITLE
[LowVis] Can text shadowing be used to meet minimum contrast requirements? 

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#98]
Name: Moe Kraft
Email: maureen_kraft@us.ibm.com
Affiliation: IBM
Document: UW
Item Number: Understanding Success Criterion 1.4.3
Part of Item: Sufficient Techniques
Comment Type: technical
Summary of Issue: Can text shadowing be used to meet minimum contrast requirements?
Comment (Including rationale for any proposed change):
On a recent design review call, the designer proposed that although the text color does not meet sufficient contrast minimum requirements with the background color or image, the border around the text does meet contrast minimum requirements and that the text with shadowing should be sufficient to meet the success criteria of 1.4.3. 

Is this possible? Should there be guidelines on the weight/thickness of the shadow and that it goes around all the text and not just one side? 
Should this be entered as a proposed technique?

A good sample can be seen in the article, Design Accessibly, See Differently: Color Contrast Tips And Toolshttp://www.smashingmagazine.com/2014/10/22/color-contrast-tips-and-tools-for-accessibility/ In the Pay Now images, the middle column shows text with a drop shadow on the foreground text and the tests are in Normal view, gray scale and deuteranopia. http://media.mediatemple.netdna-cdn.com/wp-content/uploads/2014/10/buttongradients-large.png

**Comment by joshueoconnor** [comment]
https://lists.w3.org/Archives/Public/public-comments-wcag20/2015Apr/0002.html

**Comment by DavidMacDonald** [comment]
Yes a 360 degree drop shadow that surrounds the entire letter is sufficient if it provides the minimum contrast with the letter. We should create a CSS technique for that.

**Comment by joshueoconnor** [comment]
Thanks David. Are you offering??

**Comment by WayneEDick** [comment]
The key thing is that around each letter the contrast must be sufficient 4.5 for small 3 for large.  There are two cases of the background does not produce the contrast:

background blur:  
  text-shadow: blur-width 0 0 blur-width>0
background blur + an offset shadow: text-shadow: 0 0 color1 blur-width>0, color2 x>0  y>0  blur-width>0...

In both cases all shadow colors must produce the correct contrast.  

Comments? Is this the start of a technique?

**Comment by DavidMacDonald** [comment]
I think we should table this for the low vision committee...

**Comment by joshueoconnor** [comment]
Thanks David- please update the group with any progress

**Comment by DavidMacDonald** [comment]
I've looked at the issue. I believe that we should punt it to the low vision task force. a 360 degree shadow with sufficient contrast should be fine, but this is the type of thing that the Low Vision team might want to vet. There may be certain shadow types, opacity, blur etc that they'll want to explore. Wayne's discussion above is case in point... after they vet the issue we can revisit and put together a sufficient technique.

**Comment by joshueoconnor** [comment]
Agreed, lets let the Low Vision TF review.

**Comment by WayneEDick** [comment]
I believe essentially the same method used for gradient background would work for this. Tabling is fine, but I think it is quite solvable. Check the following code:

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title> text-shadow test </title>
	<meta name="Author" content="Wayne Dick">
	<meta name="Description"
							content="Shadow Text Contrast">
	
	<style>
		body {
			width: 80%;
			margin: 45px auto;
		}
		article {
			background-color: black;
			width: 40%;
		}
		.sample {
			padding: 1em;
			background-color: black;
			color: black;
		}

		#t0 {
			text-shadow: 0 0 0px #ffffff;
		}

		#t1 {
			text-shadow: 0 0 2px #ffffff;
		}

		#t2 {
			text-shadow: 0 0 4px #ffffff;
		}

		#t3 {
			text-shadow: 0 0 6px #ffffff;
		}

		#t4 {
			text-shadow: 0 0 8px #ffffff;
		}

		#t5 {
			text-shadow: 0 0 10px #ffffff;
		}
	</style>
</head>
<body>
<header>
	<h1>Using text-shadow for Contrast</h1>

	<p>The CSS text-shadow property can be used to
		achieve contrast
		when the background-color does not provide
		sufficient contrast,
		but it only works with zero offset for both
		vertical or
		horizontal. It also will not work with
		insufficient blur width.
		Thus the form should be like a cloud surrounding
		the letters.
		Moreover, the width of the blur should be
		sufficient to ensure a
		visible boundary between the text and
		background. Here are some
		samples. </p>
</header>
<article>
	<p>Basic format is— text-shadow: up right blur
		color;</p>

	<p id="t0" class="sample">text-shadow: 0 0 0px
		#ffffff</p>

	<p id="t1" class="sample">text-shadow: 0 0 2px
		#ffffff</p>

	<p id="t2" class="sample">text shadow: 0 0 4px
		#ffffff</p>

	<p id="t3" class="sample">text shadow: 0 0 6px
		#ffffff</p>

	<p id="t4" class="sample">text shadow: 0 0 8px
		#ffffff</p>

	<p id="t5" class="sample">text shadow: 0 0 10px
		#ffffff</p>
</article>
<footer>
	<p>WCAG Issue 98.&nbsp; These don't look clear to
		me.&nbsp; The :
		symbol disappears.<br>
	</p>
</footer>
</body>
</html>

**Comment by awkawk** [comment]
Will send to Low Vision TF for consideration.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
