### ISSUE TITLE
Testing of events with JS

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#995]
[Chapter 1.18](https://w3c.github.io/wcag/conformance-challenges/#character-key-shortcuts-success-criterion-2-1-4) says

> Single key presses can be applied to content via a script 

That's only partially true. You can't rely on it to trigger the same thing as with a proper keyboard operation. With [isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted), for example, the JS function can distinguish between real and simulated events. This is also valid for all other SC, where triggering of events are to be tested with JS (2.5.2, 2.5.4 etc.). 

Also, I think there may be problems with restrictive security settings on the site, especially when used in iFrames, that prohibit running scripts on it

**Comment by sajkaj** [comment]
Closed. If this is indeed an issue for the conformance challenges note doc, it's not so for the FPWD.
